### ISSUE TITLE
Only names of the controllers available

### ISSUE THREAD

**Issue by CesarUCI** [jfoenixadmin/JFoenix#100]
I'm trying to import your library onto Scene Builder but when I tried to do so, this is what happens.

![error](https://cloud.githubusercontent.com/assets/19227345/15170201/8424dd3a-1709-11e6-8540-a1ea1c42e91b.jpg)

I can only see the controller name but the controller itself is not prewiable. I'm using Scene Builder 8.1.1. I really like this framework so can you help me?

**Comment by jfoenixadmin** [comment]
well not all controls are supported on scene builder yet, but the basic controls are ( button, textfield, radiobutton,..).

you can test it with the latest version of JFoenix.
