### ISSUE TITLE
JFXToggleButton focus color not updating

### ISSUE THREAD

**Issue by Saecki** [jfoenixadmin/JFoenix#1004]
When Styling the togglebutton through css the focus color gets updated, when styling through the set methods the focus color stays the default blue-greenish color.

CSS:
-jfx-toggle-color: #dd6677; 
-jfx-toggle-line-color: #cc4455;

![jfxtogglebuttonfocuscolorbug2](https://user-images.githubusercontent.com/43008152/58095987-60461680-7bd4-11e9-825b-48f10409aa13.png)

JAVA:
t.setToggleColor(Color.web("#dd6677"));
t.setToggleLineColor(Color.web("#cc4455"));

![jfxtogglebuttonfocuscolorbug1](https://user-images.githubusercontent.com/43008152/58095972-5b816280-7bd4-11e9-89a2-40fa7ee25cb3.png)

**Comment by jfoenixadmin** [comment]
@Saecki, can you provide SSCCE for this issue?

**Comment by Saecki** [comment]
After further investigation the focus color seems to be indicated by the first state the button had when it was first displayed. So in this case two buttons have a grey focus color one the wanted redish one and one the default blue-greenish color.

The main class:

import com.jfoenix.controls.JFXToggleButton;
import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.scene.Scene;
import javafx.scene.layout.GridPane;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class MainApp extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        GridPane root = new GridPane();

        JFXToggleButton withCss = new JFXToggleButton();
        withCss.getStyleClass().add("customToggleButton");
        withCss.setSelected(true);
        
        JFXToggleButton withCss2 = new JFXToggleButton();
        withCss2.getStyleClass().add("customToggleButton");

        JFXToggleButton withoutCss = new JFXToggleButton();
        withoutCss.setToggleColor(Color.web("#dd6677"));
        withoutCss.setToggleLineColor(Color.web("#cc4455"));
        withoutCss.setUnToggleColor(Color.web("ffffff"));
        withoutCss.setUnToggleLineColor(Color.web("#888888"));
        withoutCss.setSelected(true);
        
        JFXToggleButton withoutCss2 = new JFXToggleButton();
        withoutCss2.setToggleColor(Color.web("#dd6677"));
        withoutCss2.setToggleLineColor(Color.web("#cc4455"));
        withoutCss2.setUnToggleColor(Color.web("ffffff"));
        withoutCss2.setUnToggleLineColor(Color.web("#888888"));

        root.add(withCss, 0, 0);
        root.add(withCss2, 0, 1);
        root.add(withoutCss, 0, 2);
        root.add(withoutCss2, 0, 3);

        Scene scene = new Scene(root);
        scene.getStylesheets().add("/styles/Styles.css");

        stage.setTitle("ToggleButton Example");
        stage.setScene(scene);
        stage.show();

        withoutCss.requestFocus();
    }
    
    public static void main(String[] args) {
        launch(args);
    }

}

The CSS file:

.customToggleButton {
    -jfx-toggle-color: #dd6677;
    -jfx-toggle-line-color: #cc4455;
    -jfx-untoggle-color: #ffffff;
    -jfx-untoggle-line-color: #888888;
}

**Comment by skmedix** [comment]
As far as I tested on my end.
`setToggleColor` is not updating Circle color at all.

**Comment by Saecki** [comment]
Well I'm using javafx 11 and jdk 11 together with jfoenix 9.0.8 and on my end it certainly does.

**Comment by jfoenixadmin** [comment]
Well, I'm testing using the git repo build. So far the only issue is with the ripple color. I'll fix that and push it.
However I was thinking of removing all the coloring properties from the controls and allow it only from css, what do you think? this will reduce the listeners overhead dramatically.

**Comment by Saecki** [comment]
I prefer using the conventional methods instead of CSS because I've found them much easier to use when you have to dynamicly change colors etc.. I don't know about the listeners though.

**Comment by jfoenixadmin** [comment]
you can change the colors dynamically in css using pseudo classes (it's recommended). However let's keep styling properties accessible from code too for now. 
This issue will be fixed in the next release of JFoenix *.0.9 by the end of this month.

Regards,

**Comment by Saecki** [comment]
Just wanted to say that I noticed a similar behavior on JFXButton. When once pressed the focus color and size of the focus region doesn't seem to update anymore.
