### ISSUE TITLE
JFXAlert - Difference into Ubuntu Linux and Windows

### ISSUE THREAD

**Issue by tiagomegasul** [jfoenixadmin/JFoenix#1007]
Hi,

I need to use JFXAlert to show modal message on my application. I used the demo example for start.

Well, when i open JFXAlert on Ubuntu Linux, the application open a blank screen over the main screen with the message and button.

![JFXAlert-Ubuntu](https://user-images.githubusercontent.com/51172329/58579122-bf350c80-8220-11e9-9496-816526c77b4f.png)

I execute the same demo application on Windows and then JFXAlert has open withou background white.

![JFXAlert-Windows](https://user-images.githubusercontent.com/51172329/58579145-c78d4780-8220-11e9-884e-aca41df60380.png)

How can i make for the JFXAlert be transparent in Ubuntu Linux too?

**Comment by jfoenixadmin** [comment]
Hi @tiagomegasul 
by default the background should be transparent, unless you changed that in css. You can try removing the css styling to narrow down the cause.

**Comment by tiagomegasul** [comment]
@jfoenixadmin To test the component, I downloaded it from Git, the source code of the JFoenix Demo. In the demo application presents the same problem, ie when opening in windows is transparent and when opening in Ubuntu Linux is white background.

So I think it's not a CSS problem, but if so, could you tell me how to do it so that Ubuntu Linux also has a transparent background?
