### ISSUE TITLE
How to remove JFXTabPane shadow?

### ISSUE THREAD

**Issue by l3njo** [jfoenixadmin/JFoenix#1008]
Hello, I'm trying to remove the shadow from a JFXTabPane. I cannot find relevant documentation anywhere. I've referred to #120 and #636, and none of them are helping. I'm using JFoenix 8.0.8 with TornadoFX 1.7.19.

**Comment by jfoenixadmin** [comment]
The following css should do the trick:
`.jfx-tab-pane .depth-container { -fx-effect: none; }`

Try using <a href="http://fxexperience.com/category/scenic-view/">Scenic View</a>. it will help you finding css selectors easily.

Regards,
