### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by NandanDesai** [jfoenixadmin/JFoenix#1009]
Components like JFXSpinner, JFXProgressBar uses a lot of CPU power. Running on Java 8 (Debian 64-bit). Is there any way to make this efficient?

**Comment by jfoenixadmin** [comment]
which JFoenix version are you using? try updating to the latest version.
Some performance issues regarding these controls have been fixed. If the issue still persist, can you provide a SSCCE for it?

Regards,
