### ISSUE TITLE
Massive memory in Processes

### ISSUE THREAD

**Issue by jakeingit** [jfoenixadmin/JFoenix#101]
When I import the entire library into Scenebuilder 2.0, it takes what I have right now, a bunch of imageviews and shapes and basic UI elements and says its taking up 855k memory under Windows Task Manager -> Processes.

Only when I change one UI element... be it by changing the location or the opacity, that the memory goes up by 40k, and if I save and restart Scenebuilder, I go back to it now being 860k memory!

Just letting it idle, it went from 860k to launch, to now 925k after three minutes. I literally cant do anything other than changing one thing about this layout, saving, closing, and relaunching in cycles. Its getting annoying. Whats up?

![jfeonix_massivememory](https://cloud.githubusercontent.com/assets/1946249/15194919/0068d12c-178b-11e6-81b2-9aebac636e42.png)

**Comment by jfoenixadmin** [comment]
can you test with the latest version of scene builder 8.1.1?

**Comment by jakeingit** [comment]
I have tried this with Scene Builder 8.1.1. I attached the entire library, and it started off using 550k memory, and toggling any variable a few times rose it to 1.2m memory usage.

However, using nothing I get 150k with nothing on a new project view.

**Comment by jakeingit** [comment]
I will try this on a different computer, but I'd much rather work with it at my workstation.

**Comment by jfoenixadmin** [comment]
this issue might be related to scene builder, you can open an issue using the following link: 
https://bitbucket.org/gluon-oss/scenebuilder/issues/new
