### ISSUE TITLE
JFXRadioButton circle does not resize with font size

### ISSUE THREAD

**Issue by ipwxy** [jfoenixadmin/JFoenix#1015]
A standard JavaFX RadioButton resizes the circle when the font resizes. JFXRadioButton does not.

I'm struggling to resize the circle from CSS, as modifying properties of `.jfx-radiobutton .radio-container .radio` or `.jfx-radiobutton .radio-container .dot` gives no results.

**Comment by jfoenixadmin** [comment]
@ipwxy can you provide a SSCCE for the issue?
