### ISSUE TITLE
AnimatedFlowContainer causes resizing problems

### ISSUE THREAD

**Issue by darksmall** [jfoenixadmin/JFoenix#102]
When using an AnimatedFlowContainer for the ContentPane in the JFXDrawer, like in the demo:
`
flowHandler = innerFlow.createHandler(context);
context.register("ContentFlowHandler", flowHandler);
context.register("ContentFlow", innerFlow);
context.register("ContentPane", 
content.getChildren().add(flowHandler.start(new AnimatedFlowContainer(Duration.millis(320), ContainerAnimations.SWIPE_LEFT)));
`
The AnimatedFlowContainer here causes some odd resizing problems. Reading its source, what the AnimatedFlowContainer does is create an ImageView of a fixed size, which is a screenshot of the pane and makes the animation moving that ImageView. When you resize the scene, the ImageView size does not get updated and causes the window size to not be able to shrink. I know this is not JFoenix's fault, but maybe something can be done so it works?

My solution to resolve them temporarily is to just not use it.
`content.getChildren().add(flowHandler.start());`

**Comment by jfoenixadmin** [comment]
we reset the width/height of animatedflowcontainer after finishing the animation. so this issue should be fixed. Thanks for pointing out the issue.
