### ISSUE TITLE
JFXCheckBox odd tick mark with node orientation

### ISSUE THREAD

**Issue by AbdAlhamidZobi** [jfoenixadmin/JFoenix#1021]
JFXCheckBox have a weird tick mark when node orientation is set to Right To Left
![Capture](https://user-images.githubusercontent.com/22858957/59978138-8c8cf280-95d9-11e9-81e5-c9cec972e53c.PNG)

**Comment by jfoenixadmin** [comment]
@AbdAlhamidZobi thanks for pointing out the issue 👍
