### ISSUE TITLE
How to remove default focus of JFXDecorator?

### ISSUE THREAD

**Issue by CodeLunatic** [jfoenixadmin/JFoenix#1024]
It has default focus:

**Comment by CodeLunatic** [comment]
[!Focus](https://p.qlogo.cn/qqmail_head/Q3auHgzwzM4g2cLj1J8wBePWc7IpPAic1k1UpA3GaLFicTnfuKLquoufic6xr47seLYYRmS2MazRmrLxhaVertmIbQCh5ib8L2UZTSpbYbjBpQQ/0)

**Comment by CodeLunatic** [comment]
![Focus](https://p.qlogo.cn/qqmail_head/Q3auHgzwzM4g2cLj1J8wBePWc7IpPAic1k1UpA3GaLFicTnfuKLquoufic6xr47seLYYRmS2MazRmrLxhaVertmIbQCh5ib8L2UZTSpbYbjBpQQ/0)

**Comment by jfoenixadmin** [comment]
try calling `requestFocus `on any content node

**Comment by CodeLunatic** [comment]
I tried it，but not work

**Comment by CodeLunatic** [comment]
I'm sorry. I tried too little. It worked

**Comment by CodeLunatic** [comment]
Thank You!!!
