### ISSUE TITLE
Demo dont work with any JDK

### ISSUE THREAD

**Issue by meilleur102** [jfoenixadmin/JFoenix#1025]
Hi. I try to build the Demo and i'm not able to do anything. 

I try with JDK 12, 11, 10 and 9. 
Nothing work. 
With JDK 12-11 tell me the Could not determine java version from '12.0.1'. (with the JDK version changed) 
With 10 and 9 it's not able to build to. 

I try gradlew run.
I try gradle wrapper --gradle-version=(all the possible version from 4.2.1 to 5.5) 
When I type gradle -v on my cmd I got version 5.5.

When I try with java 9 it tell me 
* What went wrong:
Execution failed for task ':jfoenix:compileRetrolambdaMain'.
> Process 'command 'C:\Program Files\Java\jdk-9.0.4\bin\java.exe'' finished with non-zero exit value 1

And yes I change my JAVA_HOME to replace the JDK that I want to use

I run win10. 
I don't know if anyone can help me with that?

**Comment by jfoenixadmin** [comment]
Hi, the Demo is for Java 8. it's using DataFX library which doesn't support Java 9+ yet.
