### ISSUE TITLE
JFXButton with svg assigned by css does not work correctly

### ISSUE THREAD

**Issue by bogdanbaghiu** [jfoenixadmin/JFoenix#1026]
Hello. 

I'm assigning to the jfx button a svg with css. When I pass the mouse over it does not work correctly, that is, only when I put the pointer on a line of the svg it changes color but if I put the pointer on the button it does not work. I have also added the javafx button by default and the video shows that the behavior of the two are different.

I also attach the fxml and the css so that you can reproduce it.

![bug](https://user-images.githubusercontent.com/37840937/61041986-9a14eb80-a3d3-11e9-8a5d-936380f9bcd2.gif)

Do you need delete `.txt` extension:
[svg button.fxml.txt](https://github.com/jfoenixadmin/JFoenix/files/3381425/svg.button.fxml.txt)
[icons.css.txt](https://github.com/jfoenixadmin/JFoenix/files/3381426/icons.css.txt)

Greetings.

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍, the fix will be included in the next release.
Meanwhile, you can fix it by calling `Platform.runLater(()-> button.setPickOnBounds(true));` after button creation.

Regards,
