### ISSUE TITLE
Question: Get all highlighted rectangles from JFXHighlighter

### ISSUE THREAD

**Issue by hpjerico** [jfoenixadmin/JFoenix#1027]
Hello

We are currently using the JFXHighlighter to search and highlight text within large ListViews.  When the search is complete, we show how many results are found and wish to provide a way for them to focus each individual instance of the search.  Is there a way to get all the "HighLight Rectangles" that are drawn over the Parent so we may apply a different color/style to the one currently being "focused"?

Regards
Jerico

**Comment by jfoenixadmin** [comment]
Hello,
Currently, it's not supported but doable. Feel free to add your own contribution to JFoenix.

Regards,
