### ISSUE TITLE
JFXCombobox Unable to center prompt text

### ISSUE THREAD

**Issue by Hounsvad** [jfoenixadmin/JFoenix#1030]
I don't seem to be able to center the prompt text of the JFXComboBox.
It is likely that I am missing something but I have been able to center the text field for entering new text, center selected text and center the list cells.
![image](https://user-images.githubusercontent.com/36563020/61585594-55b9e600-ab5f-11e9-8277-b7f56a651a41.png)
![image](https://user-images.githubusercontent.com/36563020/61585595-8863de80-ab5f-11e9-8cfd-06730a3733eb.png)

I am using CSS to achieve what i have gotten so far.

.jfx-combo-box .text-field{
    -fx-alignment:  center;
}
.jfx-combo-box .jfx-list-cell{
    -fx-background-color: #DDDDDD;
    -fx-alignment: center;
}
![image](https://user-images.githubusercontent.com/36563020/61765469-755e4200-addd-11e9-995e-1da86176cf3c.png)
The Item will be shown centered if the combobox is set to editable, but when the combobox is not editable it will appear left.
![image](https://user-images.githubusercontent.com/36563020/61765510-a0489600-addd-11e9-8523-e502096128a3.png)

**Comment by jfoenixadmin** [comment]
Hello,
now you should be able to change the alignment using the following css:
```
.jfx-combo-box > .prompt-container {
    -fx-alignment: center-left;
}
```
this fix will be included in the next release *.*.10
Regards,
