### ISSUE TITLE
JFXDialog border radius

### ISSUE THREAD

**Issue by JordanZimmitti** [jfoenixadmin/JFoenix#1031]
Hi,
This is more of a feature then a problem but I was wondering if there was a way to have the dialog box have rounded corners.

Thanks

**Comment by jfoenixadmin** [comment]
Hi,
You can change it using the following css:
```
.jfx-dialog-overlay-pane > StackPane{
    -fx-background-radius: 20;
    -fx-background-color: white;
}
```
Regards,
