### ISSUE TITLE
RequiredFieldValidator tooltip problem

### ISSUE THREAD

**Issue by An2-San** [jfoenixadmin/JFoenix#1032]
When I add a requiredfieldvalitor to a node , it adds a tooltip. I do not set a message to the validator , I just add an icon. So it shows an empty tooltip with no message on it. I would like to delete the tooltip. I also do not want to use "node.setTooltip(null)" method, because I add my tooltip using FXML . So it would remove all my  added tooltips. Validation error message and the tooltip message needs to be intependent. 

I am using version 8.0.7 .

Is there any way to solve this ?

**Comment by jfoenixadmin** [comment]
try updating to the latest version of JFoenix

**Comment by An2-San** [comment]
> try updating to the latest version of JFoenix

I tried on the latest version 8.0.8 and it still shows the tooltip.
