### ISSUE TITLE
TabPane underline with window scale 

### ISSUE THREAD

**Issue by Rawtt** [jfoenixadmin/JFoenix#1036]
i think i found a bug in JFoenix libary and searching for a workaround.

I´m using Java 9 in an Maven Project in Eclipse (Windows 10 pro). My JFoenix version is 9.0.8

> <dependency>
>     <groupId>com.jfoenix</groupId>
>     <artifactId>jfoenix</artifactId>
>     <version>9.0.8</version>
> </dependency>

Problem: When I use the Windows scaling function then my TabPane is not working propertly.

See question on Stackoverflow :
 https://stackoverflow.com/questions/57254668/javafx-jfoenix-tabpane-not-working-correctly

**Comment by jfoenixadmin** [comment]
Hello @Rawtt,
This is a duplicate for #728, It's a bit hard for me to fix as I was not able to reproduce.

**Comment by CTaszus** [comment]
This still happens on any windows "odd" ui scaling option.
100%, 200% works
125%, 150%, 175% doesnt work

Windows scaling also seems to make controls (Scrollpane, TabPane..) blurry.

Best work-around sofar for me: Disable Autoscale for your java application and implement a "real" upscaling using 'em' in css etc.

`
if(.. GUIProperties.USE_UI_AUTOSCALE) 
	System.setProperty("prism.allowhidpi", "true");
else 			
	System.setProperty("prism.allowhidpi", "false");
`
