### ISSUE TITLE
When I user JFXListview like demo ,the subList properties do not work well

### ISSUE THREAD

**Issue by aizhuzi** [jfoenixadmin/JFoenix#1040]
I use four lists in a  parent list with sublist properties,when I expand all ,it get waring below. 

 com.sun.javafx.scene.control.skin.VirtualFlow addTrailingCells 
 index exceeds maxCellCount. Check size calculations for class com.jfoenix.controls.JFXListCell

Then the parent list can only see three child lists, it should srcoll to see more,but previous it is not this sence.

**Comment by jfoenixadmin** [comment]
sublist properties are deprecated and will be removed in next releases.
