### ISSUE TITLE
About toggle button

### ISSUE THREAD

**Issue by lostspirit1** [jfoenixadmin/JFoenix#1043]
![image](https://user-images.githubusercontent.com/38575233/62827434-0e92a400-bba5-11e9-8818-0240196fea62.png)

Hello I'm sorry if you are not allowed to ask this kind of question here
but I'm in doubt
Is there a possibility to do this with jfoenix?
Which component to use?
I searched a lot and found nothing :(

**Comment by jfoenixadmin** [comment]
Hello, you can use JFXToggleNode with an icon as its graphic.
