### ISSUE TITLE
JFXHamburger button question

### ISSUE THREAD

**Issue by JhonnySalles** [jfoenixadmin/JFoenix#1047]
Hi, I implemented this button in a my project, but I couldn't find a way to be pressing the button programmatically "button.fire ()"
Could someone tell me if he has this feature?

Thanks very much

**Comment by jfoenixadmin** [comment]
Hello @JhonnySalles 
JFXHamburger is not a button so there is no fire method. But you can do a workaround as the following:
1. add action listener to the burger
```
burger.addEventHandler(ActionEvent.ACTION, action->{
    // action to be executed
});
```
2. fire the action by calling 
`burger.fireEvent(new ActionEvent());`

Regards,

**Comment by JhonnySalles** [comment]
Thanks for the answer, in tests I could not reproduce the execution, I believe I'm doing something wrong.

In initialize I created the event to open the panel and also change the shape of the button:

public void initialize(URL arg0, ResourceBundle arg1) {
		TranslateTransition openSlidePane = new TranslateTransition(new Duration(350), pane);
		TranslateTransition closeSlidePane = new TranslateTransition(new Duration(350), pane);
		HamburgerBackArrowBasicTransition btnBurgerTask = new HamburgerBackArrowBasicTransition(btnBurger);
		btnBurgerTask.setRate(-1);
		btnBurger.addEventHandler(MouseEvent.MOUSE_PRESSED, e -> {
			btnBurgerTask.setRate(burgerBtnTask.getRate() * -1);
			btnBurgerTask.play();
			if (pane.getTranslateX() != 0) {
				openSlidePane.setToX(0);
				openSlidePane.play();
			} else {
				closeSlidePane.setToX(-(pane.getWidth()));
				closeSlidePane.play();
			}
		});
	}


In the event of another button will serve to load the content of the panel, where after loading I will be calling the event burgerbutton.
@FXML
private void openPane() {
                // ***** loadcontent
		if(pane.getTranslateX() != 0) {
			btnBurger.fireEvent(new ActionEvent());
		}
	}

In my test nothing happens, where the event is not executed.
I think it's a silly thing, but my knowledge is not that advanced.


Thank very much..

**Comment by JhonnySalles** [comment]
I found the problem, I've been using a different event.

`burger.addEventHandler(MouseEvent.MOUSE_PRESSED, e -> { });`

Thank you very much for the explanation, thanks to that I was able to adjust and make it work by code opening the panel.
