### ISSUE TITLE
JFXTreeTableView (with CellFactory) displays "excess Cells" - on Grouping

### ISSUE THREAD

**Issue by dhineshram** [jfoenixadmin/JFoenix#1048]
in below Screen Shot, I have used `JFXTreeTableView` to display some data (21 rows) to user - by `ArrayList<MyClass>`.
Based on some condition, _Cell background color_ will be changed - by `CellFactory`.

### **ISSUE IS:** When any of the column is Grouped, the new Cell (generated by CellFactory) **miss behaves**

- displays excess cells (just displaying, unable to select)
- doesn't hide on grouping

If it is a bug fix it, else please help me to fix my code

**Initially:**
![image](https://user-images.githubusercontent.com/20234332/63429266-34d30200-c437-11e9-8b3c-6d84096f81a5.png)

**On grouping any Column**
![image](https://user-images.githubusercontent.com/20234332/63429570-0dc90000-c438-11e9-80ba-7c84a8ca37c4.png)

**Displays excess cell**
_Occurs only if any of the columns is grouped._ 
And keeps multiplying the Cells whenever any column is grouped. Only the columns for which cell factory is applied miss-behaves.
![image](https://user-images.githubusercontent.com/20234332/63430923-60f08200-c43b-11e9-891d-0d728d1ad12a.png)

**Another screen shot of excess cell**
![image](https://user-images.githubusercontent.com/20234332/63431630-e3c60c80-c43c-11e9-87e2-311194a6a27f.png)

**Another screen shot of excess cell**
![image](https://user-images.githubusercontent.com/20234332/63431983-c6de0900-c43d-11e9-9cf9-0b5b934e47bf.png)

**Code that involves the 2 columns.**
My class name : `ChannelData`
Column type : `Output` -> this is `enum`

[Source Code.java.txt](https://github.com/jfoenixadmin/JFoenix/files/3525364/file.txt)

JRE used : 1.8.0_211

**Comment by jfoenixadmin** [comment]
If you can provide a SSCCE demonstrating the issue, we might be able to help.
Regards,

**Comment by jfoenixadmin** [comment]
in updateItem method you need to only update the style if item is not null and not empty otherwise you need to reset it.

**Comment by dhineshram** [comment]
Thanks a lot for really quick reply, did not realize that would cause trouble. 
I changed `updateItem()` method as below, **everything works fine...**

@Override
public void updateItem(Output item, boolean empty) 
{
	super.updateItem(item, empty);

	if (item == null || empty) 
	{
		setText(null);
		setStyle("");
	} 
	else
	{
		setText(getItem().name());

		String style = "-fx-alignment : CENTER; -fx-background-color:";
		if(getItem() == Output.Waiting)				style += "#ffcc00";	// yellow
		else if(getItem() == Output.Finished)		style += "#00b300";	// green
		else if(getItem() == Output.Active_Channel)	style += "#00b300";	// green
		else 										style += "#b30000";	// red

		setStyle(style);
	}
}

Thanks again for helping 👍 :-)
