### ISSUE TITLE
Cant run runnable jar file with jfoenix

### ISSUE THREAD

**Issue by Ed1ks** [jfoenixadmin/JFoenix#1049]
Hi,
I added the following VM Arguments to my project:
`
--add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web,com.jfoenix
--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
--add-exports javafx.controls/com.sun.javafx.scene.control=com.jfoenix
--add-exports javafx.base/com.sun.javafx.binding=com.jfoenix
--add-exports javafx.graphics/com.sun.javafx.stage=com.jfoenix
--add-exports javafx.base/com.sun.javafx.event=com.jfoenix
--add-exports javafx.graphics/com.sun.javafx.scene=com.jfoenix`

and I can run it with eclipse without any error. But if I export it to a runable jar file, and run a batch file with the same arguments, it returns following error:

`Error occurred during initialization of boot layer
java.lang.module.FindException: Module com.jfoenix not found`

If I open the .jar file with zip I can clearly see, that com.jfoenix exists.

I have following librarys:
Java 11.0.2
Javafx 11.0.2
Jfoenix 9.0.9

I also have tried to create the module-info.java but with the same result. Right now im not able to run the jar file.

**Comment by jesa29** [comment]
How do you build the jar?
