### ISSUE TITLE
Problem read an xml file in stage builder Problem reading a file in FXML szene builder

### ISSUE THREAD

**Issue by IBSalamatou** [jfoenixadmin/JFoenix#105]
Example :
<?xml version="1.0" encoding="UTF-8"?>

<?import com.jfoenix.controls.JFXTextField?>
<?import javafx.scene.layout.BorderPane?>

<BorderPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="400.0" prefWidth="600.0" xmlns="http://javafx.com/javafx/8.0.65" xmlns:fx="http://javafx.com/fxml/1">
   <center>
      <JFXTextField BorderPane.alignment="CENTER" />
   </center>
</BorderPane>

it gives me an exception
Caused by: java.lang.ClassNotFoundException: com.jfoenix.controls.JFXTextField
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2916)
	at javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2905)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2846)

**Comment by jfoenixadmin** [comment]
yeah sure, you need to import jfoenix in scene builder first. #85

**Comment by IBSalamatou** [comment]
yes I did, I can use on scene builder component of the jfoenix, but the problem occurs when I reopen name FXML on scene
![githut](https://cloud.githubusercontent.com/assets/19475706/15409348/51b48c88-1e0c-11e6-8f82-01555f96361b.JPG)
 builder

**Comment by jfoenixadmin** [comment]
well you just need to include jfoenix.jar in order to use JFoenix controls. 

in order to open an existing fxml file in scene builder, you need to open scene builder 1st then open the file. it seems double clicking on the fxml file is not working as scene builder is not loading the custom libraries by then. 

this issue is related to scene builder, you can open an issue using the following link:
https://bitbucket.org/gluon-oss/scenebuilder/issues/new

**Comment by androizer** [comment]
The same problem was bugging me for so longer period of time. Either there is a work around too. If we add the jar to the "app. classpath" variable of scenebuilder.cfg file, then it will load the custom components when double clicking on existing fxml file without giving any FXMOLoader & CNF Exception.

**Comment by IBSalamatou** [comment]
Thank you for your answers, it worked, I used the method of androizer

**Comment by aminabs** [comment]
I opened an issue [here](https://bitbucket.org/gluon-oss/scenebuilder/issues/91/custom-library-classpath-issue)

**Comment by vasigorc** [comment]
androizer's solution worked for me! Thank you

**Comment by hbszwjlc** [comment]
like this ?
 app.mainjar=SceneBuilderApp.jar
app.version=2.0
app.id=com.oracle.javafx.scenebuilder
app.preferences.id=com/oracle/javafx/scenebuilder
app.mainclass=com/oracle/javafx/scenebuilder/app/SceneBuilderApp
app.classpath=SceneBuilderKit.jar;jfoenix-1.6.0.ja
jvmarg.1=-Djava.security.manager
jvmarg.2=-Djava.security.policy=$APPDIR/app/scenebuilder.policy
jvmarg.3=-Dfile.encoding=UTF-8
jvmuserarg.1.name=-Djavafx.autoproxy.disable=
jvmuserarg.1.value=true
jvmuserarg.2.name=-Xmx
jvmuserarg.2.value=999m
jvmuserarg.3.name=-Djava.util.logging.config.file=
jvmuserarg.3.value=$APPDIR/app/logging.properties

**Comment by SteveSyun** [comment]
what is androizer?
