### ISSUE TITLE
How to fix the focused btn has Rippler fill?

### ISSUE THREAD

**Issue by jzlhll** [jfoenixadmin/JFoenix#1051]
Such as the demo app, when it runs, the full button will already has rippler fill background color.
Or when focused changed, the stage get the focus, the focused button will be has rippler background.

**Comment by Ed1ks** [comment]
I can confirm this. When you press e.g. a button or a toggleButton and unfocus the stage while the ripple is taking effect, the animation will stop. If you then return to the stage (open the window) you will see the unfinished rippler effect.
![ripplerBug](https://user-images.githubusercontent.com/46250296/65182664-10803a80-da62-11e9-9e22-59b09f002d9f.PNG)

**Comment by IntelliCe** [comment]
I realized this problem just now. I have a temporary solution for this issue. Just color the button's ripple when clicked: `.jfx-button:hover .jfx-rippler { -jfx-rippler-fill: black; }`. Note that if use this method focus color may be cleared.
