### ISSUE TITLE
JFXTextArea is always bold

### ISSUE THREAD

**Issue by Speirs47** [jfoenixadmin/JFoenix#1055]
Hi.
I just started using JFoenix and I like it a lot but I noticed that text inside JFXTextArea is always bold. It doesn't matter what font I use (I tested it on the default and on Open Sans). Here's screenshot comparing JFXTextArea and JFXTextField 
![Screenshot_20190926_124854](https://user-images.githubusercontent.com/40421338/65683332-48d4d980-e05d-11e9-89e9-b6095f3005d2.png)

**Comment by jfoenixadmin** [comment]
Hi,
You need to change font weight in css as the following:
```
.jfx-text-area {
    -fx-font-weight: normal;
}
```

**Comment by Speirs47** [comment]
Yeah, that's the first thing I tried. It doesn't help
