### ISSUE TITLE
Sonarqube badge on README.md seems outdated

### ISSUE THREAD

**Issue by silentsoft** [jfoenixadmin/JFoenix#1056]
![image](https://user-images.githubusercontent.com/16218269/65691797-7432e500-e0ac-11e9-9097-f403bc56fc4b.png)

4th badge is pointing `sonardebt` as like below (`README.md`)

```
[sonardebt]:https://sonarqube.com/dashboard?id=com.jfoenix%3Ajfoenix-root
[sonardebt img]:https://sonarqube.com/api/badges/measure?key=com.jfoenix:jfoenix-root&metric=sqale_debt_ratio
```

if you clicks the badge `https://sonarqube.com/dashboard?id=com.jfoenix%3Ajfoenix-root` then the link redirects you to `https://sonarcloud.io/dashboard?id=com.jfoenix%253Ajfoenix-root` with `404` error.

![image](https://user-images.githubusercontent.com/16218269/65693075-a5141980-e0ae-11e9-99ad-5cd0ab93bea7.png)

I think this link should be changed to `https://sonarcloud.io/dashboard?id=com.jfoenix%3Ajfoenix-root` which is `%25` less.

![image](https://user-images.githubusercontent.com/16218269/65693192-dbea2f80-e0ae-11e9-982a-edd1b29712b5.png)

BUT, I couldn't found appropriate `sqale_debt_ratio` metric  on `Get project badges` button on the bottom right with new `sonarcloud.io`.

![image](https://user-images.githubusercontent.com/16218269/65693581-7e0a1780-e0af-11e9-9125-d23eb88c1edb.png)

### Additional information
* theres also `sonar` link on `README.md` which is never used
    ```
    [sonar]:https://sonarqube.com/dashboard?id=com.jfoenix%3Ajfoenix-root
    [sonar img]:https://sonarqube.com/api/badges/gate?key=com.jfoenix:jfoenix-root
    ```
* and ..... the repo shown on sonar is seems outdated too 😭 
    ![image](https://user-images.githubusercontent.com/16218269/65694409-c970f580-e0b0-11e9-990e-b8bd031a905e.png)

**Comment by jfoenixadmin** [comment]
@silentsoft working on it

**Comment by jfoenixadmin** [comment]
I linked repo, however I'm not sure why it's not analyzing java files.
@silentsoft are you familiar with sonar cloud properties file? a help would be appreciated

**Comment by silentsoft** [comment]
@jfoenixadmin Im not familiar with sonar but I'll try it with my personal repo :)

**Comment by silentsoft** [comment]
@jfoenixadmin Okay,.... accidentally I found this document.

https://sonarcloud.io/documentation/autoscan/

```
SonarCloud can autonomously scan your code, by simply reading it from your repository! We call that AutoScan.

This is currently a Beta feature, with a limited scope and some caveats. Those limitations will be removed along the way.
```

```
The following languages are currently supported:

ABAP
Apex
CSS
Flex
Go
HTML
JS
Kotlin
PHP
Python
Ruby
Scala
Swift
TypeScript
TSQL
XML
```

for clearify, `Sonarcloud`'s `Auto Scan` feature seems not available for `java` project.
and also `CircleCI` seems not compatible with `Sonarcloud` too. (for truly `Continuous Integration`)

because when I clicks `With Travis CI : configure analysis` on `Overview` page,

![image](https://user-images.githubusercontent.com/16218269/66318289-fe553600-e955-11e9-807c-8eba73187db5.png)

it looks like truly `automated` with `.travis.yml` file

![image](https://user-images.githubusercontent.com/16218269/66318252-eed5ed00-e955-11e9-94c9-2847354a7da7.png)

but when I clicks `With other CI tools : congifure analysis` on `Overview` page,

![image](https://user-images.githubusercontent.com/16218269/66318537-74f23380-e956-11e9-9baa-782a0a27ca57.png)

it makes me to run command `./gradlew sonarqube \....` `manually` seems not `automated`

---

So ... I am wondering if `TravisCI` is on the table or not 😕

**Comment by silentsoft** [comment]
@jfoenixadmin Okay,.... accidentally I found this document.

https://sonarcloud.io/documentation/autoscan/

```
SonarCloud can autonomously scan your code, by simply reading it from your repository! We call that AutoScan.

This is currently a Beta feature, with a limited scope and some caveats. Those limitations will be removed along the way.
```

```
The following languages are currently supported:

ABAP
Apex
CSS
Flex
Go
HTML
JS
Kotlin
PHP
Python
Ruby
Scala
Swift
TypeScript
TSQL
XML
```

for clearify, `Sonarcloud`'s `Auto Scan` feature seems not available for `java` project.
and also `CircleCI` seems not compatible with `Sonarcloud` too. (for truly `Continuous Integration`)

because when I clicks `With Travis CI : configure analysis` on `Overview` page,

![image](https://user-images.githubusercontent.com/16218269/66318289-fe553600-e955-11e9-807c-8eba73187db5.png)

it looks like truly `automated` with `.travis.yml` file

![image](https://user-images.githubusercontent.com/16218269/66318252-eed5ed00-e955-11e9-94c9-2847354a7da7.png)

but when I clicks `With other CI tools : congifure analysis` on `Overview` page,

![image](https://user-images.githubusercontent.com/16218269/66319438-129a3280-e958-11e9-9338-773d07fd1054.png)

it makes me to run command `./gradlew sonarqube \....` `manually` seems not `automated`

---

So ... I am wondering if `TravisCI` is on the table or not 😕

**Comment by jfoenixadmin** [comment]
I see, that's why it was not analyzing java files. 
Thanks you @silentsoft for the explanation

**Comment by jfoenixadmin** [comment]
I think we should move to TravisCI

**Comment by silentsoft** [comment]
@jfoenixadmin great ! I'll try with `TravisCI` too 😉

**Comment by silentsoft** [comment]
@jfoenixadmin I've just signup to `TravisCI` to test and the test has been succeed ! but theres some extra issues.

### Steps What I did
1) Sign Up to `TravisCI` with GitHub account
2) click `JFoenix` repo on `TravisCI` dashboard
3) activate it
4) commit and push `.travis.yml` and `build.gradle`
    - https://github.com/silentsoft/JFoenix/commits/master

### Problems
When I configure `TravisCI`'s build image to `oraclejdk8` and `oraclejdk9` (through [this commit](https://github.com/silentsoft/JFoenix/commit/dee955b05b3d2681e53d360807c52bfada99c82f)), the test won't be succeed. `oraclejdk8` : License stuff... blablabla... `oraclejdk9` : `retrolambda` dependency makes trouble. ([build job log](https://travis-ci.org/silentsoft/JFoenix/builds/596124852))

and when i changed to `openjdk8` and `openjdk9` (through [this commit](https://github.com/silentsoft/JFoenix/commit/77e7e4907f548ae9c74b32bb44e3e5afc53887ac)), `openjdk8` : `success`, `openjdk9` : `failure` ([build job log](https://travis-ci.org/silentsoft/JFoenix/builds/596129245)) (still `retrolambda` makes trouble I guess)

so when i removed `openjdk9` build image (through [this commit](https://github.com/silentsoft/JFoenix/commit/ca4d46ec45685212d8a9b6c8069bd135fc3f0f1c)) the test finally succeed ([build job log](https://travis-ci.org/silentsoft/JFoenix/builds/596132267))

and `GitHub` commit status looks good !
![image](https://user-images.githubusercontent.com/16218269/66580364-432cd700-ebb9-11e9-88a6-5332744d8c42.png)


### ANYWAY BUT
this is what most confused thing.
[your sonarcloud quality gates](https://sonarcloud.io/organizations/jfoenixadmin/quality_gates/show/9) and [my sonarcloud quality gates](https://sonarcloud.io/organizations/silentsoft/quality_gates/show/9) seems totally same 😕 

I have no idea what is happening with sonarcloud ..... 😭

**Comment by jfoenixadmin** [comment]
@silentsoft thank you for the clarification 👍  

Regarding the retro-lambda build, it's only supported on the Java 8 version. There is no retro-lambda build for Java 9. 
Also regarding Java 9 build, master branch is not compatible with Java 9. JFoenix-9.0.0 branch should be used in the build process instead. 

I created an account for JFoenix on TravisCI, @silentsoft feel free to create PR of the build yml file 👍 

About sonarcloud, yeah it's very weird it's still ignoring the java files :s

**Comment by silentsoft** [comment]
@jfoenixadmin okay, I'll create a PR when I am done with more extra test 😉

**Comment by silentsoft** [comment]
@jfoenixadmin you can look around through #1060
