### ISSUE TITLE
Can't use JFXProgressBar

### ISSUE THREAD

**Issue by MGW14** [jfoenixadmin/JFoenix#1063]
Hello,
i just tried to use the Scene Builder to put a JFXProgressBar on my AnchorPane.
I can't place it, it shows me the crossed circle. If i double Click it on the library i get a white screen.
Thanks for your help  :D

**Comment by jfoenixadmin** [comment]
Hello,
can you provide more info about the issue? 
Also make sure you are using compatible versions of JFoenix/SceneBuilder
