### ISSUE TITLE
JDK 13 and java.lang.NoClassDefFoundError: com/sun/javafx/css/parser/CSSParser

### ISSUE THREAD

**Issue by TheRealVira** [jfoenixadmin/JFoenix#1068]
Hey JFoenix Repository! ( :

I have had great fun when working with your components ~ which brings me to our current problem. Since we are using JDK 13 we are getting weird issues because of how the CSSParser was removed from the com.sun repo.

Is there any way we could work around that? Is there going to be a fix?

Kind regards~

**Comment by acaproni** [comment]
It affects also jdk 11

**Comment by raouf2684** [comment]
It affects now JDK 14 too, im updating from JDK 8 to JDK 14 and I had too many problems with it.

**Comment by jfoenixadmin** [comment]
Make sure to use the right version of JFoenix.
JFoenix 8 is for Java 8
JFoenix 9 is for Java 9+
