### ISSUE TITLE
JFXComboBox Multiple Selection feature

### ISSUE THREAD

**Issue by azerphoenix** [jfoenixadmin/JFoenix#1069]
Hello!
Is there support for multi-selection for JFXComboBox and if yes, how I can activate it?
Thanks in advance!

P.S. Unfortunately, I haven't found anything in JavaDoc...

**Comment by jfoenixadmin** [comment]
Hello,
JFXComboBox doesn't support multi selection. it inherits the behavior of Java ComboBox control.
Feel free to add your own contribution to JFoenix.

Regards,
