### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by antic-ml** [jfoenixadmin/JFoenix#1070]
Downloading and executing the gradlew build command failed. Here's the output:

`C:\Users\Mario Gianota\JFoenix-master>gradlew build
Downloading https://services.gradle.org/distributions/gradle-4.2.1-bin.zip
...................................................................
Unzipping C:\Users\Mario Gianota\.gradle\wrapper\dists\gradle-4.2.1-bin\dajvke9o8kmaxbu0kc5gcgeju\gradle-4.2.1-bin.zip to C:\Users\Mario Gianota\.gradle\wrapper\dists\gradle-4.2.1-bin\dajvke9o8kmaxbu0kc5gcgeju

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '13.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
`

**Comment by jfoenixadmin** [comment]
Seems like you are using Java OpenJDK build instead of Oracle Java 8 build.
Make sure to use compatible java version.
Master branch is for Java 8, while jfoenix-9.0.0 branch is for Java 9-11.
