### ISSUE TITLE
JFXPopup .setPopupContainer() .setSource()

### ISSUE THREAD

**Issue by Leonardomgn** [jfoenixadmin/JFoenix#1074]
Hello!

> import com.jfoenix.controls.JFXButton;
> import com.jfoenix.controls.JFXPopup;
> import com.jfoenix.controls.JFXRippler;

```
 public void initialize(URL url, ResourceBundle rb) {
        JFXRippler rippler = new JFXRippler(lblMenu);
        rippler.setMaskType(JFXRippler.RipplerMask.RECT);
        menuBar.getChildren().add(rippler);
        openMenu();
        createPage();
    }
    private void openMenu() {
   JFXPopup pop = new JFXPopup();
        pop.setPopupContent(overFlowContainer);
        pop.setPopupContainer(anchor);
        pop.setSource(lblMenu);      
    }
```

![image](https://user-images.githubusercontent.com/58435956/71770780-ae175100-2f0f-11ea-8059-a91bf86281bd.png)

why "setPopupContainer and setSource" cannot find symbol ?

setContent change to setPopupContent?

Thanks!!

**Comment by jfoenixadmin** [comment]
Hello,
JFXPopup was reworked long time ago, these two methods were removed. Instead, you need to pass the source node for JFXPopup `show `method, which is called for showing the popup.
`pop.show(lblMenu, JFXPopup.PopupVPosition.TOP, JFXPopup.PopupHPosition.RIGHT);`

Regards,
