### ISSUE TITLE
Can't Using SnackBar using on 8.0.8 

### ISSUE THREAD

**Issue by hrnrstgzl** [jfoenixadmin/JFoenix#1084]
Hi! I want to show a toast message in my javafx desktop app. But when ı used below code;
  snackBar.enqueue(new SnackbarEvent(rootPane, Duration.millis(1000), pseudoClass));
SnackbarEvent doesn't contains a string message. How can I use a toast message on 8.0.8. Please help me and sorry for my bad English...

**Comment by gilad4** [comment]
See the snackbar demo in [IconsController.java](https://github.com/jfoenixadmin/JFoenix/blob/master/demo/src/main/java/demos/gui/uicomponents/IconsController.java)

**Comment by hrnrstgzl** [comment]
> See the snackbar demo in [IconsController.java](https://github.com/jfoenixadmin/JFoenix/blob/master/demo/src/main/java/demos/gui/uicomponents/IconsController.java)

Thanks for help. This solved my problem
