### ISSUE TITLE
Rotate CheckBox in SceneBuilder

### ISSUE THREAD

**Issue by Laufinsconsca** [jfoenixadmin/JFoenix#1088]
I noticed that when you rotate the checkbox by 90 or 270 degrees, disappears the ability to check it and to change it text.
![image](https://user-images.githubusercontent.com/33294655/76151680-e7676b00-60d0-11ea-9b51-f20d30fd880f.png)

**Comment by jfoenixadmin** [comment]
After some debugging, this issue is related to caching JFXRippler. However I'm not sure why it's disappearing for those specific rotation values (90, 270). it's a very weird issue. I'm open to suggestions.

**Comment by jfoenixadmin** [comment]
I found this closed [issue](https://bugs.openjdk.java.net/browse/JDK-8179946), so it seems it's related to JavaFX rendering engine. However the fix version is 10, so I don't think it will be pushed to 8 anytime soon :/
