### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by warmuuh** [jfoenixadmin/JFoenix#1092]
first of all, thanks for your work, i really enjoy using this library.
I do feel though that there is not much work happening anymore, neither on the most important feature of supporting jdk12 nor on responding to newly opened issues.
Due to jdk advancing and introducing new features, jfx also releasing new versions (version 14 currently), i feel that this library currently prevents me from adopting these new versions.

Is this project dead and we need to look for alternatives? Or is there a roadmap or at least some plans to continue working on this project?

**Comment by SchweinchenFuntik** [comment]
new versions of Java do not introduce anything new for this library, especially newer versions are not LTS. you can try this library with the new version, and if you find errors, you can  bug report

**Comment by warmuuh** [comment]
Just have a look at all the issues labelled with jdk12. Lots of exceptions due to reflective access. But I guess, that is a statement, thanks.

**Comment by SchweinchenFuntik** [comment]
Well, as long as activity has fallen, no one bothers you to fork and fix problems, this is how the open source works. 

PS: I'm not a developer of this

**Comment by PAlex404** [comment]
> first of all, thanks for your work, i really enjoy using this library.
> I do feel though that there is not much work happening anymore, neither on the most important feature of supporting jdk12 nor on responding to newly opened issues.
> Due to jdk advancing and introducing new features, jfx also releasing new versions (version 14 currently), i feel that this library currently prevents me from adopting these new versions.
> 
> Is this project dead and we need to look for alternatives? Or is there a roadmap or at least some plans to continue working on this project?

Yes this project is pretty much dead, the dev keeps doing little changes but this library needs a big refactor
The code is too much spaghetti
It is old, you are right there are a lot of issues related to newer versions of java.

@SchweinchenFuntik  yes you are right too, one could fork the library and make adjustments but the thing is the code is so old and bad written that it would require a lot of effort to rewrite it, considering that there is no documentation on what classes do (there are some comments here and there but that's not documentation)
I could try it, but unfortunately I have not enough time lately
