### ISSUE TITLE
[Suggestion]hope the jfxbutton displays a shadow when the mouse is hover on it

### ISSUE THREAD

**Issue by Stars-One** [jfoenixadmin/JFoenix#1093]
The jfxbutton is so better,but when I use flat button,it make user confused that they don't know it is a button.
So I hope the button display a shadow when the mouse is hover,like the UI of web

**Comment by jfoenixadmin** [comment]
you can change button background on mouse over using css.

```
.custom-button{
    -fx-background-color: TRANSPARENT;
}
.custom-button:hover{
// change background with some transparency
}
```
