### ISSUE TITLE
JFXDrawerStack  remove mouse drag

### ISSUE THREAD

**Issue by akaZX** [jfoenixadmin/JFoenix#1096]
I am wondering is it possible to remove mouse dragging from drawer stack. 
found that this is responsible on what happens when drag is performed
`drawersStack.setOnDragDetected(event -> {                
                return;
            });`

**Comment by jfoenixadmin** [comment]
you need to consume the event inside the drag filter:
`drawersStack.addEventFilter(MOUSE_DRAGGED, event -> event.consume());`
