### ISSUE TITLE
Focus on buttons and checkboxes is not rendered

### ISSUE THREAD

**Issue by emcastro** [jfoenixadmin/JFoenix#111]
Focus is not currently implemented.
After clicking on buttons and checkboxes, it is still possible to use `tab` and `space` keys to operate controls.
However, there is not visible feedback.

Here is a simple test case:
 * In the Demo, select the checkbox entry;
 * Click on the first checkbox, its state changes;
 * Press on the `space` key, the checkbox state changes again;
 * Press the `tab` key, and the `space` key again, the next checkbox state changes;
 * and so on...

**Comment by jfoenixadmin** [comment]
Focus state is already implemented in JavaFX Button, you only need to set a custom css for JFXButton in order to show it.

**Comment by emcastro** [comment]
I tried adding the following into `jfoenix-main-demo.css` of JFoenix demo.

```css
.custom-jfx-check-box:focused{
    -fx-checked-color: YELLOW;
    -fx-unchecked-color: RED;
}
```

It does not produce anything.

Did I miss something?


Have you any sample use of `:focused` applied to checkbox?

**Comment by jfoenixadmin** [comment]
JFXCheckBox and JFXButton have been updated to render the focus state automatically.

Regards,
