### ISSUE TITLE
How to add actions on JFXButton

### ISSUE THREAD

**Issue by mintonzhang** [jfoenixadmin/JFoenix#1113]
Excuse me, I encountered a problem, the Action has been added to fxml, but it does not take effect in the Controller. My English is not very good, I found many articles, but I couldn't find it. If anyone knows, please tell me. Thank you

```html
fxml 

        <!-- 水平布局盒子-->
        <HBox spacing="20" style="-fx-padding: 0 0 0 50;">
            <JFXButton prefWidth="100" prefHeight="40" buttonType="RAISED" text="BUTTON"
                       style="-fx-font-size:14px;-fx-background-color:WHITE;" onAction="#click"/>
            <JFXButton prefWidth="100" prefHeight="40" buttonType="RAISED" text="COLORED"
                       style="-fx-text-fill:WHITE;-fx-background-color:#5264AE;-fx-font-size:14px;"/>
            <JFXButton prefWidth="100" prefHeight="40" buttonType="RAISED" text="DISABLED"
                       style="-fx-background-color:WHITE;-fx-font-size:14px;" disable="true"/>
        </HBox>

```
```java
Controller

@ViewController(value = "/fxml/Button.fxml")
public final class ButtonController {


    public void click(ActionEvent mouseEvent) {
        System.out.println();
    }
}

```

it dose not work .can you tell me reason?

**Comment by AlQa-hOlic** [comment]
Pls link to the project repo. The information you have provided is not sufficient.

Which is the library you are using? @ViewController is not part of the javafx library

Normally button action methods are annotated with @FXML

**Comment by mintonzhang** [comment]
Hi @AlQa-hOlic  That  ‘ViewController’ is from 'io.datafx' repo 
```html
    <dependency>
      <groupId>io.datafx</groupId>
      <artifactId>flow</artifactId>
      <version>8.0.1</version>
    </dependency>
```
it is just a data bind library. 

I just want to add a click event of a button, but after adding it, the click does not respond。
My controller has no attributes and should not use @FXML

**Comment by AlQa-hOlic** [comment]
Ok so here is what I understand.
Take a look at the [datafx tutorial 1](https://github.com/guigarage/DataFX/blob/master/tutorials/flow1/src/main/java/io/datafx/tutorial/SimpleController.java).

```java
@FXML
@ActionTrigger("myAction")
private Button actionButton;

@ActionMethod("myAction")
public void onAction() {
    clickCount++;
    resultLabel.setText("Button was clicked " + clickCount + " times");
}
```

I think what you are missing is the `@ActionMethod('button-fx-id')` annotation.

If just adding that does not work you may have to add the `@ActionTrigger('button-fx-id')` annotation too.

**Comment by AlQa-hOlic** [comment]
And this issue is not related to the JFeonix Library at all

**Comment by mintonzhang** [comment]
I just found out, so I closed this question. thank you very much @AlQa-hOlic

**Comment by mintonzhang** [comment]
Can you tell me where I can learn more about javafx? There are too few resources I can find. @AlQa-hOlic

**Comment by AlQa-hOlic** [comment]
Sure, I learnt the basics from youtube but browsing through existing code on GitHub helped me the most. Also I’d be happy to help (I could have used community help when I was learning 😅).

**Comment by mintonzhang** [comment]
Which chat app do you use? I often use WeChat and qq, how about you? Maybe we can communicate in another way.

**Comment by AlQa-hOlic** [comment]
https://pastebin.com/kwzgBDkA
