### ISSUE TITLE
JDK 11 and JFoenix

### ISSUE THREAD

**Issue by AdelDima** [jfoenixadmin/JFoenix#1122]
Hi,
I build JFoenix on JDK8 and it works fine, now I cloned the branch 9 to test it with JDK 11 unfraternally did not work.
Should I use JAVA 12 instead of JAVA 11?

**Comment by jfoenixadmin** [comment]
Hi,
can you be more specific and provide more details about the build issue?

**Comment by AdelDima** [comment]
> Hi, Thank you for your replay.
> can you be more specific and provide more details about the build issue?

Sure
## Jave Version
<img src="https://cdn-std.droplr.net/files/acc_610439/GcW5Bs">

## Build Issue
<img src="https://cdn-std.droplr.net/files/acc_610439/979VFn">

## Build With --stacktrace
<img src="https://cdn-std.droplr.net/files/acc_610439/9iHTiC">

**Comment by jfoenixadmin** [comment]
Well, try running `gradlew :jfoenix:build` to build JFoenix jar instead of `gradlew build` as JFoenix demo is only compatible with  java 8
