### ISSUE TITLE
Hello people! 

### ISSUE THREAD

**Issue by Draven10** [jfoenixadmin/JFoenix#1124]
I am trying to use Jfoenix 9, on JDK 14 and Java build 1.8.0_251-b08. I am using Eclipse, imported the jar 9.0.10 in the classpath and set the following VM arguments: 

`--add-modules=javafx.controls
--add-modules javafx.controls,javafx.fxml
--add-modules=javafx.controls,javafx.swing

--add-opens java.base/java.lang.reflect=ALL-UNNAMED
--add-opens java.base/java.lang.reflect=com.jfoenix
--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
--add-exports javafx.controls/com.sun.javafx.scene.control=com.jfoenix
--add-exports javafx.base/com.sun.javafx.binding=com.jfoenix
--add-exports javafx.graphics/com.sun.javafx.stage=com.jfoenix
--add-exports javafx.base/com.sun.javafx.event=com.jfoenix`

but I am not able to run my app properly, I am getting the following issues:

Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.jfoenix.controls.behavior.JFXGenericPickerBehavior (in unnamed module @0x75afcdc4) cannot access class com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to unnamed module @0x75afcdc4

My project is due soon and any help would be highly appreciated :D thank you!

**Comment by jfoenixadmin** [comment]
try adding `--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED`

**Comment by Draven10** [comment]
> try adding `--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED`

nope, still not working... I am using it in a non modular project, I have to specify... and gettting the same error basically

'Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.jfoenix.controls.behavior.JFXGenericPickerBehavior (in unnamed module @0x78c2b9dc) cannot access class com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to unnamed module @0x78c2b9dc'
