### ISSUE TITLE
ListView Popup

### ISSUE THREAD

**Issue by cranst0n** [jfoenixadmin/JFoenix#113]
I'm running into some issues with a `JFXListView` inside a `JFXPopup`. It seems to be related to the number of elements I put in the list view:

Here's a screenshot of the popup when I put 4 items in the list:
![4-items](https://cloud.githubusercontent.com/assets/1173143/16275823/beaca80c-3879-11e6-9360-6dcb9f560368.png)

And this one only has 3 items:
![3-items-collapsed](https://cloud.githubusercontent.com/assets/1173143/16275829/c4b5d1ec-3879-11e6-9ed8-9f795a64ca07.png)

Any advice would be appreciated.

**Comment by jfoenixadmin** [comment]
well, JFXListView computes its height according to the number of its items ( so there might be some calculation issues). if you can add some code demonstrating the issue, it would be great.

Regards,

**Comment by cranst0n** [comment]
Ah I see what you mean. I'm using scala but I did my best to strip down my app to a minimal example that exhibits the problem. Forgive the messiness. I'm fresh off the Swing train and this is my first foray into JavaFX. If you find it necessary, I can probably port it over to Java.

```scala
import scalafx.Includes._

import javafx.application.Application
import javafx.event.EventHandler
import javafx.scene.Scene
import javafx.scene.control.Label
import javafx.scene.input.{ MouseEvent }
import javafx.scene.layout.GridPane
import javafx.stage.Stage

import org.tbee.javafx.scene.layout.MigPane

import com.jfoenix.controls._
import com.jfoenix.controls.JFXPopup._

class TestApp extends Application {

  override def start(primaryStage: Stage): Unit = {

    val root = new MigPane("fill, insets 0, gap 0")

    val button       = new JFXButton("Button")
    val canvasPane   = new GridPane()
    val popupContent = new JFXListView[Label]()
    val popup        = new JFXPopup()

    popup.setContent(popupContent)
    popup.setPopupContainer(root)
    popup.setSource(canvasPane)
    popupContent.getItems().add(new Label("Item 1"))
    popupContent.getItems().add(new Label("Item 2"))
    popupContent.getItems().add(new Label("Item 3"))
    // popupContent.getItems().add(new Label("Item 4")) // Commenting this out makes entire popup collapse

    canvasPane.add(button, 0, 0)

    button.onMouseClicked = new EventHandler[MouseEvent] {
      override def handle(e: MouseEvent): Unit = {
        popup.show(PopupVPosition.TOP, PopupHPosition.RIGHT, 0, 0)
      }
    }

    val contentPane = new MigPane("insets 0")
    contentPane.add(canvasPane, "grow, push, wrap")
    root.add(contentPane, "grow, push, wrap")

    val decorator = new JFXDecorator(primaryStage, root)
    val scene     = new Scene(decorator, 400, 400)

    primaryStage.setScene(scene)
    primaryStage.show()
  }
}

object TestApp {

  def main(args: Array[String]): Unit = {
    Application.launch(classOf[TestApp], args: _*)
  }
}

```

**Comment by cranst0n** [comment]
Not sure if this is a robust fix but when I add this to my CSS, I don't see this behavior.

```
.jfx-list-view {
  -fx-min-width : 150px;
}

**Comment by jfoenixadmin** [comment]
It seems the issue is related to the java version you are using. which java are you using? can you update to the latest java version and retest? 

Regards,

**Comment by cranst0n** [comment]
I believe I'm up to date (.
```bash
> lsb_release -d
Linux Mint 17.3 Rosa
> java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by jfoenixadmin** [comment]
well, I tested your example but couldn't reproduce when using the latest version of java.

**Comment by cranst0n** [comment]
Thanks. I've built from source but still not luck. Still seems like the `-fx-min-width` corrects whatever I'm running into though.

**Comment by jfoenixadmin** [comment]
the JFXListView has been reworked, you can try it with latest version of jfoenix.
