### ISSUE TITLE
JFXTabPane has wrong selected tab line length (OpenJFX 11)

### ISSUE THREAD

**Issue by qtran** [jfoenixadmin/JFoenix#1130]
Hi, I recently moved to OpenJFX 11 and found a bug in JFXTabPane. The selected tab line has a wrong length depending on the size of the tab size

![image](https://user-images.githubusercontent.com/386593/87597365-f77ffe80-c6f1-11ea-9338-296bac74c219.png)

Code to reproduce:

```
public class TestApplication extends Application {

    public static void main(String[] args) {
	launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

	final JFXTabPane pane = new JFXTabPane();
	pane.getTabs().add(new Tab("Test"));
	pane.getTabs().add(new Tab("Teeeeeest"));
	pane.getTabs().add(new Tab("Tst"));

	primaryStage.setScene(new Scene(pane, 600, 400));
	primaryStage.show();

    }
}
```

Tested with 9.0.10

**Comment by jfoenixadmin** [comment]
Will close this issue, as it is a duplicate for #728
