### ISSUE TITLE
JfxHighlighter not working properly in ListView

### ISSUE THREAD

**Issue by gchariharan** [jfoenixadmin/JFoenix#1132]
Hi,
    I tried to use the JfxHighlighter to highlight the contents in the listview. I used the below line
JFXNodeUtils.addDelayedEventHandler(searchText, Duration.millis(400), KeyEvent.KEY_TYPED, event -> jfxHighlighter.highlight(availableSignalsList, searchText.getText()));

It works properly until you scroll on the list view. My filtered list is so big that i need to scroll the listview. When i scroll the listview,
it is not highlighting anything.

**Comment by jfoenixadmin** [comment]
Hi, 
ListView updates the cells contents on scroll, thus you need to add some scroll listeners to refresh the highlighter.

Regards,
