### ISSUE TITLE
jfoenix-8.0.10.jar doesn't have components in jfoenix-9.0.10.jar

### ISSUE THREAD

**Issue by chriskorosu** [jfoenixadmin/JFoenix#1138]
After downloading/importing jfoenix-8.0.10.jar into Gluon SceneBuilder, I noticed that some of the components advertised on the main page are missing. For example, the JFXDatePicker. 

So I tried it with jfoenix-9.0.10.jar, and the components were there.

Not sure if this is an error or by design, but couldn't find any reference to this difference, so figured I'd mention it

**Comment by jfoenixadmin** [comment]
Make sure you are using compatible versions of JFoenix and SceneBuilder
