### ISSUE TITLE
Centering ProgressBar

### ISSUE THREAD

**Issue by cranst0n** [jfoenixadmin/JFoenix#114]
I've got a `StackPane` with a `Canvas` and `JFXProgressBar` that should both be centered.

I can't seem to center the progress bar though:

```scala
canvasPane.getChildren().addAll(canvas, loadProgressBar)
canvasPane.setAlignment(Pos.CENTER)
```

When I change the type of my progress bar to `javafx.scene.control.ProgressBar` it centers as I expected. I've also switched it to a `JFXSpinner` for a sanity check and that also centers.

**Comment by jfoenixadmin** [comment]
true, thanks for pointing out the issue. 
it's been fixed, you can test it using the latest version of JFoenix.

**Comment by cranst0n** [comment]
Looks good. Thanks for the fix!
