### ISSUE TITLE
Disable toggle button using animation

### ISSUE THREAD

**Issue by CesarUCIGIT** [jfoenixadmin/JFoenix#115]
I have JFX Toggle Pane and inside of it I have 4 JFX-Toggle buttons. The problem is that I want these toggle buttons to  behave as Tabs, so that when I select one button, any of the other which could have been selected too, turns to unselected. Here is an image so you can see.
![image](https://cloud.githubusercontent.com/assets/20340630/16658161/255f7646-441a-11e6-85d6-8b222899ea56.png)
I would also like to display the transition effect for each event. Greetings.

**Comment by jfoenixadmin** [comment]
Please note that you need to implement this behavior, by listening to toggle button selectedProperty() and calling the method setSelected(boolean) manually for other buttons. 

Note: JFXTogglePane does NOT behave like that. It's a pane that can be toggled ( change background color) , It does NOT toggle its content.

so you need to use VBox as the parent of the 4 JFXToggleButtons, and implement toggle behavior manually as mentioned.
