### ISSUE TITLE
How to contribute/setup library

### ISSUE THREAD

**Issue by gringofe** [jfoenixadmin/JFoenix#1155]
Hello,

first, I want to thank you for creating this library! I found it really useful and it makes my applications look beautiful. I have, however, found some limitations which I would like to try to remove/improve, but I can't get the library to properly show up/compile/build in IntelliJ. 

I am using Java 11 + JavaFX 11.

**Comment by sshahine** [comment]
Hello, Make sure you are using the a compatible version of JFoenix 9.*
