### ISSUE TITLE
Implement IFXValidatableControl in java module

### ISSUE THREAD

**Issue by JhonnySalles** [jfoenixadmin/JFoenix#1164]
Good night.

I'm trying to implement the validation interface, to create a custom validation for a textfield. However, I don't know if it is because I am using modules in Java, but I get the message that the interface is not accessible to use it.
I am trying to use it, as it was informed that the facade will be discontinued.

I also tried to open it, but I was unsuccessful, and I am not sure what is wrong.

Below are images of the error

![image](https://user-images.githubusercontent.com/43912638/100154061-ca9fdd00-2e83-11eb-8658-48d9cfabc39a.png)

![image](https://user-images.githubusercontent.com/43912638/100153781-5feea180-2e83-11eb-8e13-772efcc98b6c.png)

![image](https://user-images.githubusercontent.com/43912638/100154086-d25f8180-2e83-11eb-95ef-fea72bb82362.png)

**Comment by sshahine** [comment]
Hello,
Plz note that `IFXValidatableControl` is used to make controls support validation. However what you need to do is to extend `ValidatorBase` and implement your own validation logic there and use it for the JFXTextField.

**Comment by JhonnySalles** [comment]
Ok, I will try this, thank you very much.
