### ISSUE TITLE
Icons resize on hover

### ISSUE THREAD

**Issue by jyskit** [jfoenixadmin/JFoenix#117]
I have a problem with icons changing size when I hover on a button with an icon. Here is the code:
`<JFXButton fx:id="printer" buttonType="RAISED" prefHeight="64.0" prefWidth="64.0" style="-fx-text-fill:WHITE;-fx-background-color:#5264AE;-fx-font-size:14px;" text="" AnchorPane.bottomAnchor="0.0" AnchorPane.leftAnchor="0.0" AnchorPane.rightAnchor="0.0" AnchorPane.topAnchor="0.0">`
`	<VBox.margin>`
`		<Insets bottom="10.0" />`
`	</VBox.margin>`
`	<graphic>`
`		<FontAwesomeIconView fill="WHITE" glyphName="PRINT" size="40" />`
`	</graphic>`
`</JFXButton>`

Here is the result without hovering:
![no_hover](https://cloud.githubusercontent.com/assets/2023033/16855317/123c74dc-4a15-11e6-99a8-1ac0372f0898.png)

And with hover:
![hover](https://cloud.githubusercontent.com/assets/2023033/16855332/1f1288a4-4a15-11e6-9558-b3392a0ea3f0.png)

**Comment by jfoenixadmin** [comment]
you need to check your css files if you have any, i tried the previous example, couldn't reproduce this behavior.

**Comment by jyskit** [comment]
I tracked down the CSS rule that causes this. It is the very first rule from jfoenix-main-demo:
.root {
	-fx-font-family: "Roboto";	
}

Very strange, I think.

**Comment by jfoenixadmin** [comment]
well, it's possible as FontAwesome use their own font family, so it might be overridden by the root class (or at least the size of the font).

I recommend building your own css file instead of just using jfoenix-main-demo.css

**Comment by ByJacob** [comment]
I write answer because i have the similar problem.

set css Style:
`.glyph-icon {
  -fx-font-size: 15px; /* size from icon */
  -fx-font-family: "FontAwesome"; 
}`

help me for fix resize (find in [stackoverflow](https://stackoverflow.com/a/51755632/6026286))
