### ISSUE TITLE
All picker controls are not working on jdk 11 using netbeans apache 12.1

### ISSUE THREAD

**Issue by linoqui14** [jfoenixadmin/JFoenix#1173]
All picker controls like TimePicker, DatePicker and etc.. are giving me this error
`Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: superclass access check failed: class com.jfoenix.controls.behavior.JFXGenericPickerBehavior (in unnamed module @0x25b366d) cannot access class com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control.behavior to unnamed module @0x25b366d`

I am using maven and lates version of JFoenix

**Comment by sshahine** [comment]
this issue is related to #889
