### ISSUE TITLE
Add New Component Or Update Existing Button

### ISSUE THREAD

**Issue by ProALiOnLine** [jfoenixadmin/JFoenix#118]
Hello
Please Can Add This Button 
https://github.com/UltraMixer/LaddaFX
On Your Amazing Library Or Update JFXButton
Because I need it in my designs.
Thank you very much and appreciated the work

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks, it's a nice control to have in JFoenix. However we might have a different implementation of the submit button using material design animations. 

Regards,
