### ISSUE TITLE
Buttons are transparent

### ISSUE THREAD

**Issue by KingOfDog** [jfoenixadmin/JFoenix#119]
I wanted to create a little, nice material design JavaFX-application.
But the JFoenix buttons were transparent and didn't get the ripper fill color.

**Comment by jfoenixadmin** [comment]
can you provide an example to demonstrate the issue?

**Comment by KingOfDog** [comment]
Yes, of course.

![bild2](https://cloud.githubusercontent.com/assets/17073459/16944778/72f5e8f4-4da2-11e6-91a8-985f4cdfbec6.PNG)

I just added a button and set the ripper fill and the text. All the other options have the default values.

In the preview the button hasnt the ripper fill color and also in the preview in eclipse the button hasnt got any color. Why?

**Comment by jfoenixadmin** [comment]
I think what you are looking for is the background color, plz **NOTE** that rippler fill is the color of the ripple effect when you click on the button, not its background.
to set the background of the button, you need to add to style property : -fx-background-color and give it a value.

**Comment by KingOfDog** [comment]
Oh okay, but it would be nice if you add an option to set the background color. Everything else is good developed.
