### ISSUE TITLE
JVXDrawer with full-height side pane

### ISSUE THREAD

**Issue by rjahn** [jfoenixadmin/JFoenix#12]
It would be nice to have support for full-height sidepanes. Sometimes it looks better to overlap the whole application and not only the content area!

Currently, the side-pane height has the same height as the drawer.

**Comment by rjahn** [comment]
forget this issue, because it's not a problem to use the drawer "full-size"

**Comment by jfoenixadmin** [comment]
well the maximum size of the drawer side pane is the maximum height/width of the stage, to set that the drawer must be the parent of other stage nodes.
