### ISSUE TITLE
jfoenix css 

### ISSUE THREAD

**Issue by rebai-halim** [jfoenixadmin/JFoenix#121]
good morning

so jfx-tab-pane is the css class for jfxtabpane , but where is the localtion of css file contain this class and  all jfoenix components css class ?? 

i find 2 css file : jfoenix-desing.css and jfoenix-components.css but i not found all componets of jfoenix in there 2 css file ?? there an other css file ???

thanks

**Comment by jfoenixadmin** [comment]
css style classes are defined in each control code, you can use **ScenicView** to check all the style classes of the nodes in your scene. I'm closing this issue as it's related to  #120. 

plz if you have more questions related to JFoenix, reopen #120 and add your comments. there is no need to open duplicate issues for the same topic, thanks.
