### ISSUE TITLE
javafx css error

### ISSUE THREAD

**Issue by rebai-halim** [jfoenixadmin/JFoenix#122]
hi

i want to remove grid line from tableview but the vertical line it always display in tableview but i find this errors in my css file : 

1. Unknown property: "-fx-table-cell-border-color" 
2. "-fx-grid-lines-visible" is not supported by the given selectors

i use jdk 1.8.u92 , i know that javafx use by default modera.css (include in jfxrt.jar file) and where i open this file i found all css tags but in my css file i always find this errors (1 a 2) !!!!!!

---------------------------------------------------------------------------
@font-face not work to for me !!!!!!!!!

error :  "Only url-values are allowed"

in all docs avery one says that is work fine but in pratic not work 

-----------------------------------------------------------------------------

where is the problems ???

**Comment by jfoenixadmin** [comment]
please open issues related to jfoenix not javafx. 
Thanks
