### ISSUE TITLE
jfoenix responsive 

### ISSUE THREAD

**Issue by rebai-halim** [jfoenixadmin/JFoenix#123]
hi

how jfoenix responsive work ???

an exemple (java code if possible) and thanks

**Comment by jfoenixadmin** [comment]
Hi 

JFXResponsiveHandler applies one of a predefined pseudo classes to all the nodes in the scene. thus you can have a different css styles for each of the pseudo classes. You can simply apply it to your scene, by calling its constructor 

`new JFXResponsiveHandler( stage, JFXResponsiveHandler.PSEUDO_CLASS_MEDIUM)` 

there are 4 pseudo classes:

- **PSEUDO_CLASS_EX_SMALL** : "extreme-small-device"
- **PSEUDO_CLASS_SMALL** : "small-device"
- **PSEUDO_CLASS_MEDIUM** : "medium-device"
- **PSEUDO_CLASS_LARGE** : "large-device"

so in your css you can have different styles for each of the pseudo classes, for example,

```
.jfx-button:extreme-small-device{
-fx-pref-width:40;
-fx-pref-height:40;
} 

.jfx-button:medium-device{
-fx-pref-width:100;
-fx-pref-height:100;
} 
```
so the button will be resized according to the applied pseudo class.

**Comment by rebai-halim** [comment]
thanks 

i need to know how i can organize of change my layout (vbox to hbox or inverse) with jfoenix responsive

**Comment by rebai-halim** [comment]
Hi
you give me an exemple of css but how i can detect in real-time any change of my screen size to apply jfoenix responsice css for my components ?? there an listener in javafx css like html (@media) who responsable for any change for screen dimension (@media on html) ???

**Comment by jfoenixadmin** [comment]
No, you need to check the screen size in your application and decide which pseudo class to apply. To get the screen size you can do the following:

```
import javafx.application.Application;
import javafx.geometry.Rectangle2D;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.stage.Screen;
import javafx.stage.Stage;

public class Main extends Application {
    @Override
    public void start(Stage stage) {
        Group root = new Group();
        Scene scene = new Scene(root, 500, 200);
        stage.setScene(scene);

        Rectangle2D primaryScreenBounds = Screen.getPrimary().getVisualBounds();

        //set Stage boundaries to visible bounds of the main screen
        stage.setX(primaryScreenBounds.getMinX());
        stage.setY(primaryScreenBounds.getMinY());
        stage.setWidth(primaryScreenBounds.getWidth());
        stage.setHeight(primaryScreenBounds.getHeight());

        stage.show();
        
    }
    public static void main(String[] args) {
        launch(args);
    }
}
```
