### ISSUE TITLE
javafx css errors

### ISSUE THREAD

**Issue by rebai-halim** [jfoenixadmin/JFoenix#124]
1.  javafx css tag error :
         -fx-table-cell-border-color: transparent; -> Unknown property: "-fx-table-cell-border-color"
	 -fx-grid-lines-visible: false;  -> "-fx-grid-lines-visible" is not supported by the given selectors

what is the probleme here ???

2. where i can find all css tag for all components for jfoenix , in find 2 css file (jfoenix-design.css & jfoenix-componets.css) but all 2 not contains all componets jfoenix css , there is another css files contains reste of jfoenix compoents (like :  jfxtabpane)   

i use jdk 1.8-u92

**Comment by jfoenixadmin** [comment]
plz check the application ScenicView, it will help you tracking all the css style classes.

http://fxexperience.com/scenic-view/

**Comment by rebai-halim** [comment]
Hi

error to download scenic-view !!!!!!!!!

error :  C:\Users\halim\Downloads\Compressed\scenic-view-8.7.0.zip: Unexpected end of archive

what's happen ????
