### ISSUE TITLE
Hello,The developer of JFoenix,i can not open the official website.

### ISSUE THREAD

**Issue by pureimagine** [jfoenixadmin/JFoenix#1241]
Hello,The developments of JFoenix,recently,i know about this project which i can do lots of great thins in my school project .But i need more wiki to know ablout jow to use the controller of JFoenix.But i can not to open the wobsite of JFoenix to get help.Can everybody fix it.Thanks
![image](https://user-images.githubusercontent.com/28209291/175762898-ccaa6133-e062-4759-90e1-bd7df2340efe.png)

**Comment by ctoabidmaqbool** [comment]
Hum! it's looks like official domain e.g. jfoenix.com is expired!

**Comment by tolgayilmaz86** [comment]
and any plan to reactivate it?

**Comment by sshahine** [comment]
will close as its related to #1249
