### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by rebai-halim** [jfoenixadmin/JFoenix#125]
Hi

1.  add an float label for component JFXCombobox like jfxtextfields & jfxtextarea
2. change the icon (svg) for arrow button for jfxcombobox  
3. width of botton-border for jfxtextfield & jfxtextaera is son bold make thin

thanks

**Comment by rebai-halim** [comment]
Hi 

how to user badge & snakbar components for jfoenix (exemple of code please)

thanks

**Comment by jfoenixadmin** [comment]
you can check JFoenix Demo, it shows all of jfoenix controls.
