### ISSUE TITLE
How can I change the height to 10 of JFXToggleButton?

### ISSUE THREAD

**Issue by alansun2** [jfoenixadmin/JFoenix#1254]
How can I change the height to 10 of JFXToggleButton?

**Comment by DropSnorz** [comment]
Hi. I don't know what you need exactly, but I'm using the `setSize()` method to change the toggle button scale. The default size is 10.

```java
JFXToggleButton activeToggleButton = new JFXToggleButton();
activeToggleButton.setSize(5);
```

Example in [OwlPlug app](https://github.com/DropSnorz/OwlPlug):

![image](https://user-images.githubusercontent.com/15964929/215264016-d4124336-8b56-4fb7-8900-78aefae8c9d9.png)

**Comment by alansun2** [comment]
@DropSnorz thanks a lot for answer, in fact I just want to change JFXToggleButton's padding. Now I set the padding = -10.
