### ISSUE TITLE
TreeTableDemo

### ISSUE THREAD

**Issue by Ankursrivastavaaa** [jfoenixadmin/JFoenix#127]
I was working on Demo File TreeTableDemo.java, the problem which I faced was -

Follow this step:
1- Enter Some value on any Cell of Editable row.
2- Click on Some Other row (Do Not press tab)

The cell do not retain its value, if i click on tab the value is retained.
Please help me with a fix here.

**Comment by jfoenixadmin** [comment]
well this issue is related to javafx behavior, a solution would be to allow cancelEdit only when pressing escape key. However this issue might be fixed later by java, so i prefer to wait a bit before applying it in JFoenix.

Regards,

**Comment by Ankursrivastavaaa** [comment]
Its strange that Java Dev has not noticed such a big bug. 
Any suggestions how to bypass it? It makes TableView almost unusable

**Comment by jfoenixadmin** [comment]
sure you can extend GenericEditableTreeTableCell and force commit when selection is changed.
you can use the following class as the cell editor:

```
class AutoCommitEditor<S, T> extends GenericEditableTreeTableCell<S, T>{
		public AutoCommitEditor(EditorNodeBuilder builder) {
			super(builder);
			forceCommit();	
		}
		public AutoCommitEditor() {
			super();
			forceCommit();
		}
		private void forceCommit(){
			treeTableViewProperty().addListener((o,oldVal,newVal)->{
				if(newVal!=null)
					newVal.getSelectionModel().selectedItemProperty().addListener((obj,oldItem,newItem)->{
						commitHelper(true);
					});
			});	
		}
	}
```
so you need to use AutoCommitEditor insteadof GenericEditableTreeTableCell

**Comment by Ankursrivastavaaa** [comment]
I tried the above code snippet, still I am facing the same issue.The Control is coming to this position , but it is still not retaining its value.
Below is the sample of my code.
// While Initializing table
valueColumn.setCellFactory(
				(TreeTableColumn<Component, String> param) -> new GenericEditableTreeTableCellServiceImpl<Component, String>(
						new TextFieldEditorBuilder()));


public class GenericEditableTreeTableCellServiceImpl<S, T> extends GenericEditableTreeTableCell<S, T> {
	
	public GenericEditableTreeTableCellServiceImpl(TextFieldEditorBuilder textFieldEditorBuilder) {
		super(textFieldEditorBuilder);
		forceCommit();
	
	}

	public GenericEditableTreeTableCellServiceImpl() {
		super();
		forceCommit();
	}

	private void forceCommit() {

		treeTableViewProperty().addListener((o, oldVal, newVal) -> {
			if (newVal != null)
				newVal.getSelectionModel().selectedItemProperty().addListener((obj, oldItem, newItem) -> {
					System.out.println(Calendar.getInstance().getTime()+" Inside force Comit");
					commitHelper(true);
				});
		});
	}
}

**Comment by jfoenixadmin** [comment]
are you committing the new value in your data model?
you need to set on edit commit action by calling _valueColumn.setOnEditCommit(handler)_, the handler must change the actual value in your data model.

**Comment by Ankursrivastavaaa** [comment]
Yes. I was updating the value by calling valueColumn.setOnEditCommit(handler).

I just added tableName.refreshTable(); after updating the value in Data Model and it started working.

Thanks a lot !!!
We can close this issue now.
