### ISSUE TITLE
JFXTreeTableView- Extended Features

### ISSUE THREAD

**Issue by Ankursrivastavaaa** [jfoenixadmin/JFoenix#128]
Hi,

Please note this is not a bug. I wanted to confirm if these features are available in JFXTreeTableView.
1- If i want to Dynamically change the edit property of any Cell- e.g, based on some event I want to make cells editable or not , like in Swings there was isCellEditable()
2- Make a checkbox/Dropdown type of cell in a specific column depending on requirement.

**Comment by jfoenixadmin** [comment]
Hi yes sure, these features are available in TreeTableView thus they are available also in JFXTreeTableView.

**Comment by Ankursrivastavaaa** [comment]
How do we Implement it?
While Initializing Table for the first time we do :+1: 
nameColumn.setCellFactory(
				(TreeTableColumn<String, String> param) -> new GenericEditableTreeTableCell<>());

Which makes the cell editable.
Now If I have to make that cell dynamically editable, what should I do?
do I need to extend GenericEditableTreeTableCell class and override its methods?

**Comment by jfoenixadmin** [comment]
no, you just need to set nameColumn.setEditable(false);

**Comment by Ankursrivastavaaa** [comment]
nameColumn.setEditable(false); will make the entire column un-editable.  I want to check it at cell level.
When I click on a cell, I need to validate whether this cell is editable or not (This editable Property may not apply for entire column)

**Comment by jfoenixadmin** [comment]
1- no need to override the method updateItem() you can override startEdit() instead.
2- GenericEditableTreeTableCell is a generic cell that have an EditorNodeBuilder which is used to create the editor node, an example of EditorNodeBuilder is TextFieldEditorBuilder. 
you can create your own EditorNodeBuilder that shows any control you want whether it's a simple control (Check box/Dropdown/Custom Buttons,...) or a complex one.

**Comment by Ankursrivastavaaa** [comment]
It would have been great if we had an extra EditorNodeBuilder for Check box/Dropdown/Custom Buttons provided as default by JFoenix.
Please update me if you guys are planning to create new Classes for the same.

**Comment by jfoenixadmin** [comment]
Sorry there are no plans for that at the moment, as it's very trivial implementation. You can try to implement it yourself and add your contribution to JFoenix :) , an example is provided in **_TextFieldEditorBuilder_** class.
