### ISSUE TITLE
JFXButton with icon doesn't ripple in any case

### ISSUE THREAD

**Issue by rjahn** [jfoenixadmin/JFoenix#13]
Simply create a JFXButton with text and icon, e.g.
Add this

```xml
<graphic>
  <Icon awesomeIcon="REPLY" size="1.5em" style=";"styleClass="option-jfx-list-view-icon" />
</graphic>
```
to a button in your Button.fxml (demo application) or use:

```java
JFXButton butt = new JFXButton("BUTTON A");
butt.setButtonType(ButtonType.RAISED);
butt.setStyle("-fx-font-size:14px;-fx-background-color:WHITE;");
butt.setGraphic(new Icon(AwesomeIcon.USER, "1.5em", ";", "option-jfx-list-view-icon"));
```

If you hover over the text, the cursor won't change to hand (css thing), but if you press the left mouse button over the text, the rippler does nothing. The shadow-effect works.

**Comment by jfoenixadmin** [comment]
Fixed, thanks for pointing it out.
