### ISSUE TITLE
Custom text formatting for slider values

### ISSUE THREAD

**Issue by SamCarlberg** [jfoenixadmin/JFoenix#136]
The default behavior of the JFXSlider text is to round the slider value to the nearest `long` and display that. This is a problem when the decimal values are important. Right now I'm getting around this by subclassing `JFXSliderSkin` and using reflection to get the `sliderValue` Text, remove the default binding, and add my custom one. It would be great to be able to at least expose the `sliderValue` variable to subclasses, or a method to explicitly set a `Callback<JFXSlider, StringBinding>` for a custom text binding.

**Comment by jfoenixadmin** [comment]
your suggestion has been added to JFXSlider control.
