### ISSUE TITLE
MansoryPaneController

### ISSUE THREAD

**Issue by FlavioRossi** [jfoenixadmin/JFoenix#138]
![image](https://cloud.githubusercontent.com/assets/8763674/17782005/003bb6be-6548-11e6-86a6-fd62fd0ff462.png)

![image](https://cloud.githubusercontent.com/assets/8763674/17782027/2041b864-6548-11e6-8611-889b3657b927.png)

I Can't find the problem

**Comment by jfoenixadmin** [comment]
i think jfoenix.jar is not included in your classpath properly.
