### ISSUE TITLE
Using JFXDialog without Flow API

### ISSUE THREAD

**Issue by DevenBhalerao** [jfoenixadmin/JFoenix#139]
I only need to display an error message or an information message. Including Flow Api in my project just for this would be overkill. Is there any alternate way to do it? Like manually passing instances of stackpane and region?

**Comment by jfoenixadmin** [comment]
Please note that the Flow API is used in JFoenix Demo, and all of JFoenix controls are not dependent on any 3rd party api/jar.

you can use JFXDialog directly in your code using:

`dialog = new JFXDialog(dialogContainer, content, transitionType) `
