### ISSUE TITLE
JFXButton triggers action on shadow click

### ISSUE THREAD

**Issue by rjahn** [jfoenixadmin/JFoenix#14]
Create a RAISED Button and click with the mouse on the shadow outside of the "visible button area".
The button action will be triggered.

Simply test it with main demo application (Dialogs).

It's not a big problem, but it's unusual to use/click the shadow.

**Comment by benjaminfoo** [comment]
I think its because the input-eventhandlers are registered on the complete node (+shadow effect) - not the actual panel of the node.

**Comment by rjahn** [comment]
This isn't a problem on mobile devices, because fingers aren't as small as mouse pointers.

**Comment by jfoenixadmin** [comment]
Fixed.
