### ISSUE TITLE
JFXListView cell factory customization

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#143]
Hi,
I want to know if it's possible for your to let users define their own custom view for an item in JFXListCell?
As I can see, you create a new Label instance using this code:
`newNode = new Label(item.toString());`

I need a way of creating complex item views. I suggest you let users do this using extension: Introduce a protected method which creates the same label by default. this way one may override it to change its behavior.

let me know if it's OK?
thanks

**Comment by jfoenixadmin** [comment]
Hi, 
You can already do that by extending JFXListCell and overriding the method updateItem. all that you need to do is to update the graphic of the cell or set it to null if you don't want to show it.

**Comment by aminabs** [comment]
The point is to keep all your code (the ripple, sublist, etc) and have custom item views. You please take a look at your code and give an answer to the following question:
How can I create a, let say, Hbox with two labels inside, for a JFXListView of User items where User is a simple java class which, let say, have a string 'name' and an integer 'id' fields. the first label is to show the name and the second is to show the id, for example.

I think the most simple way of doing such customization is through extension if possible.

**Comment by jfoenixadmin** [comment]
please check the previous answer, thanks.

**Comment by jfoenixadmin** [comment]
Here is an example to make it clear:

``` JAVA
list.setCellFactory(new Callback<ListView<User>, ListCell<User>>() {
			@Override
			public ListCell<User> call(ListView<User> param) {
				return new JFXListCell<User>(){
					@Override
					public void updateItem(User item, boolean empty) {
						super.updateItem(item, empty);
						if(item!=null && !empty){
							HBox container = new HBox();
							container.setMouseTransparent(true);
							container.getChildren().add(new Label(item.getName()));
							container.getChildren().add(new Label(item.getId()));
							setGraphic(container);
						}
					}
				};
			}
		});
```
