### ISSUE TITLE
Bug with JFXDatePicker

### ISSUE THREAD

**Issue by bares1993** [jfoenixadmin/JFoenix#147]
@FXML
    private JFXDatePicker datapickerDateOfBirth;

            System.out.println(datapickerDateOfBirth.getEditor().getText());

If i pick a date in my JavaFX GUI than try to get the value of the datapicker, the value is always the empty String .... 

if i use the original javafx datapicker with the same method there is no problem

**Comment by jfoenixadmin** [comment]
Hello, 

what you need to call is datePickerFX.getValue() instead of getEditor().getText().
also when are you calling the sysout command? can you provide the full code if possible? 
otherwise i need to close this issue, as it's not valid.

**Comment by bares1993** [comment]
That was the solution....ty very much
