### ISSUE TITLE
Setting default rippler fill doesn't work for JFXButton with graphic

### ISSUE THREAD

**Issue by rjahn** [jfoenixadmin/JFoenix#15]
If you have a button with an icon/graphic, the rippler fill is wrong. You check if the first children is a Label or LabeledText in JFXButtonSkin... I guess this isn't correct :)

There shouldn't be a rippler-fill difference between buttons with and without graphic.

**Comment by rjahn** [comment]
This worked for me (maybe not as generic as you need it?)

```java
Node ndChild = getChildren().get(getChildren().size() - 1);

if(ndChild instanceof LabeledText){
	buttonRippler.setRipplerFill(((LabeledText)ndChild).getFill());			
	((LabeledText)ndChild).fillProperty().addListener((o,oldVal,newVal)-> buttonRippler.setRipplerFill(newVal));
}else if(ndChild instanceof Label){
	buttonRippler.setRipplerFill(((Label)ndChild).getTextFill());			
	((Label)ndChild).textFillProperty().addListener((o,oldVal,newVal)-> buttonRippler.setRipplerFill(newVal));
}
```

**Comment by jfoenixadmin** [comment]
Fixed, thanks for pointing the issue. however since the implementation of ButtonSkin might be changed later, we prefer to check all children instead of the last one.

**Comment by rjahn** [comment]
Was a temp fix for me. Your solution is as it should be :)
