### ISSUE TITLE
TreeTableView Column Resize Policies

### ISSUE THREAD

**Issue by baegmon** [jfoenixadmin/JFoenix#150]
Hi,
I've been using JFXTreeTableView and I noticed that Column Resize Policies do not work for JFXTreeTableView.

Is that a bug or is there a different way to set policies for JFXTreeTableView?

**Comment by jfoenixadmin** [comment]
Hi, can you provide a sample code? 
i tested the column resize policy and it's working:

````JAVA
treeView.setColumnResizePolicy(TreeTableView.CONSTRAINED_RESIZE_POLICY);
````

make sure to use the TreeTableView resize policy.
