### ISSUE TITLE
JFXToggleButton styled with css does not work properly

### ISSUE THREAD

**Issue by gitman89** [jfoenixadmin/JFoenix#151]
![isssue](https://cloud.githubusercontent.com/assets/12411598/18404816/44fc6e86-76ed-11e6-821c-e00315dc67d8.png)

I use JFXToggleButton in Menu:
`JFXToggleButton toggleSwitch = new JFXToggleButton();
CustomMenuItem customMenuItem = new CustomMenuItem(toggleSwitch);`

I styled JFXToggleButton  to have blue color as a main theme in my app using css:
`.jfx-toggle-button{
  	-fx-toggle-color: -blue-item-color;
	-fx-padding: -14 0 -14 0;	
}`

Now when my app starts and I go to menu I see toggled buttons are marked with green color (default one) - see pic 1

When I go to this menu again after some time toggled buttons are without any color - see pic 2

Now at any moment of using app If I toggle off and back on button it gets correct color - see pic 3

Please note all three pictures where taken without restarting app. Also app dose not swap css on runtime. 

By the way great job with this lib!

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for pointing out the issue, it's been fixed :+1: 
<a href="http://www.jfoenix.com/download/jfoenix.jar">download</a> the latest version of JFoenix to get the fix.

**Comment by gitman89** [comment]
Hi,
I just download new jar and I see that behaviour is better but still not fully proper.
Now it works like this:
When I open menu for the first time toggled togglebuttons still got green color.
When I open the same menu for the second (and any next time) toggled button got proper  - blue color.

To comparewith previous behaviour it is like jumping from step 1 to step 3 without having to toggle off and back on button.

**Comment by jfoenixadmin** [comment]
Hello, 
the issue has been fixed in the latest version.
<a href="http://www.jfoenix.com/download/jfoenix.jar">download</a> the latest version of JFoenix to get the fix.

**Comment by gitman89** [comment]
Hi,
I can confirm that last version is working fine in all cases.
Thank you for your support!
