### ISSUE TITLE
center text align for text field

### ISSUE THREAD

**Issue by MetaiR** [jfoenixadmin/JFoenix#153]
hi
`alignment="CENTER"` has no effect in the blow code
`<JFXTextField alignment="CENTER" layoutX="99.0" layoutY="19.0" />`
so how to set text align to center?

**Comment by jfoenixadmin** [comment]
please note that alignment is an attribute related to the position of the control (textfield in your case), it's not related to text alignment inside the text field. 
if you are trying to use the text field in RTL language, you need to set the node orientation to RTL:

`field.setNodeOrientation(NodeOrientation.RIGHT_TO_LEFT);`
