### ISSUE TITLE
JFXTextField doesn't enable keyboard on android

### ISSUE THREAD

**Issue by tiagoRodrigues23** [jfoenixadmin/JFoenix#154]
hi
I recently compiled a project for android using javaFX Ports and i used some jfxtTextField
for input data, but when i try to input some text in one of these components
the android keyboard doesn't appear, i tested with a normal
TextField and all works great, Can you help me?

**Comment by jfoenixadmin** [comment]
plz note that you need to <a href="http://www.jfoenix.com/download/jfoenix-0.0.0-SNAPSHOT-retrolambda.jar">download</a> and use the retrolambda build of JFoenix which is android compatible.

**Comment by tiagoRodrigues23** [comment]
OK i'll try it
is this available in maven repository?

**Comment by jfoenixadmin** [comment]
yes

**Comment by tiagoRodrigues23** [comment]
Ok, thanks for your support.
