### ISSUE TITLE
Dialog box

### ISSUE THREAD

**Issue by MetaiR** [jfoenixadmin/JFoenix#158]
is there any tutorial about how to make and use dialog box with their transition?
and is there any general tutorial for make something like demo app?

**Comment by jfoenixadmin** [comment]
well you can check JFoenix site for the documentation, however it doesn't cover all controls yet:
http://jfoenix.com/documentation.html

also you can check the youtube channel "Genuine Coder"
https://www.youtube.com/channel/UCCXbhmjID-T2I0KfuDPbi6A

he posted some tutorials about using JFoenix.

**Comment by MetaiR** [comment]
@jfoenixadmin 
as you say too, **they are not cover all controls**

**Comment by furjoy** [comment]
Generating javadoc and reading them does help me though.

**Comment by MetaiR** [comment]
@furjoy 
can you say How?\

**Comment by furjoy** [comment]
Just run
```bash
gradlew javadoc
```
and find the generated javadoc under ```subprojects/jfoenix/build/docs/javadoc/```
