### ISSUE TITLE
Frame of Checkbox that starts checked is colored

### ISSUE THREAD

**Issue by Gikkman** [jfoenixadmin/JFoenix#159]
I found this issue today when I tried using your library. 

If you create a JFXCheckbox, and sets it to SELECTED in SceneBuilder, then change the Un Checked Color to red and its Checked Color to green, then launch the application, your checkbox will have a bright red frame around it. However, if you now uncheck the box and re-check it, the red frame will dissapear.

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue :+1:  it's been fixed in the latest version of JFoenix.
