### ISSUE TITLE
Library footprint

### ISSUE THREAD

**Issue by benjaminfoo** [jfoenixadmin/JFoenix#16]
Hello world, 

first of all, great work on the project, I really like it. However, I think the dependencies are to heavy for a javafx ui framework... is it possible to use jfoenix without the complete datafx-project for example?

**Comment by jfoenixadmin** [comment]
Hello,
Yes sure, DataFX is used for demonstration only. JFoenix is not dependent on DataFX.

**Comment by rjahn** [comment]
FontAwesome is the only dependency.

**Comment by jfoenixadmin** [comment]
it will be removed from the library, as we already implemented our own SVGGlyphLoader. you can check the updated demo.

**Comment by benjaminfoo** [comment]
Sweet, thank you for the feedback :+1:
