### ISSUE TITLE
ListView Expanded at true does not work

### ISSUE THREAD

**Issue by kevincaradant** [jfoenixadmin/JFoenix#161]
Hi

I think I miss something. I can't have a list expanded even when I have: `list.setExpanded(true);` Do you have any idea why ? Any CSS or something else to add ? Thank you

```
			//LEFT MENU
			JFXDrawer leftDrawer = new JFXDrawer();
			JFXListView<Label> list = new JFXListView<Label>();
			for(int i = 0 ; i < 3 ; i++) list.getItems().add(new Label("Item " + i));
			list.depthProperty().set(1);
			list.setExpanded(true);
			StackPane leftDrawerPane = new StackPane();
			leftDrawerPane.getChildren().add(list);
			leftDrawer.setSidePane(leftDrawerPane);
			leftDrawer.setDirection(DrawerDirection.LEFT);
			leftDrawer.setDefaultDrawerSize(150);
			leftDrawer.setOverLayVisible(true);
			leftDrawer.setResizableOnDrag(true);
//			
//			
//			//DRAW CONTENT
			JFXDrawersStack drawersStack = new JFXDrawersStack();
			drawersStack.setContent(menuPane);
			h3.addEventHandler(MouseEvent.MOUSE_PRESSED, (e)->{
				burgerTask2.setRate(burgerTask2.getRate()*-1);
				burgerTask2.play();
				drawersStack.toggle(leftDrawer);
			});
```

**Comment by jfoenixadmin** [comment]
well you need set the vertical gap value, by default it's set to 0
so you need to call:

`list.setVerticalGap(20.0);`

there is a fix regarding computing the listview height, it's pushed in JFoenix latest version.

**Comment by kevincaradant** [comment]
I don't see any difference :/. And I download the jar yesterday, I think I have the lastest version :)

**Comment by jfoenixadmin** [comment]
did you set the vertical gap?

**Comment by kevincaradant** [comment]
Yes. I refactor my project. Now I'm under Scene Builder but the problem is still here.

As you can see at the right top, I set the verticalGap and I don't see any diffrence. 

Look at my structure, maybe it's the reason :/, sorry I'm new, so I don't know how I can help you.

![image](https://cloud.githubusercontent.com/assets/6093175/18904833/654685e2-8560-11e6-9c53-32f2f7286bc8.png)

**Comment by jfoenixadmin** [comment]
you need to set the vertical gap not the current vertical gap

**Comment by jfoenixadmin** [comment]
please note that you need to set a value for the vertical gap and set expanded to true. 
not sure why the scene builder is not showing the expanded property, however you can set it through FXML or CSS

- FXML   `<JFXListView ...   expanded="true">`
- CSS        `-fx-expanded: true`

**Comment by kevincaradant** [comment]
Ah yes thank you:  -fx-expanded: true works

**Comment by sylmoss** [comment]
-fx-expanded: true
Is the only one that works for me too.

**Comment by Setcch** [comment]
-fx-expanded: true works for me too. Thanks

**Comment by Pieprzyk** [comment]
.jfx-list-view {
    -fx-expanded: true
}

for me it still do not work I tried to do

list.setExpanded(true);
list.setExpanded(false);
list.setExpanded(true);

and it works with labels in list but while I changed the node to VBox in list then last of items is empty I did the debug and VBox got nodes but they are not showing in list the box is empty when list is expanded however while it's not then it's showing properly

**Comment by jfoenixadmin** [comment]
Hello, plz note that the css property is:
`-jfx-expanded` instead of `-fx-expanded` this was changed a long time ago.

**Comment by sayeedajmal** [comment]
> please note that you need to set a value for the vertical gap and set expanded to true. 
> not sure why the scene builder is not showing the expanded property, however you can set it through FXML or CSS
> - FXML   `<JFXListView ...   expanded="true">`
> - CSS        `-fx-expanded: true`
> 

Its giving in scene builder..
 Expended & vertical gap..
