### ISSUE TITLE
Question: How can fill properly the JFXlistView with a fxml file using SceneBuilder ?

### ISSUE THREAD

**Issue by kevincaradant** [jfoenixadmin/JFoenix#163]
Hi,

I copy/past this in my own file:

```
<JFXListView fx:id="list1" styleClass="custom-jfx-list-view"
			layoutX="0" layoutY="50">
			<Label>Item 1</Label>
			<JFXListView fx:id="subList" styleClass="sublist">
				<groupnode>
					<Label> My Sub List </Label>
				</groupnode>
				<Label> Buttons </Label>
				<Label> Check Box </Label>
			</JFXListView>
			<Label>Item 2</Label>
			<Label>Item 3</Label>
			<Label>Item 4</Label>
			<JFXListView fx:id="subList1" styleClass="sublist">
				<groupnode>
					<Label> My Sub List </Label>
				</groupnode>
				<Label> Buttons </Label>
				<Label> Check Box </Label>
			</JFXListView>
			<Label>Item 6</Label>
			<Label>Item 7</Label>
			<Label>Item 8</Label>
		</JFXListView>

```
Directly in the fxml file ... that works but it's really bad I guess. 
Someone can help me on this subject. 
Create items and groupenode. Even on internet I don't find any information about it :/
Thank you

**Comment by jfoenixadmin** [comment]
please note that not all controls are compatible with scene builder, it needs some customization from the scene builder side in order for it to work properly. feel free to open a request in the scene builder bitbucket repository 

https://bitbucket.org/gluon-oss/scenebuilder

**Comment by kevincaradant** [comment]
Thank you ;)
