### ISSUE TITLE
Bug: Problem with the JFXRadioButton name

### ISSUE THREAD

**Issue by kevincaradant** [jfoenixadmin/JFoenix#164]
I let show you this picture:
![image](https://cloud.githubusercontent.com/assets/6093175/18919220/98003fd6-859d-11e6-9d51-2d7fc7c7aa90.png)

On the top left, it's a normal radioButton.
Others are yours.
As you can see when you have "name_joke", it's appears at the end like "namejoke".

Edit: Maybe, it's a bug of SceneBuilder but I don't know so I created this issue. I let you to me know ;)

**Comment by jfoenixadmin** [comment]
well i tried the previous example and it seems that Scenebuilder has its own skin for the Radiobutton as we were able to reproduce the issue using Java RadioButton control.
also after debugging the issue, it seems its related to updateDisplayedText method in LabeledSkinBase.
will work on fixing the issue in JFXRadioButtonSkin, thanks for pointing out the issue :+1:

**Comment by kevincaradant** [comment]
OK let me know when I can upgrade the version of JFoenix from Maven :)

**Comment by jfoenixadmin** [comment]
the changes have been pushed to maven (snapshot / official release v1.0.0) along with JFXRadioButton rework.

**Comment by kevincaradant** [comment]
Perfect :) Thanks.
Just one thing. How can you update your library with Maven if you keep the same version? Maybe the last time if you can upgrade in minor version so 1.0.1 that will be more easily because I have to remove it directly in .m2 folder because, I didn't success to say at Maven, take the last update. I tried to build the project with the task 'packages' and also do a 'Maven Update' but it was a fail.
