### ISSUE TITLE
JFXDecorator closes all the application and not only his own window

### ISSUE THREAD

**Issue by kevincaradant** [jfoenixadmin/JFoenix#166]
I use JFXDecorator to make some popups Dialog. 
The problem is when I apply JFXDialog on them, when I close the popup, all my application is closed :/ 
Any issue about it or bad use from me ?

**Comment by jfoenixadmin** [comment]
By default the close button in JFXDecorator calls Platform.exit() which will close your application.
however what you need to do is to change the close action by calling 

`decorator.setOnCloseButtonAction(Runnable);`

**Comment by kevincaradant** [comment]
yep it works thanks :)
