### ISSUE TITLE
AnimatedFLowContainer is not present in your repo ? 

### ISSUE THREAD

**Issue by kevincaradant** [jfoenixadmin/JFoenix#168]
I tried your AnimatedFlowContainer in your demo, it's perfect.

But AnimatedFlowContainer  is not contained in your repo (.jar) like a Class which can call it ? Have I miss something or I have to add the Java file in my project to use it? 

Thank you :)

**Comment by jfoenixadmin** [comment]
Hello, plz note that AnimatedFlowContainer is part of the demo only ( it's used in DataFX Framework).
it's not part of JFoenix jar. so if you want to use it then yes you have to add the java file to your project.

Regards,

**Comment by kevincaradant** [comment]
OK, I do that. Thanks
