### ISSUE TITLE
Possible upgrade to the latest Fontawesome library with material design  font ? 

### ISSUE THREAD

**Issue by kevincaradant** [jfoenixadmin/JFoenix#169]
Hi

I see,  you are using an old library of font awesome.  I still don't use the new,  but now,  there are a lot of font in material design etc available with the last version.  I don't know if that can interest you but it's a suggestion to upgrade :)

**Comment by jfoenixadmin** [comment]
Fontawesome is only used in the demo, and it's not part of JFoenix (upgrading fontawesome library is not part of JFoenix development). There is a JFoenix control called SVGGlyph that you can use to show any svg image in your application.
