### ISSUE TITLE
How we use JFoenix

### ISSUE THREAD

**Issue by rjahn** [jfoenixadmin/JFoenix#17]
This is an information issue for the project leads, if you want to see some use-cases:

We have some Screenshots of our generic mobile application:
http://blog.sibvisions.com/2015/10/21/code-once-run-anywhere/

And a video (it's about live css hacking, but...)
https://www.youtube.com/watch?v=fnooIzGUxFk

**Comment by jfoenixadmin** [comment]
cool framework :+1:
