### ISSUE TITLE
how to change close property of dialog and drawer

### ISSUE THREAD

**Issue by MetaiR** [jfoenixadmin/JFoenix#170]
hello,
I want to close the navigation and dialog box when ever some function's are passed but when user click on other side of my application (somewhere which not in dialog or navigation box body) these are closed automaticly, how to solve this matter?

**Comment by MetaiR** [comment]
yessssssssssssss,
thank uuuuuu,
could you tell me how to get more information about this library components?

**Comment by kevincaradant** [comment]
I don't know what can I answer. I ask also a lot of questions here :). In the other side,  I watch and analyze the demo in this repository,  you have a lot of examples inside.  After with Eclipse or an other IDE,  you can make some examples,  and for example,  the overlay method,  I discovered it yesterday,  I tried a lot of setters methods to see their use and the component behavior :).  Maybe the author of this repository may help you more than I can. Don't forget to close the issue if you think it's good. Anyway,  Good continuation :)

**Comment by jfoenixadmin** [comment]
Feel free to check the JFoenix demo, it provides many examples. you can also find a basic tutorial on JFoenix website ( however it needs to be updated , as it doesn't cover all the controls and JFoenix features )

http://jfoenix.com/documentation.html#Button

Regards,
