### ISSUE TITLE
JFXSlider

### ISSUE THREAD

**Issue by ManOfGod** [jfoenixadmin/JFoenix#174]
How can I change the color of the JFXSlider? how can I hide the circle track if the slider is inactive?

**Comment by jfoenixadmin** [comment]
to change the color of JFXSlider you can check #160, hiding the circle track if the slider is inactive is not implemented in JFXSlider skin. Feel free to add your own contribution to the library.

Regards,

**Comment by ManOfGod** [comment]
I'm still new to JavaFX so maybe some time I can make a PR for this. At this point I'm still learning the basics of the framework.
