### ISSUE TITLE
JFoenix drawer hide & draw funciton not  appearing

### ISSUE THREAD

**Issue by badarshahzad** [jfoenixadmin/JFoenix#177]
I am stuck on this point I searched a lot but didn't find suitable answer what should I do to bring drawer from left side. 

- I want when user click the Hamburger the drawer should appear and when again click on drawer then it should hide? functions are not working hide and draw?

drawer.setOnDrawerClosed();
drawer.setOnDrawerOpened();
I find this from discussion! if this is the last option then how to use it

```
HamburgerBasicCloseTransition burgerClose = new HamburgerBasicCloseTransition(hamburger);
		burgerClose.setRate(-1);
		hamburger.addEventHandler(MouseEvent.MOUSE_PRESSED, (e)->{
			burgerClose.setRate(burgerClose.getRate()*-1);
			burgerClose.play();
			
			if(drawer.isShown())
                                  drawer.hide
			else
                                 drawer.draw
//not working
				
			
		});
```

**Comment by badarshahzad** [comment]
I solved the problem by just adding drawer.open and drawer.close.
Thank you for JFoenix

**Comment by rootedKen** [comment]
thank you

**Comment by badarshahzad** [comment]
Welcome :+1:
