### ISSUE TITLE
Using JFoenix in Intellij-idea-ce

### ISSUE THREAD

**Issue by Clumsy-Coder** [jfoenixadmin/JFoenix#178]
I would like to use JFoenix in Intellij-Idea-CE as a library and be able to export it to a JAR. How do I add to Intellij-Idea? I noticed the README.md had information about adding a dependancy using Maven, can it be done with Gradle? Do I need to precompile it before I add it as a dependancy?

**Comment by emcastro** [comment]
The explanation in the README.md, even if the title is Maven, are for
Gradle.

2016-10-18 21:22 GMT+02:00 Muhammad Umar Bari <notifications@github.com>:

**Comment by jfoenixadmin** [comment]
the README.md contains information about using JFoenix from Maven central in Gradle Project.
Note that JFoenix already using Gradle as a build tool.
