### ISSUE TITLE
JFXProgressBar NPE on switching indeterminate state

### ISSUE THREAD

**Issue by aNNiMON** [jfoenixadmin/JFoenix#18]
If  `JFXProgressBar`was initialized by non-indeterminate value, then trying to set progress to -1 causes `NullPointerException` at  [JFXProgressBarSkin.java:68](https://github.com/jfoenixadmin/JFoenix/blob/master/src/com/jfoenix/skins/JFXProgressBarSkin.java#L68)
Here's sample program to reproduce issue:

```java
@Override
public void start(Stage primaryStage) {
    ProgressBar pb = new ProgressBar(5);
    JFXProgressBar jfxpb = new JFXProgressBar(5);
    Button button = new Button("Set indeterminate");
    button.setOnAction(e -> {
        pb.setProgress(-1);
        jfxpb.setProgress(-1);
    });
    Scene scene = new Scene(new VBox(button, pb, jfxpb), 200, 200);
    primaryStage.setScene(scene);
    primaryStage.show();
}
```

**Comment by jfoenixadmin** [comment]
Fixed, thanks for pointing out the issue.
