### ISSUE TITLE
css color for JFXTabPane

### ISSUE THREAD

**Issue by mokun** [jfoenixadmin/JFoenix#180]
how do I change the background color, text color and the tabs color in JFXTabPane ?

Your website said the DEFAULT_STYLE_CLASS is jfx-tab-pane

So, I created : 

.jfx-tab-pane {
    -fx-text-fill: red; 
    -fx-background-color: orange; 
}

But they change the color partially for me.

Do I need to create my own JFXTabPaneSkin.java ? 

thanks much

**Comment by sluedecke** [comment]
I use this to style my tabbar:

```
/*
    The tab bar
*/

.jfx-tab-pane .headers-region {
    -fx-background-color: #1b75bc;
}
.jfx-tab-pane .tab-header-background {
    -fx-background-color: #1b75bc;
}
.jfx-tab-pane .tab-selected-line {
    -fx-stroke: #75bc1b;
    -fx-stroke-width: 3pt;
}
```

**Comment by jfoenixadmin** [comment]
this issue is related to #145
