### ISSUE TITLE
JFXRadioButton broken if used with graphics

### ISSUE THREAD

**Issue by sluedecke** [jfoenixadmin/JFoenix#181]
Commit 4660375c6e6d369e6b71c2bc6d89627a6603ee63 introduced a change where the first children is cast into a text.  When an image is set with setGraphics, the first children is no longer the text, but the image and thus the class cast fails.

**Comment by jfoenixadmin** [comment]
thanks for pointing out the issue :+1:

**Comment by jfoenixadmin** [comment]
it's been fixed in the latest version of jfoenix.

**Comment by jfoenixadmin** [comment]
JFoenix jar has been updated, you can download it <a href="http://www.jfoenix.com/download/jfoenix.jar">here<a/>
