### ISSUE TITLE
Simple swtich between JFoenix and native look

### ISSUE THREAD

**Issue by Kaito23** [jfoenixadmin/JFoenix#182]
hey,

I'm would like to use JFoenix on my current project.
But I want the user to decide if he wants the default javafx look
or the material design look.
**Is there a simple way to disable JFoenix?**
Only approach I had would be a singleton class, that
collects all the components and places and removes the classes
on the elements.

Notice by the way: I'm programming the frontend by hand,
I do not use the scene builder.

Greetings
Kaito

And I just leave a "GREAT WORK" here :)

**Comment by jfoenixadmin** [comment]
Hello, 
well what you can do is to use the factory pattern to generate the ui controls. so you have an interface that provides ui controls, and two different implementations  javafx / JFoenix.

An example of factory pattern:
https://www.tutorialspoint.com/design_pattern/factory_pattern.htm
