### ISSUE TITLE
How to add children dynamically using JFXMasonryPane ?

### ISSUE THREAD

**Issue by salwyn** [jfoenixadmin/JFoenix#183]
Hi, I like JFXMasonryPane very much. The only thing I can't understand is how to add children dynamically? Pseudo code as below:
`button.setOnClick(e -> {
    masonryPane.getChildren().add(new Label("test"));
});
`
I tried a lot but can't see "test" labels, do I really need to modify JFoenix source code?

**Comment by jfoenixadmin** [comment]
Hi, 
will debug this, thanks for pointing out the issue :+1: 

Regards,

**Comment by jfoenixadmin** [comment]
the issue has been fixed, you can test it using the latest JFoenix jar
this fix is not yet pushed to maven central, it will be pushed by the end of the month.

Regards,

**Comment by salwyn** [comment]
Thank you very much admin, sorry for the late reply~
I'll try it ASAP. :-) :+1:
