### ISSUE TITLE
how to use with jfxports on android?

### ISSUE THREAD

**Issue by samuaz** [jfoenixadmin/JFoenix#185]
how to correct build or use complied JFoenix jar with jfxports?

I try downloanding the compiled jar and also the retrolambda version, gradle build ok the app... but when i open it on my android the app crash, and if i download the source and build jfoenix, gradle cant build my app give this error https://github.com/jfoenixadmin/JFoenix/issues/184

any guide to use it correctly with jfxports?

thanks

**Comment by jfoenixadmin** [comment]
you can check the link below, it provides an example of JavaFXPorts eclipse plugin. you can try to run a simple javaFX example, then try to use JFoenix retrolambda jar

http://gluonhq.com/the-new-gluon-plugin-for-eclipse/
