### ISSUE TITLE
How to rightly remove Treeitem in JFXTreeTableView?

### ISSUE THREAD

**Issue by mrjcnby** [jfoenixadmin/JFoenix#186]
When i try to delete (remove) TreeItem in JFXTreeTableView ( `FXCollections.observableArrayList().remove() and getChildren().remove()`) - item will be deleted in .getChildren(), but don't deleted at originItems . So after that, when i try to group column- i will see deleted items. What's wrong?

**Comment by jfoenixadmin** [comment]
It should work both ways, thanks for pointing out the issue :+1:

**Comment by jfoenixadmin** [comment]
the issue has been fixed you can test it using the latest version of JFoenix
