### ISSUE TITLE
Can not be used JFXComboBox with javafxports on Android

### ISSUE THREAD

**Issue by ltorok** [jfoenixadmin/JFoenix#188]
Android logcat output:
[log.txt](https://github.com/jfoenixadmin/JFoenix/files/562115/log.txt)

Android 6 and bellow dont support streams - forEach method etc.
See: row 188 in com.jfoenix.controls.JFXListCell where is: getChildren().forEach((child)->{

**Comment by ltorok** [comment]
Here is patch:
`protected void makeChildrenTransparent(){
		/*getChildren().forEach((child)->{
			if(child instanceof Label || child instanceof Shape){
				child.setMouseTransparent(true);
			}
		});*/		
		
		for (Node child : getChildren()) {
			if(child instanceof Label || child instanceof Shape){
				child.setMouseTransparent(true);
			}
		}
	}`

**Comment by jfoenixadmin** [comment]
the issue has been fixed, thanks for pointing out the issue  :+1: 

Regards,
