### ISSUE TITLE
Upgrade to FontAwesomeFX 8.5 possible?

### ISSUE THREAD

**Issue by pajoma** [jfoenixadmin/JFoenix#19]
I am using the JFXTabPane, which depends on the class de.jensd.fx.fontawesome.Icon. You have version 8.0.10 in your libs folder.  Since I am also using FontAwesomeFX in version 8.5, I am running into problems. Is it possible to update JFoenix?

**Comment by jfoenixadmin** [comment]
Fixed, we removed FontAwesomeFX from JFoenix, JFoenix is no longer dependent on FontAwesome. We already have our own implementation to deal with SVG glyphs using the classes SVGGlyph and SVGGlyphLoader.
Feel free to pull the latest changes or download the jar file to get the fix.
