### ISSUE TITLE
Cannot use rippler in different shape

### ISSUE THREAD

**Issue by guoyiteng** [jfoenixadmin/JFoenix#190]
When I try to use a rippler in a polygon, it says that it only takes an region instead of a shape. Then, I try to create a label in a polygon shape and use the rippler effect, the shape of rippler is still a rectangle. The setShape method in rippler does not work. When I try to use a JFXButton in a polygon shape, the setShape method does not work either.
Thus, I cannot find a workaround for this issue.

**Comment by jfoenixadmin** [comment]
you can test it using the latest JFoenix jar, plz note that the changes are not yet pushed to maven central.
