### ISSUE TITLE
How to add listerner for TableView cell or row change ?

### ISSUE THREAD

**Issue by HekmatFavid** [jfoenixadmin/JFoenix#194]
I want when i clicked TableView row or cell, something like rowchanged event, print 
rowID of selected row or table cell content to console by sout statement.
Thanks

**Comment by jfoenixadmin** [comment]
Hello, you can either add a ListChangeListener to table view items, or implement a custom cell factory that print the row index / item of the current cell.

Regards,

**Comment by HekmatFavid** [comment]
Thank's for your help 
i can do by this code

        usersTreeTableView.setRowFactory(tv->{
            JFXTreeTableRow<UserRecursive> row = new JFXTreeTableRow<>();
            row.setOnMouseClicked(event -> {
                    UserRecursive rowData = row.getItem();
                    System.out.println(rowData.id);
            });
            return row ;
        });

**Comment by HekmatFavid** [comment]
Thank's for your help 
i can do by this code

        usersTreeTableView.setRowFactory(tv->{
            JFXTreeTableRow<UserRecursive> row = new JFXTreeTableRow<>();
            row.setOnMouseClicked(event -> {
                    UserRecursive rowData = row.getItem();
                    System.out.println(rowData.id);
            });
            return row ;
        });
