### ISSUE TITLE
Editable TreeTableView Boolean Data Type

### ISSUE THREAD

**Issue by HekmatFavid** [jfoenixadmin/JFoenix#195]
Is the way for Using  other type of method instead of (TextFieldEditorBuilder) that only accept String types for Boolean and Integer or other data types?
Thank you.

**Comment by jfoenixadmin** [comment]
Hello, 
yes sure, you just need to implement EditorNodeBuilder interface for your custom data type.
TextFieldEditorBuilder is just an example to show how to edit String values using a text field.

Regards,
