### ISSUE TITLE
JFXTreeTableView Css Problem

### ISSUE THREAD

**Issue by HekmatFavid** [jfoenixadmin/JFoenix#196]
I use tree-table-view class for JFXTreeTreeTableView like this : 

 <JFXTreeTableView  styleClass="tree-table-view" translateY="40" prefWidth="500"  fx:id="usersTreeTableView">

but it dosen't change any thing in appearance.

stylesheets successfully loaded in Main Method :
scene.getStylesheets().add(Main.class.getResource("/view/resources/css/jfoenix-components.css").toExternalForm());

**Comment by jfoenixadmin** [comment]
Hello,

well the "tree-table-view" style class is the default java class for tree table view, so there is not need to add it as a style class. also you need to provide more details about the css file you are loading otherwise it's hard to tell what's causing the issue.

Regards,
