### ISSUE TITLE
New window question

### ISSUE THREAD

**Issue by gramholo20** [jfoenixadmin/JFoenix#198]
Hello,

I have a problem with demo application. 
I want to add login window and to open demo application after successful login.
I know that I have to get flow and flow handler and to link action with controller, like it is done in SideMenuController class.

Regards

**Comment by jfoenixadmin** [comment]
Hello, 
ok.. so what's your question?

**Comment by gramholo20** [comment]
Can you show me simple example how to do it?
I want to do something like this http://pastebin.com/c4R0UrJA

**Comment by jfoenixadmin** [comment]
I'm sorry but I'll close this issue as it's not related to JFoenix development.
