### ISSUE TITLE
Prompt text of the first control disappears after switching views

### ISSUE THREAD

**Issue by reke592** [jfoenixadmin/JFoenix#201]
I was trying to create a simple scene controller, but I can't figure out why the first control prompt text is always missing after I navigate into different views.

```
    private Parent root;
    private Stage primaryStage;
    private static SceneController _instance = new SceneController();


    // singleton instance of scene controller
    public static SceneController getInstance() {
        return _instance;
    }


    public void showLogin() {
        this.setView(new LoginComponent());
    }

    public void showSignUp() {
        this.setView(new SignUpComponent());
    }

    private void setView(Parent component) {
        this.root = component;
        this.refreshStage();
    }

    private void refreshStage() {
        if(this.primaryStage.getScene() == null)
            this.primaryStage.setScene(new Scene(new Region()));

        this.primaryStage.getScene().setRoot(this.root);
        this.primaryStage.setTitle("this.root.getId());
        this.primaryStage.show();
    }


    // application start
    @Override
    public void start(Stage primaryStage) throws Exception {
        this.primaryStage = primaryStage;
        this.root = new LoginComponent();
        this.refreshStage();
        _instance = this;
    }

    void init(String ... args) {
        Application.launch(args);
    }
```

**Comment by jfoenixadmin** [comment]
Hello, 
I'm sorry but the issue is not clear, can you provide more details about your issue?

Regards,

**Comment by reke592** [comment]
Thanks for the reply,

my fxml file has root tags, so I can reuse my components. after I instantiated the component class and set the scene root to my component instance, the prompt text of the first TextField control disappear, but when I click on TextField, the prompt text will appear, repeating the process unfocus and focus, the prompt text and input overlapped each other.

[https://github.com/reke592/casa.git](https://github.com/reke592/casa.git)

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍 the fix will be pushed by the end of the month to git and maven repo.

Regards,

**Comment by reke592** [comment]
👍
