### ISSUE TITLE
JFXButton text init for SceneBuilder is not neede anymore

### ISSUE THREAD

**Issue by emcastro** [jfoenixadmin/JFoenix#202]
Commit c0ac9c4e10e6af00abbb8a4460f4cbc9687f394a adds text to JFXButton, JFXCheckBox, JFXRadioButton, ans JFXToggleButton

It is not needed anymore as SceneBuilder sets a sample value to text properties of controls, even for custom controls. It is even counterproductive with one design text-less buttons (icon only).

A revert commit makes it (tested both using latest full blown SceneBuilder and Intellij SceneBuilder plugin).

**Comment by jfoenixadmin** [comment]
Hello, well we tested it with the latest gluon scene builder 8.2 however the issue still persist.
