### ISSUE TITLE
DatePicker text editor didn't update when using bidirectional bindings.

### ISSUE THREAD

**Issue by reke592** [jfoenixadmin/JFoenix#203]
I was trying to add a bidirectional bindings in my signup form DatePicker Control. I don't know why the text editor value is empty, it just show the prompt text, but when I click on the calendar button the value is already set there. I can't find the right way on how to update the editor value, so I use the promptTextProperty provided by the control to show the value in my repository class. My problem now is when the user accidentally clicked the text editor provided by the control, the DatePicker value is automatically set to null, it affects my repository class, so when I click on the nextButton and go back to the previous form, I got a NullPointerException because I was trying to apply a date format to a null value.

**Comment by reke592** [comment]
I think, the DatePicker is using the value provided in the text editor, since I only put my class value into it's prompt text property, the text editor by default value is null, and when the editor is clicked, the bidirectional binding takes effect. So the real issue here is the text editor. It didn't update when using bidirectional bindings.

**Comment by jfoenixadmin** [comment]
plz note that you need to bind your property to the **value property** of date picker not the text editor text property

**Comment by reke592** [comment]
`this.dpBirthDate.valueProperty().bindBidirectional(this.newUserContext.birthdateProperty());`

I have this on my code, what it does is set the LocalDate value of the DatePicker, but the text editor provided by the control is not updated and still have the value of null, but when I clicked on the calendar button provided by the control, I can see there value is already selected.

**Comment by jfoenixadmin** [comment]
plz test with the latest version of JFoenix, this issue is related to #200 which is already fixed.

Regards,

**Comment by reke592** [comment]
I'm using the latest version that fixed the issue #201 .

here's my codes, 
https://github.com/reke592/casa.git

you can check it by clicking the signup button to show the form,

when you click the next button and then click the back button, there will be no error,

but when you click the calendar text editor, click the next button then click the back button, there is a NullPointerException, because in my `components.SignUpComponent1.initBindings()` I was trying to apply a DateTimeFormatter to the value of DatePicker which is null.

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍 the fix is pushed to maven central and github repo.

Regards,

**Comment by reke592** [comment]
thanks 👍 Its all because of your library
