### ISSUE TITLE
How to change the JFXListView icon expanded color

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#204]
Hola, queria saber ¿como puedo cambiar el color al icono de JFXListView de la expansion? , e intentado hacerlo pero no lo e conseguido, gracias :D.

Hello, I wanted to know how can I change the color to the JFXListView icon of the expansion? . I try to do it but did not get it, thanks :D

![paragit](https://cloud.githubusercontent.com/assets/22163898/20913279/4e12be58-bb44-11e6-872b-b9d01d56e9ed.png)

**Comment by jfoenixadmin** [comment]
Hello,
you can use the following css to change the color

```
.jfx-list-view .jfx-list-cell .sublist-header > .drop-icon{
	-fx-background-color: GRAY;
}

.jfx-list-view .jfx-list-cell:filled:hover .sublist-header > .drop-icon{
	-fx-background-color: BLACK;
}

```
