### ISSUE TITLE
Label Float no longer works when setting JFXTextField text programmatically

### ISSUE THREAD

**Issue by quigonjohnn** [jfoenixadmin/JFoenix#206]
Since the input field rework (7925d0b), I've been unable to set text in a field programmatically without the prompt text overlapping the text. This only occurs with label float on, and when the field is not focused. There are many places in my program that I need to display previous values for editable fields, but below is one example.

* In this case the cursor was on the username field when the values were loaded:

![username selected](https://cloud.githubusercontent.com/assets/6594863/20990591/b0232bd8-bd2d-11e6-8cec-daaa44b94d2e.png)

* Email field selected:
![email selected](https://cloud.githubusercontent.com/assets/6594863/20990665/0c6e3b9e-bd2e-11e6-8797-d573b35bd478.png)

Once the prompt text has been raised above the field, it works fine and doesn't come down when new text is loaded, but if the field is cleared, the problem returns when next the text is set programmatically. I have so far been unable to manually trigger the label float in the way that it used to work and my only option has to revert to an older version.

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 the fix will be pushed soon to maven and github. no need to revert to old versions. 

Regards,

**Comment by jfoenixadmin** [comment]
the fix is pushed to maven central and github

Regards,

**Comment by quigonjohnn** [comment]
Perfect, thanks for the quick response
