### ISSUE TITLE
JFXDrawer hide/show events

### ISSUE THREAD

**Issue by rjahn** [jfoenixadmin/JFoenix#21]
It would be useful to know that hide/show is finished. 
Use-case: SidePane is visible and contains a logout button. Logout will remove the content of the sidepane. But if we remove the content immediately after hide() call, the user is able to see the empty side-pane.

A callback or listener or hide(function) would help....

**Comment by jfoenixadmin** [comment]
its already implemented, plz check the methods setOnDrawerClosed,setOnDrawerOpened.

**Comment by rjahn** [comment]
right, both events exist but at least onDrawerClosed doesn't work as expected because hide method fires onDrawerClosedProperty.get().handle(new JFXDrawerEvent(JFXDrawerEvent.CLOSED)); as last statement.

The transition isn't finished at this point.

I didn't test onDrawerOpenedProperty.

**Comment by jfoenixadmin** [comment]
please test on the latest version of JFoenix, as we recently fixed the timing issue.

**Comment by rjahn** [comment]
shame on me - works as expected!

**Comment by IGSonko** [comment]
salut, je demande de l'aide conncernant la methode isShown() de JFXDrawer. elle est soulignée en rouge chez moi et empeche la compilation
