### ISSUE TITLE
JFXProgressBar not able to resize accroding to window width

### ISSUE THREAD

**Issue by nicknpe** [jfoenixadmin/JFoenix#210]
I added JFXProgressBar in a StackPane in scene builder and set max width to max_value.
When I maximize the window its width does not maximize.

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 the issue is due to using shapes in JFXProgressBar implementation. The skin needs to be reworked in order to use panes instead. will keep you updated once the rework is done.

Regards,
