### ISSUE TITLE
3 dimensional JFXListView

### ISSUE THREAD

**Issue by andre89barros** [jfoenixadmin/JFoenix#212]
Hi everyone,

I am building a program in which a 3 dimensional JFXListView is needed. It is possible to implement?
I am doing it directly by fxml, but i am only able to reproduce a 2 dimensional JFXListView.
The code would look something like this:

```
<JFXListView fx:id="list" prefHeight="322.0" prefWidth="171.0">

			<JFXListView fx:id="resources" styleClass="sublist"> 
				<groupnode>
					<Label styleClass="sub-label">
						<graphic><FontAwesomeIconView fill="#ffffff" glyphName="USER" size="18" /></graphic>Recursos
					</Label>
				</groupnode>

				<JFXListView fx:id="internal_resources" styleClass="sublist"> <!--  vamos deixar para ja uma classe de estilo -->
					<groupnode>
						<Label styleClass="sub-label">
							<graphic><FontAwesomeIconView fill="#ffffff" glyphName="USER" size="18" /></graphic>Internos
						</Label>
					</groupnode>
					<Label><graphic><FontAwesomeIconView fill="#ffffff" glyphName="USER" size="14" /></graphic>Funcionários</Label>
					<Label><graphic><FontAwesomeIconView fill="#ffffff" glyphName="USER" size="14" /></graphic>Máquinas </Label>
					<Label><graphic><FontAwesomeIconView fill="#ffffff" glyphName="USER" size="14" /></graphic>Operações</Label>

					<padding>
                        <Insets bottom="0" left="10" right="0" top="0" />
                	</padding>
				</JFXListView>
				<padding>
                        <Insets bottom="0" left="10" right="0" top="0" />
                </padding>
			</JFXListView>
</JFXListView>
```

![image](https://cloud.githubusercontent.com/assets/12816655/21193208/573b9e10-c223-11e6-86d1-566f7e03cc22.png)

The problem is that even though the 3 level appears in the title (Internos), it is not expanding to show the corresponding labels.
Thanks in advance.

**Comment by jfoenixadmin** [comment]
Hello, 
Currently JFXListView only supports 2 levels. there are some changes needs to be considered in order to support multiple levels.
I recommend using TreeView to deal with multiple levels instead of JFXListView for now.

Regards,

**Comment by jfoenixadmin** [comment]
Hello,
We recommend using the new JFXTreeView instead of JFXListView for this purpose.

Regards,
