### ISSUE TITLE
Back to the normal state of the Sublist, I want to have only one expanded sublist

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#217]
Hola, como podria hacer para solo tener una sublista expandida en una lista que tiene mas de una sublista, algun evento o metodo que me permita poner la sublista en su estado normal ya que quiero que solo tenga una sublista abierta.

Hello, how could I do to just have an expanded sublist in a list that has more than one sublist, some event or method that allows me to put the sublist in its normal state since I want it to have only one sublist open.

Thanks for this great job!

![answare](https://cloud.githubusercontent.com/assets/22163898/21569139/2c58e2ea-ce88-11e6-9564-e0ac8f636824.png)

**Comment by jfoenixadmin** [comment]
Hello, 

currently JFXListView doesn't support this behavior, it might be added later. feel free to add your contribution to JFoenix.

Regards,
