### ISSUE TITLE
Publish JFoenix.jar  to maven central or jcenter ?

### ISSUE THREAD

**Issue by cosyman** [jfoenixadmin/JFoenix#22]
I have found publish.gradle in project, but I can't locate jfoenix.jar from maven central or jcenter.

Will jfoenix.jar be published to that?

Thanks

**Comment by JohnnyQQQQ** [comment]
this would be great +1!

**Comment by sialcasa** [comment]
+1

**Comment by jfoenixadmin** [comment]
its uploaded to maven Snapshots, you can include it using gradle as the following:

repositories {
    maven {
       url "https://oss.sonatype.org/content/groups/public"
    }
}
dependencies { 
 	compile 'com.jfoenix:jfoenix:0.0.0-SNAPSHOT' 	
}

**Comment by aalmiray** [comment]
thanks! Remember that the provided gradle build files have basic configuration for the bintray plugin. You can change it to fit your own needs, publish to bintray.com, then link to jcenter. You can sync artiafcts from Bintray to Maven Central with an extra piece of configuration on the Bintray website. Thus you'll only need to publish to one server and have artifacts available at both :wink:

**Comment by jfoenixadmin** [comment]
Thanks you :+1:

**Comment by TheNightWolf** [comment]
Attempting to use the maven snapshot it gives the following error:

`Could not resolve all dependencies for configuration ':compile'.
 Could not find fakeGroup:jfxrt:dalvik.
  Searched in the following locations:
      https://oss.sonatype.org/content/groups/public/fakeGroup/jfxrt/dalvik/jfxrt-dalvik.pom
      https://oss.sonatype.org/content/groups/public/fakeGroup/jfxrt/dalvik/jfxrt-dalvik.jar
  Required by:
      :[Project Name]:unspecified > com.jfoenix:jfoenix:0.0.0-SNAPSHOT`

Thoughts?

**Comment by jfoenixadmin** [comment]
I updated the gradle build files, the issue is fixed feel free to test.
Thanks for pointing out the issue.

**Comment by salmonb** [comment]
According to the information provided here, I would expect this working in a pom.xml:

```
    <pluginRepositories>
        <pluginRepository>
            <id>snapshots</id>
            <url>https://oss.sonatype.org/content/groups/public</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>com.jfoenix</groupId>
            <artifactId>jfoenix</artifactId>
            <version>0.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

```
But it doesn't. Did I do something wrong?
