### ISSUE TITLE
JFXTabPane in VBox with VGrow Always

### ISSUE THREAD

**Issue by SylvainAssemat** [jfoenixadmin/JFoenix#225]
Hi

First of all congrats for this amazing library
Just change my developper life :-)

I have an issue using JFXTabPane in SceneBuilder when i put the VGrow ALWAYS 
The Gluon SceneBuilder stuck, and not ohter way than killing the task process.

I have an issue using JFXTabPane in SceneBuilder when i put it in a AnchorPane and settings all the Anchor settings (right , top, left, ...)
The Gluon SceneBuilder stuck, and not ohter way than killing the task process.

Have you ever seen this before ?

Thanks

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for pointing out the issue 👍 , we will look into it.
Regards,

**Comment by jfoenixadmin** [comment]
Hello, 
unfortunately we were not able to reproduce the issue using the latest Gluon SceneBuilder, can you retest using the latest SceneBuilder and the latest JFoenix jar.
