### ISSUE TITLE
can't import jfoenix in the eclipse IDE

### ISSUE THREAD

**Issue by darkklin** [jfoenixadmin/JFoenix#226]
i trying to use JFXTextField  in eclipse IDE
but i can't to import it to the class  
![screenshot_7](https://cloud.githubusercontent.com/assets/25209561/22082277/c484867c-ddcf-11e6-8ca8-1599bbb37044.png)

what should i do ?

**Comment by joncarr** [comment]
Right click on your project in the package explorer, select Properties. On the left select "Java Build Path", then select the library tab on the right.  In the library tab, click on "Add external JARS" then navigate to the JFoenix jar file you downloaded and select it.
![selection_004](https://cloud.githubusercontent.com/assets/564071/22094101/693e3140-ddd0-11e6-9417-c0ab6d84a8e3.png)
