### ISSUE TITLE
JfxTextField clear or setText("")  method and JFXComboBox getSelectionModel().clearselection and setValue(null) gives NullPointerException

### ISSUE THREAD

**Issue by alizadehmammadali** [jfoenixadmin/JFoenix#227]
Hello Thanks for amazing libriary.There is one problem in my project is that I can not clear jfxtextfield text and clear comboBox selection item.I tried both setText("") and clear method but It gives NullPointerException.Please help me to correct it

**Comment by jfoenixadmin** [comment]
Hello,
can you provide a sample code demonstrating your issue, as we were not able to reproduce using the latest JFoenix jar.

Regards,
