### ISSUE TITLE
JFXListView: Mouse events not registered

### ISSUE THREAD

**Issue by theTechnoKid** [jfoenixadmin/JFoenix#229]
Mouse events won't register on a `JFXListView` if the click was on an item on the list. The rippler action must be blocking listeners in some way. The only mouse events registered are on an empty part of the list view.

**Comment by jfoenixadmin** [comment]
Hello, this issue is related to #215 which is already fixed. can you retest again using the latest JFoenix jar?
if the issue still persist, please provide a sample code demonstrating the issue.

Regards,

**Comment by elarb** [comment]
So I am not the only one with the problem. I have a listview and added a Popup that should be shown on Mouse Click. It shows when running my App from my IDE but isn't showing when running the App from an executable.

**Comment by jfoenixadmin** [comment]
Hello, Can you retest using the latest version of JFoenix? as we were not able to reproduce the issue.
if the issue still persist please provide a sample code for demonstration.

Regards,

**Comment by elarb** [comment]
I am using version 1.0.0 (Maven dependency). It's the only version available from Maven.

**Comment by theTechnoKid** [comment]
That's the one I'm using too.

**Comment by jfoenixadmin** [comment]
well it's not the latest version of JFoenix, it will get updated by the end of this month.
you can download the latest version of JFoenix from <a href="http://www.jfoenix.com/download/jfoenix.jar"> here </a>

**Comment by theTechnoKid** [comment]
Is there any actual versioning for JFoenix? I love the project; the features are amazing! But it is hard to download the new version manually every time, especially when I'm already using maven for my dependencies. It's also hard to tell when there is a new release, because there are no tags being used in Github. Thanks telling me that the maven hasn't been updated yet!
