### ISSUE TITLE
JFXSlider color issue

### ISSUE THREAD

**Issue by aNNiMON** [jfoenixadmin/JFoenix#23]
I've updated library and found an issue with JFXSlider

![old](https://cloud.githubusercontent.com/assets/1321838/10968584/fc73b87e-83ca-11e5-87f5-d564fb12527a.gif)  lib version 30 october

![new](https://cloud.githubusercontent.com/assets/1321838/10968590/0350ce16-83cb-11e5-87ea-1d0177cd310b.gif) new version

![std](https://cloud.githubusercontent.com/assets/1321838/10968591/069c9672-83cb-11e5-8133-17ff3dab82d3.gif) standard slider

*Press `Shift+f5` for sync gifs*

**Comment by jfoenixadmin** [comment]
did you test the issue on the latest version? i tried it , however couldn't reproduce.

**Comment by aNNiMON** [comment]
I used latest compiled jar version and now try to build from sources - same problem.

**Comment by jfoenixadmin** [comment]
can you send the code that produced this issue?

**Comment by aNNiMON** [comment]
```java
@Override
public void start(Stage primaryStage) {
    Scene scene = new Scene(new JFXSlider(), 150, 150);
    primaryStage.setScene(scene);
    primaryStage.show();
}
```

**Comment by aNNiMON** [comment]
It seems, setting [thumb stroke color](https://github.com/jfoenixadmin/JFoenix/blob/master/src/com/jfoenix/skins/JFXSliderSkin.java#L254) fires [`strokeProperty`](https://github.com/jfoenixadmin/JFoenix/blob/master/src/com/jfoenix/skins/JFXSliderSkin.java#L172) and rewrites `thumbColor` color via `trackColor `.

After commenting [this line](https://github.com/jfoenixadmin/JFoenix/blob/master/src/com/jfoenix/skins/JFXSliderSkin.java#L172), color restores succesfully. Why do we need this property?

**Comment by jfoenixadmin** [comment]
rewriting the thumb color is necessary in case the user changed the slider color at run time. 
Fixed , thanks for pointing the issue.

**Comment by aNNiMON** [comment]
Thanks, works great. 

Now I need to fit slider to container width, but it does not resizes. 
Here is possible solution:

```java
// JFXSliderSkin
private double trackSize;

@Override
protected void layoutChildren(final double x, final double y, final double w, final double h) {

	if (trackSize != (isHorizontal ? w : h)) {

		if (!initialization) initializeVariables();

		if (isHorizontal) {
			// ..
		} else {
			// ..
		}

		if (!initialization) {
			initializeMouseEvents();
			initializeTimeline();
			initialization = true;
		}
		positionThumb(true);
	}
}
```

and code for test it

```java
@Override
public void start(Stage primaryStage) {
    VBox root = new VBox(new Slider(), new JFXSlider());
    Scene scene = new Scene(root, 150, 150);
    primaryStage.setScene(scene);
    primaryStage.show();
}
```

**Comment by jfoenixadmin** [comment]
Thanks, nice work.
