### ISSUE TITLE
Java 9 Modular Support?

### ISSUE THREAD

**Issue by aromanelli** [jfoenixadmin/JFoenix#230]
Hello! We are considering using this for our application, but we have a requirement to be able to have our application run under Java 9 with its modular/Jigsaw support.

What is the status of JFoenix and Java 9/Jigsaw?

EDIT: Including the dependency output ...
>jdeps -jdkinternals jfoenix.jar
jfoenix.jar -> JDK removed internal API
jfoenix.jar -> javafx.controls
jfoenix.jar -> javafx.graphics
   com.jfoenix.controls.JFXCheckBox$StyleableProperties -> com.sun.javafx.css.converters.PaintConverter       JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXDatePicker$StyleableProperties -> com.sun.javafx.css.converters.BooleanConverter     JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXDatePicker$StyleableProperties -> com.sun.javafx.css.converters.PaintConverter       JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXListView$StyleableProperties -> com.sun.javafx.css.converters.BooleanConverter     JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXListView$StyleableProperties -> com.sun.javafx.css.converters.SizeConverter        JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXPasswordField$StyleableProperties -> com.sun.javafx.css.converters.BooleanConverter     JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXPasswordField$StyleableProperties -> com.sun.javafx.css.converters.PaintConverter       JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXRadioButton$StyleableProperties -> com.sun.javafx.css.converters.ColorConverter       JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXRippler$StyleableProperties -> com.sun.javafx.css.converters.BooleanConverter     JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXRippler$StyleableProperties -> com.sun.javafx.css.converters.PaintConverter       JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXRippler$StyleableProperties -> com.sun.javafx.css.converters.SizeConverter        JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXSpinner$StyleableProperties -> com.sun.javafx.css.converters.SizeConverter        JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXTextArea$StyleableProperties -> com.sun.javafx.css.converters.BooleanConverter     JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXTextArea$StyleableProperties -> com.sun.javafx.css.converters.PaintConverter       JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXTextField$StyleableProperties -> com.sun.javafx.css.converters.BooleanConverter     JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXTextField$StyleableProperties -> com.sun.javafx.css.converters.PaintConverter       JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXToggleButton$StyleableProperties -> com.sun.javafx.css.converters.PaintConverter       JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXToggleNode$StyleableProperties -> com.sun.javafx.css.converters.BooleanConverter     JDK internal API (JDK removed internal API)
   com.jfoenix.controls.JFXToggleNode$StyleableProperties -> com.sun.javafx.css.converters.ColorConverter       JDK internal API (JDK removed internal API)
   com.jfoenix.controls.behavior.JFXColorPickerBehavior -> com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior JDK internal API (javafx.controls)
   com.jfoenix.controls.behavior.JFXColorPickerBehavior -> com.sun.javafx.scene.control.behavior.KeyBinding   JDK internal API (JDK removed internal API)
   com.jfoenix.controls.behavior.JFXDatePickerBehavior -> com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior JDK internal API (javafx.controls)
   com.jfoenix.controls.behavior.JFXDatePickerBehavior -> com.sun.javafx.scene.control.behavior.KeyBinding   JDK internal API (JDK removed internal API)
   com.jfoenix.controls.behavior.JFXTreeTableCellBehavior -> com.sun.javafx.scene.control.behavior.TreeTableCellBehavior JDK internal API (javafx.controls)
   com.jfoenix.converters.ButtonTypeConverter         -> com.sun.javafx.css.StyleConverterImpl              JDK internal API (JDK removed internal API)
   com.jfoenix.converters.DialogTransitionConverter   -> com.sun.javafx.css.StyleConverterImpl              JDK internal API (JDK removed internal API)
   com.jfoenix.converters.IndicatorPositionConverter  -> com.sun.javafx.css.StyleConverterImpl              JDK internal API (JDK removed internal API)
   com.jfoenix.converters.RipplerMaskTypeConverter    -> com.sun.javafx.css.StyleConverterImpl              JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXButtonSkin                    -> com.sun.javafx.scene.control.skin.ButtonSkin       JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXButtonSkin                    -> com.sun.javafx.scene.control.skin.LabeledText      JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXCheckBoxOldSkin               -> com.sun.javafx.scene.control.skin.CheckBoxSkin     JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXCheckBoxSkin                  -> com.sun.javafx.scene.control.skin.CheckBoxSkin     JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXColorPickerSkin               -> com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior JDK internal API (javafx.controls)
   com.jfoenix.skins.JFXColorPickerSkin               -> com.sun.javafx.scene.control.skin.ComboBoxPopupControl JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXColorPickerSkin$StyleableProperties -> com.sun.javafx.css.converters.BooleanConverter     JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXColorPickerSkin$StyleableProperties -> com.sun.javafx.scene.control.skin.ComboBoxBaseSkin JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXComboBoxListViewSkin          -> com.sun.javafx.scene.control.skin.ComboBoxListViewSkin JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXCustomColorPickerDialog       -> com.sun.javafx.util.Utils                          JDK internal API (javafx.graphics)
   com.jfoenix.skins.JFXDatePickerSkin                -> com.sun.javafx.scene.control.behavior.ComboBoxBaseBehavior JDK internal API (javafx.controls)
   com.jfoenix.skins.JFXDatePickerSkin                -> com.sun.javafx.scene.control.skin.ComboBoxPopupControl JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXListViewSkin                  -> com.sun.javafx.scene.control.skin.ListViewSkin     JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXListViewSkin                  -> com.sun.javafx.scene.control.skin.VirtualFlow      JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXNestedTableColumnHeader       -> com.sun.javafx.scene.control.skin.NestedTableColumnHeader JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXNestedTableColumnHeader       -> com.sun.javafx.scene.control.skin.TableColumnHeader JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXNestedTableColumnHeader       -> com.sun.javafx.scene.control.skin.TableViewSkinBase JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXPasswordFieldSkin             -> com.sun.javafx.scene.control.skin.TextFieldSkin    JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXProgressBarSkin               -> com.sun.javafx.scene.control.skin.ProgressBarSkin  JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXRadioButtonOldSkin            -> com.sun.javafx.scene.control.skin.RadioButtonSkin  JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXRadioButtonSkin               -> com.sun.javafx.scene.control.skin.RadioButtonSkin  JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXSliderSkin                    -> com.sun.javafx.scene.control.skin.SliderSkin       JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXSliderSkinOLD                 -> com.sun.javafx.scene.control.behavior.BehaviorBase JDK internal API (javafx.controls)
   com.jfoenix.skins.JFXSliderSkinOLD                 -> com.sun.javafx.scene.control.behavior.SliderBehavior JDK internal API (javafx.controls)
   com.jfoenix.skins.JFXSliderSkinOLD                 -> com.sun.javafx.scene.control.skin.BehaviorSkinBase JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTabPaneSkin                   -> com.sun.javafx.scene.control.behavior.BehaviorBase JDK internal API (javafx.controls)
   com.jfoenix.skins.JFXTabPaneSkin                   -> com.sun.javafx.scene.control.behavior.TabPaneBehavior JDK internal API (javafx.controls)
   com.jfoenix.skins.JFXTabPaneSkin                   -> com.sun.javafx.scene.control.skin.BehaviorSkinBase JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTabPaneSkin$TabHeaderContainer -> com.sun.javafx.scene.control.MultiplePropertyChangeListenerHandler JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTabPaneSkin$TabHeaderContainer -> com.sun.javafx.scene.control.behavior.BehaviorBase JDK internal API (javafx.controls)
   com.jfoenix.skins.JFXTabPaneSkin$TabHeaderContainer -> com.sun.javafx.scene.control.behavior.TabPaneBehavior JDK internal API (javafx.controls)
   com.jfoenix.skins.JFXTableColumnHeader             -> com.sun.javafx.scene.control.skin.TableColumnHeader JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTableColumnHeader             -> com.sun.javafx.scene.control.skin.TableViewSkinBase JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTableHeaderRow                -> com.sun.javafx.scene.control.skin.TableHeaderRow   JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTableHeaderRow                -> com.sun.javafx.scene.control.skin.TableViewSkinBase JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTableHeaderRow$1              -> com.sun.javafx.scene.control.skin.NestedTableColumnHeader JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTableHeaderRow$1              -> com.sun.javafx.scene.control.skin.TableHeaderRow   JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTableHeaderRow$1              -> com.sun.javafx.scene.control.skin.TableViewSkinBase JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTextAreaSkin                  -> com.sun.javafx.scene.control.skin.TextAreaSkin     JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTextFieldSkin                 -> com.sun.javafx.scene.control.skin.TextFieldSkin    JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXToggleButtonOldSkin           -> com.sun.javafx.scene.control.skin.ToggleButtonSkin JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXToggleButtonSkin              -> com.sun.javafx.scene.control.skin.ToggleButtonSkin JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXToggleNodeSkin                -> com.sun.javafx.scene.control.skin.ToggleButtonSkin JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTreeTableCellSkin             -> com.sun.javafx.scene.control.behavior.CellBehaviorBase JDK internal API (javafx.controls)
   com.jfoenix.skins.JFXTreeTableCellSkin             -> com.sun.javafx.scene.control.behavior.TreeTableCellBehavior JDK internal API (javafx.controls)
   com.jfoenix.skins.JFXTreeTableCellSkin             -> com.sun.javafx.scene.control.skin.TableCellSkinBase JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTreeTableRowSkin              -> com.sun.javafx.scene.control.skin.TreeTableRowSkin JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTreeTableViewSkin             -> com.sun.javafx.scene.control.skin.TableHeaderRow   JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTreeTableViewSkin             -> com.sun.javafx.scene.control.skin.TableViewSkinBase JDK internal API (JDK removed internal API)
   com.jfoenix.skins.JFXTreeTableViewSkin             -> com.sun.javafx.scene.control.skin.TreeTableViewSkin JDK internal API (JDK removed internal API)

**Comment by jfoenixadmin** [comment]
Hello, 
yeah there are some refactoring issues in Java 9 , however they are not blocking issues. so JFoenix will be compatible with Java 9 once it's officially out.

Regards,

**Comment by backtozero** [comment]
Less than a week before Java9.
Please make new branch.
