### ISSUE TITLE
ScrollPane with JFXMasonryPane has no scroll bar unless resized

### ISSUE THREAD

**Issue by 1blustone** [jfoenixadmin/JFoenix#233]
![scroll](https://cloud.githubusercontent.com/assets/17903523/22308280/a25a9eac-e346-11e6-9eaa-d08a7ae8dc4e.PNG)

![res](https://cloud.githubusercontent.com/assets/17903523/22308462/57616fe2-e347-11e6-8976-f1d98a1884b1.PNG)
As you can see, there is no scroll bar on the stage until I resize it.
I wrote a very simple piece of code to demonstrate this.

	public void start(Stage primaryStage) {
		JFXMasonryPane root = new JFXMasonryPane();
		ScrollPane pane = new ScrollPane(root);
		pane.setFitToWidth(true);

		Scene scene = new Scene(pane, 300, 300);

		for(int i = 0; i < 200; i++)
			root.getChildren().add(new Label("Test"));

		primaryStage.setTitle("Test");
		primaryStage.setScene(scene);
		primaryStage.show();
	}

As far as I can tell, this should work.

I've tried working around it by calling `layoutChildren` manually:

	Platform.runLater(() -> {
		try {
			Method lc = JFXMasonryPane.class.getDeclaredMethod("layoutChildren");
			Field matrix = JFXMasonryPane.class.getDeclaredField("matrix");
			Field valid = JFXMasonryPane.class.getDeclaredField("valid");
			valid.setAccessible(true);
			matrix.setAccessible(true);
			lc.setAccessible(true);

			matrix.set(root, null);
			valid.set(root, false);
			lc.invoke(root);
		} catch (Exception e) {
			e.printStackTrace();
		}
	});

but this seems a bit too hacky and often won't work properly (ignores pref. sizes, displaying `...` in labels that are definitely large enough, sometimes playing the resize animation and sometimes not, etc.)

Not sure what is going on, but it feels somewhat like the height is being calculated later than it should be.

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for pointing out the issue 👍 , will debug the issue however in the mean time you can simply call:
_`Platform.runLater(()->root.requestLayout());`_
there is no need to use reflection in order to re-layout the pane.

Regards,

**Comment by 1blustone** [comment]
This works well. I was somehow not aware of the existence of `requestLayout`. Thanks for the workaround 👍

**Comment by valnaumov** [comment]
@jfoenixadmin May I ask, why this issue was closed? Is this behavior by design?
