### ISSUE TITLE
JFXHamburger

### ISSUE THREAD

**Issue by skptr** [jfoenixadmin/JFoenix#237]
hi, i following  jFXHamburger demo, but i've got error when tried to use MouseEvent,

 public void initialize(URL url, ResourceBundle rb) {
        hamburger = new JFXHamburger();
        HamburgerSlideCloseTransition transition = new HamburgerSlideCloseTransition(hamburger);
        transition.setRate(-1);
        **hamburger.addEventHandler(MouseEvent.MOUSE_PRESSED, (e)->{** 
            transition.setRate(transition.getRate()* - 1);
            transition.play();
        });
    } 

 _hamburger.addEventHandler(MouseEvent.MOUSE_PRESSED, (e)->{
  required: EventType<T>,EventHandler<? super T>
  found: int,(e)->{ tra[...](); }
  reason: cannot infer type-variable(s) T
    (argument mismatch; int cannot be converted to EventType<T>)
  where T is a type-variable:
    T extends Event declared in method <T>addEventHandler(EventType<T>,EventHandler<? super T>)
1 error_

plese help .....

**Comment by jfoenixadmin** [comment]
Hello, I think you are importing the wrong event class AWT event instead of JavaFX event.
