### ISSUE TITLE
Cannot style textfield-line and textfield-focused-line 

### ISSUE THREAD

**Issue by virusavatar** [jfoenixadmin/JFoenix#238]
Since importing the latest jfoenix.jar, the default textline underneath most components (JFXTextField, JFXTextArea, JFXDatePicker, JFXComboBox, etc ) has been altered from the thicker gray bar to a 1px black line.  It has also been moved around and doesn't have padding compared to the previous build.

I have no issue with most of this, but is there was a way to restore it to the original stroke thickness and effect through CSS? I have had no success in styling the textline's thickness. I have tried both Scenic View and the built in CSS analyzer of Scene Builder to identify the css classes, but nothing I've tried under .textfield-line and .textfield-focused-line can increase the thickness.

First image is the jfoenix components as they were before importing the latest jar:
![1](https://cloud.githubusercontent.com/assets/25521934/22600945/cb9b0aac-ea0a-11e6-9d35-4183b725ba43.png)

Second image is the same components after importing the latest jar.
![2](https://cloud.githubusercontent.com/assets/25521934/22600946/cf16944e-ea0a-11e6-9a77-9bd22b91d229.png)

**EDIT**: I have found a partial answer after much experimenting. Maybe this will save some time for someone else.
For most components, the line is under the .textfield-line and .textfield-focused-line classes and the properties are -fx-background-color. However, the combo box has those same lines as -jfx-focus-color and -jfx-unfocus-color. A bit more consistency in naming would make understanding jfoenix components a lot easier.

You can increase the thickness/color as follows (although it looks a bit thicker than before):
.textfield-line{
	-fx-background-color: #b8b8b8;
	-fx-scale-y: 250%;
}
.textfield-focused-line{
	-fx-background-color: purple;
	-fx-scale-y: 125%;
}
This does NOT work for combo boxes. You can only change the color as far as I can tell, not the thickness of the line.
.jfx-combo-box{
	-jfx-unfocus-color: red;
	-jfx-focus-color: blue;
}

Is there a way to change the thickness of the combo box selection line?

**Comment by jfoenixadmin** [comment]
Hello, 
well to change the thickness line you can simple change the pref height property instead of the scale.
```
.input-line{
    -fx-pref-height:10;
}
```
Regarding the combo box, the lines style classes were not added. Thanks for pointing out the issue 👍 
the fix is pushed in the latest jfoenix.jar 

Plz note the style classes have been changed to .input-line, .input-focused-line

Regards,

**Comment by jfoenixadmin** [comment]
Please note that the fix will be pushed to maven by the end of the month to JFoenix 1.2

Regards,
