### ISSUE TITLE
Unable to Style Labels in JFXListView

### ISSUE THREAD

**Issue by Sourish1997** [jfoenixadmin/JFoenix#239]
Hi,

I am having some problems in using JFXListView. I want the individual labels to have larger font size. But when I tried styling the labels using CSS, there was no effect. Also, when I set expanded property of the JFXListView to true, it stops taking up the entire space available. Please help me.

FXML:

`<JFXListView fx:id="questionsList" depthProperty="1" layoutX="300" layoutY="50" maxWidth="1.7976931348623157E308" styleClass="custom-jfx-list-view" stylesheets="@../main/mainStyle.css">
               <Label text="Question 1: Churu and Strings" styleClass="bold-large-label"/>
               <Label text="Question 2: Chef in the Garden" styleClass="bold-large-label"/>
            <VBox.margin>
               <Insets left="10.0" right="10.0" top="20.0" />
            </VBox.margin>
           </JFXListView>`

CSS:

`.bold-large-label{
       -fx-font-size: 30
       -fx-font-weight: bold
   }`

Taking entire space available with setExpanded = false:

![untitled2](https://cloud.githubusercontent.com/assets/12952975/22630246/725f0556-ec1c-11e6-8950-77ff012c4c3d.png)

Not taking entire space available with setExpanded = true:

![untitled3](https://cloud.githubusercontent.com/assets/12952975/22630248/7681e446-ec1c-11e6-9104-031384ca2cba.png)

**Comment by jfoenixadmin** [comment]
Hello, 
Regarding the css issue, it's cause the syntax is wrong. Semicolons are missing.

`.bold-large-label{ -fx-font-size: 30; -fx-font-weight: bold;}`

Regarding the resize issue, it's a bug and has been fixed in the latest JFoenix.jar, Thanks for pointing out the issue 👍 

Regards

**Comment by Sourish1997** [comment]
Thanks a lot.

**Comment by Sourish1997** [comment]
Just wanted to point out that after this commit, we can no longer set the depth of the list view via fxml. Not much of an issue because we can still do it via the controller...but thought I should mention it.
