### ISSUE TITLE
Apply  JFoenix to android from gluon plugin

### ISSUE THREAD

**Issue by codocntt** [jfoenixadmin/JFoenix#242]
I built app android from java fx by gluon gluon for eclipse IDE.  I use JFoenix for decorating the GUI.  I work desktop app well, but when I built apk for android and run app scratch. Can you tell me how to apply the library to android plaftform?

**Comment by jfoenixadmin** [comment]
Hello,
well you need to use the JFoenix retrolambda jar in order to compile your app on android.
plz provide more details about the issue if possible

Regards,

**Comment by codocntt** [comment]
buildscript {
    repositories {
    	jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'org.javafxports:jfxmobile-plugin:1.3.1'
    }
}

apply plugin: 'org.javafxports.jfxmobile'

repositories {
	jcenter()
    mavenCentral()
}

mainClassName = 'com.ipos.app.Main'

jfxmobile {
    android {
        manifest = 'src/android/AndroidManifest.xml'
		compileSdkVersion = 21
		androidSdk = 'C:/Android/sdk'
		buildToolsVersion '25.0.1'
        signingConfig {
            storeFile file('D:/debug.keystore')
	      	storePassword 'xxx'
	      	keyAlias 'xxx'
	      	keyPassword 'xxx'
        }
        packagingOptions {
        	exclude 'META-INF/DEPENDENCIES'
            exclude 'META-INF/DEPENDENCIES.txt'
            exclude 'META-INF/NOTICE'
            exclude 'META-INF/NOTICE.txt'
            exclude 'META-INF/notice.txt'
            exclude 'META-INF/LICENSE'
            exclude 'META-INF/LICENSE.txt'
            exclude 'META-INF/license.txt'
            exclude 'META-INF/ASL2.0'
        	exclude 'META-INF/MANIFEST.MF'
        }
    }
}

dependencies {
	compile fileTree(dir: 'lib', include: ['*.jar'])
	runtime fileTree(dir: 'libs', include: '*.jar')
	compile file('lib/jfoenix-0.0.0-SNAPSHOT-retrolambda.jar')
	compile group: 'com.google.code.gson', name: 'gson', version: '1.7.2'
	compile 'org.apache.httpcomponents:httpcore:4.4.1'
	compile 'org.apache.httpcomponents:httpclient:4.5'
	runtime 'org.apache.httpcomponents:httpcore:4.4.1'
	runtime 'org.apache.httpcomponents:httpclient:4.5'
	runtime group: 'com.google.code.gson', name: 'gson', version: '1.7.2'
	compile files("C:/Android/sdk/platforms/android-21/android.jar")
    compile "org.javafxports:jfxdvk:8u60-b3"
}
This is build file in gradle project. Please, tell me some reason why I can not apply the JFoenix library building android applicaiton.

**Comment by jfoenixadmin** [comment]
What is the error you are getting?

**Comment by visnesever** [comment]
Error:(12, 0) Could not get unknown property 'iosClasses' for task set.
how to fix it :(

**Comment by xnock** [comment]
I also have the same error here
Error:(10, 0) Could not get unknown property 'iosClasses' for task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.
with the exact same line which is "apply plugin: 'org.javafxports.jfxmobile'"
