### ISSUE TITLE
Block events to other windows on JFXDialog Show

### ISSUE THREAD

**Issue by Sourish1997** [jfoenixadmin/JFoenix#244]
Hi,

I was wondering if it is possible to block events to other windows when the JFXDialog is displayed like it is possible with frames using stage.initModality(Modality.APPLICATION_MODAL) and stage.showAndWait(). The closest to this that I have been able to mimic is by using dialog.setOverlayClose(false), but then the window containing the parent stackPane can still be closed by clicking the exit button on the title bar.

**Comment by jfoenixadmin** [comment]
Hello,

Currently the JFXDialog is shown in the same stage, so it's not possible to use stage modality to block events. we are aware of this issue, and will fix it in later version of JFoenix. well keep you updated once it's been released.

Regards,

**Comment by Sourish1997** [comment]
Thanks

**Comment by bgmf** [comment]
@Sourish1997 You could extends the dialog and add some mechanics for this as a workaround for now

	private static final ObservableMap<Stage, ObservableList<SimpleDialog>> OPEN_DIALOGS = FXCollections.observableHashMap();
	
	/**
	 * @return all open dialogs from all {@link Stage}s
	 */
	public static ObservableList<SimpleDialog> getOpenDialogs() {
		ObservableList<SimpleDialog> clone = FXCollections.observableArrayList();
		OPEN_DIALOGS.values().forEach(clone::addAll);
		return FXCollections.unmodifiableObservableList(clone);
	}
	
	/**
	 * @param stage
	 *            the {@link Stage} to query the open dialogs for
	 * @return all open lightweight dialogs from the specified {@link Stage}
	 */
	public static ObservableList<SimpleDialog> getOpenDialogs(Stage stage) {
		if (OPEN_DIALOGS.get(stage) == null)
			return FXCollections.unmodifiableObservableList(FXCollections.observableArrayList());
		return FXCollections.unmodifiableObservableList(FXCollections.observableArrayList(OPEN_DIALOGS.get(stage)));
	}
	
	private void addToOpenDialogs() {
		if (myStage == null)
			return;
		ObservableList<SimpleDialog> list = OPEN_DIALOGS.get(myStage);
		if (list == null) {
			list = FXCollections.observableArrayList();
			OPEN_DIALOGS.put(myStage, list);
		}
		list.add(this);
	}
	
	private void removeFromOpenDialogs() {
		if (myStage == null)
			return;
		ObservableList<SimpleDialog> list = OPEN_DIALOGS.get(myStage);
		if (list == null) {
			list = FXCollections.observableArrayList();
			OPEN_DIALOGS.put(myStage, list);
		}
		list.remove(this);
	}

	// use addToOpenDialogs(); at the end of the #show method (override #show, call super#show and append the method)
	// use removeFromOpenDialogs(); at the end of the overriden #close method

And in my Application (or where I set up the Stage)

	@Override
	public void start(Stage stage) throws Exception {
		// ...
		stage.setOnCloseRequest(this::handleCloseRequest);
		// ...
	}
	private void handleCloseRequest(WindowEvent event) {
		if (stage != null && ExtJFXDialog.getOpenDialogs().size() > 0) {
			// do something - or consume the event and return...
		}
	}

At least this is what I'm doing. One could argue if this solution is "clean" at all - I'd say: It isn't - but it's sufficient for my use case.

Disclaimer: I personally did not simply extend the JFXDialog, but more or less recreated and heavily extend it, since I additionally needed it to be decorated for a boring desktop application, where no Material Design was used...

**Comment by jfoenixadmin** [comment]
Hello,

We added JFXAlert control to JFoenix, it extends Java Dialog. Thus it supports modality and doesn't require a parent pane. it will be pushed to maven central by the end of the month, meanwhile you can get it by downloading the latest JFoenix jar.

Regards,
