### ISSUE TITLE
JFXToggleButton styled with css

### ISSUE THREAD

**Issue by SylvainAssemat** [jfoenixadmin/JFoenix#245]
Hi

I try to modify the color of this JFXToggleButton but i can find out what i m doing wrong.

With this code below, only -fx-text-fill: orange; is working

Do you have an idea ?

Css : 
.jfx-toggle-button {
		-fx-toggle-color: orange;
 		-fx-untoggle-color: orange;
  		-fx-toggle-line-color: orange;
  		-fx-untoggle-line-color: orange;	
  		-fx-text-fill: orange;
}

.borderpane{
	-fx-background-color: blue;
}

Code : 

`public class Main extends Application {
	@Override
	public void start(Stage primaryStage) {
		try {
			//Planning root = new Planning();
			BorderPane bp = new BorderPane();
			bp.getStyleClass().add("borderpane");
			JFXToggleButton tb = new JFXToggleButton();
			System.out.println("--> "+tb.getStyleClass().get(0));
			System.out.println("--> "+tb.getStyleClass().get(1));
			tb.setPadding(new Insets(20,20,20,20));
			tb.setText("test");
			bp.setCenter(tb);
			Scene scene = new Scene(bp);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage.setMaximized(true);
			primaryStage.setScene(scene);
			primaryStage.show();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void main(String[] args) {
		Utils.INSTANCE.getLog();
		launch(args);
	}
}`

**Comment by jfoenixadmin** [comment]
Hello,
Plz note the css attributes have been updated to use the -jfx prefix instead of -fx.
so try the following:
```
.jfx-toggle-button {
    -jfx-toggle-color: orange;
    -jfx-untoggle-color: orange;
    -jfx-toggle-line-color: orange;
    -jfx-untoggle-line-color: orange;
    -fx-text-fill: orange;
}
```
Regards,

**Comment by SylvainAssemat** [comment]
Perfect working ! thanks for all your work !
