### ISSUE TITLE
[ISSUE] Example option menu do not close app

### ISSUE THREAD

**Issue by xamix** [jfoenixadmin/JFoenix#247]
I tested the Example demo and it seem that the toolBarPopup and item click are not working:

![image](https://cloud.githubusercontent.com/assets/9742044/23108504/a0ead6fa-f70e-11e6-892a-bf28550e8798.png)

When  click on exit, app do not close.

It seem that the following code in MainController.java is not fired:

```
exit.setOnMouseClicked((e) -> {
			Platform.exit();
});
```

I'm doing something wrong?

**Comment by jfoenixadmin** [comment]
Hello, 
the behavior of JFXListCell has been changed to match the default behavior of JavaFX list cell, so the event is consumed by the list instead of passing it to the label. thanks for pointing out the issue 👍 

Regards,
