### ISSUE TITLE
Resize the rippler when JFXButton changed width

### ISSUE THREAD

**Issue by sunxfancy** [jfoenixadmin/JFoenix#248]
Thanks for your amazing project. There is a problem that I have a JFXButton with adjustable width, but the rippler did not change its width after a click. I'd like to know how to bind the rippler's width with the button. 

Before:
![screenshot from 2017-02-20 21-43-11](https://cloud.githubusercontent.com/assets/6300305/23127363/bbfeceea-f7b5-11e6-98be-2e0021a740c7.png)
After:
![screenshot from 2017-02-20 21-39-27](https://cloud.githubusercontent.com/assets/6300305/23127366/c1df0fd2-f7b5-11e6-9086-929e0dbd2304.png)

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for pointing out the issue 👍 

Regards,
