### ISSUE TITLE
[ISSUE] Option menu stuck at the opened position

### ISSUE THREAD

**Issue by xamix** [jfoenixadmin/JFoenix#249]
I tested the Example demo and it seem that the option menu (toolBarPopup) do not attach the window broder when it is opened and a resize of the window occur:

For example launch the demo app, it will open without full screen. Then open the option menu like below:

![image](https://cloud.githubusercontent.com/assets/9742044/23226589/5ea8569e-f936-11e6-89e5-4681123d24fa.png)

Then (always with the option menu open), click on the fullscreen button or resize the window:
 
![image](https://cloud.githubusercontent.com/assets/9742044/23226663/a4ca6928-f936-11e6-9bb9-8fb2c2241fe8.png)

As shown above, the option menu stay at the position it was open.
Maybe this is a issue?

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for pointing out the issue 👍  , a rework of the JFXPopup will be coming soon it will fix this issue.

Regards,
