### ISSUE TITLE
[WINDOWS] Custom decorator do not handle auto resize 

### ISSUE THREAD

**Issue by xamix** [jfoenixadmin/JFoenix#250]
Hello,

On Windows 7 the demo application cannot use the following feature:

When you can drag a window to the right or to the left then they maximize at half the screen, letting you quickly and neatly see two windows simultaneously.
Not by only using the mouse, but you can use Win+Left and Win+Right to dock a window to the left or right side of a screen. 

As a side note, Win+Shift+Left and Win+Shift+Right move a window between screens.

It seem that the custom decorator is the problem. When removed it works but I loose the fullscreen button which need to be implemented on another button

**Comment by jfoenixadmin** [comment]
Hello,
In order to use that feature, you must use the windows decorator. The custom JFoenix decorator does not support this feature, feel free to contribute.

Regards,

**Comment by xamix** [comment]
Thank you very much for your quick time to answer :-)
For the moment I will use the default decorator.

Regards.
