### ISSUE TITLE
JFXDatePicker works on PC but doesen't work on Raspberry Pi

### ISSUE THREAD

**Issue by TonytheHorse** [jfoenixadmin/JFoenix#251]
Hi guys, I'm recently making a JavaFX project on Raspberry Pi 2B with Netbeans and SceneBuilder. I work with jfoenix library because I think jfoenix library provides a beautiful interface allows me to interact with users.
The library perfectly work on my PC and  Raspberry Pi 2B except one thing ：I can't create a project with JFXDatePicker on Raspberry Pi. When I run the project on Raspberry Pi, it came out with a run time exception and said：

"java.lang.NoSuchMethodError:com.jfoenix.skins.JFXDatePickerSkin.getEditableInputNode()Ljavafx/scene/control/TextField;"

I can deploy any Jfoenix library on the project which I run on my PC, and I can also deploy any Jfoenix library(JFXButton, JFXColorpicker, ...etc) on the project which I run on my Raspberry Pi except the JFXDatePicker.

I appreciate in advance if anyone can tell me the reason and how to fix it.

**Comment by jfoenixadmin** [comment]
Hello,
you need to update the java version on Raspberry Pi to Java 8 u66 or above, updating to the latest java version is recommended.

Regards,

**Comment by TonytheHorse** [comment]
Thanks for replaying.
I check my current  version and it says it's java 1.8.0_65.
But I try to update the java version by using the command "sudo apt-get install oracle-java8-jdk".
And it says that my java version is the latest version. I'm a little confused that  java 1.8.0_65 is not the latest version, but how come the result is that? 
I try the method here(http://raspberrypi.stackexchange.com/questions/45976/how-do-i-update-java-8-in-raspbian) but it still doesn't work.
Is there any another way to update the java version on my Raspberry Pi?

**Comment by jfoenixadmin** [comment]
Sorry, not sure how to update java version on raspberry pi.
this issue will be closed as its not related to JFoenix development.

Good luck with your project,
