### ISSUE TITLE
JFXDataPicker 

### ISSUE THREAD

**Issue by mk0stka** [jfoenixadmin/JFoenix#253]
get Exception by choosing time and confirming with enter  

Exception in thread "JavaFX Application Thread" java.time.format.DateTimeParseException: Text '01:49' could not be parsed at index 5

tested with latest jfoenix(beta)lib
and latest git clone 

System: using macOS and German

**Comment by jfoenixadmin** [comment]
Hello,
Well the supported time format is SHORT, which means the text should be '01:49 AM' (or PM). 

Regards

**Comment by mk0stka** [comment]
that's correct, but the systemlanguage need to be english that it is working properly.
AM(PM) is not inserted automatically and through an exception

**Comment by mk0stka** [comment]
I fixed the error by my self.

in class `JFXDatePickerSkin` and method `updateTimeDisplayNode()` I exchanged the time formatter. It is better to make a custom pattern instead of taking the local date. Now it is working like a charm. 

`DateTimeFormatter fmt = DateTimeFormatter.ofPattern("h:m a");`

Great work keep it up!

regards

**Comment by jfoenixadmin** [comment]
Hello, the time options has been removed from JFXDatePicker and replaced with custom control called JFXTimePicker, you can set your own converter there.

Regards,
