### ISSUE TITLE
Jfoenix dependency don't packaging by maven

### ISSUE THREAD

**Issue by JuniorMiqueletti** [jfoenixadmin/JFoenix#254]
Hello!
I have a maven project on Intellij... 
when i "**Run**" my application on IDE works fine, 
but when i build by maven (**clean install**) and run the generated jar the error happen...

**Run command:**
> java -jar MyAppJFX-1.0-SNAPSHOT.jar

**Error:**
> Caused by: java.lang.ClassNotFoundException: com.jfoenix.controls.JFXButton

**maven dependency**
`<dependency><groupId>com.jfoenix</groupId>
            <artifactId>jfoenix</artifactId>
            <version>1.2.0</version>
        </dependency>`

Regards

**Comment by jfoenixadmin** [comment]
Hello,
you can check the following link:
http://stackoverflow.com/questions/15871065/classnotfoundexception-in-maven-project

this issue will be closed as it's not related to JFoenix development.

Regards,

**Comment by JuniorMiqueletti** [comment]
**Great!**

Here worked fine with maven-shade-plugin :)

> I suggest you add maven build instructions for others users on Readme.md

*See you*
