### ISSUE TITLE
JFXTextField floating lable is too high, when text is set by setText method

### ISSUE THREAD

**Issue by xcariba** [jfoenixadmin/JFoenix#255]
If you set text with field.setText(...) floating label is located 12px higher. After first focus everything works fine.

![screenshot from 2017-03-07 10-50-09](https://cloud.githubusercontent.com/assets/7170514/23646941/5184c1a8-0324-11e7-8377-349af7e8a7d9.png)

**Comment by jfoenixadmin** [comment]
Hello,
did you test using the latest version of JFoenix 1.2.0? as we were not able to reproduce the issue.
if the issue still persist plz provide a sample code demonstrating the issue.

Regards,

**Comment by xcariba** [comment]
I've tested it using current master version. 
I've added 
`validatedPassowrd.setText("SampleText");`
in TextFieldController in demo and started `gradle run`.  
Java version 1.8_121, OS - Fedora 25 x86_64
Maybe it has something to do with
`promptText.setTranslateY(-textPane.getHeight());` in JFXTextFieldSkin, since it positions label above JFXTextField.

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 , the fix will be pushed to maven central by the end of the month.

Regards,

**Comment by xcariba** [comment]
Thank you for quick fix, you are awesome =)

**Comment by ashishshinde33** [comment]
I am on a same boat. Awaiting for fixed jar.
