### ISSUE TITLE
JFXComboBox's default StringConverter bug

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#257]
Hi,
I am reporting a bug with JFXComboBox's default StringConverter in jfoenix v1.2.0:

Just take a look at line number 100 in JFXComboBox.java, and you will see a cast from String to generic type T which is wrong obviously:

```
public T fromString(String string) {
	return (T) string;
}
```

**Comment by jfoenixadmin** [comment]
Hello, this is the default converter for string values, it's not a generic converter.
you need to set your own converter when customizing the combobox.

Regards,
