### ISSUE TITLE
JFXTextArea does not show prompt text if text not empty

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#258]
Hi,
I've added a JFXTextArea to some container with a sample prompt text on it. The issue is the prompt text disappears when I started to enter some keys on the text area. It remains disappeared if I un-focus from the text area with a non empty text entered.

**Comment by jfoenixadmin** [comment]
Hi,
please make sure you set the label float property to true in order for the prompt text to float above the text area. if the issue still persist, a sample code demonstrating the issue would be appreciated as we were not able to reproduce the issue.

Regards,

**Comment by aminabs** [comment]
Oh, sorry. You are right.
Setting label float property to true solved the issue.
