### ISSUE TITLE
Where I can find the javadocs? 

### ISSUE THREAD

**Issue by badarshahzad** [jfoenixadmin/JFoenix#259]
I found a lot but I didn't find javadocs for jfoenix. What I found these are just the below links. In these links I just saw the coding example no any documentation. So could you please tell me where I can find ?

- http://www.jfoenix.com/documentation.html
- https://github.com/jfoenixadmin/JFoenix/tree/master/src/com/jfoenix/controls

**Comment by jfoenixadmin** [comment]
Hello,
you can download the javadocs for JFoenix 1.2 from <a href="www.jfoenix.com/download/jfoenix-0.0.0-SNAPSHOT-javadoc.jar">here</a>. 
this is not pushed to maven yet. it will be pushed by the end of the month.

Regards,

**Comment by badarshahzad** [comment]
Thank you.
