### ISSUE TITLE
JFXCombobox and JFXToggleButton get weird outline.

### ISSUE THREAD

**Issue by Jefwillems** [jfoenixadmin/JFoenix#260]
I am trying to use the 2 elements mentioned above, but they both get a weird outline when i use them. 
I included some pictures with description [here](http://imgur.com/a/sUqgu).

**Comment by jfoenixadmin** [comment]
Hello,
Not sure what's causing this issue, a sample code demonstrating this issue would be appreciated.
in the mean time, you can simply fix this issue by setting the background of these controls to transparent in your css file.

Regards,

**Comment by Jefwillems** [comment]
After submitting this ticket, i realized i setting the background-color to transparent would help, so for now it works! It's a pretty huge project, but i'll try to take some snippets and combine them into a project asap.
Thanks for the help!
