### ISSUE TITLE
why the combobox height is increase when i select on item 

### ISSUE THREAD

**Issue by boudjaamaa** [jfoenixadmin/JFoenix#262]

**Comment by jfoenixadmin** [comment]
Hello,
Can you provide a sample code demonstrating the issue?

Regards,

**Comment by boudjaamaa** [comment]
hi, i'm using fxml as view and in the controller i put ObservableList as items of my combobox

**Comment by jfoenixadmin** [comment]
according to the info provided, we were not able to reproduce the issue.
a sample code showing the issue would be appreciated, otherwise the issue will be closed.

Regards,
