### ISSUE TITLE
ComboBox setText bug

### ISSUE THREAD

**Issue by skmedix** [jfoenixadmin/JFoenix#265]
**Tested with:**
**JFoenix** - 1.2
**Java** - 1.8.0_121

---

**Example code:**
[First screen](https://gist.githubusercontent.com/skmedix/0f54445053eaf83cc8dce50df92475f9/raw/3cc82245acccd9e613f5c9541227824ba507bbd1/BasicComboBoxSample.java)
[Second screen](https://gist.github.com/skmedix/567a67c91f66f2fc568fd21fce0d4458/raw/9031784ce18c6f5caaa0d76e9008585d9cc7a2bb/BasicComboBoxSample.java)

---
**How ComboBox looks with standard JavaFX controls**
javafx.scene.control.ComboBox & javafx.scene.control.ListCell
![image](https://cloud.githubusercontent.com/assets/3246162/24160359/d8c631b8-0e61-11e7-9503-a7a1f6893977.png)

**How ComboBox looks with JFoenix controls**
com.jfoenix.controls.JFXComboBox & com.jfoenix.controls.JFXListCell
(looks same with standard javafx ListCell)
![image](https://cloud.githubusercontent.com/assets/3246162/24160308/b7fabdfa-0e61-11e7-8e02-3c036d0ac8b6.png)

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 , to solve it currently you just need to implement toString method in Employee class. however, will check what's causing this issue as it's a valid case.

Regards,

**Comment by jfoenixadmin** [comment]
please note the default behavior of JFXListCell is to create a graphic node for the cell. You just need to call _**setGraphic(null)**_ in the **_updateItem_** method.

Regards,
