### ISSUE TITLE
Inconsistent Code Formatting 

### ISSUE THREAD

**Issue by Tybobobo** [jfoenixadmin/JFoenix#267]
As it is right now, a lot of code is messy and formatted inconsistently throughout the entire project.
It seems some users "do their own thing" and disregard existent coding style from the rest of the code. 
 
I propose we do a clean code format throughout the project, as well as clean up old code that is commented out. 
If you truly need to have code snippets commented out, there is always the option to look through old commits. Or at the very least add an comment informing developers why there is a lengthy code snippet.

This is **not** meant as an personal insult against the few individuals that contribute with amazing new features and fixes without cleaning their code, but instead meant as constructive critisism for how your code can become more readable. :)

Perhaps we could go so far to create a more formal page demonstrating the project formatting and styles?

**Comment by jfoenixadmin** [comment]
Feel free adding your own contribution to JFoenix 👍 
this issue will be closed as it's not related to JFoenix technical development.

Regards,
