### ISSUE TITLE
JFXProgressBar do not animate when shown in JFXDialog popup

### ISSUE THREAD

**Issue by tjonsson** [jfoenixadmin/JFoenix#269]
Add a JFXProgressBar with default values to a JFXDialog and call .show(..)

The dialog is shown but JFXProgressBar appears frozen.
This worked fine in version 1.0.0

**Comment by jfoenixadmin** [comment]
Hello, 
this issue seems related to java implementation of ProgressBar and the internal method _**impl_isTreeVisible()**_.
to solve this issue, you can add event handler on dialog opened to relayout the progress bar skin as below:

```
dialog.setOnDialogOpened((event)->{
    jfxBar.requestLayout();
});
```

Regards,

**Comment by tjonsson** [comment]
Thank you, that worked.

It looks like  JFXTextField is suffering from this too. The Label above the text field is initially located wrong. But correctly positions it self if requestLayout() is called on it.

**Comment by jfoenixadmin** [comment]
Hello, 
we were not able to reproduce using JFXTextField, a sample code demonstrating this issue would be appreciated. please make sure you are using the latest JFoenix build 1.2

Regards,
