### ISSUE TITLE
JFXTextField labelFloat setText positioning problem

### ISSUE THREAD

**Issue by HaidarMara** [jfoenixadmin/JFoenix#273]
When you have a JFXTextField with labelFloat set to true and you use setText to change the text programmaticly the text doesnt float in the right position till you click on the textfield.

On startup after setText:
http://prntscr.com/eoywvr

What its supposed to look like:
http://prntscr.com/eoyx79

**Comment by jfoenixadmin** [comment]
Hello, 
This issue is related to #255 the fix is not pushed to maven central yet, it will be by the end of the month.
in JFoenix 1.3

Regards,

**Comment by thetric** [comment]
@HaidarMara you can get the current version via https://jitpack.io/#jfoenixadmin/JFoenix
