### ISSUE TITLE
Consider always enabling Checkstyle

### ISSUE THREAD

**Issue by thetric** [jfoenixadmin/JFoenix#277]
I was wondering why an unused checkstyle exist. A Gradle config exists but it is not enabled by default - but it _should_.

I think it is a good idea to use a code analysis tool like Checkstyle. One reason is that it can enforce a coding convention to increase the code's readability. Another is that it might be easier to integrate pull request because they do _not_ reformat the whole source code.

The current situation is that the checkstyle version is *way too old* (`6.0` was released three years ago! current is `7.6.1`). Updating the plugin version shows that the `checkstyle.xml` isn't compatible anymore so we would need to update to/create a new `checkstyle.xml`. This leads to another point: the `checkstyle.xml` itself. The rule set is rather short and in my opinion it could be more strict. A guide for a new `checkstyle.xml` could be the [Google config](http://checkstyle.sourceforge.net/google_style.html)

**Comment by jfoenixadmin** [comment]
Hello, 
Sure we could use Google java config , feel free to send a pull request.

Regards,

**Comment by jfoenixadmin** [comment]
will push the fix soon.

**Comment by thetric** [comment]
Closed with #280
