### ISSUE TITLE
JFXDecorated how to changed node?

### ISSUE THREAD

**Issue by DevSett** [jfoenixadmin/JFoenix#278]
Why can not I just change the node, I have to re-open the stage ...
Error without overwrite Stage: java.lang.IllegalStateException: Cannot set style once stage has been set visible

**Comment by jfoenixadmin** [comment]
Hello,
not sure what's the issue (changing which node?), a sample code demonstrating the issue would be appreciated. 

Regards,

**Comment by DevSett** [comment]
`@Lazy
@SpringBootApplication
public class Main extends AbstractJavaFxApplicationSupport {


    @Autowired
    private ConfigurationControllers.View mainApp;
    @Autowired
    private ConfigurationControllers.View editingTest;
    public static Main singleton;

    Stage stage;

    @Override
    public void start(Stage stage) throws Exception {
        JFXDecorator decorator = new JFXDecorator(stage, mainApp.getView());
        decorator.setCustomMaximize(true);
        stage.setTitle("кАтлеты v 1.0-Release");
        stage.setScene(new Scene(decorator, 820, 570));
        stage.setResizable(false);
        stage.centerOnScreen();
        stage.show();
        this.stage = stage;
        singleton = this;
    }


    public static void main(String[] args) {
        launchApp(Main.class, args);
    }

    public void setStage(Parent parent) {
        stage.getScene().setRoot(new JFXDecorator(stage, parent));
//        stage.getScene().setRoot(parent);
    }
}`

**Comment by DevSett** [comment]
When I apply the method setStage an error occurs` Error without overwrite Stage: java.lang.IllegalStateException: Cannot set style once stage has been set visible`

**Comment by jfoenixadmin** [comment]
Hello, 
plz note that calling JFXDecorator constructor will set the stage style to UNDECORATED, which you can't do once the stage is visible. I what you are trying to do in setStage is: 

`((StackPane)stage.getScene().getRoot().getChildrenUnmodifiable().get(1)).getChildren().setAll(parent);`

you need to change the decorator content instead of creating a new decorator.

Regards,

**Comment by DevSett** [comment]
th
