### ISSUE TITLE
getText get null 

### ISSUE THREAD

**Issue by sinadarvi** [jfoenixadmin/JFoenix#282]
hi,
i do this : 
```java
JFXTextField text = new JFXTextField();
text.setText("hello");
```

and after that i do this
```java
if(text.getText()!=null ) {
                text.getText();
            }
```
and i get NullPointerException on `text.getText()` !!!

i think it's cause of `textIsNull` , but i don't sure!!
thanks.

**Comment by jfoenixadmin** [comment]
Hello, 
if you can provide the whole code, we might be able to help. otherwise will close this issue, as the provided info is not enough.

Regards,

**Comment by sinadarvi** [comment]
hi,
okey, here is my code : 
`JFXTextField ipGrabber = new JFXTextField();
        JFXTextField portGrabber = new JFXTextField();
        ipGrabber.setPromptText("IP :");
        ipGrabber.setText("192.168.26.1");
        portGrabber.setPromptText("Port :");
        portGrabber.setText("26881");

        JFXButton connect = new JFXButton("Connect");
        connect.setOnAction(event -> {

            if(ipGrabber.getText()==null && portGrabber.getText()==null) {
                mclient.serverIP = ipGrabber.getText();
                mclient.serverPort = Integer.parseInt(portGrabber.getText());
            }`

and here is erorr:
`Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at controllers.MowerStatusController.lambda$initializeConnectingLayout$1(MowerStatusController.java:147) //code : mclient.serverIP = ipGrabber.getText();`

**Comment by thetric** [comment]
Are you certain that `mclient` isn't `null`?

**Comment by sinadarvi** [comment]
no.
problem fixed.
sorry for interrupting...
