### ISSUE TITLE
Expanding JFXListCell programmatically

### ISSUE THREAD

**Issue by kenoung** [jfoenixadmin/JFoenix#287]
Hi, 

Is it currently possible to expand listcells in listviews? JFXListCell has a public method but I'm unable to get the listcell object from the listview.

Thanks!

**Comment by jfoenixadmin** [comment]
Hello,
we recommend using JFXTreeView instead of JFXListView for having multilevel tree. expanded property of JFXListCell is deprecated it might be removed in later versions of JFoenix.

Regards,
