### ISSUE TITLE
JFXTabPane set Side not working 

### ISSUE THREAD

**Issue by goxr3plus** [jfoenixadmin/JFoenix#288]
Trying to change the Side of JFXTabPane is not working for some reason :)

https://github.com/jfoenixadmin/JFoenix/issues/30 Will this be fixed?
---

Code:

```
import com.jfoenix.controls.JFXTabPane;

import javafx.application.Application;
import javafx.geometry.Side;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.Tab;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class MyApp extends Application {
    
    
    /**Main Method
     * @param args
     */
    public static void main(String args[]) {
	launch(args);
    }

    public void start(Stage primaryStage) {
	
	JFXTabPane tabPane = new JFXTabPane();
	//Here trying to set the side
	tabPane.setSide(Side.LEFT);
	
	for(int i=0; i<4; i++)
	    tabPane.getTabs().add(new Tab("Tab "+i,new Label("Imagicon")));
	
	
	primaryStage.setScene(new Scene(new BorderPane(tabPane),400,400));
	primaryStage.show();
    }
}
```

**Comment by goxr3plus** [comment]
One more question :)

How to change the style of JFXTabPane ? I am trying using 

.jfx-tab-pane .tab-header-area .tab-header-background {
    /*-fx-opacity: 0.0;*/
    -fx-background-color:linear-gradient(#38424b 0.0%, #1f2429 20.0%, #191d22 100.0%);  	    
}

.jfx-tab-pane .tab .tab-label { 
    -fx-alignment: CENTER;
    -fx-text-fill: white;
    -fx-font-size: 12.0px; /* before it was 12px */
    -fx-font-weight: bold;
    -fx-wrap-text: true;
    -fx-cursor:hand;
}

but nothing happens ...

**Comment by jfoenixadmin** [comment]
Hello,
JFXTabPane  nly support the TOP side for now, it will be reworked soon. in the meantime, feel free to add your own contribution to JFoenix.

Regards,

**Comment by goxr3plus** [comment]
Thanks for reply:)

2017-04-04 9:45 GMT+03:00 JFoeniX <notifications@github.com>:

**Comment by mokun** [comment]
JFXTabPane doesn't work in MacOS using JDK121. When I click on any one of a tab, it freezes up. 

Surprisingly, after I replace JFXTabPane with the plain vanilla JavaFX's TabPane, it also freezes up on me in MacOS. 

In Linux or Windows, I never run into the same problem.

**Comment by jfoenixadmin** [comment]
Hello, 
we updated JFXTabPane, now it supports the side property. you can test using the latest JFoenix jar.
please note that it's not pushed to maven central yet, it will be by the end of the month.

Regards,

**Comment by goxr3plus** [comment]
I will definitely test it :) !  👍
