### ISSUE TITLE
Cannot dowload jar file directly

### ISSUE THREAD

**Issue by EdgarB** [jfoenixadmin/JFoenix#289]
I am trying to download the jar file from http://www.jfoenix.com/download/jfoenix.jar , but the url is not working.

**Comment by skmedix** [comment]
You can also try to [download the jar](https://search.maven.org/remotecontent?filepath=com/jfoenix/jfoenix/1.3.0/jfoenix-1.3.0.jar) from [Maven Repo](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.jfoenix%22%20AND%20a%3A%22jfoenix%22).

**Comment by EdgarB** [comment]
That worked, thank you.
