### ISSUE TITLE
JFXComboBox.getSelectionModel().clearSelection() not workin good

### ISSUE THREAD

**Issue by mouad12345** [jfoenixadmin/JFoenix#290]
Hello Thanks for amazing libriary.There is one problem in my project is that I can not clear comboBox selection item using the latest JFoenix jar.

![11](https://cloud.githubusercontent.com/assets/26985060/24796899/ee7179d2-1b86-11e7-8953-59d0a0f3e0d6.png)
![12](https://cloud.githubusercontent.com/assets/26985060/24796900/ee71e516-1b86-11e7-9550-a347ade34c75.png)
Regards,

**Comment by mouad12345** [comment]
I'm add `com.setValue("");` after `com.getSelectionModel().clearSelection();` 
`@FXML
    void clear(ActionEvent event) {
      com.getSelectionModel().clearSelection();
      com.setValue("");
    }
`
and problem solved 
![11](https://cloud.githubusercontent.com/assets/26985060/24802450/f2bec5da-1b9f-11e7-94b9-18b71e281891.png)

Regards,

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍 will push the fix as soon as possible.

Regards,

**Comment by jfoenixadmin** [comment]
please note that the fix is not pushed to maven central yet. it will be by the end of the month.
meantime, you can download the latest JFoenix jar from jfoenix site to get the fix.

Regards,
