### ISSUE TITLE
JFXSnackBar long toast messages cover snack's action

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#292]
Hi,
Is there anyway to bind widthProperty of the toast part of a snackbar (the Label)  to 80% of some node via css?
I want to put a non-absolute limit on the toast such that when the container of the snackbar is large enough the snackbar stretches and if the container is short width the toast does not exceed the width of the container but cut the message and put three dot's at the end of the message.

For now I am able to limit the width using absolute width value like this:

> .jfx-snackbar-toast {
>     -fx-min-width: 100;
>     -fx-max-width: 150; // -fx-max-width: 80% does not work
>     -fx-wrap-text: false;
> }

**Comment by jfoenixadmin** [comment]
Hello,
You can't simply bind the widthProperty using css only. You need to get the toast node using its css class and the lookup method, and bind its maxWidthProperty manually.

**Comment by aminabs** [comment]
Thanks, I will give it a try.

**Comment by jfoenixadmin** [comment]
but why do you need to change the width of the toast label? 
you just need to set the wrap text property to true and change the JFXSanckBar prefwidth property when needed

**Comment by aminabs** [comment]
Thanks.
Now,
I did bind snackbar's prefWidth property to my desired property and set the wrap text property to false which is exactly what I was looking for.
