### ISSUE TITLE
CombBox growes vertically

### ISSUE THREAD

**Issue by svgas100** [jfoenixadmin/JFoenix#293]
The Combbox growes vertically after disabling and enabling everytime for 2 pixels. Even if i set the Height of the Combox itself and of the gridpane

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍, please note the the fix will be pushed to maven central by the end of the month. in the meantime, you can get it by downloading the latest JFoenix jar.

Regards
