### ISSUE TITLE
Rippler doesn't work through FXML

### ISSUE THREAD

**Issue by JNordik** [jfoenixadmin/JFoenix#294]
Rippler doesn't work through FXML in IDEA Scene Builder.

My code:
`<JFXRippler maskType="CIRCLE" prefHeight="50.0" prefWidth="50.0" ripplerFill="#2093b0">
    <children>
        <Label text="TEST" />
    </children>
</JFXRippler>`

Code from git demo too doesn't work:
`<JFXRippler maskType="CIRCLE" style="-fx-ripple-color:WHITE;">
                            <StackPane fx:id="titleBurgerContainer">
                                <JFXHamburger fx:id="titleBurger">
                                    <HamburgerBackArrowBasicTransition/>
                                </JFXHamburger>
                            </StackPane>
                        </JFXRippler>`

IntelliJ IDEA 2017.1.1
Build #IC-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by jfoenixadmin** [comment]
Hello,
What doesn't work exactly? what's the error? please provide more info about the issue.

Regards,

**Comment by JNordik** [comment]
Hello, just nothing happens on click. No errors in log history.

Through the code, everything works well:
`Label label = new Label("TEST");
label.setStyle("-fx-background-color:WHITE;-fx-padding:20");
JFXRippler rippler = new JFXRippler(label);`

**Comment by jfoenixadmin** [comment]
please note that default property tag to JFXRippler is "control" not children, also the rippler consider the size of its control, so there is not need to set prefWidth and prefHeight, you can use padding on the label instead.

`<JFXRippler maskType="CIRCLE"  ripplerFill="#2093b0"> <Label text="TEST" style="-fx-padding: 10" /> </JFXRippler>`

Regards,
