### ISSUE TITLE
JFXTimePicker's getEditor().clear() is not clearing the TextField when called.

### ISSUE THREAD

**Issue by evillatoro** [jfoenixadmin/JFoenix#295]
While trying to clear the TextField of the JFXTimePicker I noticed that doing timePicker.getEditor().clear() didn't do anything.
I do:
@FXML
private JFXTimePicker timePicker;

and inside a method I call the method:

private void clearField()
{
        timePicker.getEditor().clear();
}

**Comment by Iw1s** [comment]
Looking through the files of `JFXTimePicker`, I don't think `getEditor()` is implemented correctly. Neither do I know why it's there at all.  
However, to set the value of the `TextField` one can simply use `jfxTimePicker.setValue(new LocalTimeStringConverter().fromString("")`.

**Comment by jfoenixadmin** [comment]
Hello, 
_getEditor()_ method will be updated later to fix this issue. Meanwhile, you can simply call `jfxTimePicker.setValue(new LocalTimeStringConverter().fromString(""))`  to clear the value.

Regards

**Comment by jfoenixadmin** [comment]
Hello,
you can now clear the editor text by setting timepicker value to null:
`jfxTimePicker.setValue(null);`
please note that you need to use the latest jfoenix jar as we fixed some issues in pickers.

Regards,
