### ISSUE TITLE
JFXTimePicker fires action avent two times when entering text value manually.

### ISSUE THREAD

**Issue by vin-malagrino** [jfoenixadmin/JFoenix#296]
Hi,
I'm not sure this is an issue but seems to be a strange thing.
If I add the time value directly inside the textfield of the time picker and then I press enter, the action event callback function associated to the time picker is called two times.

For examples:
I add manually inside the text field the time "10:20 AM"
![cattura](https://cloud.githubusercontent.com/assets/27771471/25181301/660db80a-2511-11e7-8fd5-541d8b426b82.PNG)
then I press enter.

This is  my controller snippet.
![cattura](https://cloud.githubusercontent.com/assets/27771471/25181429/cb56c396-2511-11e7-8efc-0a96a1279908.PNG)
 
This is the result.
![cattura](https://cloud.githubusercontent.com/assets/27771471/25181465/ed2a0c1c-2511-11e7-827d-2917b8872df2.PNG)

**Comment by Iw1s** [comment]
Going through the files, it seems like this is an issue.
If you take a look at `JFXTimePickerSkin.java`, there's a method called `handleControlPropertyChanged(String p)` which calls `jfxTimePicker.fireEvent(new ActionEvent());`:  

```
@Override
protected void handleControlPropertyChanged(String p) {
    if ("CONVERTER".equals(p)) {
        updateDisplayNode();
    } else if ("EDITOR".equals(p)) {
        getEditableInputNode();
    } else if ("SHOWING".equals(p)) {
        if (jfxTimePicker.isShowing()) {
            show();
        } else {
            hide();
        }
    } else if ("VALUE".equals(p)) {
        updateDisplayNode();
        jfxTimePicker.fireEvent(new ActionEvent());
    } else {
        super.handleControlPropertyChanged(p);
    }
}
```

Removing/commenting out this method prevents the event from being fired up twice.  
If that's not intended, one can file a pull request and fix this.

**Comment by jfoenixadmin** [comment]
Hello,
The fix will be pushed to maven central by the end of the month in JFoenix 1.4

Regards,
