### ISSUE TITLE
adding jFoenix jar file

### ISSUE THREAD

**Issue by ccssecotool** [jfoenixadmin/JFoenix#298]
Hi all,
        I am using the Netbeans IDE for JavaFX development and using the JavaFX 1.1 screen builder. My issue is how do I add the jFoenix jar on to that???

**Comment by jfoenixadmin** [comment]
Hello, we recommend using the latest Gluon Scene builder.
This issue is related to #40 

Regards,

**Comment by ccssecotool** [comment]
ok thanks but how do I integrate the Gluon screen builder with Netbeans IDE.
