### ISSUE TITLE
Few issues with JFXTabPane

### ISSUE THREAD

**Issue by jojorabbit** [jfoenixadmin/JFoenix#30]
When tabs are on bottom the line that represents select tab is on wrong tab.
On screenshot first tab is selected and line is on last.

Another issue is when clicking on tab headers, sometimes we need to click few times so selection goes to that tab.

See screenshot attached.

Nice to have would be to have line below tab label or to have property to set the line to top or bottom.

![screenshot284](https://cloud.githubusercontent.com/assets/854237/11914215/2fb970c6-a67a-11e5-9235-828104f1ef12.jpg)

**Comment by jfoenixadmin** [comment]
there has been some changes regarding JFXTabPane, it only support the TOP side for now.
however we fixed the issue regarding the selection.

**Comment by jfoenixadmin** [comment]
Hello, 
JFXTabPane now supports the side property.

Regards,
