### ISSUE TITLE
JFXMasonryPane collums and rows are limited to 100

### ISSUE THREAD

**Issue by MrWolvetech** [jfoenixadmin/JFoenix#302]
The maximum number of rows and collums of a JFXMasonryPane is to 100 no matter what you set `setLimitColumn()` or `setLimitRow()` to.

see:
https://github.com/jfoenixadmin/JFoenix/blob/master/jfoenix/src/main/java/com/jfoenix/controls/JFXMasonryPane.java#L102

https://github.com/jfoenixadmin/JFoenix/blob/master/jfoenix/src/main/java/com/jfoenix/controls/JFXMasonryPane.java#L110

**Comment by jfoenixadmin** [comment]
Hello,
please note that setLimitColumn() or setLimitRow() are used to limit the number of columns and rows if there computed values exceeded this limit. otherwise the pane will use the computed values. 

Your fix will change this behavior which is not intended.

Regards,

**Comment by MrWolvetech** [comment]
Try adding a lot of children, the number of rows ans columns wil never exceed 100. Even if you set the limit to 200. `setRowLimit` doesn't do anything

**Comment by mej71** [comment]
```
row = 100;
row = getLimitRow() != -1 && row > getLimitRow() ? getLimitRow() : row;
```
These lines are the culprits (JFXMasonryPane.java, line 107).  If getLimitRow returns greater than 100, it sets it at 100 anyways.

**Comment by rruffer** [comment]
I'm having the same problem. Any solution?
