### ISSUE TITLE
JFXListView was problem

### ISSUE THREAD

**Issue by Olimov-Umidbek** [jfoenixadmin/JFoenix#303]
Hi. 

I use JFXListView, but if add JFXButton or label children width not change. It's my code

package uz.ubtuit.se_group.messenger.controller;

import com.jfoenix.controls.JFXButton;
import com.jfoenix.controls.JFXListView;
import com.jfoenix.controls.JFXRippler;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.geometry.Insets;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListCell;
import javafx.scene.control.ListView;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.paint.Color;
import javafx.scene.paint.Paint;
import javafx.scene.shape.Circle;
import uz.ubtuit.se_group.messenger.components.Items;
import uz.ubtuit.se_group.messenger.components.Rippers;
import uz.ubtuit.se_group.messenger.modul.Contacts;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.net.URL;
import java.util.ResourceBundle;

/**
 * Created by arion on 4/20/17.
 */
public class MainLayoutController implements Initializable{

    @FXML
    private JFXListView<JFXButton> listView;
    @FXML
    private JFXButton buttonContacts;
    @FXML
    private Label contactName;
    @FXML
    private Label lastMessage;
    @FXML
    private Label date;
    @FXML
    private ImageView avatar;

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        for (int i = 0; i < 10; i++) {
            contactName.setText("Umidbek Olimov " + i);
            lastMessage.setText("Hi my dear friend !!!");
            date.setText("12.02");
            listView.getItems().add(buttonContacts);
        }
        listView.setFixedCellSize(50);
    }

}
Please help me 
![screenshot from 2017-04-26 09-13-35](https://cloud.githubusercontent.com/assets/25737983/25417852/a9f22976-2a60-11e7-93a4-8edbf3f5731a.png)

**Comment by jfoenixadmin** [comment]
Hello,
Can you provide a sample example demonstrating the issue?
please note that changing the children width will not change the list width, you need to change the list width manually.

Regards,

**Comment by Olimov-Umidbek** [comment]
It's works. My code some problems. I've repaired. Thank you
