### ISSUE TITLE
How to change JFXCombo Box text color to white

### ISSUE THREAD

**Issue by lahirunc** [jfoenixadmin/JFoenix#305]
Please help me. I know this is a dumb question but please help

**Comment by aminabs** [comment]
Try one of these css styles. Hope it helps.

-jfx-focus-color: white;

-jfx-unfocus-color: white;

.combo-box > .list-cell {
    -fx-background: black;
    -fx-background-color: black;
    -fx-text-fill: white;
}

**Comment by lahirunc** [comment]
Non of these work

**Comment by aminabs** [comment]
If you mean the editor of the combobox, you might need to find a proper css property to set the editor's text color considering the default editor is a textfield.

**Comment by lahirunc** [comment]
i mean this

![image](https://cloud.githubusercontent.com/assets/20990764/25537045/95d83e7a-2c5a-11e7-9680-cce6cf2a3731.png)
![image](https://cloud.githubusercontent.com/assets/20990764/25537065/aaff7412-2c5a-11e7-8904-de7620e93f27.png)

**Comment by Sashie** [comment]
try this maybe?
```
.combo-box > .combo-box-button-container {
-fx-background: black;
-fx-background-color: black;
-fx-text-fill: white;
}
```

**Comment by lahirunc** [comment]
Nope still didnt work.. Hmm

**Comment by Sashie** [comment]
boop boop ^.^

```
.jfx-combo-box {
	-fx-background-color:  PINK;
}

.jfx-combo-box .label {
	-fx-background-color:  WHITE;
	-fx-text-fill: RED;
}
```

**Comment by lahirunc** [comment]
@Sashie thanks mate! You did it thanks alot cuz im doing this for my degree project and im having my dead line near by thanks alot.

**Comment by Sashie** [comment]
by rights that's up to the ones who run this repo but i see no harm in it,,

**Comment by lahirunc** [comment]
Oh, then I'm opening this window and from here I will open another stage and in it, I have a tree view. Could I know how can I get those values back to text fields in the below shown. like lets say the one shown below is 1st window then I click on the button near the cuscode and opens another 2nd window which contains tree view which from there i need selected row values passed to my 1st below shown stage.  

> https://cloud.githubusercontent.com/assets/20990764/25537065/aaff7412-2c5a-11e7-8904-de7620e93f27.png

**Comment by Joanne86** [comment]
pregunto lo mismo
