### ISSUE TITLE
How to clear treeview data

### ISSUE THREAD

**Issue by lahirunc** [jfoenixadmin/JFoenix#307]
I want to clear my treeview loaded data when i press clear button

![image](https://cloud.githubusercontent.com/assets/20990764/25564723/e3916a4c-2dd6-11e7-8557-4920b6b7af16.png)

**Comment by Sashie** [comment]
Assuming you're using some kind of array to hold the data in the treeview, you could simply clear that and re-display the updated information

**Comment by lahirunc** [comment]
Hey Sashie,

I'm using this code

`JFXTreeTableColumn<vehicle, String> vnoCol = new JFXTreeTableColumn<>(col1);
        vnoCol.setPrefWidth(150);
        vnoCol.setCellValueFactory(new Callback<TreeTableColumn.CellDataFeatures<vehicle, String>, ObservableValue<String>>() {
            @Override
            public ObservableValue<String> call(TreeTableColumn.CellDataFeatures<vehicle, String> param) {
                return param.getValue().getValue().tblVNo;
            }
        });

        JFXTreeTableColumn<vehicle, String> brandCol = new JFXTreeTableColumn<>(col2);
        brandCol.setPrefWidth(150);
        brandCol.setCellValueFactory(new Callback<TreeTableColumn.CellDataFeatures<vehicle, String>, ObservableValue<String>>() {
            @Override
            public ObservableValue<String> call(TreeTableColumn.CellDataFeatures<vehicle, String> param) {
                return param.getValue().getValue().tblBrand;
            }
        });

        JFXTreeTableColumn<vehicle, String> typeCol = new JFXTreeTableColumn<>(col3);
        typeCol.setPrefWidth(150);
        typeCol.setCellValueFactory(new Callback<TreeTableColumn.CellDataFeatures<vehicle, String>, ObservableValue<String>>() {
            @Override
            public ObservableValue<String> call(TreeTableColumn.CellDataFeatures<vehicle, String> param) {
                return param.getValue().getValue().tblType;
            }
        });
        
        JFXTreeTableColumn<vehicle, String> milageCol = new JFXTreeTableColumn<>(col4);
        milageCol.setPrefWidth(150);
        milageCol.setCellValueFactory(new Callback<TreeTableColumn.CellDataFeatures<vehicle, String>, ObservableValue<String>>() {
            @Override
            public ObservableValue<String> call(TreeTableColumn.CellDataFeatures<vehicle, String> param) {
                return param.getValue().getValue().tblMilage;
            }
        });        

        
        
        try {
            String tcol1 = null,tcol2 = null,tcol3 = null,tcol4 = null;
            con=db.getConnection();
            
            if(cusSearch==false){
                query="SELECT `VNo`, `Brand`,`Type`,`Milage` FROM vehicles where CusID ='" + txtCusID.getText() + "'";
                
                tcol1="VNo";
                tcol2="Brand";              
                tcol3="Type";
                tcol4="Milage";
                
            }else if(cusSearch==true){
                
                query="SELECT * FROM customer";
                
                tcol1="CusID";
                tcol2="Name";              
                tcol3="Tel";
                tcol4="Email";
            }
            
            

            PreparedStatement pst=con.prepareStatement(query);

            rs=pst.executeQuery();          
            
            
            while(rs.next()){       
                String vno=rs.getString(tcol1);
                String brand=rs.getString(tcol2);
                String type=rs.getString(tcol3);
                String milage=rs.getString(tcol4);
                
                vehicles.add(new vehicle(vno,brand,type,milage));               
            }

            con.close();
        } catch (SQLException ex) {
            
        }
//        

        TreeItem<vehicle> root = new RecursiveTreeItem<vehicle>(vehicles, RecursiveTreeObject::getChildren);
        treeView.getColumns().setAll(vnoCol, brandCol, typeCol,milageCol);
        treeView.setRoot(root);
        treeView.setShowRoot(false);
    `

**Comment by lahirunc** [comment]
and i want to get these values to my text boxes when i click on a row. Please help me!

**Comment by lahirunc** [comment]
Can you please help me because i tried 

` TreeItem c = (TreeItem)treeView.getSelectionModel().getSelectedItem();
  c.getParent().getChildren().clear();`

which only remove when i click on the treeview it self but it doesnt remove the data when i refresh the tree it brings up the previous data duplicating them. please help. I need really quick. Big thanks

**Comment by lahirunc** [comment]
I kinda found it. Its` vehicle.clear()`

**Comment by Sashie** [comment]
;)
