### ISSUE TITLE
JFXComboBox float label

### ISSUE THREAD

**Issue by Djaler** [jfoenixadmin/JFoenix#312]
If I select some item from combobox in init method (@PostConstruct) or in FXML (using value parameter), floating label animation not happening. If I select any item manually or in some event handler, it works good.
![image](https://cloud.githubusercontent.com/assets/7964583/25659152/25489412-300f-11e7-90cd-e4b13178c89d.png)

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 , the fix will be pushed to maven central in the next release.
Meanwhile, you can download JFoenix.jar from the website to get the fix.

Regards,

**Comment by Djaler** [comment]
Thank you for so fast fix!
