### ISSUE TITLE
Customize different themes for different snackbar

### ISSUE THREAD

**Issue by niteesh19** [jfoenixadmin/JFoenix#313]
Let's say I use snackbars for different purposes, one for showing success, one for error, etc
How can I customize different themes / colors for these snackbars in css?

Currently, I do this by 
`val errorNotify = JFXSnackbar(thisPane)`
`(thisPane.children[1] as Group).children[0].styleClass.add("error-toast")`

Also, the above code doesn't work for the subsequent show of snackbar as now the children has been changed.

There should be an easier way I suppose.

**Comment by niteesh19** [comment]
Also, when I create an instance of JFXSnackbar it calls the registerSnackbarContainer.
Now when the snackbar is shown and given a timeout of say 5secs, why doesn't it call the unregisterSnackbarContainer after the snackbar closes.
Because of this my pane layouts keep changing everytime a snackbar is registered.
unregistering snackbars manually everytime in an event handler is a pain.

**Comment by jfoenixadmin** [comment]
Hello,
you need to add the style class to JFXSnackbar instance not the Group node, this issue is related to #309.
the Group node style classes are bound to the snackbar instance so you can't change them directly.

Regards,

**Comment by niteesh19** [comment]
Yea it works now.
Btw I was trying this before itself
`val errorNotify = JFXSnackbar(thisPane)`
`errorNotify.styleClass.add("error-toast")'

But it didn't used work as I had a jfoenix version 1.2.0

**Comment by niteesh19** [comment]
Sorry, I closed the issue, but my second query still exists

**Comment by jfoenixadmin** [comment]
regarding the unregister method, there is no need to call it you just need to change the style classes and the content of the snackbar before showing it.

Regards,

**Comment by niteesh19** [comment]
PFA a screenshot from the Javafx Layout Debugger:
![selection_002](https://cloud.githubusercontent.com/assets/16698917/25738398/7dc8b482-319a-11e7-842f-19139bfe19e9.png)

As you can see in the screenshot, if I don't call the unregister method, there are a number of "Group" nodes lying around, even after all the snackbars are closed.
If I manually unregister, all these group nodes are removed.
As such it is not a big issue, but performance of the app might significantly reduce on a long term basis.
I am not sure why is it a problem to unregister after the snackbar closes; If we can have a flag which unregisters snackbars after their timeouts that would be great.

**Comment by jfoenixadmin** [comment]
Please note that you can only use 1 JFXSnackbar instance and reuse it instead of creating multiple instances.
