### ISSUE TITLE
JFXComboBox not working with Integer

### ISSUE THREAD

**Issue by faltfe** [jfoenixadmin/JFoenix#314]
I'm trying to figure out how to combine the JFXComboBox with an Integer instead of Strings. What I've done so far:
```java
@FXML
JFXComboBox<Integer>        carID;
...
carID.getItems().addAll(1, 2, 3, 4);
Integer test = carID.getSelectionModel().getSelectedItem(); // <-- Error at runtime
```
(tested with version 1.4.0 from the maven repo)

When I run this code I'll get the following error message:
_Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer_

But this only happens when i **enable** the combobox as **editable.**

Thanks for any help.

**Comment by Sashie** [comment]
What error are you getting? I tested this and it gives no errors

**Comment by jfoenixadmin** [comment]
Hello, 
Please note that ComboBox deals with String by default, to change the type you need to change the StringConverter too. so you should add the following:

```
combo.setConverter(new StringConverter<Integer>() {
    @Override
    public String toString(Integer object) {
        return object == null ? "" : object.toString();
    }
    @Override
    public Integer fromString(String string) {
        return Integer.parseInt(string);
    }
});
```

Regards,

**Comment by faltfe** [comment]
Thank for your help. With the StringConverter it is working as aspected.
