### ISSUE TITLE
Autocomplete bindAutoCompletion

### ISSUE THREAD

**Issue by lahirunc** [jfoenixadmin/JFoenix#315]
Hello, 
I'm getting this error when i use the below shown code. I even have imported both Textfield controls.

`import com.jfoenix.controls.JFXTextField;`
`import javafx.scene.control.TextField;`

![image](https://cloud.githubusercontent.com/assets/20990764/25738947/50b6af00-319d-11e7-9fc6-cd17a29f7120.png)

Thanks in advance! :)

**Comment by jfoenixadmin** [comment]
this method you are calling is part of ControlFX library not JavaFX or JFoenix.

Regards,
