### ISSUE TITLE
How to read rows in Tree Table

### ISSUE THREAD

**Issue by lahirunc** [jfoenixadmin/JFoenix#318]
![image](https://cloud.githubusercontent.com/assets/20990764/25787223/465c5cf4-33bd-11e7-81e0-ff69f5b64288.png)
In above im using the add button to add data from Service Pane to TreeView. How can i read it back when i click on it to the text fields so that i can alter them? I want to remove the row from the treeview and show the details in that on my text fields and combos. How can i do it? 

Thank you very much!

**Comment by jfoenixadmin** [comment]
Hello,
you need to get the data from your data model, however this issue will be closed as it's not related to JFoenix development.

Regards,

**Comment by lahirunc** [comment]
Well im using JFXTree view thats why

**Comment by Sashie** [comment]
What they mean is that this question although using a Jfoenix component is capable of being answered on google for any standard javafx treeview examples, just broaden your search terms

**Comment by lahirunc** [comment]
I tried mate. Couldnt find. Sorry its k no worries
