### ISSUE TITLE
Buttons with built-in loading indicators

### ISSUE THREAD

**Issue by ProALiOnLine** [jfoenixadmin/JFoenix#320]
Hi
I am grateful to you for this wonderful library and I hope to add this component within your library
`http://lab.hakim.se/ladda/`
`https://github.com/hakimel/Ladda`
thank you

**Comment by jfoenixadmin** [comment]
Hello, 
it looks nice, it might be added later to the library however not planned yet. Meanwhile, feel free to add your own contribution to JFoenix.

Regards,
