### ISSUE TITLE
CSS JFXDialogLayout

### ISSUE THREAD

**Issue by SylvainAssemat** [jfoenixadmin/JFoenix#321]
Hi

Just wondering how to override the CSS of JFXDialogLayout (jfoenix 1.4.0)

`JFXDialogLayout content = new JFXDialogLayout();`
				`content.setHeading(new Text("Heading"));`
				`content.setBody(new Text(msg));`
				`JFXDialog dialog = new JFXDialog(ws.getContainer(), content, JFXDialog.DialogTransition.CENTER);`
				`dialog.show();`

I try to cha,ge the color : 
`
.jfx-dialog-layout .jfx-layout-heading .title {
	-fx-text-fill: #2196F3;
}
`

Nothing change.
Always black like in the source code. (setStyle)

Any ideas ?

Thanks for the work

**Comment by jfoenixadmin** [comment]
Hello, 

You can do the following:
`.jfx-dialog-layout .jfx-layout-heading .text { -fx-fill: #2196F3; }`

Regards,

**Comment by SylvainAssemat** [comment]
Humm , seems still not working 

Just find a trick using the text component 

```
Text tt = new Text();
				tt.setText("\nThis is a text sample");
				tt.setFont(Font.font ("Roboto", 15));
				tt.setFill(Color.RED);
				content.setBody(tt);
```

**Comment by jfoenixadmin** [comment]
Please note that your doing what we suggested using code instead of css.
Regards,
