### ISSUE TITLE
Component Customization

### ISSUE THREAD

**Issue by AfzHas** [jfoenixadmin/JFoenix#322]
I  customize the component and how can i Export as Jar file.
Ex: 
![2](https://cloud.githubusercontent.com/assets/28733534/26115484/bcf6a11e-3a7d-11e7-9aef-64e64fcb1286.png)

**Comment by jfoenixadmin** [comment]
Hello,
You can build JFoenix using `gradlew :jfoenix:build` which will generate your cusomized jfoenix.jar.

Regards,

**Comment by AfzHas** [comment]
Hi JFoenix, Im big fan of you, and u really make awesome job with javaFX. My wishes for your future JFoenix updates. So can u please just give me a clear instructions or a simple tutorial for that please.

**Comment by jfoenixadmin** [comment]
Hello,
this link will help to get you started in developing custom controls in JavaFX:
http://www.guigarage.com/2012/11/custom-ui-controls-with-javafx-part-1/
Regards,

**Comment by jfoenixadmin** [comment]
you need to use gradle and run the following command:
`gradlew :jfoenix:build`

**Comment by AfzHas** [comment]
Bro Thank you very much. Can i know when your new update available?

**Comment by AfzHas** [comment]
Bro i use "gradlew :jfoenix:build" to build it, Then where can i find the jar file ?

**Comment by AfzHas** [comment]
I build a JAR file with your  help. Now i need to customize the JFXTabpane. I just want to remove the right and left control button. And i just need to keep drag only. Could you pls help me with that.
