### ISSUE TITLE
JFXTimePicker Hour pane empty after switch from minutes back to hours

### ISSUE THREAD

**Issue by christophburger** [jfoenixadmin/JFoenix#328]
Switching to hour selection after minute selection gives an empty pane.
Screenshot: https://ibb.co/h1Rnqv

This only occurs in 12h-mode. In 24-hours mode it works as expected. Error also occurs in your demo-application.

Thanks.

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍 , the fix will be pushed to maven central by the end of the month.
meanwhile you can get it by downloading the latest JFoenix jar.

Regards,

**Comment by Iw1s** [comment]
@jfoenixadmin Seems fine to me. Though, I wonder how on earth I didn't see such an obvious bug. 😞   

_BTW: I'm still very interested in this project, but just got no time to contribute at the moment as university is devouring my time._
