### ISSUE TITLE
JFXTabpane Stroke Color Not Changing

### ISSUE THREAD

**Issue by AfzHas** [jfoenixadmin/JFoenix#329]
How to change stoke color? I use "-fx-strock:" but it is not working.

**Comment by jfoenixadmin** [comment]
Which node are you trying to change its color? the line or labels?

**Comment by AfzHas** [comment]
OK, bro i got that. Thanks for your help.

**Comment by peteralien** [comment]
It doesn't work for me either.... the node is the selection line.
