### ISSUE TITLE
JFXListView autosize error

### ISSUE THREAD

**Issue by myteer** [jfoenixadmin/JFoenix#33]
### Code
```
public class ListViewTest extends Application {
	
	int i = 0;

	@Override
	public void start(Stage primaryStage) throws Exception {
		VBox root = new VBox(10);
		
		JFXListView<String> listView = new JFXListView<String>();
		Button btn = new Button("add");
		btn.setOnAction(e -> {
			listView.getItems().add("item" + (i++));
		});
		
		root.getChildren().addAll(btn, listView);
		
		Scene scene = new Scene(root, 800, 600);
		primaryStage.setScene(scene);
		primaryStage.show();
	}
	
	public static void main(String[] args) {
		launch(args);
	}

}
```
### before click `add` button

![1](https://cloud.githubusercontent.com/assets/9781523/12165127/3eee9ac2-b556-11e5-81be-b256ca775059.png)

### first click `add` button
the height is 0
![2](https://cloud.githubusercontent.com/assets/9781523/12165256/48f6d3ee-b557-11e5-9724-aadf3e42e015.png)

### click again `add` button
the `item0` is show , the `item1` is overflow, A scroll bar appeas.
![3](https://cloud.githubusercontent.com/assets/9781523/12165310/d0518e7e-b557-11e5-9cb9-c375b0707c8a.png)

**Comment by jfoenixadmin** [comment]
fixed, in order to set a fixed height for the listview you can call the method setPrefHeight or setMaxHeight. Thanks for pointing out the issue.
