### ISSUE TITLE
JFXHamburger

### ISSUE THREAD

**Issue by sumanramchandraco** [jfoenixadmin/JFoenix#331]
hi, I following jFXHamburger , but I've got an error when tried to use MouseEvent,

    @FXML
    private JFXHamburger hamburger;
    @Override
    public void initialize(URL url, ResourceBundle rb) {
        // TODO
       hamburger = new JFXHamburger();
       HamburgerSlideCloseTransition transition = new HamburgerSlideCloseTransition(hamburger);
        transition.setRate(-1); 
        hamburger.addEventHandler(MouseEvent.MOUSE_PRESSED, (e)->{
        transition.setRate(transition.getRate()* - 1);  
        transition.play();
});
    }   

when I click on JFXHamburger It's didn't change. what the problem actually

**Comment by jfoenixadmin** [comment]
Hello,
I'm not sure how you are creating your javafx application, but getting the JFXHamburger from FXML then creating a new instance in the initialize method seems buggy!

Regards,

**Comment by JhonnySalles** [comment]
Hi, I implemented this button in a my project, but I couldn't find a way to be pressing the button programmatically "button.fire ()".
Could someone tell me if he has this feature?
