### ISSUE TITLE
Proposition: Put JFoenix site on the repo as branch

### ISSUE THREAD

**Issue by skmedix** [jfoenixadmin/JFoenix#333]
It doesn't have to be [GitHub Pages](https://pages.github.com/) pinned to a [domain by record](https://help.github.com/articles/using-a-custom-domain-with-github-pages/). But branch with website would give contributors possibilities to improve it. ;)

**Comment by jfoenixadmin** [comment]
we created a new repository for JFoenix website:

https://github.com/jfoenixadmin/JFoenix-Website

**Comment by skmedix** [comment]
That's great, thanks!
