### ISSUE TITLE
ComboBox issues

### ISSUE THREAD

**Issue by zeljkosh** [jfoenixadmin/JFoenix#336]
I played a little bit with this library, and i found some problems with combo box:

First, using JFoenix combo box requires me to use both string converter and to override listview :
 `StringConverter<Customer> customerCon = new StringConverter<Customer>() {
	            @Override
	            public String toString(Customer object) {
	                return object.getCustomerName();
	            }  @Override
	            public Customer fromString(String string) {
	                return null;
	            }  };`

this code in standard combo box, gives me a customer both on combo box, and on combo box list menu.
Its solvable issue (as i said, i needed to overwrite listeview) but its annoying.

Second problem i have trouble understanding is this, 
I have completly same two projects, the only difference is, in one i have Jfoenix combo box, in other normal combo box, but other then that, projects are ABSOLUTELY the same, i used hibernate to fetch some data, and then i put that data in my combo box, while with normal combo box this works perfect, in jfoenix it crashes reporting Lazy Load exception, then i just changed jfoenix combo box to combo box in FXML and tried again, and with normal combo box, it loads with no issues.

**Comment by jfoenixadmin** [comment]
Hello,
Can you provide a sample example demonstrating the issue? or at least some log info in order to tell whats causing the issue?

Regards,

**Comment by zeljkosh** [comment]
Here is the whole code, just add it to your javafx app 

`
    @FXML 
    private ComboBox<User> cb;
     @FXML 
    private JFXComboBox<User> jfcb;
StringConverter<User> userConverter = new StringConverter<User>() {
	            @Override
	            public String toString(User object) {
	                return object.getName();
	            }  @Override
	            public User fromString(String string) {
	              return null;
	           }  };

    @Override
    public void initialize(URL url, ResourceBundle rb) {
    cb.setItems(FXCollections.observableArrayList(
    new User(12,"John"),
    new User(2,"Ann"), 
    new User(33,"Matt")));
   
    jfcb.setItems(FXCollections.observableArrayList(
    new User(12,"John"),
    new User(2,"Ann"), 
    new User(33,"Matt")));
    
    cb.setConverter(userConverter);
    jfcb.setConverter(userConverter);
    }    
   `

http://imgur.com/hkf0BdC here is the url, where i took picture of the combo boxes.

The other issue , i will post later, but i dont have time at the moment.

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍 , feel free to open another issue regarding the lazy loading exception if it persists.

Regards,
