### ISSUE TITLE
JFXDecorator can not bind double click maximize event to ButtonsContainer when set fullScreen false

### ISSUE THREAD

**Issue by blacksider** [jfoenixadmin/JFoenix#340]
Recently I init a JFXDecorator use this:
        `JFXDecorator decorator = new JFXDecorator(this.mainStage, container.getView(), false, true, true);`

with fullScreen false, I found that the double click maximize event lost, and I check the source code of JFXDecorator and found code like this:
```
if (fullScreen) {
    btns.add(btnFull);
    // maximize/restore the window on header double click
    buttonsContainer.setOnMouseClicked((mouseEvent) -> {
        if (mouseEvent.getClickCount() == 2) {
               btnMax.fire();
        }
    });
}
```
That makes double click event only can be bound when fullscreen is true, but in my mind, this event should always be there, always working, no matter I want to use full screen.
And I think this binding should always be there, or use a property to control it, is that right? (Version is 1.4.0)

**Comment by blacksider** [comment]
I use a little to trick to make it works again, but that is not the best way I think.
Like this:
```
Optional<Node> btnContainerOpt = decorator.getChildren().stream()
    .filter(node -> {
        return node.getStyleClass().contains("jfx-decorator-buttons-container");
    }).findFirst();
if (btnContainerOpt.isPresent()) {
    Node buttonsContainer = btnContainerOpt.get();
    buttonsContainer.setOnMouseClicked((mouseEvent) -> {
        if (mouseEvent.getClickCount() == 2) {
            decorator.setMaximized(!this.mainStage.isMaximized());
        }
    });
}
```

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for pointing out the issue 👍 
you could have just done the following instead:
```
Node buttonsContainer = decorator.lookup(".jfx-decorator-buttons-container");
buttonsContainer.setOnMouseClicked((mouseEvent) -> {
    if (mouseEvent.getClickCount() == 2) {
        decorator.setMaximized(!this.mainStage.isMaximized());
    }
});
```
also please note that this won't work properly if custom maximize was set to true, as the stage won't get maximized.

however will fix the issue by moving the maximize/restore code outside the if statement.

Regards,

**Comment by jfoenixadmin** [comment]
The fix will be pushed to maven central by the end of the month, meanwhile you can get it by downloading the latest JFoenix jar.

Regards

**Comment by blacksider** [comment]
Thanks, instead I am using a custom decorator extend JFXDecorator and directly get the btnMax, but I am look forward to the end of the month!
