### ISSUE TITLE
When I search the data again, creating a new RecursiveTreeItem and adding it to the treetableview, the filter stops working

### ISSUE THREAD

**Issue by cesahenrique** [jfoenixadmin/JFoenix#341]
How to solve this? 

The first time it works correctly, however when I search the data in the database again and TreeTableView.setRoot (myRoot) again it does not work.

**Comment by jfoenixadmin** [comment]
Hello,
Can you provide a sample example demonstrating the issue?
please note that you don't need to change the root, you can just change the data model (adding / removing items to the observable list will be directly reflected on tree items).

Regards,

**Comment by cesahenrique** [comment]
Thank you very much!

I was applying setPredicate () to treeTableView. When I applied the setPredicate () in my RecursiveTreeItem "root" the filter on the grid worked correctly.

**Comment by cesahenrique** [comment]
Thank you very much!

I was applying setPredicate () to treeTableView. When I applied the setPredicate () in my RecursiveTreeItem "root" the filter on the grid worked correctly.
