### ISSUE TITLE
RequiredFieldValidator icon missing

### ISSUE THREAD

**Issue by SylvainAssemat** [jfoenixadmin/JFoenix#342]
Hi

I think i m face of an issue.
I have 2  JFXTextField (in Hbox) with 2 RequiredFieldValidator 

The first is ok (labelm and icon)
The second missing  the icon

![sans titre](https://cloud.githubusercontent.com/assets/5692760/26742830/98038060-47df-11e7-9841-1ce9f084ce53.png)

`RequiredFieldValidator loginValidator = new RequiredFieldValidator();
		loginValidator.setMessage("Login vide");
		loginValidator.setIcon(GlyphsBuilder.create(FontAwesomeIconView.class)
				.glyph(FontAwesomeIcon.WARNING)
				.size("1em")
				.styleClass("error")
				.build());
		tf_mail.getValidators().add(loginValidator);
		tf_mail.focusedProperty().addListener((o, oldVal, newVal) -> {
			if (!newVal) {
				tf_mail.validate();
			}
		});
		RequiredFieldValidator passwordValidator = new RequiredFieldValidator();
		passwordValidator.setMessage("Password vide");
		passwordValidator.setIcon(GlyphsBuilder.create(FontAwesomeIconView.class)
				.glyph(FontAwesomeIcon.WARNING)
				.size("1em")
				.styleClass("error")
				.build());
		
		tf_password.getValidators().add(passwordValidator);
		tf_password.focusedProperty().addListener((o, oldVal, newVal) -> {
			if (!newVal) {
				tf_password.validate();
			}
		});`

**Comment by jfoenixadmin** [comment]
Hello,
Unfortunately, we were not able to reproduce the issue using the previous code. so most probably the issue is caused by some css styling. 

Regards,

**Comment by SylvainAssemat** [comment]
You 'are right , that's was the solution 

Shame on me :-(

Thanks for you contribution
