### ISSUE TITLE
JFX POPUP , when ever I set content(a vbox) in popup it is showing Nullpointer exception.

### ISSUE THREAD

**Issue by adarshjha** [jfoenixadmin/JFoenix#343]
`     
    // popup initialize
        JFXButton b1 = new JFXButton("View");
        JFXButton b2 = new JFXButton("Edit");
        JFXButton b3 = new JFXButton("Delete");
        JFXButton b4 = new JFXButton("Add to");
        
        b1.setPadding(new Insets(10));
        b2.setPadding(new Insets(10));
        b3.setPadding(new Insets(10));
        b4.setPadding(new Insets(10));

        VBox vbox=new VBox(b1,b2,b3,b4); 
         
         popup.setPopupContent(vbox);
         popup.
     }   

    

    @FXML
    private void showPopup(MouseEvent event) {
        if (event.getButton() == MouseButton.SECONDARY) {
            popup.setAutoFix(true);
            popup.show(view,JFXPopup.PopupVPosition.TOP, JFXPopup.PopupHPosition.LEFT, event.getX(), event.getY());
        }
    }`

**Comment by adarshjha** [comment]
Ignore the popup. line.

**Comment by jfoenixadmin** [comment]
Hello,
well if you are getting NullPointerException when setting the popup content, it means either the popup is null or the vbox is null. you initialized the vbox properly in your code, thus the popup is null and it might not have been initialized correctly.

please provide the whole code in order to help debugging the issue.
Regards,

**Comment by adarshjha** [comment]
Thanks in advance bro, but I think I have properly initialized. Have a look at the complete code.
`public class LaunchController implements Initializable {
   

    @FXML
    private JFXTextField searchfield;
    @FXML
    private JFXHamburger hammenu;
    @FXML
    private JFXListView<Label> view;
    @FXML
    private JFXButton addtogroup;
    @FXML
    private JFXButton delete;
    @FXML
    private JFXButton export;
    @FXML
    private JFXButton search;
    @FXML
    private JFXButton add;
    @FXML
    private AnchorPane pane;
    @FXML
    private StackPane stackpane;
    private JFXPopup popup;

    databasehandler databaseHandler1;
   
   
    
   

    @Override
    public  void initialize(URL url, ResourceBundle rb) {
        try {
            databaseHandler1 = databasehandler.getInstance();  //getting an object 
            String qu = "Select name FROM CONTACT";
            ResultSet rs = databaseHandler1.execQuery(qu);
            if (rs != null) {
                while (rs.next()) {
                    String name = rs.getString("name");
                    Label lbl = new Label("     " + (name));
                    if (new File("D:\\Work\\Programming\\javaFx Projects\\Contact\\src\\contact\\ui\\files\\Profile\\" + name + ".jpg").exists()) {
                        FileInputStream fis = new FileInputStream("D:\\Work\\Programming\\javaFx Projects\\Contact\\src\\contact\\ui\\files\\Profile\\" + name + ".jpg");
                        Image image = new Image(fis, 35, 35, true, true);
                        lbl.setGraphic(new ImageView(image));
                    } else {
                        FileInputStream fis = new FileInputStream("D:\\Work\\Programming\\javaFx Projects\\Contact\\src\\contact\\ui\\files\\person.png");
                        Image image = new Image(fis, 35, 35, true, true);
                        lbl.setGraphic(new ImageView(image));
                    }

                    view.getItems().add(lbl);
                }
            }
        } catch (FileNotFoundException | SQLException ex) {
            Logger.getLogger(LaunchController.class.getName()).log(Level.SEVERE, null, ex);
        }
       initpopup();
    }
    @FXML
    private void addnewview(MouseEvent event) throws IOException {
        AnchorPane newpane = FXMLLoader.load(getClass().getResource("/contact/ui/addnew/Add new.fxml"));
        pane.getChildren().setAll(newpane);
    }

     private void initpopup(){
         
    // popup initialize
        JFXButton b1 = new JFXButton("View");
        JFXButton b2 = new JFXButton("Edit");
        JFXButton b3 = new JFXButton("Delete");
        JFXButton b4 = new JFXButton("Add to");
        
        b1.setPadding(new Insets(10));
        b2.setPadding(new Insets(10));
        b3.setPadding(new Insets(10));
        b4.setPadding(new Insets(10));

        VBox  vbox=new VBox(b1,b2,b3,b4); 
      
        popup.setPopupContent(vbox); 
         
     }   

    

    @FXML
    private void showPopup(MouseEvent event) {
        
        if (event.getButton() == MouseButton.SECONDARY) {
            popup.setAutoFix(true);
            popup.show(view,JFXPopup.PopupVPosition.TOP, JFXPopup.PopupHPosition.LEFT, event.getX(), event.getY());
        }
      
    }
}
`

**Comment by jfoenixadmin** [comment]
Well, you just missed calling the constructor!
you need to add the following in initpopup method:
`popup = new JFXPopup();`

**Comment by adarshjha** [comment]
Oo my bad. Thanks a ton bro.
