### ISSUE TITLE
JFXPopup issues

### ISSUE THREAD

**Issue by victoreassis** [jfoenixadmin/JFoenix#344]
I'm currently testing the demo package, I only made a git clone and load the project into eclipse, but I'm having a issue with the popup, the container apparently is not hidden when its supposed to be. The gif bellow ilustrates the problem. I'm using the latest version of the JDK, btw.

![popout problem](https://cloud.githubusercontent.com/assets/4192833/26754830/5c43b224-4858-11e7-8ab6-b92f50d6b04b.gif)

**Comment by jfoenixadmin** [comment]
Hello,
We tested the JFXPopup control using the latest JDK 1.8.0_u131, however we were not able to reproduce the issue. can you validate your java version from cmd using the command:
`java -version`

Regards,

**Comment by victoreassis** [comment]
The result is:
> java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by jfoenixadmin** [comment]
We tested on the same environment, however we were not able to reproduce.

**Comment by jfoenixadmin** [comment]
can you retest on a different machine and validate if the issue still persist?

Regards,

**Comment by victoreassis** [comment]
I tested in the Windows 7 machine from work and the popup is ok. Maybe is my system, I'm running Manjaro. I will test it with another OS at home, probably this issue is from my side then.
