### ISSUE TITLE
How to remove JFXDialog content ?

### ISSUE THREAD

**Issue by geckoflume** [jfoenixadmin/JFoenix#345]
Hello,
is there a method to remove the content from a JFXDialog ?
I couldn't find any, so everytime I do dialog.setContent(content), it adds one more content on foreground. Am I doing it the wrong way ?

![removecontent](https://user-images.githubusercontent.com/6378002/26933951-4bcb2774-4c68-11e7-9bba-3bd276991c2a.gif)

**Comment by jfoenixadmin** [comment]
Hello,
well the implementation of setContent should call the method setAll instead of add, will fix it soon and push the changes.
Thanks for pointing out the issue 👍 

Regards,

**Comment by jfoenixadmin** [comment]
The fix will be pushed to JFoenix 1.6 by the end of the month, meanwhile you can get the fix by downloading the latest JFoenix jar.

Regards,
