### ISSUE TITLE
JFXPopUp is not imported 

### ISSUE THREAD

**Issue by ricardovasquez** [jfoenixadmin/JFoenix#346]
Hi, I want to use a popup on my application but I can't find it on the list of components in SceneBuilder. It doesn't appears on the list when I import the library, I'm using the last version (1.5.0). Thank you! and  Thank you for the library, it's an awesome work!

![jfxpopup1](https://user-images.githubusercontent.com/14225490/27004357-17abc40c-4dd6-11e7-9412-70d42e2bef7a.png)

![jfxpopup2](https://user-images.githubusercontent.com/14225490/27004431-29699830-4dd7-11e7-892b-9b28a82c9ba0.png)

**Comment by jfoenixadmin** [comment]
Hello, 
Well JFXPopup has been reworked, it extends PopupControl (the same as java Popup) instead of Control. Thus it can't be added as a custom control anymore (not supported in Scene Builder), you can use it directly in code the same as java popup. for example:

```
JFXPopup popup = new JFXPopup(content);
button.setOnMouseClicked(e -> popup.show(button,
 PopupVPosition.BOTTOM, PopupHPosition.LEFT));
```
Regards,

**Comment by ricardovasquez** [comment]
Now it works! Thank you.
