### ISSUE TITLE
how to add image to JFXButton

### ISSUE THREAD

**Issue by sumanramchandraco** [jfoenixadmin/JFoenix#348]
Hi all team members, I am new in javafx jfoenix I want to know how to add image and text within the JFXButton.

**Comment by jfoenixadmin** [comment]
Hello,
its pretty much the same as JavaFX Button control, you can use the method `setGraphic `for this.

Regards,

**Comment by sumanramchandraco** [comment]
Thank you for the reply but can you suggest me how do I use this in FXML. Plz give us any example
