### ISSUE TITLE
Ressource bundle support

### ISSUE THREAD

**Issue by rbkpro** [jfoenixadmin/JFoenix#349]
How to implement language support / internationalization  ?

**Comment by jfoenixadmin** [comment]
Hello, language support is already implemented in JavaFX.

Regards,

**Comment by rbkpro** [comment]
Thank you 
But I mean when you need to use  @ViewController

**Comment by jfoenixadmin** [comment]
@ViewController is part of DataFX library, its used to reverse the dependency between fxml and its controller. You can find some examples online that will help you to get started.

Regards,
