### ISSUE TITLE
Change TabPane ripple color from CSS

### ISSUE THREAD

**Issue by natinusala** [jfoenixadmin/JFoenix#35]
Hello,

How do I change the TabPane ripple color from CSS ? I looked at the Java code and the rippler has no id nor class associated with it, so I don't think I can link it from the CSS... I saw the `-fx-ripple-color` property but it doesn't seem to work wherever I put it.

**Comment by jfoenixadmin** [comment]
well the property is <b>-fx-rippler-fill</b> not <b>-fx-rippler-color</b>, here is an example of how to change the JFXTabPane rippler color:

<pre>
.jfx-tab-pane .tab-header-area .jfx-rippler{
	<b>-fx-rippler-fill</b>:RED;
}
</pre>

**Comment by natinusala** [comment]
It works, thanks!

**Comment by yogi0823** [comment]
need css for  JFXTabpane 

change slider color on selected tab and also change the background color of tab pane by background like this
![required](https://cloud.githubusercontent.com/assets/7446446/14489549/7e1aaf34-018b-11e6-9f66-a238a05f3120.PNG)

**Comment by bobnathanzeonbe** [comment]
idk why this isnt working for me. I put a usual tab from the builder to jfx tab pane

**Comment by peteralien** [comment]
For the background color of tab pane , try this:

.jfx-tab-pane .headers-region
{
  -fx-background-color: black;
}

.jfx-tab-pane .tab-header-background
{
  -fx-background-color: black;

For changing the slider color on selected tab that's my BIG problem. I'm using jfoenix 1.7.0 and i tried everything that i could remember so far... and nothing! :(((( If someone could give me some tips i really apreciate.

**Comment by jfoenixadmin** [comment]
Hello, 
you can change the slider color and rippler color using the following css:
```
.jfx-tab-pane .tab-selected-line {
	 -fx-stroke: #color;
 }

 .jfx-tab-pane .tab-header-area .jfx-rippler {
	 -jfx-rippler-fill: #color;
 }
```

Regards,

**Comment by peteralien** [comment]
Yes, but "-fx-stroke" doesn't work in the v1.7.0 !

i tried a few minutes ago:

.jfx-tab-pane .tab-selected-line
{
  -fx-border-color: red;
}

and it worked.
I still didn't found out how to change the Tabs labels color.
