### ISSUE TITLE
JFXDialog transparent?

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#350]
Hello, I would like to know if there is any way to color transparent the JFXDialog (contentHolder) or put opacity, Thanks. :)

**Comment by jfoenixadmin** [comment]
Hello,
you can change the color of the overlay pane in css:

```
.jfx-dialog-overlay-pane {
    -fx-background-color: rgba(0.0, 0.0, 0.0, 0.1);
}
```

Regards,

**Comment by continueperu** [comment]
Hi, I used this style to achieve what I wanted.

.jfx-dialog-overlay-pane > StackPane {
	-fx-background-color:  TRANSPARENT;
}

![screenshot_20170618_143816](https://user-images.githubusercontent.com/29350192/27263675-008a7cfa-5434-11e7-8005-d5e0ce753b62.png)

Thanks for the help: D

**Comment by TioCoding** [comment]
Hi, I used this style to achieve what I wanted.

```
.jfx-dialog-overlay-pane > StackPane {
    -fx-background-color: TRANSPARENT;
}
```
The result.

![screenshot_20170618_143816](https://user-images.githubusercontent.com/22163898/27263700-7f724c00-5434-11e7-96f0-9c61b6700ea0.png)

**Comment by ussernamenikita** [comment]
Hi, can you explaine how can i do that ? I use this css to root pane in dialog : 
`.jfx-dialog-overlay-pane {
    -fx-background-color: TRANSPARENT;
}`
But instead of transparent background i have this : 
![default](https://user-images.githubusercontent.com/9387936/29567826-0af44f94-8757-11e7-8f0a-ef2a761746f4.png)
This white pane beyond pane with round corners must be transparent. 
Or i need put css with this text with some specific place ?

**Comment by TioCoding** [comment]
Try my solution.
`.jfx-dialog-overlay-pane > StackPane {
      -fx-background-color: TRANSPARENT;
}`

**Comment by ussernamenikita** [comment]
Thank you for answer. I need add this to my root pane ?

**Comment by ussernamenikita** [comment]
This works  : 
`backetDialog = new JFXDialog(null, backetPane, JFXDialog.DialogTransition.TOP);
Parent p = backet.Pane.getParent();
if(p instanceof Pane)
{
((Pane) p).setBackground(new Background(new BackgroundFill(Color.TRANSPARENT,null,null)));
}
backetDialog.setStyle("-fx-background-color: TRANSPARENT");`

**Comment by NicoStrecker** [comment]
Why cant i click my JFXTextField (it is on a stack pane which is on a anchor pane if it matters)

It does not react on my mousclicks and i dont know what to do

**Comment by ussernamenikita** [comment]
@NicoStrecker, Hi. You need show your code and xml file. Or you make the element inactive in the code or it is below by another element in the xml markup. Anyway without code. In any case, without a code, no one can help you.
