### ISSUE TITLE
Problem with JFXTextField's floating Label

### ISSUE THREAD

**Issue by aDzzZ77** [jfoenixadmin/JFoenix#351]
Hi, 
I have a problem with the floating label of fields. When the JFXTextField is "prefilled" (by a default value for example), there is an offset with the Floating label
![image](https://user-images.githubusercontent.com/12281924/27222406-67d915f0-528c-11e7-86f3-fa08a845a0d3.png)

But when I click on it, the text is positioned correctly as you can see below
![image](https://user-images.githubusercontent.com/12281924/27222269-e5968028-528b-11e7-9b39-98e7036b318f.png)

Is there any solution to fix it ?

Thanks

**Comment by jfoenixadmin** [comment]
This issue is already fixed #255, can you please re-validate the issue using the latest JFoenix jar.

Regards,

**Comment by aDzzZ77** [comment]
I didn't see that was resolved, thanks for your quick answer it works now :)
