### ISSUE TITLE
Can't change input line color of JFXDatePicker

### ISSUE THREAD

**Issue by jccortes** [jfoenixadmin/JFoenix#355]
Hi! I'm not finding a way to change the input line color of JFXDatePicker, while in JFXTextField and others components is very easy, is there any solution for that? Please let me know.

**Comment by jfoenixadmin** [comment]
Hello, 
You can set the default color of JFXDatePicker by code or css:
in code
`picker.setDefaultColor(Color.RED);`
in css:
`-jfx-default-color: RED;`

Regards,

**Comment by jccortes** [comment]
Is true, the DatePicker color change and his focus color, but "the input line" not, in others components is called un focus color, anyway thanks for your answer and go on with your excellent work

**Comment by jfoenixadmin** [comment]
you can change the unfocus color of datepicker text field by using the following css:
```
.jfx-date-picker .jfx-text-field{
    -jfx-unfocus-color: BLUE;
}
```

Regards,
