### ISSUE TITLE
Is there any equivalent component for javafx's default TableView?

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#357]
Hi there,
A very simple question is mine: "Is there any JFXTableView out there?"

I would guess I should use JFXTreeTableView instead, am I right?
If yes, would you please let me know how to set the view to be only a tableview (no tree required). 
Thanks,

**Comment by jfoenixadmin** [comment]
Hello,

Currently there is no custom control for TableView, You can materialize the TableView ui using css only. 
Will close this issue as it's a duplicate for #222 

Regards,
