### ISSUE TITLE
Missing Documentation or Example for CheckBox animation

### ISSUE THREAD

**Issue by misterfifi1** [jfoenixadmin/JFoenix#358]
Hi, 

I am trying to reproduce the animation presented on the home page, but I can't find any information neither in the JAVA, nor in CSS.

Could you help me?

https://camo.githubusercontent.com/0af2b7d4a442e928e184a740c7af13df80b3eba4/687474703a2f2f6a666f656e69782e636f6d2f6769662f636865636b626f782e676966

Regards,

**Comment by jfoenixadmin** [comment]
Hello, 
JFXCheckBox has been reworked, its skin has been changed. The old skin that shows the previous ui is deprecated and no longer supported. However it's still there "JFXCheckBoxOldSkin.java" if you wanna use it. 
The gif for JFXCheckBox is outdated and must be updated, thanks for pointing out the issue 👍 

Regards,

**Comment by misterfifi1** [comment]
Hi, 

Thanks for your reply, so finally to use the old Skin we have just to instantiate a new JFXCheckBoxOldSkin(checkBox);

Just 2 quick questions: 
- how is it possible to change the tick color? 
- Why did you deprecated it? For bugs or guidelines? 

Regards,

**Comment by jfoenixadmin** [comment]
Hello, 
It's deprecated for guidelines. You can change the tick color by changing the control checked color.

Regards,
