### ISSUE TITLE
how to add sublists in JFXListView,following code fails

### ISSUE THREAD

**Issue by dheeraj9198** [jfoenixadmin/JFoenix#36]
JFXListView<Label> jfxListView = new JFXListView<Label>();
        jfxListView.getStylesheets().add(getClass().getClassLoader().getResource("css/jfoenix-main-demo.css").toExternalForm());

        JFXListView<HBox> jfxListView1 = new JFXListView<HBox>();
        jfxListView1.setGroupnode(new Label("head"));

        for(int k =0;k< 40;k++){
            jfxListView1.getItems().add(ViewFactory.getLectureItemView());
        }
        jfxListView.addSublist(jfxListView1,0);

        primaryStage.setScene(new Scene(jfxListView,390,400));
        primaryStage.show()

**Comment by jfoenixadmin** [comment]
you just need to call the method: 
<pre>jfxListView.getItems().add(jfxListView1);</pre>
the method <i>addSublist</i> is used to keep track of the index, however it will be removed later.

**Comment by dheeraj9198** [comment]
GREAT !!!!
that works.
thanks.

**Comment by abbestrov** [comment]
setGroupnode() is deprecated and addSublist() not exists in latest release.
what is the alternative to making JFXListView have sublist items?
like the demo.
![delMe](https://user-images.githubusercontent.com/13640539/55325470-19159200-547d-11e9-9fa8-82b22e4f0723.PNG)
