### ISSUE TITLE
Color picker does not work inside ScrollPane

### ISSUE THREAD

**Issue by jumpstreet13** [jfoenixadmin/JFoenix#363]
Color picker does not fill with color inside ScrollPane, and i do not know why.

**Comment by jfoenixadmin** [comment]
Hello, 
can you provide more details about this issue? console output / sample demo in order to reproduce.

Regards,

**Comment by jumpstreet13** [comment]
Hello, i have no console output about some errors. 
If i pick color, colorpicker has this color in it's property, but not filled with it.
![screen shot 2017-07-11 at 08 17 10](https://user-images.githubusercontent.com/19886384/28052110-8d40eb04-6611-11e7-8b1e-3518959f40af.png)
![screen shot 2017-07-11 at 08 17 02](https://user-images.githubusercontent.com/19886384/28052111-8d4978f0-6611-11e7-87e1-15208a6b2d59.png)
But if i double click on colorpicker, it get's previous chosen color
![screen shot 2017-07-11 at 08 19 17](https://user-images.githubusercontent.com/19886384/28052132-b9a418ec-6611-11e7-80f6-d229d484442a.png)
And after that if i click on element nearby with colorpicker, colorpicker again becomes white.
![screen shot 2017-07-11 at 08 21 42](https://user-images.githubusercontent.com/19886384/28052183-0574b3da-6612-11e7-87ab-929c94c2d332.png)
I do not know, maybe it is something with scrollPane behaviour ? 
Thank's for answer :)

**Comment by jfoenixadmin** [comment]
Hello, 
we already tested JFXColorPicker inside ScrollPane and were not able to reproduce the issue. From the attached images it seems that you removed the color label from the color picker using css somehow, can you please re-validate this issue without applying any css?

Regards,

**Comment by jumpstreet13** [comment]
I found the reason of problem, in the css file. 
.root{
	GB_scrollbar-track: derive(-fx-color, 27.5%);
    GB_scrollbar-thumb: derive(-fx-color, -26.3%);
    GB_scrollbar-corner-border: derive(GB_scrollbar-track, -10%);
    -fx-background: #2b2b2b;
}
If I remove the line: -fx-background: #2b2b2b; then all works fine. Thanks for advice :) 
But do you know, how can i set backround color now?

**Comment by jfoenixadmin** [comment]
Well,
not sure it's a good idea to put `-fx-background` property in `.root` as it will be applied to any node in the scene. 
I believe what you are looking for is `-fx-background-color` :)

```
.root{
GB_scrollbar-track: derive(-fx-color, 27.5%);
GB_scrollbar-thumb: derive(-fx-color, -26.3%);
GB_scrollbar-corner-border: derive(GB_scrollbar-track, -10%);
-fx-background-color: #2b2b2b;
}
```
Regards,

**Comment by jumpstreet13** [comment]
Thank you very much !! :) I've solved the problem.
Regards
