### ISSUE TITLE
JFXDatePicker floating label

### ISSUE THREAD

**Issue by gcmartins93** [jfoenixadmin/JFoenix#366]
If I set JFXDatePicker's date in init method (@PostConstruct), the floating label animation is not triggered, but, if click at the field and manually select its value it works as expected. Similar to #312.
![20049426_10203515691969552_1789539178_o](https://user-images.githubusercontent.com/6655028/28182814-b0a9efd6-67e3-11e7-9e80-1ab30c3fe5e4.png)

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 , will look into it.

Regards,

**Comment by jfoenixadmin** [comment]
the fix is not pushed to maven central yet, it will be by the end of the month. Meanwhile, you can get the fix by downloading the latest JFoenix jar from the website, 

Regards,

**Comment by roger1891** [comment]
I have the same issue for this one.

**Comment by jfoenixadmin** [comment]
@roger1891 which version of JFoenix are you using? I recommend updating to the latest JFoenix version 8.0.7 Java 8 / 9.0.6 for Java +9.
Regards,
