### ISSUE TITLE
Material Icons do not preserve ratio using SVGGlyphLoader

### ISSUE THREAD

**Issue by alegd** [jfoenixadmin/JFoenix#367]
Hi, I'm trying to use the MaterialIcons-Regular.svg file in order to have google material design icons in my app, the thing is that when I load them using SVGGlyphLoader.getGlyph() or SVGGlyphLoader.getIcoMoonGlyph() as in demo app, the icons that doesn't have a height equal to width gets deformed. It would be great if a could get some help to make the icons preserve they ratio. Thanks in advanced.

**Comment by jfoenixadmin** [comment]
Hello, 
we added a method called `setSizeRatio `to `SVGGlyph `object which will resize the svg to a certain size while keeping the width/height ratio.

you can get the fix by downloading the latest jfoenix jar. 
The fix will be pushed to maven central by the end of the month.

Regards,

**Comment by jfoenixadmin** [comment]
you can get the fix by downloading the latest JFoenix jar from the website.

Regards,

**Comment by alegd** [comment]
Yeah, that seems to work just fine. Thanks so much for this fix. However can I suggest something... maybe if you make a method named setPreserveRatio() that receive a boolean parameter would be more intuitive for Java developers,  just like other component have such as ImageView. Thanks again!!
