### ISSUE TITLE
JFXComboBox Cutomization

### ISSUE THREAD

**Issue by gcmartins93** [jfoenixadmin/JFoenix#368]
Is there an example on how to customize JXComboBox setButtonCell to display an image instead of text? I'm trying to override it like this:
```java
comboBoxLocale.setButtonCell(new ListCell<Locale>() {
            @Override
            protected void updateItem(Locale item, boolean empty) {
                super.updateItem(item, empty);
                if (item == null || empty) {
                    setGraphic(null);
                } else {
                    ImageView flag = new ImageView("/images/flags/" + item.getCountry() + ".png");
                    flag.setFitHeight(30);
                    flag.setPreserveRatio(true);
                    setGraphic(flag);
                    setAlignment(Pos.CENTER);
                }
            }
        });
```
but it raises an NullPointerException error on JFXComboBoxListViewSkin (More specifically at line 244, where initial prompt text is filled using javafx prompt).

```java

if(!getSkinnable().isEditable()){
    promptTextFill.set(((Text)((ListCell<T>)super.getDisplayNode()).lookup(".text")).getFill());
}
```

Any help?

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 , will look into it.

Regards,

**Comment by jfoenixadmin** [comment]
the fix is not pushed to maven central yet, it will be by the end of the month. Meanwhile, you can get the fix by downloading the latest JFoenix jar from the website, 

Regards,

**Comment by jfoenixadmin** [comment]
Hello, 
plz notice that changing the button cell might cause some issue with prompt text, to solve them your update item method should be as the following:
```
@Override
protected void updateItem(Locale item, boolean empty) {
    super.updateItem(item, empty);
    if (item == null || empty) {
        setGraphic(null);
    } else {
        if(combo.isLabelFloat()) setText(null);
        // set the new Graphic here
    }
    this.setVisible(item != null || !empty);
}
```

**Comment by gcmartins93** [comment]
Nice, great work on it. I'm going to update the dependencies and give it a try later today.

Thanks.
