### ISSUE TITLE
Disable Tab Pane animations

### ISSUE THREAD

**Issue by CrazyXacker** [jfoenixadmin/JFoenix#369]
Hi. How can i disable transition animations and ripple fill animations in JFXTabPane?

I've experiencing memory leaks with JavaFX on Linux Mint with hardware acceleration, so i decide to disable it for that system and us software acceleration. But ripple effect and transition animation is veeeery slow it that mode.

**Comment by CrazyXacker** [comment]
Sorry, only transition animation. Ripple effect slow only when transition animation played.

**Comment by jfoenixadmin** [comment]
Hello,
currently there is no option to disable the tabs animation however this option will be added soon hopefully in JFoenix 1.7

Regards,

**Comment by CrazyXacker** [comment]
Ok. Thank you for responce. For now, i builded my own version of lib with no animation. Waiting for 1.7 ;)

**Comment by SnShalitha** [comment]
@CrazyXacker.. I am facing the same issue.. Can some one help out.. May be your customized library of no animation
