### ISSUE TITLE
JFXTreeTableColumn and JFXTreeTableView problems

### ISSUE THREAD

**Issue by Aqluse** [jfoenixadmin/JFoenix#371]
Firstly, I can't use it in SceneBuilder, simply because it wasn't imported on the importing of library.
![14-07-2017 180449](https://user-images.githubusercontent.com/13728921/28213500-b387f5e0-68bf-11e7-976e-21b2ab898a2d.png)

Secondly, there is non-material design of JFXTreeTableColumn (and JFXTreeTableView itself too)
![14-07-2017 181213](https://user-images.githubusercontent.com/13728921/28213576-1e9215e6-68c0-11e7-88fb-8b97fcacd541.png)
My Controller class, but there is no modifies on styling and in fxml there is no any too.
`public class FiletreeController {
    @FXML
    private JFXTreeTableView<Audiofile> mTreeTableView;
    private JFXTreeTableColumn<Audiofile, String> mFileFullNameCol;

    /**
     * Инициализация класса-контроллера. Этот метод вызывается автоматически
     * после того, как fxml-файл будет загружен.
     */
    @FXML
    private void initialize(){
        mFileFullNameCol = new JFXTreeTableColumn<>("Имя файла");
        mFileFullNameCol.setCellValueFactory(param -> param.getValue().getValue().fileFullName());

        mTreeTableView.getColumns().setAll(mFileFullNameCol);
        mTreeTableView.setRoot(getTreeItem(new File("D:\\Downloads\\Треки")));
    }

    private TreeItem<Audiofile> getTreeItem(File currentFile){
        TreeItem<Audiofile> item = new TreeItem<Audiofile>(new Audiofile(currentFile.getName(), currentFile.getPath()));

        if (currentFile.isDirectory()) {
            item.setExpanded(true);
            File[] files = currentFile.listFiles();
            if (files != null)
                for (File file : files)
                    item.getChildren().add(getTreeItem(file));
        }

        return item;
    }
}`

**Comment by Aqluse** [comment]
Sorry for code-formatting failures

**Comment by jfoenixadmin** [comment]
Hello,
JFXTreeTableView adds more functionalities to TreeTableView such as grouping/filtering/editing rows. The table styling is mainly done through css. You can check `jfoenix-main-demo.css` for the css style.

Regards,

**Comment by Aqluse** [comment]
@jfoenixadmin 
But why it is not from the box, if site said "JFoenix enhances java tree table view regarding its design" and library positioning as Material components addon? And actually all components that I've already used from the library follow Material Design

**Comment by jfoenixadmin** [comment]
Wel,l we added JFXRippler to TreeTableRow once, however showing the ripple effect on every row click was a bit distracting thus we removed it and kept the css styling and the column sort animation for now. Other design enhancements and features might be added in the future. Meanwhile, feel free to add your own contribution to JFoenix.

Regards,

**Comment by Aqluse** [comment]
@jfoenixadmin 
I don't need ripple effect on it, but I really wanted to see JFXTreeTableView style like one showed on gifs from main page of this repository. I just added it to my project ... and do not even see something close to Material styling, it equals to stock TreeTableView, why? I thought there's a problem.
(but JFXTabPane looks materialish, strange)

**Comment by jfoenixadmin** [comment]
as mentioned before you need to include the css styling in your project:

```
.tree-table-view {
    -fx-tree-table-color: rgba(82, 100, 174, 0.4);
    -fx-tree-table-rippler-color: rgba(82, 100, 174, 0.6);
}

.tree-table-view:focused .tree-table-row-cell:selected {
    -fx-background-color: -fx-tree-table-color;
    -fx-table-cell-border-color: -fx-tree-table-color;
    -fx-text-fill: BLACK;
}

.tree-table-view:focused .tree-table-row-cell:selected .tree-table-cell {
    -fx-text-fill: BLACK;
}

.tree-table-view .column-header,
.tree-table-view .column-header-background,
.tree-table-view .column-header-background .filler {
    -fx-background-color: TRANSPARENT;
}

.tree-table-view .column-header {
    -fx-border-width: 0 1 0 1;
    -fx-border-color: #F3F3F3;
}

.tree-table-view .column-header .label {
    -fx-text-fill: #949494;
    -fx-padding: 16 0 16 0;
}

.tree-table-view .column-header .arrow, .tree-table-view .column-header .sort-order-dot {
    -fx-background-color: #949494;
}

.tree-table-view .column-header:last-visible {
    -fx-border-width: 0 2 0 1;
}

.tree-table-view .column-header-background {
    -fx-border-width: 0 0.0 1 0;
    -fx-border-color: #F3F3F3;
}

.tree-table-view .tree-table-cell {
    -fx-border-width: 0 0 0 0;
    -fx-padding: 16 0 16 0;
    -fx-alignment: top-center;
}

.tree-table-view .column-overlay {
    -fx-background-color: -fx-tree-table-color;
}

.tree-table-view .column-resize-line, .tree-table-view .column-drag-header {
    -fx-background-color: -fx-tree-table-rippler-color;
}

.tree-table-view:focused {
    -fx-background-color: -fx-tree-table-color, -fx-box-border, -fx-control-inner-background;
    -fx-background-insets: -1.4, 0, 1;
    -fx-background-radius: 1.4, 0, 0;
    /*....*/
    -fx-padding: 1; /* 0.083333em; */
}

.tree-table-row-cell > .tree-disclosure-node > .arrow {
    -fx-background-color: -fx-text-fill;
    -fx-padding: 0.333333em 0.229em 0.333333em 0.229em; /* 4 */
    -fx-shape: "M 0 -3.5 L 4 0 L 0 3.5 z";
}

.tree-table-row-group {
    -fx-background-color: rgba(230, 230, 230);
}

.tree-table-view .menu-item:focused {
    -fx-background-color: -fx-tree-table-color;

}

.tree-table-view .menu-item .label {
    -fx-padding: 5 0 5 0;
}
```
