### ISSUE TITLE
Class 'com.jfoenix.controls.JFXScrollPane' does not support property 'topBar'

### ISSUE THREAD

**Issue by sumanramchandraco** [jfoenixadmin/JFoenix#373]
How we can solve this error.

**Comment by jfoenixadmin** [comment]
Hello,
can you provide a sample demo demonstrating this issue in order to tell what's wrong?

Regards,

**Comment by sumanramchandraco** [comment]
<JFXScrollPane fx:id="scroll">
        <topBar> /* here i get the error*/
            <children>
                <JFXButton fx:id="backButton">
                    <StackPane.alignment>CENTER_LEFT</StackPane.alignment>
                    <StackPane.margin>
                        <Insets>
                            <left>
                                20
                            </left>
                        </Insets>
                    </StackPane.margin>
                </JFXButton>
            </children>
        </topBar>

**Comment by jfoenixadmin** [comment]
if you can attach the fxml it would be more helpful

**Comment by jfoenixadmin** [comment]
it seems the error is not related to JFXScrollPane, will close this issue as there is not much info to reproduce.

Regards,
