### ISSUE TITLE
ComboBox not setting String array's itens

### ISSUE THREAD

**Issue by arthurcvm** [jfoenixadmin/JFoenix#374]
In JavaFX I ever set the items like this:

`    @FXML
    public void initialize() {
        // Carregando lista de estados na Box.
        estadoBox.setItems(FXCollections.observableArrayList(estados));
    }`

but whit JFoenix API I don't have success, look my code:

`...

    @FXML
    private ComboBox<String> estadoBox = new ComboBox<String>();
...

private String estados[] = {"AC", "AL", "AP", "AM", "BA", "CE",
        "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR",
        "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "TO"};
...

@FXML
    public void initialize() {
        // Carregando lista de estados na Box.
        estadoBox.setItems(FXCollections.observableArrayList(estados));
    }

...`

after this the comboBox yet is void.

**Comment by jfoenixadmin** [comment]
Hello, 
We tried the previous example, however we were not able to reproduce. is there any exception on the console? 

Regards,

**Comment by arthurcvm** [comment]
No, nothing of exceptions, the code is ok, but the component not displays the list.

**Comment by jfoenixadmin** [comment]
can you provide a sample demo for this issue? as we were not able to reproduce.

Regards,

**Comment by jfoenixadmin** [comment]
after having another look at the code you provided, it seems you are creating a new combo instead of using the one retrieved from fxml which is wrong. The declaration of combo box field should be as the following:
```
@FXML
private ComboBox<String> estadoBox;
```

**Comment by arthurcvm** [comment]
I discovery and solve the problem, the problem is in FXML, I miss typing in FXML and the component name stayed "estadobox" in Java Controller "estadoBox", the creation is ok, look the new code:

`@FXML
    private JFXComboBox<String> estadoBox = new JFXComboBox<String>();`

In you reply suggested change the declaration, but in this way return null pointer exception:

`@FXML
private ComboBox<String> estadoBox;`

**Comment by jfoenixadmin** [comment]
My bad I assumed you were using DataFX library, glad the issue is solved.

Regards,
