### ISSUE TITLE
JFXSlider is consuming some mouse events

### ISSUE THREAD

**Issue by gabrielpaim** [jfoenixadmin/JFoenix#375]
Hello,

As it seems, JFXSlider is consuming some mouse events, such as onMouseDragged, onMouseReleased and onMouseDragReleased. Is this an expected behaviour? Although one could use the valueChangingProperty instead, I noticed it when porting my code from normal Slider to JFXSlider.

Thanks, congratulations, great tool, good work :-)

**Comment by jfoenixadmin** [comment]
Hello,

Thanks for pointing out the issue 👍, will look into it. can you please provide a sample code demonstrating the issue?

Regards,

**Comment by gabrielpaim** [comment]
Sure.



    public static void main(String[] args) {
        launch(args);
    }
    
    @Override
    public void start(Stage primaryStage) throws Exception {
        
        JFXSlider slider = new JFXSlider();
        slider.setOnMouseReleased(event -> {
            System.out.println("mouse released");
        });
        Scene scene = new Scene(slider);
        primaryStage.setScene(scene);
        primaryStage.show();
        
    }
