### ISSUE TITLE
setContent and other methods not found

### ISSUE THREAD

**Issue by macka601** [jfoenixadmin/JFoenix#376]
Hi, 
Imported your Jar (also tried via Maven), and tried to build the hamburger example, however compiler cant find 
popup.setContent(list);
popup.setPopupContainer(root);
popup.setSource(
popupSource.setOnMouseClicked((e)-> popup.show(JFXPopup.PopupVPosition.TOP, JFXPopup.PopupHPosition.LEFT));

Is the example wrong? or have i linked it wrong?

**Comment by jfoenixadmin** [comment]
Hello,
this seems to be an old version of JFoenix, JFXPopup has been reworked and these methods are removed.
you can download the latest JFoenix jar from the website or JFoenix 1.6 from maven central.

Regards,
