### ISSUE TITLE
JFXTreeTableView 

### ISSUE THREAD

**Issue by mirisha** [jfoenixadmin/JFoenix#377]
Hello
How can I create "Raw Details" section for each row of the JFXTreeTableView ?

**Comment by jfoenixadmin** [comment]
Hello,
What do you mean exactly by "Raw Details" ? can you clarify more the issue.

Regards,

**Comment by mirisha** [comment]
I want to be able to display "additional data" for a row in the tree.
The user will perform mouse click (or double click) on a row - this will open a "sub" container (between the current raw and the next raw) that will display additional data related to the row (the additional data will be a table view control)
Can it be done on JFXTreeTable View?

I saw simillar question regarding JavaFx TableView here:
https://stackoverflow.com/questions/39110036/javafx-tableview-open-detail-information-between-rows-on-click

Thank you

**Comment by jfoenixadmin** [comment]
Hello, 
Currently you can't do that in JFXTreeTableView, as you mentioned before you can use TableView and override the Row skin in order to achieve your goal. 

Regards,
