### ISSUE TITLE
JFXComboBox Select Problem

### ISSUE THREAD

**Issue by jeanJavaMan** [jfoenixadmin/JFoenix#379]
Hello, I'm here to ask for your help. I'm not very good in English so I'll use google translator hehe.
My jfxcombobox selects an item, but does not show on the screen.
First I get the items from the database, then I select the item, but the screen does not appear. I'll show you some print.
**Look** at the combobox with the name "Curso de Interesse"
![screenshot at jul 21 12-54-28](https://user-images.githubusercontent.com/17498775/28471922-21459ea2-6e15-11e7-96fe-1dbcea8215ed.png)
The code I use is this
```java
Thread t = new Thread(() -> {
            Platform.runLater(() -> {
                ObservableList<Curso> queryAll = BancoDeDados.curso().queryAll();
                //My JFXComboBox
                this.cbCurso.setItems(queryAll);
                //Here I select but it goes blank
                this.cbCurso.getSelectionModel().select(contato.getCursoInteresse());              
            });
        });
        t.setDaemon(true);
        t.start();
```
I've checked to see if it actually has the items.
![screenshot at jul 21 12-54-38](https://user-images.githubusercontent.com/17498775/28472146-d011a598-6e15-11e7-88b0-c87f91a18e81.png)
This code works normally in the JavaFX components, I'm just passing it to Jfoenix, but in this case the ComboBox has this problem.
Funny that the comboBox (name Situacao) that I put Enum in it works fine.

I apologize for the English, but could anyone help me?
And one more note, I made a print to check if the item is selected, and is actually selected
```java
//The item is selected but does not show on the screen.
System.out.println("Curso Selecionado: " + this.cbCurso.getSelectionModel().getSelectedItem());
```

**Comment by jeanJavaMan** [comment]
After beating his head a lot. Putting the combobox as editable, returns to normal operation.
```java
this.cbCurso.setEditable(true);
```
![screenshot at jul 21 18-05-23](https://user-images.githubusercontent.com/17498775/28482571-4cdabaf0-6e3f-11e7-8681-282a06b3c6a6.png)
For what reason?
But at least now I can move on with my project.

**Comment by jfoenixadmin** [comment]
Hello,
not sure what's causing the problem in your application, as we were not able to reproduce the issue using a simple example and the latest JFoenix jar. Can you please re-validate using the latest JFoenix jar?

Regards,

**Comment by jeanJavaMan** [comment]
Hi, thanks for replying.
Well I'm using version 1.6.0, tested with other versions when I got to version 1.4.0, the text prompt appeared some problems. I'm using the latest Hibernate. My probema only solves putting the combobox for editable.
Putting the combobox as editable is no problem for me here in this project, so I will go ahead and see if when using combobox with another class give the same problem. Thank you so much

**Comment by jfoenixadmin** [comment]
Hello,
