### ISSUE TITLE
JFXListView separator

### ISSUE THREAD

**Issue by AhmedMouradDev** [jfoenixadmin/JFoenix#381]
Hi, I've been wondering if it's possible to add a separator line between listview rows? just like the one from android where you set the decoration

I've tried to add one manually between the cells in Non-Expanded mode and remove it when expanding but can't seem to remove the row padding or prevent it from being selected

![image](https://user-images.githubusercontent.com/29189251/28558864-27d46a6c-7114-11e7-8b5a-a5bc035c2dc4.png)

Thank you

**Comment by jfoenixadmin** [comment]
Hello,
Well currently there is no such feature in JFXListView.  if you added the separator as a cell, then the user should be able to select it. To overcome this you can add a pseudo class to the separator cell to keep the background color on selection so it won't appear to the user as selected.

Regards,
