### ISSUE TITLE
JFXDrawer

### ISSUE THREAD

**Issue by noshaba** [jfoenixadmin/JFoenix#382]
Hello,

if I have content behind the JFXDrawer, that I want to edit, I can't even if the JFXDrawer is closed.
It only works if I do a setVisible(false) but then I don't see the animation anymore. Could you maybe make it that way, that if close() has finished that you call a setVisible(false) and before you open(), you do a setVisiable(true). This would really feel more natural...
Unfortunately, I don't know how to get when the close() animation has finished...

**Comment by jfoenixadmin** [comment]
Hello,
JFXDrawer doesn't block events on the content node when closed. can you provide a sample code demonstrating this issue?

Regards,

**Comment by noshaba** [comment]
Well, not on the content node, but if there is something behind the drawer, then I can't access it because the drawer is on top of it (just closed). E.g. you put a text field somewhere and then on top of that you put the drawer, so when it is open it overlays the text field and when it is closed you see the text field and can edit it (except that you can't edit it the way the drawer is implemented now).

**Comment by jfoenixadmin** [comment]
Well, I see your point. The TextField should be part of the drawer content in order to get the right behavior. JFXDrawer was not designed to handle this case. Feel free to add your own contribution to JFoenix.

Regards,

**Comment by valimaties** [comment]
The approach is not good @noshaba .
The drawer must be the container which must have your other objects to display. You could set them using setContent() of the drawer class. 
![Drawer](https://user-images.githubusercontent.com/49796453/235161214-f5991bdd-9d09-4ebd-b360-e4f183c772a0.gif)
