### ISSUE TITLE
JFXTreeTableView add/remove on observableArrayList are not reflected to the control

### ISSUE THREAD

**Issue by mirisha** [jfoenixadmin/JFoenix#384]
I have JFXTreeTableView which is defined with a root item as ObservableList<User> users
I am trying to add/remove items from the users list, but the changes are not been reflected to the JFXTreeTableView  control.
I also tried to force updating the JFXTreeTableView  by using  treeView.refresh(); but it did not helped

As i understand from previous discussion in this post:
https://github.com/jfoenixadmin/JFoenix/issues/186 
that there should be  a complete support in pushing updated from the ObservableList to the JFXTreeTableView 
 
here is my sample code
                       
                    ObservableList<User> users = FXCollections.observableArrayList();
			users.add(new User("Computer Department", "23","CD 1"));
			users.add(new User("Sales Department", "22","Employee 1"));

			for(int i = 0 ; i< 5; i++){
				users.add(new User("HR Department", i%10+"","HR 2" + i));	
			}
			
			// build tree
			final TreeItem<User> root = new RecursiveTreeItem<User>(users, RecursiveTreeObject::getChildren);		
			JFXTreeTableView<User> treeView = new JFXTreeTableView<User>(root, users);		
			
			treeView.setShowRoot(false);
			treeView.setEditable(true);
			treeView.getColumns().setAll(deptColumn, ageColumn, empColumn);
			
--> and now if I do an "add" operation on the collection it does not effect the view
			users.add(new User("HR Department ", "32","Employee 6" ));
			treeView.refresh();

I also checked this in your demo  sample : TreeTableViewController
which perform add in run time by  doing

`treeTableViewAdd.setOnMouseClicked((e) -> {
			root.getChildren().add(new Person(names[random.nextInt(names.length)], names[random.nextInt(names.length)], random.nextInt(100)));
			treeTableView.currentItemsCountProperty().set(treeTableView.currentItemsCountProperty().get()+1);
		});`

I tried to do the add operation on the "people1" collection instead on  root (which is a RecursiveTreeObject) 
like so:

`treeTableViewAdd.setOnMouseClicked((e) -> {
			people1.add(new Person(names[random.nextInt(names.length)], names[random.nextInt(names.length)], random.nextInt(100))); 
			treeTableView.refresh();					
		});`
it also did not worked

Thank you

**Comment by jfoenixadmin** [comment]
Hello,
How did you manage to create JFXTreeTableView using the following constructor?
`JFXTreeTableView<User> treeView = new JFXTreeTableView<User>(root, users);	`
we tested the add/remove operation on JFXTreeTableView, both methods are working. if you could provide the whole code that demonstrates this issue we could be able to help.

Regards,

**Comment by mirisha** [comment]
I used the sample code from the following thread
https://github.com/jfoenixadmin/JFoenix/issues/186
the new JFXTreeTableView<User>(root, users); was available there
I can see this constructor is not even supported in the latest version.

Any way, it made my understand that I may be testing my sample on an old version.  So when switching to latest version the problem was fixed
thank you for the help
