### ISSUE TITLE
css doesn't reset back after pseudoClassStateChanged

### ISSUE THREAD

**Issue by vincenzomartusciello** [jfoenixadmin/JFoenix#385]
I've created boolean bindings to lock and unlock the buttons, but after using the pseudoclass the css does not seem to be restored, how can I fix it?

before
![red](https://user-images.githubusercontent.com/5598384/28735238-abb5db4a-73e4-11e7-835e-4ad0a20587a3.png)

after
![nored](https://user-images.githubusercontent.com/5598384/28735240-abd9f3ae-73e4-11e7-827d-7a2d6fb408b7.png)

I'm using this to customize css
```

.jfx-text-field:validation-error {
    -fx-background-color: #ffcccc ;
}
.jfx-date-picker:validation-error .text-field {
    -fx-control-inner-background: #ffcccc ;
}
.jfx-combo-box:validation-error {
    -fx-background-color: #ffcccc;
}
.jfx-time-picker:validation-error .text-field {
    -fx-background-color: #ffcccc;
}
```

and this in java

`        nodo.pseudoClassStateChanged(PseudoClass.getPseudoClass("validation-error"), invalid);
`

where invalid is boolean

I fix adding this to css 

`.jfx-text-field, .jfx-date-picker .text-field, .jfx-combo-box, .jfx-time-picker .text-field {
    -fx-background-color: transparent;
    -jfx-focus-color: #1b75bc;
}`

but it's normal?

**Comment by jfoenixadmin** [comment]
Hello,
if you are changing the pseudo state correctly in code then no it's not normal. will look into it, thanks for pointing out the issue 👍 .

Regards,
