### ISSUE TITLE
JFXDatePicker styling the editor

### ISSUE THREAD

**Issue by AhmedMouradDev** [jfoenixadmin/JFoenix#389]
Hey again,
I can't seem to be able to style the editor, i want to change its unfocus color so i've tried this approach

`.jfx-date-picker > .editor {
    -jfx-unfocus-color: #9E9E9E;
}`

but it doesn't seem to work at all, so any hint?

Thank you

**Comment by jfoenixadmin** [comment]
Hello,
currently you can change it by having the following css:
`.jfx-date-picker > .jfx-text-field { -jfx-unfocus-color: #9E9E9E; }`

Regards,
