### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by ofirmiron** [jfoenixadmin/JFoenix#391]
Is there a way to show the advance color picker (the one shown in the picture) without having a color picker control on the scene. I just want to have a button that will open it, and run independently of the stage/scene.
![color picker](https://user-images.githubusercontent.com/17969689/28993357-47e3d858-7969-11e7-9941-94da97c07948.PNG)

**Comment by jfoenixadmin** [comment]
Hello,
Yes, the control is called JFXCustomColorPickerDialog, you can use it independently of JFXColorPicker.

Regards,
