### ISSUE TITLE
JFXSnackbar timeout doesn't work

### ISSUE THREAD

**Issue by AhmedMouradDev** [jfoenixadmin/JFoenix#392]
I've recently upgraded to v1.6 of JFoenix jar and noticed that the timeout of the snackbar doesn't work, once the snackbar is shown it stays there,

this's the method i use to show the snackbar

`private void showInformationSnackBar(String msg) {

        JFXSnackbar fXSnackbar = new JFXSnackbar(dialogRoot);

        fXSnackbar.show(msg, 3000);
    }`

It should be noted that it worked properly before upgrading, so is there any additional work i need to do with the new version?

Thank you,

**Comment by jfoenixadmin** [comment]
Hello, 
Thanks for pointing out the issue 👍 , will push the fix asap. You can get it by downloading the latest JFoenix jar

Regards,
