### ISSUE TITLE
FXtreeTableView   synchronization problem to ObservableList 

### ISSUE THREAD

**Issue by mirisha** [jfoenixadmin/JFoenix#393]
Hi
I am using FXtreeTableView  (table) by binding to observable list like so

ObservableList<ExecutableItem> _tasksQueueCalib = FXCollections.observableArrayList();
TreeItem<ExecutableItem>  rootTreeItem =  new RecursiveTreeItem<ExecutableItem>(_tasksQueueCalib , RecursiveTreeObject::getChildren);

table.setRoot(rootTreeItem);
bindRootPropertyOfTree(table,rootTreeItem);
table.setShowRoot(false);

I want to implement "reorder" functionality, meaning the user selects an item in the treeTable and he can choose to move it one row up or one raw down

I am doing it by changing the ObservableList like so:

 _tasksQueueCalib .add(fromIndex-1, _selectedItem);
_tasksQueueCalib .remove(fromIndex+1);

after this step the items in the _tasksQueueCalib look good, but the items in the FXtreeTableView   are not corresponding

for example - original list in the tree: 1,2,3
the user chooses to "move up" item 3: so the ObservableList  holds 1,3,2 but the FXtreeTableView    displays 1,2 (item 3 completely removed)

I tried to perform the "add" and "remove" on the collection inside Platform.runLater statment to make sure the update are done in the UI thread, but it did not helped

Are you aware of a problems in reflecting changes of  "reordering" items in the observable list into the FXtreeTableView     control ? 
It seams like there is some synchronization problem.

Thank you

**Comment by jfoenixadmin** [comment]
Hello,
Well reordering table items should be only reflected on the UI model which is the TreeItem list, it shouldn't be reflected on the actual data model.
thus you can reorder the items using the following;

```
TreeItem item = root.getChildren().remove(fromIndex+1);
root.getChildren().add(fromIndex-1, item);
```

Regards,
