### ISSUE TITLE
JFXSnackbar appears again after calling JFXSnackbar.close()

### ISSUE THREAD

**Issue by vasso123** [jfoenixadmin/JFoenix#394]
Hello, 
I noticed that, after calling close on a snack bar, it appears again immediately, and closes after timeout.
I assume it's a non intended behaviour?

Kind regards

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 , sure it's no an intended behavior.

Regards,

**Comment by M-FF-M** [comment]
If you want to fix this bug: save the animation created in lines 223 and 284 (JFXSnackbar.java) in a private variable (e.g. private Animation animation_save). Then call animation_save.stop(); in method close (line 283) before doing anything else.
