### ISSUE TITLE
SnackbarEvent constructor

### ISSUE THREAD

**Issue by vasso123** [jfoenixadmin/JFoenix#395]
Hi,
I noticed that the 3rd constructor in the SnackbarEvent
`SnackbarEvent(String message, String actionText, long timeout, boolean persistent, EventHandler<? super MouseEvent> actionHandler)`
 is not correctly passing parameters to the main constructor, to be precise, next parameters are not being passed to the main constructor: actionText, timeout, persistent, actionHandler.

Kind regards

**Comment by jfoenixadmin** [comment]
Hi
you are right, this is duplicate for #392  pushed the fix to maven central / jfoenix website.

Regards,
