### ISSUE TITLE
JFXSnackbar setting effects

### ISSUE THREAD

**Issue by vasso123** [jfoenixadmin/JFoenix#396]
Hi,

I noticed that setting effects on a snack bar has no "effects" :)
For example:
`JFXSnackbar snackBar = new JFXSnackbar(rootNode);
DropShadow dropShadow = new DropShadow();
dropShadow.setRadius(5.0);
dropShadow.setOffsetX(3.0);
dropShadow.setOffsetY(3.0);
dropShadow.setColor(Color.color(0.4, 0.5, 0.5));
snackBar.setEffect(dropShadow);
snackBar.getStyleClass().add("snackbar-error");
snackBar.enqueue(new JFXSnackbar.SnackbarEvent("Hello World!", null, null, 5000, false, null));`
, I see no shadow underneath the snack bar.

Kind regards

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 , well JFXSnackBar needs a rework soon. It's not well structured as it shouldn't extend the Node class. It should be treated as a popup control.

Regards,

**Comment by jfoenixadmin** [comment]
Hello,
You should be able to style JFXSnackBar directly now.

Regards,
