### ISSUE TITLE
Problem with prompttext after 1.7.0 update

### ISSUE THREAD

**Issue by vincenzomartusciello** [jfoenixadmin/JFoenix#399]
**Version 1.6.0**
![1 6](https://user-images.githubusercontent.com/5598384/29236494-54189dc8-7f0b-11e7-855e-7c2e6607e13b.png)

**Version 1.7.0**
![1 7](https://user-images.githubusercontent.com/5598384/29236495-5419ae70-7f0b-11e7-9cd2-25f03a60b02b.png)

It's normal?

**Comment by jfoenixadmin** [comment]
Hello, 
what's the problem?
in 1.7.0 the default prompt text fill has been set to "#4D4D4D"
You can simply change it by adding the following to your css file:

```
.jfx-text-field,
.jfx-text-field:focused {
    -fx-prompt-text-fill: #color;
}
```

Regards,

**Comment by vincenzomartusciello** [comment]
thanks
