### ISSUE TITLE
License compatibility

### ISSUE THREAD

**Issue by aalmiray** [jfoenixadmin/JFoenix#4]
It looks like some code has been copied from Fxperience (`com.jfoenix.jidefx.CachedTimelineTransition`, authored by Jasper Potts). This code was published under GPLv2 + CP but JFoenix is published under LGPLv3. I worry there may be a license incompatibility issue here, which would prevent this library form being used in a serious environment where license compliance is a deciding factor (all FLOSS licenses should be honored all the way :smirk:).

**Comment by jfoenixadmin** [comment]
it's been removed from the library
