### ISSUE TITLE
SceneBuilder 2 doesn't support importing of jar files any more

### ISSUE THREAD

**Issue by manfredk** [jfoenixadmin/JFoenix#40]
Tried to follow your installation instructions, downloaded the jfoenix.jar and wanted to import it with SceneBuilder 2, but haven't found the import jar option. Any idea how to solve this?

**Comment by hemangsk** [comment]
Hi, I did the installation yesterday and Scene Builder 2 is working fine with import JAR file feature, but the thing is, The Import JAR/fxml feature appear in the Scene Builder 2 after you click on the settings icon.
I am attaching an image, hope you observe where we have to click (that tiny settings icon )
![screen shot 2016-02-03 at 8 24 26 pm](https://cloud.githubusercontent.com/assets/13018570/12785811/50158f86-cab4-11e5-8b94-eadf4ef204db.png)

**Comment by manfredk** [comment]
Hi Hemang, thanks for the quick reply, that solved the issue. Cheers, Manfred
