### ISSUE TITLE
Asterisk Mark for mandatory fields.

### ISSUE THREAD

**Issue by ashishshinde33** [jfoenixadmin/JFoenix#400]
![asterisk](https://user-images.githubusercontent.com/26764585/29238854-e3f76024-7f5a-11e7-879d-584fbdd40b84.png)

Is there any way or css to change the color of only (*)star in prompt text with float label.

**Comment by jfoenixadmin** [comment]
Hello,
Currently JFoenix doesn't support such a feature, you can only add validation text under the text field.
Feel free to add your own contribution to JFoenix.

Regards,
