### ISSUE TITLE
JFXButton custom CSS background class

### ISSUE THREAD

**Issue by begonaalvarezd** [jfoenixadmin/JFoenix#405]
Hello!! I just noticed that there is a new JFoenix jar version to download (my last update was 10 months ago), but I am facing a style issue with the RAISED JFXButtons. Lets say I have a raised button with a custom class 
`.white-background{
	-fx-background-color: #FFFFFF;
}`

which looks as follows 
![white_button_enabled](https://user-images.githubusercontent.com/3624944/29524978-91355664-8691-11e7-9488-9ea80630593a.png)

So far so good, same behavior as before...until I set the button to **disabled**. Then...instead of being as the old JFoenix (same white style as before but with a 0.4 opacity, see below)
![white_button_disabled_old](https://user-images.githubusercontent.com/3624944/29525065-d6c04306-8691-11e7-9465-63d63c7bf714.png)

The button turns grey..it is like there is some shadow box somewhere... see bellow
![white_button_disabled_new](https://user-images.githubusercontent.com/3624944/29525128-03386b16-8692-11e7-8ad6-c5e91d94a334.png)

I have been trying to find where it comes from but I really do not manage to see what is happening. 

Thank you very much! :)

**Comment by jfoenixadmin** [comment]
Hello,
Thanks for pointing out the issue 👍 , will look into it.

Regards,

**Comment by begonaalvarezd** [comment]
Wow that was fast! Now it is working great as always :smile: 

Thank you so much for your support :+1:

**Comment by Carbs0126** [comment]
Hello, the JFoenix is awesome! and thank you for your open source code. 
 I am a javafx learner, and i don't know how to add a shadow to a window, could you tell me how to add shadow? i have made my stage as  `primaryStage.initStyle(StageStyle.TRANSPARENT);`
