### ISSUE TITLE
JFXComboBox change rippler color

### ISSUE THREAD

**Issue by AhmedMouradDev** [jfoenixadmin/JFoenix#407]
Hi,

I've trying to change the blue ripple color of the cells of the popup but can't find the CSS class or attribute responsible for doing so...

Best regards,

**Comment by jfoenixadmin** [comment]
Hi,
you can change it using the following css:
```
.combo-box-popup .list-view .jfx-list-cell .jfx-rippler {
    -jfx-rippler-fill: #color;
}
```

Regards,

**Comment by Dooardarshan** [comment]
Hi can you please tell me how to change the hover color ?
