### ISSUE TITLE
Can't change the color of the Tabs Selection Bar (JFXTabPane)

### ISSUE THREAD

**Issue by peteralien** [jfoenixadmin/JFoenix#410]
I'm using the 1.7.0 version of jfoenix, but i can't change the color of the Tabs Selection Bar :(

Everything works except changing the Tabs Selection Car color, it always remain yellow.
Can anyone help me with this.

Here is the code i have:

.jfx-tab-pane
{
    -fx-padding: 1px;
    -fx-background-color: blue, -fx-control-inner-background;
    -fx-background-insets: 0, 1;
}

.jfx-tab-pane .headers-region
{
    -fx-background-color: cornflowerblue;
}

.jfx-tab-pane .tab-header-background
{
    -fx-background-color: cornflowerblue;
}

.jfx-tab-pane .tab-header-area .jfx-rippler
{
    -jfx-rippler-fill: orange;
}

.jfx-tab-pane .tab-header-area .tab-selected-line
{
    -fx-stroke: red;
}

Many thanks.

**Comment by peteralien** [comment]
Well i just did with:

.jfx-tab-pane .tab-selected-line
{
  -fx-border-color: red;
}

Now what i can't do is changing the color of the arrows that appear in the header area of the JFXTabPane.

**Comment by jfoenixadmin** [comment]
Hello,
you can change it using the following css:
```
.jfx-tab-pane .tab-header-area .control-buttons-tab .tab-down-button{
    -fx-background-color: #color;
}
```
Regards,

**Comment by peteralien** [comment]
Many thanks, jfoenixadmin. It worked.
