### ISSUE TITLE
JFXTreeTableView - After using the Filter, the Application doesn't exit well

### ISSUE THREAD

**Issue by peteralien** [jfoenixadmin/JFoenix#413]
The Application doesn't close/exit well. Can anyone tell me why?
I tried to change the code but still doesn't exit.

Another thing, if i click in the "Group" Button twice, the data in the JFXTreeTableView becames awkward﻿ when i click in the arrows that appear.

Here is the code that i have:

public void start(Stage primaryStage)
  {
    JFXTreeTableColumn<User, String> deptColumn = new JFXTreeTableColumn<>("Departamento");
    deptColumn.setResizable(false);
    deptColumn.setPrefWidth(150);
    deptColumn.setCellValueFactory((TreeTableColumn.CellDataFeatures<User, String> param) ->
    {
      if (deptColumn.validateValue(param))
        return param.getValue().getValue().department;
      else
        return deptColumn.getComputedValue(param);
    });
    
    JFXTreeTableColumn<User, String> empColumn = new JFXTreeTableColumn<>("Empregado");
    empColumn.setResizable(false);
    empColumn.setPrefWidth(150);
    empColumn.setCellValueFactory((TreeTableColumn.CellDataFeatures<User, String> param) ->
    {
      if (empColumn.validateValue(param))
        return param.getValue().getValue().username;
      else
        return empColumn.getComputedValue(param);
    });
    
    JFXTreeTableColumn<User, String> ageColumn = new JFXTreeTableColumn<>("Idade");
    ageColumn.setResizable(false);
    ageColumn.setPrefWidth(150);
    ageColumn.setCellValueFactory((TreeTableColumn.CellDataFeatures<User, String> param) ->
    {
      if (ageColumn.validateValue(param))
        return param.getValue().getValue().age;
      else
        return ageColumn.getComputedValue(param);
    });
    
    deptColumn.setCellFactory((TreeTableColumn<User, String> param) -> new GenericEditableTreeTableCell<>(new TextFieldEditorBuilder()));
    deptColumn.setOnEditCommit((CellEditEvent<User, String> t) -> t.getTreeTableView()
      .getTreeItem(t.getTreeTablePosition()
      .getRow())
      .getValue().department.set(t.getNewValue()));
    
    empColumn.setCellFactory((TreeTableColumn<User, String> param) -> new GenericEditableTreeTableCell<>(new TextFieldEditorBuilder()));
    empColumn.setOnEditCommit((CellEditEvent<User, String> t) -> t.getTreeTableView()
      .getTreeItem(t.getTreeTablePosition()
      .getRow())
      .getValue().username.set(t.getNewValue()));
    
    ageColumn.setCellFactory((TreeTableColumn<User, String> param) -> new GenericEditableTreeTableCell<>(new TextFieldEditorBuilder()));
    ageColumn.setOnEditCommit((CellEditEvent<User, String> t) -> t.getTreeTableView()
      .getTreeItem(t.getTreeTablePosition()
      .getRow())
      .getValue().age.set(t.getNewValue()));
    
    ObservableList<User> users = FXCollections.observableArrayList();
    users.add(new User("Computer Department", "29", "Carlos Teixeira"));
    users.add(new User("Sales Department", "24", "Luís Vaz"));
    users.add(new User("Sales Department", "32", "António Augusto"));
    users.add(new User("Sales Department", "28", "Mário Rodrigues"));
    users.add(new User("Sales Department", "41", "Manuela Maria"));
    users.add(new User("IT Department", "42", "Pedro Fonseca"));
    users.add(new User("HR Department", "35", "Manuel Vilarinho"));
    users.add(new User("HR Department", "26", "Suzel Almeida"));
    
    for (int i = 1; i <= 3; i++)
      users.add(new User("Computer Department", Integer.toString(i * 18), "CD-" + (i + 1)));
    
    for (int i = 1; i <= 3; i++)
      users.add(new User("Sales Department", Integer.toString(i * 19), "Sales-" + (i + 4)));
    
    for (int i = 1; i <= 3; i++)
      users.add(new User("IT Department", Integer.toString(i * 19), "IT-" + (i + 1)));
    
    for (int i = 1; i <= 3; i++)
      users.add(new User("HR Department", Integer.toString(i * 20), "HR-" + (i + 2)));
    
    GridPane main = new GridPane();
    main.setPadding(new Insets(20, 20, 20, 20));
    main.setHgap(10);
    main.setVgap(30);
    
    TreeItem<User> root = new RecursiveTreeItem<>(users, RecursiveTreeObject::getChildren);
    JFXTreeTableView<User> treeView = new JFXTreeTableView<>(root);
    treeView.setPlaceholder(new Label("A Tabela encontra-se vazia!"));
    treeView.setShowRoot(false);
    treeView.setEditable(true);
    treeView.getColumns().setAll(deptColumn, empColumn, ageColumn);
    main.add(treeView, 2, 0);
    
    JFXButton groupButton = new JFXButton("Group");
    groupButton.setOnAction((action) -> new Thread(() -> treeView.group(deptColumn)).start());
    main.add(groupButton, 0, 1);
    
    JFXButton unGroupButton = new JFXButton("UnGroup");
    unGroupButton.setOnAction((action) -> treeView.unGroup(deptColumn));
    main.add(unGroupButton, 0, 2);
    
    Label filterTitle = new Label("FILTRO A APLICAR:");
    filterTitle.setId("filterTitle");
    main.add(filterTitle, 0, 3);
    JFXTextField filterField = new JFXTextField();
    main.add(filterField, 1, 3);
    filterField.textProperty().addListener((observable, oldValue, newValue) ->
    {
      treeView.setPredicate(user ->
      {
        return user.getValue().department.get().contains(newValue) || 
               user.getValue().username.get().contains(newValue) ||
               user.getValue().age.get().contains(newValue);
      });
    });
    
    Label itemsFoundedTitle = new Label("Items Encontrados: ");
    itemsFoundedTitle.setId("itemsFoundedTitle");
    main.add(itemsFoundedTitle, 0, 4);
    Label nItems = new Label();
    nItems.setId("nItems");
    nItems.textProperty().bind(Bindings.createStringBinding(() -> String.valueOf(treeView.getCurrentItemsCount()), treeView.currentItemsCountProperty()));
    main.add(nItems, 1, 4);
    
    Scene scene = new Scene(main, 1000, 700);
    scene.getStylesheets().add(JFoenix_JFXTreeTableView.class.getResource("/jfoenix_jfxtreetableview/Styles.css").toExternalForm());
    primaryStage.setScene(scene);
    primaryStage.setResizable(false);
    primaryStage.show();
  }

  private static class User extends RecursiveTreeObject<User>
  {
    final StringProperty department;
    final StringProperty username;
    final StringProperty age;

    User(String department, String age, String userName)
    {
      this.department = new SimpleStringProperty(department);
      this.username = new SimpleStringProperty(userName);
      this.age = new SimpleStringProperty(age);
    }
}

Many thanks.

**Comment by jfoenixadmin** [comment]
Hello,
what do you mean by the application doesn't exit well? 
Also the group feature it's still under development, it might cause some errors if not called properly.

Regards,

**Comment by peteralien** [comment]
After using the Filter in the App, if i try to exit (clicking in the X button of the Window), the App continues to run in the background, doesn't terminate/exit well. I can see it running in NetBeans and in the Taskbar.

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍 , the fix will be pushed to maven central by the end of the month in JFoenix 1.8.

Regards,
