### ISSUE TITLE
JFXNodesList should not bind max size to pref size of first added node

### ISSUE THREAD

**Issue by dlemmermann** [jfoenixadmin/JFoenix#415]
The nodes list binds its max width and height to the pref width and height of the first node / button that is being added to it. If this button does indeed set a pref size (e.g. in CSS "-fx-pref-height: 100"), then the nodes list will not be laid out correctly anymore in a parent container. If the nodes list is for example placed inside a VBox then this box will not be big enough.

**Comment by jfoenixadmin** [comment]
Hello,
well it's intended behavior. The nodes list is a pane and we want to limit it's bounds to its root node (1st child). if you can provide a sample example to demonstrate the issue and to clarify, it would be appreciated.

Regards,

**Comment by jfoenixadmin** [comment]
Hello,
yeah, you are right. thanks for pointing out the issue 👍 

Regards

**Comment by jfoenixadmin** [comment]
Hello, 
@dlemmermann Can you please validate the fix?
