### ISSUE TITLE
JFXNodesList - How can i grab the Name or ID of the Node that was clicked

### ISSUE THREAD

**Issue by peteralien** [jfoenixadmin/JFoenix#420]
Hello,

Can anyone tell me how can i know which Node was clicked inside a JFXNodesList by the user?
I tried with setOnMouseClicked((MouseEvent event), but got no luck with it :(

﻿How can i, for example, put the name of the node that belongs to a JFXNodesList in a Textfield or in NetBeans Console?

I'm using jfoenix 1.7.0.

Many thanks.

**Comment by peteralien** [comment]
I tried with this and i did it, but is there a more simple and direct aproach?

  button?.setID("A1");
  button?.addEventHandler(MouseEvent.MOUSE_CLICKED, new eventHandler());


  
  private class eventHandler implements EventHandler<Event>
  {
    @Override
    public void handle(Event evt)
    {
      System.out.println(((Control) evt.getSource()).getId());
...
    }
  }

**Comment by jfoenixadmin** [comment]
Hello,
Currently JFXNodesList only responsible for laying out the nodes, there is not selection model for JFXNodesList.

Regards,
