### ISSUE TITLE
JFXDialog - Justify text

### ISSUE THREAD

**Issue by peteralien** [jfoenixadmin/JFoenix#422]
Is it possible to justify a big text inside a JFXDialog.

In my java file i have:

JFXDialogLayout conteudo = new JFXDialogLayout();
    
    JFXDialog dialog = new JFXDialog(pane, conteudo, JFXDialog.DialogTransition.CENTER);
    dialog.setOverlayClose(false);  // Evita o fecho do Dialog quando o utilizador clicar dentro do Stage.
    
    Text t1 = new Text();
		t1.setText("O que é o Lorem Ipsum?");
		t1.setFont(Font.font ("Times New Roman", FontWeight.BOLD, FontPosture.ITALIC, 19));
		t1.setFill(Color.BLACK);
    
    conteudo.setHeading(t1);
    
    Text t2 = new Text();
		t2.setText("O Lorem Ipsum é um texto modelo da indústria tipográfica e de impressão.\n" +
               "O Lorem Ipsum tem vindo a ser o texto padrão usado por estas indústrias\n" +
               "desde o ano de 1500, quando se misturou os caracteres de um texto para\n" +
               "criar um espécime de livro. Este texto não só sobreviveu 5 séculos, mas\n" +
               "também o salto para a tipografia electrónica, mantendo-se essencialmente\n" +
               "inalterada. Foi popularizada nos anos 60 com a disponibilização das folhas\n" +
               "de Letraset, que continham passagens com Lorem Ipsum, e mais recentemente\n" +
               "com os programas de publicação como o Aldus PageMaker que incluem versões\n" +
               "do Lorem Ipsum.");
		t2.setFont(Font.font ("Arial", 15));
		t2.setFill(Color.NAVY);
    
    conteudo.setBody(t2);
    
    JFXButton btn2 = new JFXButton("Sair");
    btn2.setId("btn2");
    btn2.setOnAction((ActionEvent event) ->
    {
      dialog.close();
    });
    
    conteudo.setActions(btn2);

Many thanks.

**Comment by jfoenixadmin** [comment]
Hello,
You can use Label instead of Text, and set text alignment to JUSTIFY.
will close this issue as it's not related to JFoenix development.

Regards
