### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by DevSett** [jfoenixadmin/JFoenix#423]
how to place a popup in the center without knowing its size (More precisely, the size of the buddies are always named since in the pop-up there will be a label that changes every time)

jfxPopup size return -1 or 0
and content from jfxPopup return 0 or -1
```
 jfxPopup.show(
                    stage.getScene().getRoot(), JFXPopup.PopupVPosition.TOP, JFXPopup.PopupHPosition.LEFT,
                    ...,...
            );
```

**Comment by DevSett** [comment]
jfxPopup.setOnShown(event -> {
                jfxPopup.setX(stage.getX() + stage.getWidth() / 2 - jfxPopup.getWidth() / 2);
                jfxPopup.setY(stage.getY() + stage.getHeight() / 2 - jfxPopup.getHeight() / 2);
            });

**Comment by jfoenixadmin** [comment]
Hello,
you can use JFXDialog or JFXAlert to get the corresponding behavior instead of JFXPopup.

Regards,
