### ISSUE TITLE
Coding error in SnackbarEvent constructor

### ISSUE THREAD

**Issue by M-FF-M** [jfoenixadmin/JFoenix#425]
If I'm not completely mistaken, there is a coding error in JFXSnackbar.java:
Line 389 should be: this(message, null, actionText, timeout, persistent, actionHandler);
instead of this(message, null,null, 3000, false, null);

**Comment by jfoenixadmin** [comment]
Hello, 
Definitely, thanks for pointing out the issue 👍 

Regards,
