### ISSUE TITLE
Icon Buttons

### ISSUE THREAD

**Issue by ProfessorProspector** [jfoenixadmin/JFoenix#427]
I had kinda expected JFoenix to have this, but there doesn't seem to be any kind of button like this with just an image and a circular ripple: 
![image](https://user-images.githubusercontent.com/6166773/30464070-2cd08ea4-9984-11e7-944a-91daa7a5f012.png)

Does this exist and I'm unable to find what it's called?

For my current project I have thrown together a crude one for myself, and if it doesn't exist in JFoenix I may make a nicer one and PR it in 
![image](https://user-images.githubusercontent.com/6166773/30464121-7ca65030-9984-11e7-88f3-584541e52719.png)

**Comment by jfoenixadmin** [comment]
Hello,
can you clarify the issue? 
you can simply create such a button by adding an icon and a border radius to JFXButton

Regards,

**Comment by ProfessorProspector** [comment]
Ah yes, of course.
