### ISSUE TITLE
JFXButton in JFXDialog

### ISSUE THREAD

**Issue by LosTigeros** [jfoenixadmin/JFoenix#428]
Is this normal behavior for JFXButton in JFXDialog?
When that button isn't in JFXDialog, then it work properly (background shows without disappearing problem).
After clicking the button, then it shows normaly.

https://imgur.com/a/TY40b

Style:
```
-fx-background-color: linear-gradient(to right, #9c27b0, #6a1b9a);
-fx-background-radius: 15px;
```

**Comment by jfoenixadmin** [comment]
Hello,
We were not able to reproduce the issue, it might be related to the applied css file.
can you double check your css file? it seems you are changing the background on mouse over event.

Regards,

**Comment by LosTigeros** [comment]
No, i'm not:
CSS
```
.fontSemiBold {
    -fx-font-family: 'Montserrat SemiBold';
}
.fontSize10 {
    -fx-font-size: 10;
}
.textFillWhite {
    -fx-text-fill: #ffffff;
}
.specialButton {
    -fx-background-color: linear-gradient(to right, #9c27b0, #6a1b9a);
    -fx-background-radius: 15px;
}
```

Button creation
```
saveButton = new JFXButton();
saveButton.setText("ZAPISZ");
saveButton.setPrefSize(100.0, 30.0);
saveButton.getStyleClass().addAll("fontSemiBold", "fontSize10", "textFillWhite", "specialButton");
```

**Comment by LosTigeros** [comment]
Okay, i figured it out. I've redownloaded JFoenix in Maven and it works now. Strange but true.
