### ISSUE TITLE
Problem with JFXTextField validator and requestFocus()

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#429]
Hi, i have a problem when I call the requestfocus () method on a JFXTextField with LabelFloat true that is validated. When I have the focus on the textfield and with a button I call the textField requestFocus () method the problem arises, the LabelFloat drops down and stays there until I again focus on JFXTextField.
![deepinscreenshot_20170917052144-iloveimg-cropped](https://user-images.githubusercontent.com/22163898/30519934-82ae4132-9b68-11e7-92e9-8fe93647d44f.png)

What I want to do, is to validate the textfield and at the same time make a requestFocus () to the same textfield.

Method for validation:
```
txtLastName.focusedProperty().addListener((o, oldVal, newVal) -> {
            if (!newVal) txtLastName.validate();
        })
```

Try to separate the call to the validate, executing it together with the requestFocus () method, but the result is the same
```

txtLastName.validate();
txtLastName.requestFocus();

```

**Comment by TioCoding** [comment]
I'm using the version 1.8 of Maven. Thanks

**Comment by jfoenixadmin** [comment]
Hello,
We were not able to reproduce the issue, can you provide a sample code demonstrating the issue?

Regards,

**Comment by TioCoding** [comment]
This happens when I call the resetValidation () method and I click the button quickly. This is the code I have:

```
txtTest.focusedProperty().addListener((o, oldVal, newVal) -> {
            if (!newVal) {
                txtTest.validate();
            }
        });

        btnTest.setOnAction(e -> {
            txtTest.resetValidation();
            txtTest.requestFocus();
        });
```

**Comment by TioCoding** [comment]
Also tested with the following code, and the error comes out on the first try when you press the button (remember that the click on the button has to be fast, because if you keep the focus on the button does not show the problem):

```
btnAction.setOnAction(e -> {
   txtTest.resetValidation();
   txtTest.validate();
   txtTest.requestFocus();
});
```

**Comment by jfoenixadmin** [comment]
Hello,
still was not able to reproduce, can you provide the full code?

Regards,

**Comment by TioCoding** [comment]
There are two blocks of code in the controller, each one shows the same problem but in different implementation, I hope this works :D.

https://github.com/TioCoding/JFoenixTest

**Comment by jfoenixadmin** [comment]
Hello,
We were able to reproduce the issue in the example you provided. it's fixed by using AnimationTimer instead of Transitions/Timelines.

Thanks for pointing out the issue 👍 

Regards,
