### ISSUE TITLE
Open classes for extending

### ISSUE THREAD

**Issue by Djaler** [jfoenixadmin/JFoenix#430]
Can you, please, make your classes, like a skins, more opened for extending. I mean, now all fields are private and I cannot add or change some behaviour in my inherited class. I thinks they should be protected instead

**Comment by jfoenixadmin** [comment]
Hello,
Can you be specific plz, what classes are you trying to extend? 

Regards,

**Comment by Djaler** [comment]
For example, JFXTextFieldSkin

**Comment by jfoenixadmin** [comment]
Well not all fields/methods should be protected,
so can you create a PR with your changes for this issue? 

Regards,

**Comment by jfoenixadmin** [comment]
Hello,
Will close this issue for now. if you would like to make some fields/methods protected for extending, feel free to open a PR with your changes.

Regards,
