### ISSUE TITLE
[Feature] JFXToggleNode unselectable in group as option

### ISSUE THREAD

**Issue by backtozero** [jfoenixadmin/JFoenix#431]
It would be nice to have option of restricting unselecting node while its in the group.

From javadoc of javafx.scene.control.RadioButton: 

> Only one RadioButton can be selected when placed in a {@link ToggleGroup}.
> Clicking on a selected RadioButton will have no effect.  A RadioButton that is not
> in a ToggleGroup can be selected and unselected.  By default a RadioButton is
> not in a ToggleGroup.  Calling {@code ToggleGroup.getSelectedToggle()}
> will return you the RadioButton that has been selected.

Its really simple to implement, just overiding one method from ToggleButton as RadioButton does:
```
    @Override public void fire() {
        // we don't toggle from selected to not selected if part of a group
        if (getToggleGroup() == null || !isSelected()) {
            super.fire();
        }
    }
```

I guess there should be property that makes it optional, so overall changes looks like this:

```
    private SimpleBooleanProperty unselectableInGroup = new SimpleBooleanProperty(true);

    /**
     * Toggles the state of the radio button if and only if the RadioButton
     * has not already selected or is not part of a {@link ToggleGroup}.
     */
    @Override
    public void fire() {
        // we don't toggle from selected to not selected if part of a group
        if (getUnselectableInGroup() || getToggleGroup() == null || !isSelected()) {
            super.fire();
        }

    }

    public final SimpleBooleanProperty unselectableInGroupProperty() {
        return this.unselectableInGroup;
    }

    public final boolean getUnselectableInGroup() {
        return unselectableInGroupProperty().get();
    }

    public final void setUnselectableInGroup(boolean value) {
        this.unselectableInGroupProperty().set(value);
    }

```
And in fxml it will look like:
```
<JFXToggleNode toggleGroup="$toggleGroup1" unselectableInGroup="false">
    <Label styleClass="title-label">InGroup</Label>
</JFXToggleNode>
```

I can make PR if this is ok.

**Comment by jfoenixadmin** [comment]
Hello,
You can add this behavior by simply extending the JFXToggleNode, and override the method fire(). There is no need to mix the radio button behavior with JFXToggleNode using a property.

Regards,
