### ISSUE TITLE
JFXTreeTableView with 20,000 rows is slow to clean

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#433]
Hello, I'm using the JFXTreeTableView, and trying to put more than 20,000 rows working correctly, the problem arises when I want to clean all records, it's very slow. This is the code I have:

```
private ObservableList<ProductoStockInicialTable> listaProductosSaldo;
listaProductosSaldo = FXCollections.observableArrayList();
tablaSaldos.setRoot(new RecursiveTreeItem<(listaProductosSaldo,RecursiveTreeObject::getChildren));
tablaSaldos.setShowRoot(false);
```
To add the 20,000 records I do with this method:

```
public void addListProductoFraccionSaldo(List<ProductoStockInicialTable> listaProductoFraccion) {
        listaProductosSaldo.addAll(listaProductoFraccion);
    }
```
And to clean it I do with this other method:

```
public void clearListProductoFraccion() {
      listaProductosSaldo.clear(); // Is very slow
}

```
I am doing some misuse of the JFXTreeTableView? or maybe there is a more optimal solution to mine? Thank you so much for everything. Regards.

**Comment by TioCoding** [comment]
Using the question, how can I do to clear the entire JFXTreeTableView, use clear method(), but I delete the ones that are showing in the table, when I make a filter with the predicate() method, only I delete the ones that are shown with the filter, when I return the filter to its normal state, me the ones that were not shown. How could you solve this problem? Thanks in advance

**Comment by jfoenixadmin** [comment]
Hello,
Well you can try deleting JFXTreeTableView items directly instead of deleting from the data model.
can you provide the full code? maybe we can try optimize it.

Regards,
