### ISSUE TITLE
JFXNodesList not becoming responsive

### ISSUE THREAD

**Issue by aboosidhu** [jfoenixadmin/JFoenix#435]
i would like to create a simple menubar(home,admin,settings)for my POS App with JFXnodelistview.For that i have choosed a button alongwith an imageview.And i got working code from 
github and its working perfectly,but my problem is my application is little responsive so that it should(button,image,text on that) resize according to screen size.so for resizing 
normally i used binding,but when i try to bind the button it resizes properly,but the alignment of parent and child  nodes spreading through the entire screen,i tested in all the way by putting nodelistview in hbox,stackpane,etc..but its working(no mismatch in alignment) correctly when i set prefwidth in css but sadly responsiveness not working.so is there any way to make nodelist as responsive like binding?

Here is my code
private DoubleProperty fontSize = new SimpleDoubleProperty(10);
	fontSize.bind(dataPane.getScene().widthProperty().add(root.getScene().heightProperty()).divide(100)); //getting scene size for binding

	JFXButton bt= new JFXButton("Home");
        bt.setContentDisplay(ContentDisplay.TOP);
        bt.styleProperty().bind(Bindings.concat("-fx-font-size: ", fontSize.asString(), ";")); //binding button according to screensize 
        bt.getStyleClass().add("animated-option-button");
        FileInputStream input= new FileInputStream("images/ihome.png");
        Image image = new Image(input, 100, 100, true,true);
        ImageView imageView=new ImageView(image);
        imageView.setPreserveRatio(true);
        imageView.fitWidthProperty().bind(fontSize)); //binding imageview on button according to screensize 
        imageView.fitHeightProperty().bind((fontSize));
	bt.setGraphic(imageView);
                           
        //same code for button2....
	JFXButton bt2= new JFXButton("Home");
	......
	......
         
	bt2.setGraphic(imageView2);

	JFXNodesList nodesList=new JFXNodesList();
        
        nodesList.addAnimatedNode(bt);
        nodesList.addAnimatedNode(bt1);
        nodesList.setRotate(270);
       	nodesList.setSpacing(10);
        
	StackPane main = new StackPane();
      	main.getChildren().add(nodesList);
       	main.setPadding(new Insets(10));
css
.animated-option-button {
    -fx-pref-width: 50px;
    -fx-background-color: #44B449;
    -fx-background-radius: 50px;
    -fx-pref-height: 50px;
    -fx-text-fill: white;
    -fx-border-color: WHITE;
    -fx-border-radius: 50px;
    -fx-border-width: 4px;

**Comment by jfoenixadmin** [comment]
Hello,
can you please clarify the issue? and if you can provide a full example demonstrating the issue (maybe with images), it would be great.

Regards,

**Comment by aboosidhu** [comment]
Hi,Thanks for your replay,i have solved the responsive problem with simpleway,i have removed the lines 
-fx-prefwidth:50px; and -fx-prefHieght:50px from css and put into
button.styleProperty().bind(Bindings.concat("-fx-font-size: ", fontSize.divide(2).asString(), ";",
                                                     "-fx-pref-width: ", fontSize.multiply(4).asString(), ";",
                                                     "-fx-pref-height: ", fontSize.multiply(4).asString(), ";"));
 so it worked..

**Comment by aboosidhu** [comment]
Sadly i need to say 2 problems regarding jfx nodeslistview
1. it will not closing sub nodes when close the main node
2. not hiding the selected node.
actully i would like to modify it as a dropdown listview but i cant because of these problems.
Thank you.

**Comment by jfoenixadmin** [comment]
Hello,
Well these problems can be considered as features (as they are not implemented yet), feel free to add your own contribution to JFoenix.

Regards,
