### ISSUE TITLE
Distributing software with JFoenix: Quick question

### ISSUE THREAD

**Issue by mayuso** [jfoenixadmin/JFoenix#437]
My English is pretty limited and I am having trouble understanding Apache License 2.0.

I am working on a simple Java tool using JFoenix that I plan on releasing for free but not as open source. **Is that possible?** **What do I need to do to avoid any kind of problems regarding licenses?**

Thanks for your patience and sorry for using the issue system for stuff like this. I'll close the "issue" as soon as possible.

**Comment by jfoenixadmin** [comment]
Hello,
Yes sure, you can. However in case of any changes, you just need to add a NOTICES file listing your changes.

Regards,

**Comment by mayuso** [comment]
Many thanks. No, I don't plan on changing anything. JFoenix works great as it is for me. If I wanted to improve anything I would simply contribute to this repo. Many thanks for your message and your work in general :)
