### ISSUE TITLE
Add an example for JFXAlert

### ISSUE THREAD

**Issue by swftvsn** [jfoenixadmin/JFoenix#438]
Hi,

I couldn't find any examples how to use the alert box, could you add an example? (Or direct me to one if I missed it..)

Thanks!

**Comment by jfoenixadmin** [comment]
Hello,
Here is an example
```
        // stage must have a scene
        JFXAlert<Void> alert = new JFXAlert<>(stage);
        alert.setContent(content);
        button.setOnAction(action-> alert.show());
```

Regards,

**Comment by swftvsn** [comment]
Thanks for the input!

Why the alert is generic, ie what can I do with the <Void>, like JFXAlert<Long>?

**Comment by jfoenixadmin** [comment]
Hello,
JFXAlert<R> extends Dialog<R> where R is the return type of the dialog via resultProperty().

Regards,
