### ISSUE TITLE
Possible new control JFXNotifications

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#439]
Hi everyone, thanks for the great project you have had so far. I would like to contribute something to JFoenix, as I hope this project continues to improve. I tell the story first. I was looking for a notification component to implement it in my application, I found one in ControlsFx, but it does not implement MaterialDesing, so I rewrote its Notifications control to add a style to that of MaterialDesing. As you will see in the code, it is an overwriting of the one created by ControlsFx (I deleted some things, added in others and mostly are controlsfx). I would like to know if there is any problem that this is part of JFoenix. I leave the demo so that you can try it. Greetings and again thanks for JFoenix !!.

![deepinscreenshot_20170927073132](https://user-images.githubusercontent.com/22163898/30913505-114aa850-a356-11e7-8175-c6c8b621ce2a.png)

https://github.com/TioCoding/JFXNotifications

**Comment by skmedix** [comment]
@jfoenixadmin https://material.io/guidelines/patterns/notifications.html#notifications-templates

**Comment by jfoenixadmin** [comment]
Hello,
Well the controlFX license allow redistribution of code with modification so it should be fine. The notification looks cool, however @TioCoding  if you can provide additional templates to match material design notifications ( as in the link @skmedix provided) it would be great.

Regards,

**Comment by XlintXms** [comment]
@TioCoding i did not use Maven in my project ,so can you provide jar file in your repos.
Regards,

**Comment by TioCoding** [comment]
Development in #969
