### ISSUE TITLE
Missing Style

### ISSUE THREAD

**Issue by rafaeltrrs112** [jfoenixadmin/JFoenix#44]
The style for the raise-button class does not exists in the included style sheets. 

```
  button.getStyleClass.add("button-raised") // This does not work

//this will work
  button.setStyle("    -fx-padding: 0.7em 0.57em;\n    " +
    "-fx-font-size: 14px;\n    " +
    "-fx-button-type: RAISED;\n    " +
    "-fx-background-color: rgb(77,102,204);\n    " +
    "-fx-pref-width: 200;\n    " +
    "-fx-text-fill: WHITE;")
```

**Comment by jfoenixadmin** [comment]
yeah sure it's a custom css class for the demo, to change the button type you need to set the css property <b><i>-fx-button-type </b></i> to either **FLAT** or **RAISED** pretty much what you did.

**Comment by Tobisaninfo** [comment]
I have tried this out, but didn't see any difference between the two types. Who do I get the style from the dome, without using the stylesheet or custom styling ?
