### ISSUE TITLE
JFXCombobox LabelFloat have a problem.

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#441]
Hi, i am using the JFXComboBox with its LabelFloat property in true, everything works fine, the problem is fine when I want to add new values to the JFXComboBox and delete the previous ones. The label is placed on the values as in the image.

![22119779_1583523725044568_1587480392_o-iloveimg-cropped](https://user-images.githubusercontent.com/22163898/30956165-f5078e6e-a3fb-11e7-80b1-746ea7c558fe.png)

This is the method I have to add values to the JFXComboBox.

```
public void addListItemsComboBox(List<Employee> listEmployee){
     cboEmployee.getItems().clear();
     cboEmployee.setItems(FXCollections.observableList(listEmployee));
     cboEmployee.getSelectionModel().selectFirst();
}
```
(the error occurs when you use the method more than once)

Regards.

**Comment by jfoenixadmin** [comment]
Hello,
Well this issue is related to #429, thanks for pointing out the issue 👍 
will update the animation in all label float controls and push the fix.

Regards,
