### ISSUE TITLE
JFXPasswordField Styling Bug 

### ISSUE THREAD

**Issue by skmedix** [jfoenixadmin/JFoenix#450]
**JFoenix:** 1.9.0
**Java:** Oracle JDK 1.8.0_144

---
**Description:**
1. Bug appears since latest update
2. Unfocused field looks good
3. Focused has blue outline and white background

---
![image](https://user-images.githubusercontent.com/3246162/31144276-902f3efe-a880-11e7-90e7-6d27a71de330.png)

![image](https://user-images.githubusercontent.com/3246162/31144309-a566fe88-a880-11e7-8476-eb6e61c9192d.png)

---
**Reproducing:**

Main class:
```java
import com.jfoenix.controls.JFXPasswordField;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class JFXPasswordTest extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        JFXPasswordField passwordField = new JFXPasswordField();
        passwordField.setPrefSize(150, 30);
        passwordField.setLabelFloat(true);
        passwordField.setPromptText("Test");
        passwordField.setFocusColor(Color.RED);

        BorderPane borderPane = new BorderPane();
        borderPane.setPrefSize(250, 60);
        borderPane.setPadding(new Insets(10, 10, 10, 10));
        borderPane.setCenter(passwordField);

        primaryStage.setScene(new Scene(borderPane));
        primaryStage.show();
    }
}
```

**Comment by jfoenixadmin** [comment]
Hello,
Yeah we are aware of some styling issues in JFoenix 1.9.0 , it seems that the user agent style sheet is not applied properly. we are investigating what's causing these issues. 

Regards,

**Comment by jfoenixadmin** [comment]
Will push the fix to maven central as soon as possible.
