### ISSUE TITLE
How to control the bar that appears on the left of any TreeItem when selected in a JFXTreeView?

### ISSUE THREAD

**Issue by Soham3-1415** [jfoenixadmin/JFoenix#451]
What is the CSS identifier for the pink bar that the arrow points to in the image?

![capture](https://user-images.githubusercontent.com/17441466/31160082-59b54842-a893-11e7-834a-e1480a66d1b1.PNG)

**Comment by jfoenixadmin** [comment]
Hello,
Well currently you can't , as JFXTreeView is still in development. will keep you updated once finished.

Regards

**Comment by jfoenixadmin** [comment]
Hello,
we updated JFXTreeCell, you can now change the color using the following css:
```
.tree-cell .selection-bar {
    -fx-background-color: blue;
}
```

Regards,

**Comment by Soham3-1415** [comment]
Thanks for the update.
