### ISSUE TITLE
JFXTabPane tab-selected-line

### ISSUE THREAD

**Issue by deme78** [jfoenixadmin/JFoenix#456]
How can I change the width of the tab-selected-line. I tried the following code but it doesnt work:
.jfx-tab-pane .tab-selected-line {
    -fx-border-color: green;
    -fx-stroke-width: 3px;
}
I can set the color of the selected line but the width wont work. So i tested it on another way.

I set the border-width and the border-color of the tab like this:
.jfx-tab-pane .tab:selected  {
    -fx-border-width: 0 0 4 0;
    -fx-border-color: green;
}

But after that, I cant set the selected-line color. It takes the default color.
![grafik](https://user-images.githubusercontent.com/23071577/31218609-2be16436-a9bb-11e7-80e5-f9157f710406.png)

**Comment by jfoenixadmin** [comment]
Hello,
The selected line is a pane, so you can change its height using the following css:
```
.jfx-tab-pane .tab-selected-line {
    -fx-background-color: green;
    -fx-pref-height: 10;
}
```
You can use ScenicView in your development, it can provide alot of details about the scene structure and node style classes.

Regards,

**Comment by azdoudYoussef** [comment]
@jfoenixadmin can share with us all jfx css class with attribute (documentation), this will make our life much easier 👍

**Comment by jfoenixadmin** [comment]
@azdoudYoussef would love to, however full documentation is not available at the moment :/
JFoenix site has some <a href="http://jfoenix.com/documentation.html#Rippler">documentation</a>, however it's a bit outdated. You can also check JFoenix <a href="https://github.com/jfoenixadmin/JFoenix/wiki">wiki</a> for community documentation. Feel free to contribute to JFoenix wiki so we can all have full documentation :)

Regards,
