### ISSUE TITLE
[Feature] JFXCheckBoxTreeItem

### ISSUE THREAD

**Issue by Soham3-1415** [jfoenixadmin/JFoenix#457]
Javafx has a special tree item that works as a checkbox. It selects all the children when in a checked state and becomes indeterminate when only some of the children are checked.

http://docs.oracle.com/javafx/2/ui_controls/tree-view.htm

Example 13-5 shows an implementation of this. Currently there isn't one for JFXCheckBoxes.

**Comment by jfoenixadmin** [comment]
Hello,
it's more of a custom tree cell (there are many examples online), feel free to add your own contribution to JFoenix.

Regards,
