### ISSUE TITLE
How does the demo create collapsible JFXListView Items?

### ISSUE THREAD

**Issue by Soham3-1415** [jfoenixadmin/JFoenix#458]
![capture](https://user-images.githubusercontent.com/17441466/31225288-f6aba08e-a996-11e7-8de1-b82d95487c33.PNG)

Item 6 and 2.1 are collapsible, and I can't figure out how it is done. I didn't know that ListView items could be collapsible.

**Comment by jfoenixadmin** [comment]
Hello,
ListView items don't support this, it's part of JFoenix. However it might be removed in future versions, it could be implemented using a tree view instead.

Regards,

**Comment by jfoenixadmin** [comment]
Hello,
ListView items don't support this, it's part of JFoenix. However it might be removed in future versions, it could be implemented using tree view instead.

Regards,
