### ISSUE TITLE
Not work backspace on Android

### ISSUE THREAD

**Issue by svininykh** [jfoenixadmin/JFoenix#462]
Hello,

Did not work backspace(delete) key on Android keyboard for JFXTextField. Compile JFoenix 1.8.0 retrolambda for Android 4.2.2

**Comment by jfoenixadmin** [comment]
Hello,
did you try to use the java TextField control instead of JFXTextField? 
if the issue still persist with java TextField, then this issue is related to JavaFXPorts not JFoenix (as JFoenix only updates the ui)

Regards,

**Comment by svininykh** [comment]
Thank you for your answer. I try TextField, you were right, problem is related with JavaFXPorts.
