### ISSUE TITLE
Change color TabPane completely

### ISSUE THREAD

**Issue by CatMonster** [jfoenixadmin/JFoenix#463]
By applying these classes to a JFXTabPane 
`.jfx-tab-pane .headers-region {
    -fx-padding: 10px;
    -fx-background-color: #36474F;
}`
the space around arrows does not change like in the image
<img width="712" alt="screen shot 2017-10-10 at 15 42 30" src="https://user-images.githubusercontent.com/13244343/31389855-926c385a-add2-11e7-95c6-141affb596ca.png">

Why arrows aren't in their space? If I move the tabs to left or on right they return on their correct position

**Comment by jfoenixadmin** [comment]
Hello,
to change the color the header background use the following css:
`.jfx-tab-pane .tab-header-background { -fx-background-color: #36474F; }`
and regarding the arrow position it's a bug that was fixed in the latest JFoenix version 1.9.1
Regards,

**Comment by CatMonster** [comment]
@jfoenixadmin thanks for your answer, but by applying the code you suggested it does not work, even if I leave only your code.
Changed to version 1.9.1

**Comment by CatMonster** [comment]
Is there a way to style the arrows via css?

**Comment by jfoenixadmin** [comment]
Can you provide the css you are applying? as we tried the suggested code and it's working.
to style the arrows, you can use the following:
```
.jfx-tab-pane .control-buttons-tab{
    -fx-background-color: RED;
}
.jfx-tab-pane .control-buttons-tab .tab-down-button{
    -fx-background-color: GREEN;
}
.jfx-tab-pane .control-buttons-tab .jfx-rippler{
    -jfx-rippler-fill: Yellow;
}
```
NOTE: the rippler fill won't change in 1.9.1, as it's a bug which will be fixed in later versions (already fixed and pushed to github).

Regards,

**Comment by CatMonster** [comment]
Tried with another project and it works.
<img width="473" alt="screen shot 2017-10-12 at 08 36 29" src="https://user-images.githubusercontent.com/13244343/31482406-766e682e-af28-11e7-922c-c66098d2549a.png">
Is it possible to remove the arrows and leave the scrolling function only?
Now there's another problem: if JFXTabPane's Tabs are shorter than scene length, so they not require scrolling arrows, in the background there's another color like in the screenshot
![image](https://user-images.githubusercontent.com/13244343/31482642-65405fb6-af29-11e7-8923-54c009fdaf8b.png)
The code I use to color the JFXTabPane header is this one:
`	.jfx-tab-pane .headers-region {
	    -fx-background-color: #35464F;
	}`

**Comment by jfoenixadmin** [comment]
as mentioned before use the following css instead:
`.jfx-tab-pane .tab-header-background { -fx-background-color: #35464F; }`

**Comment by MRoblesBEA** [comment]
Hi man, look i'm using:
Netbeans IDE 8.0.2
Maven, javafx
Sceene Builder with library jfoenix:0.1.8

In Sceene builder i call to .css file, in properties:

//for change the header color, i  used:
.tab-header-background{
-fx-background-color: #356e37;
}

//for change the text color from the tabs
.tab-label {
    -fx-text-fill: white ;
}

//#356e37 is your hexadecimal color
