### ISSUE TITLE
CheckBox selected

### ISSUE THREAD

**Issue by iberras** [jfoenixadmin/JFoenix#464]
When a checkbox is selected by code or by FXML the checkbox state is not working correctly. Its like its not fully selected, but halfway.

I'm using the las version of jFoenix.

<img width="386" alt="captura de pantalla 2017-10-13 a la s 17 06 40" src="https://user-images.githubusercontent.com/7620735/31564381-fd201ba4-b038-11e7-804c-4d11360acaf7.png">

**Comment by jfoenixadmin** [comment]
Which version are you using? the latest version is 1.9.1

**Comment by iberras** [comment]
Just updated to the lastest version (i updated two weeks ago). Now it works! Thanks
