### ISSUE TITLE
JFXSnackbar method isShowing()?

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#465]
Hello, I would like to know if there is any way to tell if JFXSnackbar is displayed, since when calling the close() method, it generates an exception if the JFXSnackbar is not displayed. Regards.

**Comment by jfoenixadmin** [comment]
Hello,
Currently no, but maybe it's better to fix the exception instead. Thanks for pointing out the issue 👍 

Regards,
