### ISSUE TITLE
JFXTabPane not include FXML file

### ISSUE THREAD

**Issue by arthurcvm** [jfoenixadmin/JFoenix#468]
Hi, in my project without the JFoenix library I have a window with a TabPane and in Tabs have AnchorPanes included, but in this library return an error in SceneBuilder, look the error bellow:

![2017-10-20](https://user-images.githubusercontent.com/9640276/31847246-6bc3f8dc-b5f7-11e7-989c-dad38aed4408.png)

**Comment by jfoenixadmin** [comment]
Hello,
can you provide more info:  scene builder / java version , the log file from scene builder.

**Comment by arthurcvm** [comment]
The logfile don't create by system (C:\Users\user\AppData\Local\Temp\scenebuilder-8.3.0.log)
JavaFX Scene Builder 8.3.0
JFoenix 1.5.0
Java Version: 1.8.0_111-b14

**Comment by skmedix** [comment]
First of all, try the latest JFoenix 1.9.1

**Comment by arthurcvm** [comment]
But my project is based in 1.5, I switch the version and the same error persists.

**Comment by arthurcvm** [comment]
Hi! I include direct in the .FXML archive code and it worked, please close the issue, exemple code:

`<TabPane layoutX="14.0" layoutY="68.0" prefHeight="200.0" prefWidth="200.0" tabClosingPolicy="UNAVAILABLE" AnchorPane.bottomAnchor="47.0" AnchorPane.leftAnchor="0.0" AnchorPane.rightAnchor="0.0" AnchorPane.topAnchor="45.0">
        <tabs>
          <Tab text="Detalhes">
               <content>
                  <fx:include fx:id="balancoPanelTable" source="BalancoPanelTable.fxml" />
               </content>
          </Tab>
          <Tab text="Gráfico">
               <content>
                  <fx:include fx:id="balancoPanelChart" source="BalancoPanelChart.fxml" />
               </content>
          </Tab>
        </tabs>
      </TabPane>`

**Comment by webmaster2011** [comment]
Could you please share the content of your "BalancoPanelTable.fxml" ?
