### ISSUE TITLE
JFXComboBox prompt text color

### ISSUE THREAD

**Issue by M-FF-M** [jfoenixadmin/JFoenix#469]
I was trying to change the color of the prompt text of a JFXComboBox but I just couldn't do it. Maybe I'm missing something. Could someone tell me how to change the prompt text color?

Here is what I tried so far: `.jfx-combo-box { -fx-prompt-text-fill: #808080; }` This had no effect at all.

The following code almost works:
```
.jfx-combo-box .text { -fx-fill: #808080; }
.jfx-combo-box .list-view .list-cell .text { -fx-fill: black; }
.jfx-combo-box .list-view .list-cell:hover .text { -fx-fill: white; }
```

The problem when using this code is that the selected value will also be displayed in gray and that is not what I want:
![jfoenixcombobox](https://user-images.githubusercontent.com/19824989/31863970-20ebc6e0-b756-11e7-9565-267de41bd94b.png)
As you can see in the picture "EUR" is gray even though it should have the same color as "33.12"

**Comment by M-FF-M** [comment]
I finally found a solution. I'm not sure if that's the way it's supposed to be, but here it is (I used a `JFXComboBox<Label>`):

I added the following css: `.jfx-combo-box Label .text { -fx-fill: black; }`.

**Comment by jfoenixadmin** [comment]
Hello,
using the latest jfoenix jar you can change the color using the following css:
```
.jfx-combo-box{
    -jfx-focus-color: RED;
    -jfx-unfocus-color: YELLOW;
    -fx-prompt-text-fill: BLUE;
}
```
Regards,
