### ISSUE TITLE
JFoenix 9.0.0 Maven?

### ISSUE THREAD

**Issue by GregoryHlavac** [jfoenixadmin/JFoenix#470]
Is there any intention that this will eventually be in a maven artifact? Sort of complicates a build when you can't get all your dependencies properly from your gradle build script?

**Comment by jfoenixadmin** [comment]
yeah sure it will be published to maven central soon.

**Comment by GregoryHlavac** [comment]
Thanks.

**Comment by jfoenixadmin** [comment]
pushed JFoenix 9.0.0 to maven central it will be available in a couple of hours.
