### ISSUE TITLE
Disable Grouped of JFXTreeTableColum

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#472]
Hello, is there any method to disable grouping? So that it does not show the popup by clicking secondary on the column.

**Comment by jfoenixadmin** [comment]
Hello,
Currently there is no such a method, but you can simply remove this behavior by setting the context menu of the tree table column to null.

I noticed that the context menu is being set in Platform.runlater, this will be removed. so setting the context menu to null directly after calling the constructor should do the trick.


Regards,
