### ISSUE TITLE
jfxcheckbox

### ISSUE THREAD

**Issue by rebaihalim** [jfoenixadmin/JFoenix#473]
hi

1. i am using jfoenix 1.9.1,  in previous version of jfoenix (ex : 1.5) when jfxcheckbow is selected the fill of background is transparent just the mark appear (like NIKE without any fill of background) , my quesqtion is : how to remove background of fill and just keep the mark olone (i use classes .jfx-check-box .box, .fxx-check-box .bos-container {-fx-background-color : transparent; } but not tink happen  

2. jfxalert not show when close an other jfxalert (setOnHidden of first jfxalert but i work for jfxdiag !!!!) , any exception appear !!! what's wrong 

3. jfxtextarea : scroll appear only if prefheight of jfxtextarea >= 70 !!!

thank you

**Comment by jfoenixadmin** [comment]
Hello,
1. you can use the following css to remove the background fill:
```
.custom-jfx-check-box {
    -jfx-checked-color: TRANSPARENT;
    -jfx-unchecked-color: BLACK;
}

.custom-jfx-check-box:selected .mark{
    -fx-border-color: RED;
}
```

2. Not sure exactly what's the issue, as we tried showing/hiding multiple JFXAlerts ( event nested ) and it works fine.

3. we tried with preferred height < 70 and the scroll appears, was not able to reproduce the issue.

Regards,

**Comment by rebaihalim** [comment]
thank you sir

for my question about alert this is my simple code :
JFXAlert<Void> alert2 = new JFXAlert<>(stage);
alert5.setContent(view);
alert2.setSize(w2,h2);
alert2.showAndWait();

JFXAlert<Boolean> alert1 = new JFXAlert<>(stage);
alert1.setContent(view2);
alert1.setSize(w,h);
alert1.setOnHidden(e -> {
if(alert1.getResult())
   alert2.showAndWait();
});
alert1.showAndWait();

the probleme is alert2 is never show and any exception was throw !!!! 

2. for jfxcheckbox : background removed when i add css class 'custom-jfx-check-box' to jfxcheckbox but MARK background and color style white when i selected 
![sans titre](https://user-images.githubusercontent.com/33060539/32045673-24e40cba-ba41-11e7-90b2-a644f37c361d.jpg) 

.custom-jfx-check-box {
    -jfx-checked-color: transparent;
    -jfx-unchecked-color: rgb(200,200,200);
}

.custom-jfx-check-box:selected .mark{
    -fx-border-color: red;
    -fx-background-color: red;
}

**Comment by jfoenixadmin** [comment]
Hi,
in your alert code there are 2 issues:
1. you need to set a result converter to alert1 in order get the result as boolean 
2. you can't call showAndWait inside the setOnHidden as it's called during an animation

so you need to change the following:
```
alert1.setResultConverter(param -> true);
alert1.setOnHidden(e -> {
    if(alert1.getResult())
        alert2.show();
});
```

regarding 2, 3 we were not able to reproduce and seems to work just fine.

**Comment by rebaihalim** [comment]
hi 

thank's 

your suggestion :  

alert1.setResultConverter(param -> true);
alert1.setOnHidden(e -> {
    if(alert1.getResult())
        alert2.show();
});

not work and jfxalert stay not visible , so why when i use jfxdialog it's work fine , however jfxdialog is show in animation for hidding jfxalert (setOnHidding(e -> jfxdialog.show()) !!!! i see that jfxdialog can use but i missing MODAL property 

2. if possible to give me a simple code work fine for jfxcheck (include css) with no background and just mark 

thank you very mach

**Comment by jfoenixadmin** [comment]
Hello,
can you provide the full code of the alert issue, so I can help you better.

regarding the checkbox here is a sample example:

```
import com.jfoenix.controls.JFXCheckBox;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.CheckBox;
import javafx.scene.layout.FlowPane;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class CheckBoxDemo extends Application {

    @Override
    public void start(Stage stage) {

        FlowPane main = new FlowPane();
        main.setVgap(20);
        main.setHgap(20);

        CheckBox checkBox = new CheckBox("CheckBox");
        JFXCheckBox jfxCheckBox = new JFXCheckBox("JFX CheckBox");
        JFXCheckBox customJFXCheckBox = new JFXCheckBox("Custom JFX CheckBox");
        customJFXCheckBox.getStyleClass().add("custom-jfx-check-box");

        main.getChildren().setAll(checkBox, jfxCheckBox, customJFXCheckBox);

        StackPane pane = new StackPane(main);
        StackPane.setMargin(main, new Insets(100));

        final Scene scene = new Scene(pane, 600, 200);
        scene.getStylesheets().add(CheckBoxDemo.class.getResource("/css/check-box.css").toExternalForm());
        stage.setTitle("JFX CheckBox Demo ");
        stage.setScene(scene);
        stage.setResizable(false);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }

}

```
and the css is
```
.custom-jfx-check-box {
    -jfx-checked-color: TRANSPARENT;
    -jfx-unchecked-color: GREY;
}

.custom-jfx-check-box .mark{
    -fx-border-color: red;
    -fx-background-color:red;
}
.custom-jfx-check-box:selected .mark{
    -fx-border-color: red;
    -fx-background-color:red;
}

```
![capture](https://user-images.githubusercontent.com/14176767/32187206-f1dbc9b0-bdac-11e7-89ee-b49af04609f3.PNG)

**Comment by rebaihalim** [comment]
thank's very mach

all work fine for checkbox , i miss some css (when not select checkbox to modifiy mark background & border)

i have a question :  

in your JFXCheckbox.java you define a css class 'jfx-check-box' as default css class for this component but in css you use 'custom-jfx-check-box' !!! how can this class 'custom-jfx-check-box' chaage css behavior of jfxcheckbox and not 'jfx-check-box' ????

2. for my code about jfxalert

this code when click on button : 

try {
                    JFXAlert<Boolean> confirmDialog = new JFXAlert<>((Stage) viewFlowContext.getRegisteredObject("main-window"));

                    FXMLLoader loader = new FXMLLoader(getClass().getResource("/app/mvc/view/ConfirmView.fxml"));
                    Pane view = loader.load();

                    ConfirmController confirmController = loader.getController();
                    confirmController.setAlertTitle("Résiliation");
                    confirmController.setAlertMessageContent("Confirmer l'annulation du contrat employée :  " + dataModel.getContratSelected().get().getName() + " " + dataModel.getContratSelected().get().getType() + " ?");
                    confirmController.setAlertDialog(confirmDialog);

                    confirmDialog.setContent(view);
                    confirmDialog.setResultConverter(param -> true);
                    confirmDialog.setOverlayClose(false);
                    confirmDialog.setAnimation(JFXAlertAnimation.CENTER_ANIMATION);
                    confirmDialog.setSize(view.getPrefWidth(), view.getPrefHeight());
                    confirmDialog.setOnHidden(event1 -> {
                        if(confirmDialog.getResult())
                            cancelContrat();
                    });
                    confirmDialog.showAndWait();
                } catch (IOException e) {
                    e.printStackTrace();
                }


private void cancelContrat() {
        if(dataModel.getContratSelected().get() != null) {
            try {
                JFXAlert<Void> alertDialog = new JFXAlert<Void>((Stage) viewFlowContext.getRegisteredObject("main-window"));

                Flow flow = new Flow(ResiliationContratController.class);
                FlowHandler flowHandler = flow.createHandler(viewFlowContext);

                Pane view = flowHandler.start();
                view.setPrefSize(350,188);

                ResiliationContratController resiliationContratController = (ResiliationContratController) flowHandler.getCurrentView().getViewContext().getController();
                resiliationContratController.setAlertDialog(alertDialog);

                alertDialog.setAnimation(JFXAlertAnimation.TOP_ANIMATION);
                alertDialog.setOverlayClose(false);
                alertDialog.setContent(view);
                alertDialog.setSize(view.getPrefWidth(),view.getPrefHeight());
                alertDialog.showAndWait();
            }
            catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }


thank's for all.

**Comment by jfoenixadmin** [comment]
Hello,
1. because css is applied only on "custom-jfx-check-box" css class. for more info about javafx CSS, you can check oracle guide <a href="https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html">here</a>

2. the problem with your code is:
`confirmDialog.setSize(view.getPrefWidth(), view.getPrefHeight());`
make sure you the view has prefWidth/prefHeight, as these values are set to -1 be default.

Regards,

**Comment by rebaihalim** [comment]
1. in my code i specify dimenssion of alert (view.setPrefSize(350,188)), i try to print dimenssion of jfxalert and it show in console the same prefwidth & prefheight of my view !!!!

2. i want to change my jfxalert design, so customize my css with default class 'jfx-alert-content-container' but not think happen !! these any css class to add or if possible to give an idea about how to customize my jfxalert or jfxdialog

thank's
