### ISSUE TITLE
Custom Background in JFXListCell

### ISSUE THREAD

**Issue by aaron-za-dev** [jfoenixadmin/JFoenix#476]
Hi, how can I change the color of a JFXListCell, depending on the attribute value of my object, for example depending on the stock of a product.

I do this by extending from the ListCell <T> class:

       @Override
       protected void updateItem(Product item, boolean empty) {
           super.updateItem(item, empty);

        if(empty || item == null) {

            setText(null);
            setGraphic(null);

        } else {
            if (loader == null) {

                loader = new FXMLLoader(ListCellProduct.class.getResource("/scia/cbtav3/listviewcell/ListCellProduct.fxml"));
                loader.setController(this);

                try {
                    loader.load();
                } catch (IOException e) {
                    e.printStackTrace();
                }

            }

            

            if(item.getSTOCK() < 4){
                root.setStyle("-fx-background-color: red; -fx-text-fill: white;");
            }
            else if(item.getSTOCK() < 7 && item.getSTOCK() >= 4){
                root.setStyle("-fx-background-color: yellow; -fx-text-fill: white;");
            }
            else{
                root.setStyle("-fx-background-color: green; -fx-text-fill: white;");
            }           

            setText(null);
            setGraphic(root);

        }

The question is how to do it extending from the JFXListCell class and keeping all the properties of the JFXListView only changing the background?

**Comment by jfoenixadmin** [comment]
Hello,
to change the background of the cell, you need to call the method setStyle on the cell itself instead of the graphic node, 

Regards,

**Comment by aaron-za-dev** [comment]
Could you explain it in more detail?

**Comment by jfoenixadmin** [comment]
well you are changing the graphic (root) background color instead of the cell background.
Beside that, the previous code should work the same when using JFXListCell.
