### ISSUE TITLE
Please consider reporting this to the maintainers of com.jfoenix.controls.JFXDatePicker

### ISSUE THREAD

**Issue by haftado3** [jfoenixadmin/JFoenix#479]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jfoenix.controls.JFXDatePicker (file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%202017.2.5/jfoenix-9.0.0.jar) to field javafx.scene.control.DatePicker.editor
WARNING: Please consider reporting this to the maintainers of com.jfoenix.controls.JFXDatePicker
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by jfoenixadmin** [comment]
Hello,
Well, currently JFXDatePicker implementation depends on some fields from the parent. which are only accessible using reflection, so we can't do much about this.

Regards,
