### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#48]
Hi there,
Just want to know if you've adapted the things in the home page of your website (jfoenix) with the latest changes in your library? For example, I can not find Snackbar related classes in the jar file you've put to download. Again, I can not see any visual demo for Snackbar like the one you put there to announce existence of your new time picker.

Thanks.

**Comment by jfoenixadmin** [comment]
to get the latest version of jfoenix, you need to pull from GitHub repo and build it. 
yeah I didn't update the jar file on the site, nor added a gif of the snackbar yet. soon will update them.

Thanks again for your contribution.

**Comment by aminabs** [comment]
Thanks for your quick reply!
Building the source code is the best way as you mentioned; however, in my case it is somehow time consuming (due to my weak internet connection), and I actually did not want the full source codes. I think this is/will be true for almost all your clients :)
BTW,
Another thing you might want to update is the snapshots (bin/sources .jar) you uploaded onto the maven central repository if you don't mind.

**Comment by jfoenixadmin** [comment]
I updated the jar file on the site, other updates have to wait a bit.

Regards,

**Comment by aminabs** [comment]
Really thank you

**Comment by jfoenixadmin** [comment]
the snackbar demo gif has been added to the main page.
