### ISSUE TITLE
JFXAlert Trouble

### ISSUE THREAD

**Issue by LandyLane** [jfoenixadmin/JFoenix#481]
Hi,

So I was converting a JFXDialogLayout to JFXAlert and noticed it no longer needs the stack pane given, but instead the stage. After doing the appropriate changes, I noticed the alert is appearing at the top of the stage opposed to normal alerts (native javafx ones). I tried finding some examples of the JFXAlert's but I believe since it's new, there aren't many. 
[Before opening](https://i.gyazo.com/cc6a04b952bd7bdd6e689377115a82c2.png)

[After opening](https://i.gyazo.com/429a32d3a69f83bf519aeaa15cf62bac.png)

Code:

`JFXAlert<Exam> alert = new JFXAlert<Exam>(Launcher.getStage());
            alert.setTitle("Edit Exam");
            alert.setHeaderText("Edit the existing exam");
		
            DialogPane dialogPane = alert.getDialogPane();
	    
	    JFXTextField name = new JFXTextField(exam.getName());
	    name.setLabelFloat(true);
	    name.setPromptText("Name of Exam");
	    
	    JFXDatePicker date = new JFXDatePicker(exam.getDate());
	    
	    dialogPane.setContent(new VBox(8, name, date));
	    
/*         Can't use JFXButton's on alerts
	    JFXButton delete = new JFXButton("Delete");
	    delete.setStyle("-fx-background-color:#ef2d17");
	    
	    JFXButton finish = new JFXButton("Finish");
	    finish.setStyle("-fx-background-color:#68db5c");
	    
	    JFXButton cancel = new JFXButton("Cancel");
	    finish.setStyle("-fx-background-color:#b1b2b5"); */

	    ButtonType deleteBtn = new ButtonType("Delete");
	    ButtonType finishBtn = new ButtonType("Finish");
	    ButtonType cancelBtn = new ButtonType("Cancel");
	    
	    //dialogContent.setActions(delete, new Label("   "), new Label("   "), finish, new Label("   "), cancel);
	    alert.getDialogPane().getButtonTypes().addAll(deleteBtn, finishBtn, cancelBtn);
	    
	    alert.setResultConverter((btn) -> {
	    	if (btn == deleteBtn) {
	    		exam.setToDelete(true);
	    		return exam;
	    		
	    	} else if (btn == finishBtn) {
	    		exam.setName(name.getText());
	    		exam.setDate(date.getValue());
	    		return exam;
	    		
	    	} else {
	    		return null;
	    	}
	    });
	    return alert.showAndWait();`

If possible, an example of an alert containing a JFX component on a new stage would be helpful thanks!

**Comment by jfoenixadmin** [comment]
Hello,
unlike the java alert, you shouldn't update the dialog pane directly, instead use the method setContent

```
        JFXAlert<Void> alert = new JFXAlert<>(stage);
        alert.setContent(content);
        button.setOnAction((action->{
            alert.showAndWait();
        }));
```
Where content is of type node (you can simply use the JFXDialog content as the JFXAlert content)

Regarding the buttons bar, by default JFXAlert returns null (so it won't be created). The buttons bar should be part of the content (use buttons onAction listeners to trigger actions instead of ResultConverter).

So JFXAlert should be used in a similar way to JFXDialog, however it supports modality options.

Regards,
