### ISSUE TITLE
JFXDatePicker colors

### ISSUE THREAD

**Issue by AhmedMouradDev** [jfoenixadmin/JFoenix#484]
Hi,

Is it possible to set different colors to these two parts of the date picker or do they have to be the same color?

(1)
![image](https://user-images.githubusercontent.com/29189251/32237354-65ba90e4-be6d-11e7-9749-1e763f206654.png)

(2)
![image](https://user-images.githubusercontent.com/29189251/32237379-7f3080b0-be6d-11e7-99a0-0551fd596c15.png)

As i want to set the default color to white and this causes the date in the second picture to disappear as shown here:

![image](https://user-images.githubusercontent.com/29189251/32237807-9f15c16e-be6e-11e7-8d7e-9d0a00533a18.png)

Best regards,

**Comment by jfoenixadmin** [comment]
Hello,
Well currently, these colors are bound to each other. Will remove the binding in the next version.
Thanks for pointing out the issue 👍 

Regards,

**Comment by jfoenixadmin** [comment]
Hello, 
you can change it using the following css:
```
.jfx-date-picker .month-year-pane{
    -fx-background-color: RED;
}
```
Regards,

**Comment by AhmedMouradDev** [comment]
Hello,

Thanks for the effort for fixing the issue, but i've just noticed that the same problem happens with the (today / selected date / year) numbers when default color is white as shown below:

(Today is the 4th of nov, selected date is 3rd of nov)
![image](https://user-images.githubusercontent.com/29189251/32400081-8d81e336-c104-11e7-8d5d-73119dea63fa.png)

![image](https://user-images.githubusercontent.com/29189251/32400089-9b77da40-c104-11e7-935e-64b8d13a9153.png)

Also the date icon in the new release gets this weird white/silver background color when focused which didn't use to happen with the previous version i was using (1.7.0):

(focused)
![image](https://user-images.githubusercontent.com/29189251/32400142-1d7941fa-c105-11e7-8bfb-0eaf02ac5987.png)

(unfocused)
![image](https://user-images.githubusercontent.com/29189251/32400153-4270e4ea-c105-11e7-85ed-3272f6191fba.png)

Best regards and thanks for the effort,
