### ISSUE TITLE
JFXTextField with size=0 and disable=true makes application unresponsive

### ISSUE THREAD

**Issue by ewanld** [jfoenixadmin/JFoenix#489]
Hi!

I have a disabled JFXTextField instance inside a horizontal SplitPane. When I move the SplitPane divider position so that the text field is completely shrinked, the application freezes and I have to kill the process.

The problem doesn't appear when I use a TextField instead of JFXTextField.
My current workaround is to call setMinWidth(1) on the text field.

I am using jfoenix-1.9.1.jar with Java 8.

Here is a complete example to reproduce:

```java
import com.jfoenix.controls.JFXTextField;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.SplitPane;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class Bug extends Application {

	@Override
	public void start(Stage s) throws Exception {
		final JFXTextField txt = new JFXTextField();
		txt.setDisable(true);
		s.setScene(new Scene(new SplitPane(new BorderPane(), txt)));
		s.show();
	}

	public static void main(String[] args) {
		Application.launch(args);
	}
}
```

**Comment by jfoenixadmin** [comment]
Hello,
I tried this example, but were not able to reproduce. JFoenix 1.10.0 is out, can you re-validate the issue using the latest version?

**Comment by ewanld** [comment]
Thanks for looking into the issue. I still have the problem with v1.10.0.

I am using JDK 1.8.0_144 with windows 7 64 bit.

Here is a screen capture of the problem:

![screen](https://user-images.githubusercontent.com/12006850/32330093-533c84ea-bfdf-11e7-9021-c83b1d8b3844.gif)

**Comment by jfoenixadmin** [comment]
not sure what's causing the issue, especially knowing that JFXTextFieldSkin doesn't override any of the compute width methods.

**Comment by jfoenixadmin** [comment]
a new release of JFoenix is out, @ewanld can you revalidate the issue?
