### ISSUE TITLE
JFoenix Android 

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#49]
Hi,
Can I employ JFeonix in android using (Gluon's)  jfxmobile android plugin (javafxport)? Are you applying retrolambda for same reason?
If so, why don't you put some announcement on that great design decision on the home page (readme). Compared to controlfx, your library seems to be easily portable to android using javafxport and that's anoutstanding advantage.

Thanks.

**Comment by jfoenixadmin** [comment]
Yes, we are using retro-lambda for android compatibility. we already got JFoenix working on android using javafxport, we will update the readme soon :). thanks
