### ISSUE TITLE
how to disable changing the date in JFXDatePicker and the time in JFXTimePicker

### ISSUE THREAD

**Issue by mokun** [jfoenixadmin/JFoenix#491]
Hi, 

How do I remove the ability of the user in messing with the date in JFXDatePicker? 

I only want to show the user the date calendar like in windows 10 but don't want him/her to change the date.

```
JFXDatePicker datePickerFX = new JFXDatePicker();
datePickerFX.setValue(earthClock.getLocalDate());
datePickerFX.setEditable(false);
```

As you can see, I've tried using setEditable() to stop the tampering but it doesn't work.

Also the same with JFXTimePicker. I want no one to tamper with the time. 

Note : I have an EarthClock instance and call earthClock.getLocalDate() to update the date in datePickerFX programmatically if needed. 

Thanks much for this excellent library !
-mokun

**Comment by jfoenixadmin** [comment]
Hello, 
I tested _setEditable_ using the latest JFoenix and it seems to work just fine (there is some minor css glitch though). can you re-validate the issue using JFoenix 1.10.0

Regards,
