### ISSUE TITLE
setIs24HourView() NOT working in JFXTimePicker

### ISSUE THREAD

**Issue by mokun** [jfoenixadmin/JFoenix#492]
Hi, 

When using JFXTimePicker, I'd like to use the 24 hour view. 

if my local time is "3:03 PM", I'd like to show "15:03" instead.

In other words, I'm trying to get rid of the AM and PM.

Since I saw the setIs24HourView(true) in JFXTimePicker as follows : 
```
    public final void setIs24HourView(final boolean value) {
        _24HourViewProperty().setValue(value);
    }
```
I thought I can use it but it doesn't work.

```
JFXTimePicker timePickerFX = new JFXTimePicker();
timePickerFX.setIs24HourView(true);
```

Also, if my local time is "3:03 AM", how do pad a zero in front of the "3", making it show "03:03" ? The point is that I don't want the text field to move as it transitions from "9:59" to "10:00".

Thanks much!
mokun

**Comment by jfoenixadmin** [comment]
Hello,
I tested the 24 hours view, but wasn't able to reproduce the issue.
Regarding the time format, you need to change the converter property and set your custom format.

Regards,

**Comment by Hades85** [comment]
If you call this method setIs24HourView(true) in a actionMethod(for example click a Button) , most times it doesnt work fine. If you call setIs24HourView(true) for example in your initialize method of your controller class once it works well.
