### ISSUE TITLE
Problem with 24-hours format in Timepicker

### ISSUE THREAD

**Issue by Wyrwinio** [jfoenixadmin/JFoenix#493]
Hi. I have problem with JFXTimePicker. I wanted set in it 24-hour's format, but when I applied 
`timepicker.setIs24HourView(true);`
was changed only clock, but value in textfield as before is in 12-hour's format. Effect I introduce below 
![aaabbbcc](https://user-images.githubusercontent.com/33356058/32387525-0a50077a-c0c5-11e7-90af-9d1cf1054db0.png)
Thank you in advance for help :-)

**Comment by jfoenixadmin** [comment]
Hello,
you can change the format by changing the converter property of JFXTimePicker.

Regards,

**Comment by ilyako87** [comment]
Hi. I'm trying to do the same. But this property is not available in my Scene Builder.  Does it exist a tag-parameter in <JFXTimePicker> that allows to use 24 hours date format?

**Comment by DJViking** [comment]
Seems cumbersome to also having to set a new StringFormat<LocalTime> after setIs24HourView is set. Not very intuitive solution. Why not just have JFXTimePicker to ommit the AM/PM in its StringFormat if the is24HourView is set true.
