### ISSUE TITLE
JFoenix for Java 9 text field issues

### ISSUE THREAD

**Issue by M-FF-M** [jfoenixadmin/JFoenix#495]
I updated to Java 9 and downloaded the corresponding JFoenix jar file. Unfortunately, not everything works as flawlessly as it did before:

1.: The prompt text of JFXTextFields doesn't float anymore when I set the field value with setText():

![textfield](https://user-images.githubusercontent.com/19824989/32406189-0cdddd8c-c174-11e7-9b2c-d68d64cefd18.png)

2.: There's a second issue but I'm not completely sure whether or not this is related to JFoenix: whenever I display forms with JFoenix text fields my CPU usage goes up to 20%-50% (this didn't happen before - and it only happens when the form with the text fields is visible: if the same application shows some other content, CPU usage is much lower). Usually, when running a JavaFX application, my CPU usage is at about 2%-5% so this is a significant increase. I tried to replicate the issue with a very simple demo application but the results were inconclusive: the CPU usage still went up, but only to 10%-15%.

It would be interesting to know whether anyone else is experiencing this increase in CPU usage.

**Comment by M-FF-M** [comment]
I captured a screenshot of the CPU usage increase:
![cpuusage](https://user-images.githubusercontent.com/19824989/32406385-caf7c442-c177-11e7-8d76-e28f772301eb.png)

While monitoring the CPU usage, I did absolutely nothing except clicking on a button twice, first to switch to the view where the text field is shown and then to switch back to the view without text field. I'm still not sure what exactly the source of this increase is - I will leave another comment as soon as I know more or if I can replicate it with a very simple demo.

**Comment by M-FF-M** [comment]
I did some tests but I couldn't get rid of the CPU usage problem. When I replace all JFXTextFields with TextFields CPU usage is normal again, so it does seem to be related to JFoenix. However, there's no problem at all with JFXTextAreas and JFXComboBoxes. I was able to replicate the problem, but only to a limited degree. If I run the code provided at the very end of this post, it is possible to replicate increased CPU usage by doing the following: Start the program. CPU usage should still be normal. Click on the second text field. There is a sudden increase in CPU usage and it never gets down again to what it was before even when waiting for about a minute. I did a lot of tests and it was always the same - the difference in CPU usage before and after clicking ranges from 5% to 15%.

![cpuusage2](https://user-images.githubusercontent.com/19824989/32407258-a9bf773e-c186-11e7-99d5-b1bac08d1b06.png)

The usage in these examples is still okay for me, but when I run my actual project, it's sometimes as high as 90% (and stays at that level as long as the form with the text fields is visible) and my fan has a lot of work to do. I can still use my program but it's certainly not perfect so any ideas on how to fix the issue would be really helpful. For now, I'll just ignore it and continue developing.

```
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import javafx.scene.control.TextField;
import com.jfoenix.controls.JFXTextField;
 
public class Test extends Application {
    public static void main(String[] args) {
        launch(args);
    }
    
    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Hello World!");
		VBox fieldStack = new VBox(30);
		fieldStack.setMaxWidth(150);
		for (int i=0; i<10; i++)
		{
			JFXTextField textField = new JFXTextField();
			//TextField textField = new TextField();
			textField.setPromptText("JFoenix text field");
			//textField.setLabelFloat(true);
			if (i == 3) textField.setText("test");
			fieldStack.getChildren().add(textField);
		}
        
        StackPane root = new StackPane();
        root.getChildren().add(fieldStack);
		Scene primaryScene = new Scene(root, 300, 600);
        primaryStage.setScene(primaryScene);
        primaryStage.show();
    }
}
```

**Comment by jfoenixadmin** [comment]
Hello,
JFoenix java 9 jar has been updated on the site (still same name file though). can you download the latest jar file from <a href="http://www.jfoenix.com/download/jfoenix-9.0.0.jar">here</a>, and re-validate the issue?
1st screen shot indicates that you are using the old jar, as prompt text issues have been solved in the latest jar.

Regards,

**Comment by M-FF-M** [comment]
I'm running the newest JFoenix jar and the issue with the floating label still remains. Actually, if you run the code I posted above _with_ floating labels (that line is currently commented) you should be able to replicate the issue. The problem might be that I use `setText()` before adding the JFXTextField to a scene (?).

**Comment by jfoenixadmin** [comment]
Hello,
It seems that the prompt issue is related to java 9 new listeners in the skin class, as it works properly in java 8. Will push the fix as soon as possible, meanwhile you can simply set the label float property through css instead of code.

Regarding the CPU usage, clicking on JFXTextField will increase the CPU usage due to the animation. I tested the example you provided and the usage increased by 5-7% when focusing the fields quickly.
However when idle the CPU usage returns back to normal. 

Maybe there are some threaded task that is consuming the CPU when opening the text field form.
Monitoring your application threads might help you to solve the issue.

Regards,

**Comment by M-FF-M** [comment]
Support is really great here! Thanks for your fast reply. I just wanted to emphasize that removing all JFXTextFields and replacing them with TextFields resolves the CPU usage problem and everything else still works (and the issue only appeared when updating to Java and JFoenix 9, and in my case, the CPU usage never returns back to normal even when doing nothing for more than a minute). That is why I thought the issue must be related to JFoenix. However, as I couldn't really replicate the problem (and you couldn't replicate it at all), it must be something specific to my application - I'll just keep searching for the cause, I guess.

**Comment by jfoenixadmin** [comment]
will keep you updated in case we were able to produce this issue.

Regards,

**Comment by M-FF-M** [comment]
The CPU usage problem disappeared when I updated to the newest JFoenix jar for Java 9 (as did the floating label issue)! Thanks!

**Comment by jfoenixadmin** [comment]
Great News!! Thanks for pointing out the issue 👍
