### ISSUE TITLE
JFXDecorator error

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#505]
I try to open an application, but I get this error in the JFXDecorator
```
java.lang.IllegalStateException: Cannot set style once stage has been set visible
	at javafx.stage.Stage.initStyle(Stage.java:493)
	at com.jfoenix.controls.JFXDecorator.<init>(JFXDecorator.java:113)
	at com.jfoenix.controls.JFXDecorator.<init>(JFXDecorator.java:94)
```

in this line code:

`primaryStage.initStyle(StageStyle.UNDECORATED);`

I have an undecorated login, and when I enter the main view that error comes out.

**Comment by jfoenixadmin** [comment]
Hello,
JFXDecorator changes the stage style, and it can't be done if the stage is already showing. 
so you need to create the JFXDecorator before calling `stage.show()` method.

Regards,
