### ISSUE TITLE
JFXDialog: Setting overlayClose in constructor does not work

### ISSUE THREAD

**Issue by raphaelm** [jfoenixadmin/JFoenix#509]
Hi,

I'm unable to make a JFXDialog be "modal" in the sense that a click on the overlay does not close it by passing ``false`` as the fourth argument to its constructor. I was only able to do so by passing ``true`` and then forcing a property change by 
```
dialog.overlayCloseProperty().set(overlayClose)
```

I assume this is not intented.

Best
Raphael

**Comment by jfoenixadmin** [comment]
Hello,
you are right, sure it's not intended. thanks for pointing out the issue 👍 

Regards,
