### ISSUE TITLE
JFXDrawerStack bug?

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#51]
Hi again,
I am trying to use an instance of JFXDrawerStack this way:
1. Instantiate one and add to it an instance of a Button using the **setContent** method;
2. show it.
I can see the stack in the scene, but unfortunately I can't see the button. The stack does not show the content until I add a JFXDrawer to it using **addDrawer** method. Is it a design decision or a bug?
Another issue is that I've to first **setContent** and then I'll be able to **addDrawer**, otherwise I'll get a NullPointerException.

Thanks.

**Comment by jfoenixadmin** [comment]
JFXDrawerStack public API has been updated, you only need to use setContent and toggle methods. 
addDrawer method is set private, no longer need to be called by the user.

**Comment by aminabs** [comment]
Hey,
Thanks.
Did you update the home page link to the latest jfoenix.jar? Or, Can you automatically sync your latest snapshot builds with the maven snapshots repository materials; as I can see the latest jar artifacts are pretty old (Fri Feb 26 13:32:19 UTC 2016). So, one might not be able to get the latest jar (binary/sources) without getting the source code and build it which is pretty redundant for most of the users (not developers).

That'd be great if you make it an automatic process to let users like me to simply access to the latest binaries/sources jar through standard maven dependency tags.

**Comment by jfoenixadmin** [comment]
its been updated
