### ISSUE TITLE
Java 9 label float not displaying correctly

### ISSUE THREAD

**Issue by salmanfazal01** [jfoenixadmin/JFoenix#510]
I'm getting this issue where the text and label are in-line until I manually focus on them.

![untitled-1](https://user-images.githubusercontent.com/15085416/32748473-47ce7fea-c8b4-11e7-94ca-8636d042ed56.jpg)

I tried adding this piece of code to focus on one textfield to another automatically but it didn't seem to fix ths issue:

       Platform.runLater(() -> {
            field1.requestFocus();
            field2.requestFocus();
        });

I also read in another issue post (which is still open) that it is possible to manually call the CSS to fix this, can you please guide me with that?

Thanks

**Comment by jfoenixadmin** [comment]
Hello,
Yeah it's a known issue, for now you can fix it by setting the the property label float to true through css instead of code:

```
.jfx-text-field{
-jfx-label-float: true;
}
```

Regards,

**Comment by salmanfazal01** [comment]
I tried that using in-line styles and an external stylesheet, both dont seem to work.
Just to confirm, the stylesheet is read by my fxml file (any other style property works), but this specific property doesn't seem to work. It doesn't show up in the hints as well.

**Comment by jfoenixadmin** [comment]
Hello,  
JFoenix java 9 version has been updated, can you revalidate the issue using the latest version?

**Comment by salmanfazal01** [comment]
Hey,
Tried it, works perfectly now! Thanks
