### ISSUE TITLE
Problem with JFXToolbar shadow

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#511]
Hello, I am using the JFXToolbar inside a VBox, I put the tree of my design:

```
StackPane{
  vbox {
     JFXToolbar()
     hbox {
         stackpane() // BACKGROUND TRANSPARENT;
         stackpane() // BACKGROUND #ededed;
     }
   }
}

```

But the panel that added a background does not respect the shadow of the JFXToolbar:

![imgtoolbar](https://user-images.githubusercontent.com/22163898/32754864-9e170fb6-c8a0-11e7-9ab5-a66ae0243678.png)

How could this problem be solved?

**Comment by jfoenixadmin** [comment]
Hello,
Well VBox doesn't consider the effect applied on its children. you can either create a custom StackPane that layout its children in a similar manner to VBox, or simply add spacing to vbox.

Regards,

**Comment by TioCoding** [comment]
I have been trying different solutions, and I do not know if it is the best solution but it works for me (for the time being).

```
StackPane{
  gridPane {
     row{  
         JFXToolbar() // toolbarTittle 
     }
     row{  hbox {
         stackpane() // BACKGROUND TRANSPARENT;
         stackpane() // BACKGROUND #ededed;
     } }
   }
}
```

And finishing my design I call the method toFront () of the JFXToolbar.

`toolbarTittle.toFront();`

Now how could I solve the problem in JFXTabPane? where a child node has a backgraund but I do not want to lose the shadow.

![screenshot at 2017-11-14 12 01 46](https://user-images.githubusercontent.com/22163898/32793332-9e56ece2-c933-11e7-8ccb-5a1836f1e267.png)

**Comment by TioCoding** [comment]
If I add a spacing or padding, it does not look good to the final design.
![screenshot at 2017-11-14 12 06 29](https://user-images.githubusercontent.com/22163898/32793563-4d326f48-c934-11e7-884e-8d7c20dd901f.png)

**Comment by jfoenixadmin** [comment]
not sure it might help, but you can change the background color of the tab itself and keep the transparent background for children.

**Comment by TioCoding** [comment]
It's a good solution if I just want to have 1 background color on the tab.
But in the case you want to have 2 colors? to represent 2 sections?
For example in a section a list of data (Background: WHITE) and in the other a form (Background: SILVER)
