### ISSUE TITLE
Color PromptText of the JFXCombobox does not apply

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#513]
Hi, I try to change the color of the JFXCombobox text, but I do not have any results, this is my css:

```
.jfx-combo-box{
    -fx-background-color: transparent ;
    -fx-font-family: "Roboto Bold";
    -fx-prompt-text-fill: #adadad; // Does not apply
    -jfx-focus-color: -fx-primary-color;
    -jfx-unfocus-color: #adadad;
}
```
All properties are applied, except "-fx-prompt-text-fill: #adadad;".

I have tried adding the property "labelFloat = true" to the JFXCombobox, and after doing focus the css is applied, some solution for this problem?

Greetings and thanks in advance.

**Comment by jfoenixadmin** [comment]
Hi,
Thanks for pointing out the issue 👍, will look into it.

Regards,
