### ISSUE TITLE
JFXTimePicker automatic switch from hours to minutes

### ISSUE THREAD

**Issue by Tobi2707** [jfoenixadmin/JFoenix#514]
Is there a way to automatically switch to minutes selection after selecting a hour on my JFXTimePicker.
I looked into the sources but couldn't find any methods like getMinutesScreen or something like that.
Is there any way to get this done? Everything I can image is this:

`        timePickerFX_.valueProperty().addListener( new ChangeListener<LocalTime>( ) {
            @Override
            public void changed(ObservableValue<? extends LocalTime> observable, LocalTime oldValue, LocalTime newValue)
            {
                if(oldValue.getHour() != newValue.getHour()) {
                    // Set the minutes screen
                }
            }
        } );`

**Comment by jfoenixadmin** [comment]
Hello,
Well currently you can't, the code to switch time unit is part of JFXTimePickerContent in the method `switchTimeUnit`. it's called when `unit` property is changed. However this property is not exposed to JFXTimePicker. 
Feel free to add your own contribution to JFoenix.

Regards,
