### ISSUE TITLE
DateTimePicker does not works (scene builder)

### ISSUE THREAD

**Issue by koraniar** [jfoenixadmin/JFoenix#515]
The scene builder does not allow me drag the `JFXDatePicker` to my `AnchorPane` or any other `Pane` object, when I am importing Jfoenix.jar the JFXDatePicker is not shown

![screen shot 2017-11-18 at 10 45 55](https://user-images.githubusercontent.com/17574419/32982335-b4fe7b66-cc50-11e7-9c73-3a393b589c74.png)

I have **Java jdk1.8.0_101** and **JavaFX Scene Builder 2.0** and **SceneBuilder 9.0.1** on **OSX 10.13.1 High Sierra**

**Comment by jfoenixadmin** [comment]
Hello,
I tested the issue using scene builder 8.3.0, and it works fine. Plz note that Scene Builder 9.0.1 is for Java 9. If you are using java 9 you need to use JFoenix 9.0.0 jar from the website (1.10.0 is for java 8).

Regards,

**Comment by Malumbo21** [comment]
I Am Having the same issue ,I am unable to import JFXDatePicker 
I am using Scenebuilder 16 and jfoenix 9.0.10

**Comment by michu9971** [comment]
> 
> 
> I Am Having the same issue ,I am unable to import JFXDatePicker
> I am using Scenebuilder 16 and jfoenix 9.0.10

I am also having the same issue. Scenebuilder 16.0 and jfoenix 9.0.10.
JFXTextArea does not work too.

**Comment by Nelluna02** [comment]
I have the same problem. Scenebuilder 16.0 and tried every jfoenix version. 
I just tried DatePicker and TimePicker. Both doesnt work.

**Comment by Youssef-Ehab77** [comment]
> 
> 
> I Am Having the same issue ,I am unable to import JFXDatePicker
> I am using Scenebuilder 16 and jfoenix 9.0.10

Yea i have the same problem

**Comment by tomasDelizia** [comment]
sisoy
