### ISSUE TITLE
JFXTimePicker can not change the time value manually.

### ISSUE THREAD

**Issue by aaaakun** [jfoenixadmin/JFoenix#520]
Hi,

I can't change the time value by editing the textfield manually.
For example:
This is my picker,
![image](https://user-images.githubusercontent.com/17268177/33115648-b53fa0e2-cf9c-11e7-9cb5-1c54d3250808.png)
I change the time value into 7:20 directly inside the textfield of the picker and then I press enter.
Immediately I press enter, the time value return back to 7:15.

Looking forward to your reply.
Thanks.

**Comment by jfoenixadmin** [comment]
Hi,
you need to insert a valid time value according to the format you are using.
so if you just entered 7:20 without the PM/AM, the value will be changed to the previous value.

Regards,

**Comment by aaaakun** [comment]
Thank you!

**Comment by aaaakun** [comment]
Hi,
I click the clock icon and choose a value like this:
![t](https://user-images.githubusercontent.com/17268177/33366105-3ec21286-d525-11e7-8fb7-197c8299765c.PNG)
And my textfield shows like this :
![image](https://user-images.githubusercontent.com/17268177/33115648-b53fa0e2-cf9c-11e7-9cb5-1c54d3250808.png)
Then I just change 15 into 20 and the textfield shows like this before I pressing enter :
![ti](https://user-images.githubusercontent.com/17268177/33366300-c9d12c04-d525-11e7-858c-1fc8a2a62d2e.PNG)
After I pressing enter, the textfield back to 7:15 PM.

So I don't think this happans because of invalid value.
Looking forward to you reply.
Thank you!

**Comment by jfoenixadmin** [comment]
JFoenix monthly release is out, can you re-validate the issue using the latest version?
