### ISSUE TITLE
JFXTabPane-Arrows: Visibility bug?

### ISSUE THREAD

**Issue by deme78** [jfoenixadmin/JFoenix#525]
I think there's a bug with the visibility of the JFXTabPane-Arrows. The arrows are not completely visible, when i change the window size before i load/show the view/fxml for the first time. After that, i have to resize (width or height) the window again and then the arrows are completely visible.

### steps to reproduce:
1. resize the window, that its not fullscreen

2. show the view (in my example with a click on an button)-> arrows aren't completely visible
![jfxtabpane_bug](https://user-images.githubusercontent.com/23071577/33477117-bd75ca0e-d684-11e7-885e-783fd0589955.PNG)

3. resize the window again -> arrows are completely visible
![jfxtabpane_bug_2](https://user-images.githubusercontent.com/23071577/33477218-3672e3c4-d685-11e7-900c-8e187ddaa58c.PNG)

Is there a way to solve this problem?

**Comment by jfoenixadmin** [comment]
Which JFoenix version are you using?
 as this is a known issue and it's fixed in the latest version of JFoenix.

**Comment by deme78** [comment]
I updated the version and now it works. Thank you for your help!
