### ISSUE TITLE
Center children of the JFXMasonryPane

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#526]
Hello, I would like to know if there is any way to center the children of the JFXMasonryPane, I am testing with the property `alignment = CENTER`, but it does not work.

![captura de pantalla de 2017-12-02 13-47-08](https://user-images.githubusercontent.com/22163898/33518711-cb7d29ce-d767-11e7-9d96-c694f7c29289.png)

**Comment by jfoenixadmin** [comment]
Hello,
JFXMasonryPane uses a bin packing algorithm to layout the children, alignment property has no effect on how the children are positioned.

Regards,

**Comment by TioCoding** [comment]
Then you can not center the elements in any way?

**Comment by TioCoding** [comment]
Or they somehow occupy all the space and do not show an empty space?. But keeping the JFXMasonryPane animation

**Comment by jfoenixadmin** [comment]
Maybe using a FlowPane instead of JFXMasonryPane is a better solution in your case (where all children have the same size)
