### ISSUE TITLE
Change validation message length

### ISSUE THREAD

**Issue by mdelloso** [jfoenixadmin/JFoenix#527]
Hello, is it possible to change the length of a validation message? I have a field that only accept 1 character (so it is short) and when I make validations, the validation message is truncated.
![1](https://user-images.githubusercontent.com/4580901/33563009-819c5f70-d8f5-11e7-875a-f25a6e5a0f74.png)

**Comment by jfoenixadmin** [comment]
Hello,
well the width of the validation message is related to the width of the textfield, so you can change that.
you can either increase the text field width, or show the error icon with a tooltip instead of showing the whole error message.

Regards,

**Comment by mdelloso** [comment]
Hello, 
Okay, I think that it would be a good enhancement. Anyway thanks for the response Jfoenix is a good library.
Regards.
