### ISSUE TITLE
JFXDatePicker displays date incorrectly

### ISSUE THREAD

**Issue by ronsiven** [jfoenixadmin/JFoenix#528]
According to https://material.io/guidelines/components/pickers.html a date picker should display the selected date in the top section like Mon, Dec 4 for December 4, 2017.  JFXDatePicker has the date there to display, except rather than display the date it displays the year (Mon, Dec 17).

![jfxdatepicker_01](https://user-images.githubusercontent.com/466261/33564478-34bc2f10-d8e0-11e7-93b9-80f63f4f3602.png)  
![jfxdatepicker_02](https://user-images.githubusercontent.com/466261/33564492-3c7e7c94-d8e0-11e7-883d-fdc3a5e3ea97.png)

**Comment by jfoenixadmin** [comment]
you are right, thanks for pointing out the issue 👍
