### ISSUE TITLE
JFXTreeTableView breaks the SceneBuilder

### ISSUE THREAD

**Issue by mdelloso** [jfoenixadmin/JFoenix#529]
Hello, I amg getting problems with JFXTreeTableView componets and the SceneBuilder. When I drag a JFXTreeTableView, the UI shifts to the left and I can't get the focus of any componnent. Also, if I drag another componnent once a JFXTreeTableView  is present, the SB close itself automatically.
Regards,
Matías.

**Comment by jfoenixadmin** [comment]
Hello,
can you provide more details about this issue? 
- SceneBuilder logs 
- which version you are using of JFoenix / SceneBuilder

**Comment by mdelloso** [comment]
Hello, 
I am using JFoenix 1.10.0 (but I had the same problem with previous versions) and the Scene Builder 2.0. The SB doesn't trigge any error, it just breaks. 
Here are some screenshots with the steps that I make:

1. First I have my UI without JFXTreeTableView 
![1](https://user-images.githubusercontent.com/4580901/33672059-02562626-da88-11e7-8e81-7ac18fe0e053.png)

2. Then I select a JFXTreeTableView an I drag it to the middle panel
![2](https://user-images.githubusercontent.com/4580901/33672087-1651336e-da88-11e7-9042-953f800d40cd.png)

3. After do that, the SB breaks and I can't select any component nor center the panel in the middle of the screen.
![3](https://user-images.githubusercontent.com/4580901/33672121-33311d82-da88-11e7-9cfd-c6385fea9864.png)

Regards.

**Comment by jfoenixadmin** [comment]
Hello,
this is a very old version of Scene Builder, can you revalidate the issue using scene builder 8.x.x

**Comment by mdelloso** [comment]
Solved, I had downloaded the SB from Oracle website. I have just tested the 8.x.x version and it works. Thanks.
