### ISSUE TITLE
Customize the snackbar

### ISSUE THREAD

**Issue by sadarshannaiynar** [jfoenixadmin/JFoenix#53]
Anyway to customize the snackbar elements such us font, font size and background of snackbar.

**Comment by jfoenixadmin** [comment]
you can use the following css classes to style the snackbar: 

<pre>
.jfx-snackbar-content {
	-fx-background-color: #323232;
}

.jfx-snackbar-toast {
	-fx-text-fill: WHITE;	
}

.jfx-snackbar-action {
	-fx-text-fill: #ff4081;	
}
</pre>

**Comment by sadarshannaiynar** [comment]
Sample code to implement it would be nice. :)

**Comment by jfoenixadmin** [comment]
just add the following to your application css file
<pre>
.jfx-snackbar-content {
	-fx-background-color: RED;
}

.jfx-snackbar-toast {
	-fx-text-fill: WHITE;
	-fx-font-size: 20;	
}
</pre>

**Comment by ayushchadha23** [comment]
how change height of snackbar using css

**Comment by HouariZegai** [comment]
How to change the text alignment of the snackbar
"-fx-text-alignment: center" doesn't work.

**Comment by ianparcs** [comment]
To change the size try changing the min-height and set your preferred height size.

`.jfx-snackbar-content {
  -fx-pref-height: 50px;
  -fx-min-height: 40px;
}`

**Comment by mateusmsant** [comment]
Hey. How could I round my snackbar?

**Comment by ayushchadha23** [comment]
> Hey. How could I round my snackbar?

Have you tried
`.jfx-snackbar-toast{
-fx-border-radius:30;
-fx-background-radius:30;
}`

**Comment by Philipp0205** [comment]
For some reason I can't set the text color via css: 

```
.jfx-snackbar-toast {
    -fx-text-fill: WHITE;
    -fx-font-size: 20;  
}
```

In this example the font-size works but the text-fill not.

**Comment by ayushchadha23** [comment]
> For some reason I can't set the text color via css:
> 
> ```
> .jfx-snackbar-toast {
>     -fx-text-fill: WHITE;
>     -fx-font-size: 20;  
> }
> ```
> 
> In this example the font-size works but the text-fill not.

For some arbitrary reason, try using the ```setStyle("-fx-text-fill: WHITE");```

**Comment by Philipp0205** [comment]
> For some arbitrary reason, try using the `snkbr.setStyle("-fx-text-fill: WHITE");`

Thanks a lot!

**Comment by Philipp0205** [comment]
> For some arbitrary reason, try using the `snkbr.setStyle("-fx-text-fill: WHITE");`

Thanks for the reply. It still does not change the text-color in my case...

**Comment by ayushchadha23** [comment]
> > For some arbitrary reason, try using the `snkbr.setStyle("-fx-text-fill: WHITE");`
> 
> Thanks for the reply. It still does not change the text-color in my case...

Are you sure there isn't something which is overriding the css, if possible send console output while the app css is rendering

**Comment by Philipp0205** [comment]
There should be no css overwriting and the latter I already tested. No difference. The text stays black. 

```java
private void showSnackBar(String text, int millis) {
		JFXSnackbar snack = new JFXSnackbar(newProjectPane);
		JFXSnackbarLayout layout = new JFXSnackbarLayout(text);

		String css = this.getClass().getClassLoader().getResource("style/snackbar.css").toExternalForm();
		snack.getStylesheets().add(css);
		snack.setStyle("-fx-text-fill: WHITEt");

		snack.enqueue(new SnackbarEvent(layout, Duration.millis(millis)));
		//snack.fireEvent(new JFXSnackbar.SnackbarEvent(text,"error-toast"));
	}
```

The snackbar.css contains:
```css
.jfx-snackbar-content {
    -fx-background-color: #d5001c;
	-fx-pref-height: 50px; 
	-fx-pref-width: 40px;
	-fx-text-fill: WHITE;
}


```

**Comment by ayushchadha23** [comment]
> There should be no css overwriting and the latter I already tested. No difference. The text stays black.
> 
> ```java
> private void showSnackBar(String text, int millis) {
> 		JFXSnackbar snack = new JFXSnackbar(newProjectPane);
> 		JFXSnackbarLayout layout = new JFXSnackbarLayout(text);
> 
> 		String css = this.getClass().getClassLoader().getResource("style/snackbar.css").toExternalForm();
> 		snack.getStylesheets().add(css);
> 		snack.setStyle("-fx-text-fill: WHITEt");
> 
> 		snack.enqueue(new SnackbarEvent(layout, Duration.millis(millis)));
> 		//snack.fireEvent(new JFXSnackbar.SnackbarEvent(text,"error-toast"));
> 	}
> ```
> 
> The snackbar.css contains:
> 
> ```css
> .jfx-snackbar-content {
>     -fx-background-color: #d5001c;
> 	-fx-pref-height: 50px; 
> 	-fx-pref-width: 40px;
> 	-fx-text-fill: WHITE;
> }
> ```
Try
```
layout.getStylesheets().add(css);
```

**Comment by Philipp0205** [comment]
> Try
> 
> ```
> layout.getStylesheets().add(css);
> ```

This does't apply any css. 

`snack.getStylesheet().add(css)` apply everything except the text-fill.

**Comment by Philipp0205** [comment]
Okay I figured it out. 
Apply all css rules EXCEPT the text-fill to the snackbar. 

```
JFXSnackbar snack = new JFXSnackbar(newProjectPane);
String css = this.getClass().getClassLoader().getResource("style/snackbar.css").toExternalForm();
```

Apply ONLY the `text-fill` rule to the layout. 

```java
JFXSnackbarLayout layout = new JFXSnackbarLayout(text);
layout.getStyleClass().add("-fx-text-fill: red");
```

This is a bit confusing.

**Comment by elvnski** [comment]
Is it possible to have the snackbar appear from the top of a pane?
