### ISSUE TITLE
How to set side Menu second level?

### ISSUE THREAD

**Issue by JonDai** [jfoenixadmin/JFoenix#531]
![image](https://user-images.githubusercontent.com/15091781/33771548-5390bc82-dc6c-11e7-97a0-01af42340ef2.png)
![image](https://user-images.githubusercontent.com/15091781/33771565-5d9b8964-dc6c-11e7-92c0-48cdee4ac986.png)

before is code and picture.  I want set the "GROUP" name is --"UserManager". not is "GROUP"  .  can your help me how to reset this "GROUP" text?

**Comment by JonDai** [comment]
or can you add this case in to your demo.   this is me copy by your's demo.   and not this multilevel Situation。  thanks!

**Comment by jfoenixadmin** [comment]
Hello,
Well this feature is deprecated and will be removed in later versions of JFoenix.
To achieve this, I recommend creating a custom list cell by extending JFXListCell and setting a TitledPane as the graphic node.

Regards,

**Comment by jesa29** [comment]
Hi @jfoenixadmin !
I have a question about this component.
I'd like to use it in my project "as is", and you say that
`Well this feature is deprecated and will be removed in later versions of JFoenix.`

So I want to copy/paste it in my project and make it CustomListView, remove all deprecations, refactor, etc.

What about copyright and licenses? Can I do that? I dont want to steal anything :)
I'll save javadoc author and all other info, thanks
