### ISSUE TITLE
JFXTreeTableView Horizontal ScrollBar Not Showing

### ISSUE THREAD

**Issue by Bladymyr** [jfoenixadmin/JFoenix#532]
I have a JFXTreeTableView with 3 columns, and one or two of them may have text that doesn't fit in the table, is there any way to make the horizontal scroll bar show when this happens? I thought this would be the default behavior but I was wrong. Thanks!

**Comment by jfoenixadmin** [comment]
Hello,
Well, if the cell content was truncated then the horizontal scroll bar won't show up (default behavior). In order to solve this, you need to fix the cell width so its content won't be truncated. 

Will close this issue as it's not related to JFoenix.
Regards,
