### ISSUE TITLE
Color Picker Close Button macOS

### ISSUE THREAD

**Issue by ofirmiron** [jfoenixadmin/JFoenix#538]
The close button of the color picker is on the wrong side. The location of the close button in macOS is the left side.
![green-maximize-button-os-x-window-bar](https://user-images.githubusercontent.com/17969689/33994789-8e212112-e0e4-11e7-9959-15cf3f9d97ed.jpg)

**Comment by jfoenixadmin** [comment]
this is os specific , you can extend JFXColorPickerSkin and change the location of the buttons.

**Comment by ofirmiron** [comment]
Thanks for the reply. How can I show the default macOS window title bar and remove the close button that is currently there?

**Comment by jfoenixadmin** [comment]
in order to show these custom buttons we are using JFXDecorator to wrap the color picker content. you need to override this behavior and show the content directly without JFXDecorator.
