### ISSUE TITLE
How to change the hamburger StackPane size?

### ISSUE THREAD

**Issue by stormtroop** [jfoenixadmin/JFoenix#539]
Hello guys,

i really start to love jfoenix for javaFX, thanks for this great project.
I currently got a problem with resizing the StackPane of the JFXHamburger,
![image](https://user-images.githubusercontent.com/15097024/33998692-9cf1d87c-e0e8-11e7-80a6-9dd4f8712d86.png)

What i want to change is only the height (thickness) of these element and maybe the height of the JFXHamburger Control (if its possible).

What i tried so far, is trying to set the StackPane height

```
.jfx-hamburger-icon StackPane {
    -fx-max-height: 2px;
}
```

Thanks for your help

**Comment by jfoenixadmin** [comment]
Hello,
you can change it using the following css:
```
.jfx-hamburger StackPane {
    -fx-pref-width: 30px;
    -fx-pref-height: 4px;
    -fx-background-color: #FFF;
    -fx-background-radius: 5px;
}
```

**Comment by stormtroop** [comment]
Hi @jfoenixadmin ,

![image](https://user-images.githubusercontent.com/15097024/34002639-6bdb8f0c-e0f3-11e7-9829-0e6810992455.png)

it´s working great, thanks & have a nice day!
