### ISSUE TITLE
css hamburger icon bug?

### ISSUE THREAD

**Issue by davidjesusacu** [jfoenixadmin/JFoenix#54]
I trying to change the color to the hamburger icon using CSS, which is default BLACK , following the documentation doesn't work for my , I have tried:
```
.jfx-hamburger-icon
{
    -fx-pref-width: 40px;
    -fx-pref-height: 7px;
    -fx-background-color : #D63333;
    -fx-background-radius : 5px;
    -fx-ripple-color:WHITE;
}
```
and It doesnt work.
I have tried to change it to 
```
.jfx-hamburger{
  -fx-background-color : #D63333;
}
```
and the color appears in the full parent VBOX and not in the icon as such.

Is it a bug or it has been any refactoring which doesnt appear in the documentation?.

NOTE: I've downloaded the prebuilt jar and also built by myself the entire project , the result is the same.

**Comment by RAnders00** [comment]
In order to style only the little subcomponents, you need to select them with proper CSS selectors. Just assign the `JFXHamburger`s which you need to style a style class like `red-hamburger`. It's a simple property of any node, so you can set it in Scene Builder, via code or in the FXML code. (it's the `styleClass` property).

After that, you want to select the `StackPane`s the hamburger consists of and style them individually, like this:

```css
.red-hamburger > StackPane {
    -fx-background-color: #FF0000;
}
```

**Comment by RAnders00** [comment]
Also, I figured this out with a basic understanding of how css works and [Scenic View](http://fxexperience.com/scenic-view/). With it, I was able to find out that the hamburger consists of StackPanes.

![image](https://cloud.githubusercontent.com/assets/1629196/13578118/4b00b6c8-e496-11e5-8e02-6d3a0e2cfb96.png)

**Comment by davidjesusacu** [comment]
Got it, Thx you very much for your fast answer, I was just looking around for something new and exciting and I came across JFoenix .
I think it's worth to fix it in the main website documentation.

**Comment by RAnders00** [comment]
Now that I look at it, it's correct in the original documentation though? It clearly says

```css
.jfx-hamburger-icon StackPane {
```

Note the **`StackPane`** in there. Am I missing something?

**Comment by davidjesusacu** [comment]
It seems as if the component was call jfx-hamburger-icon instead of jfx-hamburger, just a matter of appreciation. 
Anyway, Great work, it looks great.

**Comment by RAnders00** [comment]
Maybe open another issue regarding the documentation (otherwise it will just get buried here...)
