### ISSUE TITLE
Style ignored if getUserAgentStylesheet used

### ISSUE THREAD

**Issue by fehdem** [jfoenixadmin/JFoenix#541]
Hi!
I created a custom control basing on AnchorPane, using some standard controls and some JFoenix controls.
I'm using CSS in a separate file for styling. The CSS is returned from getUserAgentStylesheet.

```
  public String getUserAgentStylesheet()
  {
    return ValueBoxTileConfigDlg.class.getResource( "value_box_tile_config_dlg.css" ).toExternalForm();
  }
```

The issue: the style classes included in the CSS get applied on the standard controls, but not on the JFoenix controls.
If I add the styles the "old way" it works as expected:
```
String css = TerminalApplication.class.getResource("../components/value_box_tile_config_dlg.css").toExternalForm();
secondStage.getScene().getStylesheets().add(css);
```

I assume that the styling works an general, because a) it gets applied to the standard controls if I'm using getUserAgentStylesheet and b) it works if a do it the "old way" for the JFoenix controls as well.

So I've got a workaround, but I would prefer using getUserAgentStylesheet for the sake of encapsulation.

Best regards,
Marcus

**Comment by jfoenixadmin** [comment]
Hello,
you can try adding the user agent stylesheet as static call in your custom control instead of overriding the method getUserAgentStylesheet. (this issue seems related to JavaFX css engine)

`StyleManager.getInstance().addUserAgentStylesheet(ValueBoxTileConfigDlg.class.getResource( "value_box_tile_config_dlg.css" ).toExternalForm());`

Regards,

**Comment by fehdem** [comment]
Hi! 
This doesn't work with Java 9. The package com.sun.javafx.css is not visible.

-Marcus

**Comment by jfoenixadmin** [comment]
Well it seems that the javafx css engine is not applying the css properly if there are multiple nested custom controls using user agent stylesheets. It works for the standard controls because "modena.css" is the platform default user agent stylesheet and it's not specified for each control.

**Comment by fehdem** [comment]
Ok. From this perspective this is not an JFoenix issue and we can close this.
Thanks for helping sorting this out.

-Marcus
