### ISSUE TITLE
where is JFXPopup in new version of JFoenix within scene builder ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [jfoenixadmin/JFoenix#542]
I Can't find JFXPopup In this current version.
the old version contains it but that is creating an issue as reported earlier ([here](https://github.com/jfoenixadmin/JFoenix/issues/229)) & [here](https://github.com/jfoenixadmin/JFoenix/issues/215)  
When I moved to newest version I don't find JFXPopup  in scene builder.
![image](https://user-images.githubusercontent.com/11150958/34138278-86a74196-e490-11e7-98bd-083f2a90369e.png)

 but it is available in the library(as per the screenshot below)
![image](https://user-images.githubusercontent.com/11150958/34138297-a2294630-e490-11e7-8bee-62feccb2c0f7.png)
 

@aalmiray @aaronanderson @rsantina @Donovon @RAnders00 
Kindly Help
Thanks

**Comment by jfoenixadmin** [comment]
Hello,
JFXPopup has been reworked, it extends PopupControl instead of Node. thus it won't show up in the scene builder. 

Regards,
