### ISSUE TITLE
How to use JFXPopup with JFXListview in this(latest) version?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [jfoenixadmin/JFoenix#543]
I have already asked the question [here ](https://github.com/jfoenixadmin/JFoenix/issues/542#issuecomment-352662010) but didn't get the solution.

**Comment by jfoenixadmin** [comment]
will close this issue as it's already opened and answered  #378

**Comment by ZaheerUdDeen** [comment]
Sure Thanks! I get the right answer now.
