### ISSUE TITLE
JFoenix 9.0.x not on Maven Central

### ISSUE THREAD

**Issue by nevisnor** [jfoenixadmin/JFoenix#544]
I was hoping to use Gradle for my new project running on Java 9, and discovered that the Java 9 version of JFoenix is not available in Maven Central. I can refer to a local jar, but would rather use Maven Central.

**Comment by jfoenixadmin** [comment]
will close this issue as it's similar to #470

**Comment by jfoenixadmin** [comment]
pushed JFoenix 9.0.0 to maven central it will be available in a couple of hours.
