### ISSUE TITLE
Which version of JFoenix should be used for running my app on JDK 8 as well as JDK 9 ?

### ISSUE THREAD

**Issue by niteesh19** [jfoenixadmin/JFoenix#545]
Hi Guys,

I was wondering which version should I be using to run my JAVAFX app on both JDK 8 and 9.
I see that there is already a JFoenix 9.0.0 released (tracking issue -
 https://github.com/jfoenixadmin/JFoenix/issues/443)
But this version strictly needs JDK 9 and I have to build my application on JDK8, which when fails.

**Comment by jfoenixadmin** [comment]
Hi
For JDK 8 , you need to use the latest 1.x.x.
For JDK 9, you need to use 9.x.x

Regards,

**Comment by niteesh19** [comment]
But if I use JFoenix 1.x.x  and build my app using JDK 8 .. the build is successful. But my app is deployed using java web start and it uses the client's JDK to run. So if my client uses JDK 9 , the app throws an error.

**Comment by jfoenixadmin** [comment]
No, in Java 9 there has been some major refactoring regarding internal JavaFX API.
