### ISSUE TITLE
JFoenix 9.0.0: Unable to load CSS-File directly

### ISSUE THREAD

**Issue by wglanzer** [jfoenixadmin/JFoenix#546]
I just created a simple Application using Java 9.0.1:

```java
/**
 * @author w.glanzer, 20.12.2017.
 */
public class TestApplication extends Application
{
  @Override
  public void start(Stage primaryStage)
  {
    Scene scene = new Scene(new BorderPane());
    
    // TestApplication.class.getResource("/css/jfoenix-design.css") => NULL
    // ModuleLayer.boot().findModule("com.jfoenix").get().getResourceAsStream("/css/jfoenix-design.css"); => NULL
    String jfoenixCSSPath = TestApplication.class.getResource("/css/jfoenix-design.css").toExternalForm();
    scene.getStylesheets().add(jfoenixCSSPath);
    primaryStage.setScene(scene);
    primaryStage.show();
  }
}
```

How to load the provided "jfoenix-design.css" correctly? All ways I try returning null. Is it obsolete to add the provided css to my scene?

EDIT: I used the new deployed 9.0.0 from MavenCentral.

My module-info:
```java
module com.github.wglanzer.test {
  requires javafx.base;
  requires javafx.graphics;
  requires com.jfoenix;

  exports com.github.wglanzer.test;
}
```

**Comment by jfoenixadmin** [comment]
Hello,
No sure it's not obsolete, but it seems that the old project structure doesn't allow accessing the resources folder in JDK 9. We might need to move the resources folder inside the module directory ( still searching as I'm still new to Java 9 and project jigsaw).

Regards,

**Comment by wglanzer** [comment]
I'm new to jigsaw too :-)
Is it possible to move the files, which have to be public, into the correct folder? 
When will this change be possible? 
I think the artifact 9.0.0 in mavenCentral won't be usefull, if this is not fixed :/

**Comment by jfoenixadmin** [comment]
not sure yet about the change, however the artifact 9.0.0 is still useful. 
"jfoenix-deisgn.css" is not used in jfoenix core, it's just an additional css so you can use material design color naming in your project. You can copy the file and add it to your project manually.

**Comment by wglanzer** [comment]
This is completely right... 
Didn't think of this easy solution...

**Comment by eldarj** [comment]
Looked for a solution but still couldn't find - is this solved yet, or should we still manually add "jfoenix-design.css"?

**Comment by jfoenixadmin** [comment]
we refactored the css files in the latest version of JFoenix, 9.0.6, however not sure if this solved the issue (didn't test it)
