### ISSUE TITLE
How to change text color in JFXTextField?

### ISSUE THREAD

**Issue by henzosabiq** [jfoenixadmin/JFoenix#549]
This is my scene : 

![jfxtextfield](https://user-images.githubusercontent.com/26890032/34429154-cf5e41d4-ec86-11e7-8e91-73179a4a26e8.png)

I want to change the text color to white. I've tried google but I cant find any identical issue. 
So, how? Thanks in advance.

**Comment by Puliczek** [comment]
if this is a normal text, you can try by adding a style:
`JFXTextFieldName.setStyle("-fx-text-inner-color: red;");`

Otherwise, if this is a hint text you should try this:
`JFXTextFieldName.setStyle("-fx-prompt-text-fill: red");'

both works for me.

**Comment by jfoenixadmin** [comment]
you can set them through css using the following code
```
.jfx-text-field, .jfx-password-field {
    -fx-prompt-text-fill: #808080;
    -jfx-focus-color: #4059A9;
    -jfx-unfocus-color: #4d4d4d;
}
```
Regards,

**Comment by MRoblesBEA** [comment]
.jfx-text-field 
{ 
-fx-text-inner-color: white;
}

white is the text color, or you can use hexadecimal, #ffffff(white)
