### ISSUE TITLE
Cannot use jfxslider in java8

### ISSUE THREAD

**Issue by DanielZhang17** [jfoenixadmin/JFoenix#551]
I found that the slider is only available in the package for Java9 and for some reason, some of the libraries I use in my application doesn't compile in Java 9  so I have to stick with Java 8. And tried to download the JFoenix source code and recompiled in Java 8, but it still don't contain the slider. Well, the only thing I want to use is the slider and it appears to me that it was not supported in Java 8. So I wonder if it is possible to have that in Java 8 or will there be some other things I can try? I really like the design of it and the original slider in Javafx is just ugly.

**Comment by jfoenixadmin** [comment]
JFXSlider is available in java 8, the latest JFoenix version for Java 8 is 1.11.1
can you provide more details about the issue?

**Comment by DanielZhang17** [comment]
I did not found the component when I try to import the jfxslider into my scene builder with the package,  maybe I should try again

**Comment by DanielZhang17** [comment]
![x1](https://user-images.githubusercontent.com/26383041/34504039-4674d31e-eff2-11e7-873a-032910642a34.PNG)
So I redownloaded the latest release for Java 8  and still can't find the slider when trying to do the import. Is that because I have both JDK 8 and 9 on my system?

**Comment by jfoenixadmin** [comment]
What is the scene builder version?
You need to make sure you are using the right versions of Java/SceneBuilder/JFoenix

**Comment by DanielZhang17** [comment]
Oh, I used the wrong version of SceneBuilder, thanks for the help. Now I can use it without problem
