### ISSUE TITLE
how to change background/text fill in tree table view ungroup/group popup

### ISSUE THREAD

**Issue by blackmo18** [jfoenixadmin/JFoenix#552]
Hello, I need some help how to change the background/text fill when ungrouping/grouping selection is showing when right-clicking a column in tree table view.

```

.tree-table-view .column-header, .tree-table-view .filler {
 -fx-size: 35;
    -fx-text-fill: white;
    -fx-border-width: 0 0 1 0;
    -fx-background-color: #0aa7a2;
    -fx-border-color:  derive(-fx-base, 80%);
    -fx-pref-height:30;
}
.tree-table-view .column-header .label {
    -fx-text-fill: white;
    -fx-alignment: center;
    -fx-opacity: 1;
}
```

![20180102_163502](https://user-images.githubusercontent.com/22386010/34478359-7cd4dd58-efdb-11e7-9c6c-eb927312c2b6.jpg)
**sorry i have to use my cp since the pop-up dissappears whenever I try to print screen**

the problem happens when I change the text color _-fx-text-fill: white_ under .column-header .label the pop-up word color also changes into white. So I need to change the text color and selection and hover color so the word group/ungroup is readable and visible.

Is there any way to achieve this via CSS?

**Comment by jfoenixadmin** [comment]
Hello,
you can change it using the following css:
```
.tree-table-view .menu-item .label {
    -fx-text-fill: BLACK;
}
```
Regards,

**Comment by blackmo18** [comment]
Hello jfoenixadmin,
I like also to ask how to change the color of the **arrow** when you **group** items in the tree table.
I know it can be done via **CSS**, it is just I don't know how it is exactly the arrangement to access it.

Some insight would be much appreciated. tnx.
