### ISSUE TITLE
Disable Group / Ungroup buttons for JFXTreeTableView

### ISSUE THREAD

**Issue by nafarkash** [jfoenixadmin/JFoenix#553]
Hi,
Pressing a column header will open a context menu with the two options: Group, UnGroup

How can I disable this menu? 
Thanks,
Naor.

**Comment by jfoenixadmin** [comment]
Hi 
it's the column context menu, you can remove it by simply calling the following for each column:

`column.setContextMenu(null);`

Regards,

**Comment by jesa29** [comment]
> Hi
> it's the column context menu, you can remove it by simply calling the following for each column:
> 
> `column.setContextMenu(null);`
> 
> Regards,

this crashes application for me, 
I've used 
`column.setContextMenu(new ContextMenu());`
