### ISSUE TITLE
Styling JFXTreeTableView

### ISSUE THREAD

**Issue by nafarkash** [jfoenixadmin/JFoenix#555]
I'm looking for a JFXTreeTableView css definition for the following cases:
- Decrease row height
- Background color for the first level child of the root (as shown below)
![image](https://user-images.githubusercontent.com/3889815/34513956-87e6001c-f073-11e7-9005-bffbc5d6fe5b.png)

Is it possible?

Thanks,
Naor.

**Comment by jfoenixadmin** [comment]
Hello,
styling JFXTreeTableView is similar to styling Java TreeTableView. You can find many examples online
(e.g https://stackoverflow.com/questions/18700478/set-row-height-in-javafx-tableview)

Regards,
