### ISSUE TITLE
JFXTabPane doesnt react to mouse pressed events

### ISSUE THREAD

**Issue by Sharknoon** [jfoenixadmin/JFoenix#557]
The JFXTabPane doesnt react to a mouse pressed event. This code doesnt work:
```
tabPane.setOnMousePressed(event -> {
    System.out.println("pressed");
});
```
Other events like onScroll, onMouseDragged, onMouseReleased and many more are working just fine.
Thank you

**Comment by Sharknoon** [comment]
I am using Java 8u144 and JFoenix 1.11.1

**Comment by jfoenixadmin** [comment]
you are right, thanks for pointing out the issue 👍 
Regards,

**Comment by Sharknoon** [comment]
No problem, can't wait for the fix :)
