### ISSUE TITLE
Java Esclipse Does not Generate Controller for jFoenix Objects/Actions. Help!

### ISSUE THREAD

**Issue by 170418S** [jfoenixadmin/JFoenix#558]
Hello there,

I'm trying to run my fxml file and I've encountered when running it. It seems that I can't run it as it gives me this error in the photo. At the same time, I can't generate the controllers that I've inserted in. I've already imported it in.

![image](https://user-images.githubusercontent.com/33929871/34557366-fa846648-f174-11e7-8818-d4720d60da09.png)
Errors

![image](https://user-images.githubusercontent.com/33929871/34557330-de5139ba-f174-11e7-9747-9cd63c6e1e83.png)
Fx:id and Actions

![image](https://user-images.githubusercontent.com/33929871/34557402-165d5e60-f175-11e7-87e9-bff21e4ea171.png)
When Generating

**Comment by jfoenixadmin** [comment]
Hi,
According to the exception, it seems that JFoenix jar is not included in your class path. Will close this issue as it's not related to JFoenix development.

Regards,
