### ISSUE TITLE
JFXDrawer

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#56]
Hi,

I've found a bug with JFXDrawer/JFXDrawerStack. If I setDefaultDrawerSize to some sizes, they will not be properly toggle-closed and the isShown method does not show the correct status.  In the DrawerDemo.java, I've changed the default size into 150 and the issue appears.
In another example on my own, the default size has to be greater than 400 or it fails as I explained.
[UPDATE]
I just comment out the setDefaultDrawerSize for the top/bottom drawer and the issue appears again. This is not true for the left and right drawers, however. I've uploaded a demo project below (see last comment).

**Comment by jfoenixadmin** [comment]
Hi, 

I couldn't reproduce after setting the default size to 150 in DrawerDemo.java, can you retest using the latest version of jfoenix?
if the issue still persist, kindly provide an example.

**Comment by aminabs** [comment]
Thanks,
I will do the same and let you know in a day or two.

**Comment by aminabs** [comment]
Thanks,
I will do the same and let you know in a day or two.

**Comment by aminabs** [comment]
Hi,
Attached please find a demo [netbeans project] which reveals a bug with JFXDrawer while toggled off (not hide correctly).

Note 1: 
In this demo, you will find two drawers [with top and bottom directions] fail to correctly hide. [Click on the buttons to show drawers and then click on the center of the screen to hide them]

Note 2:
There are two other drawers with left and right directions which work fine in this demo; however, there are some cases in my private code which they also fail exactly the same as the first two drawers (top/bottom)

Note 3: I tested the demo with two different jfeonix jar files: First with the latest artifact you put on the maven snapshots repo. [jfoenix-0.0.0-20160309.093137-10.jar]; Second with the one you've put on the home page of the project [and both of them fails the same].

Hope it helps.
[jfoenixBugReport.zip](https://github.com/jfoenixadmin/JFoenix/files/170328/jfoenixBugReport.zip)

**Comment by jfoenixadmin** [comment]
Hi, 

I tested the issue, it's due not assigning a value for <i><b>defaultSizeProperty</b></i> in JFXDrawer. I'll assign a default value of 100 which will fix the issue.

Regarding the actions hiding and drawing the isShown method returns false, that's the intended behavior. these actions are triggered when the drawer is animating, so it's not fully shown. it will return true only when the drawing animation ends.

Hope it helps.

**Comment by aminabs** [comment]
Hi,
I do not think this solves the issue. As I previously mentioned, I did set the default size to different values, and in some cases the issue popped out.
BTW, Please take a look at issue #64 which is reported by another user. I did see the same bug in my own codes and I think these issues are related.

**Comment by jfoenixadmin** [comment]
well you need to be specific, and provide another example that shows the issue when testing different values, otherwise it will be very hard to debug this issue.

**Comment by pistolla** [comment]
Hi guys, how exactly does DrawersStack know about drawers from the Demo DrawerDemo.java

**Comment by pistolla** [comment]
The catch is drawersStack.addDrawer(...); 
couldn't get for whole hour. hahaha!
