### ISSUE TITLE
Slow Animation In new Stage

### ISSUE THREAD

**Issue by VENT0** [jfoenixadmin/JFoenix#563]
Dear developers,
thank you for this awesome library. But I have a problem, when I load a new stage - everything in it laggy. All the animations are slow. But in the main stage everything works fine.

Here the video: https://youtu.be/JX9Md4EzCaQ

My code to load new Stage from FXML:
```
darkLayer.setVisible(true);             //Making main stage dark
Stage settings = new Stage();
settings.initStyle(StageStyle.UNDECORATED);
settings.initModality(Modality.WINDOW_MODAL);
settings.initOwner(VENTO.window);
Parent p = SettingsWindow.loadSettingsWindow(mainFrontArea);    //load from FXML file
settings.setScene(new Scene(p, 666, 403));
settings.show();
```

Thank you in advance.

**Comment by jfoenixadmin** [comment]
can you try loading the settings window in the main stage? 
also can you provide more details about the environment you are using?

Regards,

**Comment by VENT0** [comment]
Thank you for your response.

I solved my problem. I tried to load settings on main stage and it also laggs. Then I changed the container in settings from "Pane" to "AnchorPane" and I rewrite all my code from scratch. I guess that it was a problem in FXML because I also remake it from scratch.
