### ISSUE TITLE
DatePicker Validation

### ISSUE THREAD

**Issue by deme78** [jfoenixadmin/JFoenix#565]
Is there a way to validate the JFXDatePicker and show an error label how it's possible with the JFXTextField?

![errorlabel](https://user-images.githubusercontent.com/23071577/34711062-249986e6-f51e-11e7-9109-d0db114bf0c7.PNG)

**Comment by jfoenixadmin** [comment]
Yes, you can using ValidationFacade. 
You can find an example in JFoenix main demo (Combobox validation)

Regards,

**Comment by mataide** [comment]
I tried to validate JFXDatePicker the same way of ComboBox, but doesnt work.

Combobox is working, but if you do the same with JFXDatePicker nothings happens.
The validation is always true.

**Comment by mataide** [comment]
@deme78 got it working?

**Comment by roger1891** [comment]
Did anybody get this to work? Also does somebody have the link to the example?

**Comment by jfoenixadmin** [comment]
@roger1891 in the latest version of JFoenix, IFXValidatableControl interface has been added. So any control that implements this interface supports validation directly. JFXDatePicker implements this interface too.
