### ISSUE TITLE
Java9

### ISSUE THREAD

**Issue by MilkAndCat** [jfoenixadmin/JFoenix#566]
so I updated my Java from 8 to 9, and I do realize that Jfoenix has separate Jar file for Java 9.
However after download the Jar file then trying to import to Scene builder like I did before, nothing shows up, None of the custom controller shows up when I trying to import. 
![screen shot 2018-01-09 at 9 38 30 pm](https://user-images.githubusercontent.com/24483249/34753340-7318fd80-f585-11e7-8eaf-e4b614728211.png)

**Comment by jfoenixadmin** [comment]
you need to download Scene builder for Java 9 too.
