### ISSUE TITLE
No cursor changes

### ISSUE THREAD

**Issue by Djaler** [jfoenixadmin/JFoenix#567]
After update from 1.9.1, when I move cursor over JFXButton or JFXListView, cursor doesn't changes.

**Comment by jfoenixadmin** [comment]
By default it doesn't change, you need to change it through css

**Comment by Djaler** [comment]
Can you suggest how?

**Comment by jfoenixadmin** [comment]
you can change it using the following css:
```
.button:hover{
    -fx-cursor: hand;
}
```
Regards,
