### ISSUE TITLE
Wrong font in dialog body

### ISSUE THREAD

**Issue by Djaler** [jfoenixadmin/JFoenix#568]
After update to 1.10.0 I noticed that labels in dialog body have wrong font.
First screenshot - 1.10.0
Second screenshot - 1.9.1
![screenshot_20180110_142829](https://user-images.githubusercontent.com/7964583/34770653-bcc2c5aa-f612-11e7-887b-a5a16fea2927.png)
![screenshot_20180110_142856](https://user-images.githubusercontent.com/7964583/34770654-bce5fe44-f612-11e7-8be3-f8376546c48f.png)

**Comment by jfoenixadmin** [comment]
yeah the default font size has been updated to match material design guidelines. however you can change it through css if needed:
```
.jfx-dialog-layout .jfx-layout-body .label{
    -fx-text-fill: #757575;
    -fx-font-size: 16.0;
    -fx-wrap-text: true;
}
```
Regards,
