### ISSUE TITLE
Spinner causes slow down

### ISSUE THREAD

**Issue by LandyLane** [jfoenixadmin/JFoenix#571]
Hi, I was building an application and was wondering why it takes awhile to choose directories. After further inspection; leaving the spinner as visible has a detrimental affect on the performance of the application. Not sure why; but carry out your own tests to see if its the same. Tested on Win 10 7th gen i3; and a Win 7 3rd gen i3 both with sufficient memory and graphics processing power.

**Comment by jfoenixadmin** [comment]
Hi, 
We tested keeping the spinner visible for a long duration, however it doen't affect the memory or the application performance. It could be related to some background task running in your application.
if you can provide more details about the issue or SSCCE demonstrating the issue, we might be able to help.

Regards,
