### ISSUE TITLE
is there a way to implement smooth scolling to jfxscrollpane?

### ISSUE THREAD

**Issue by Dooardarshan** [jfoenixadmin/JFoenix#573]
i was wondering you guys has implemented smooth scrolling for jfxscrollpane. scroll speed vary according to mouse drag speed and such.

**Comment by jfoenixadmin** [comment]
Hi,
yes, you can add smooth scrolling to a scroll pane by using the static methods in JFXScrollPane:
```
JFXScrollPane.smoothScrolling(scrollPane);
JFXScrollPane.smoothHScrolling(scrollPane);
```
Regards,

**Comment by Dooardarshan** [comment]
Hi, Thanx for the respond. i tried it but it did not work. do i have to use a JFXscrollpane? coz it gave me an error. so i used a ScrollPane. but it did not work. can you help me here? thanx

**Comment by jfoenixadmin** [comment]
what's the exception when you tried to apply it to ScrollPane?

**Comment by Dooardarshan** [comment]
well there was no error. its not working. same scroll pattern.
lemme explain.
i made a custom list using scroll pane

   ScrollPane itemGrid = new ScrollPane();
    itemGrid.setPannable(true);
    VBox gp = new VBox(5);
    for (int i = 0; i < 100; i++) {
             HBox rowBox = new HBox();
             rowBox.getChildren().add(i);
             gp.getChildren().add(rowBox);
      }
    itemGrid.setContent(gp);
   JFXScrollPane.smoothScrolling(itemGrid);

this is what i did. did i do it wrong?

**Comment by jfoenixadmin** [comment]
Well it seems that the content is blocking scroll event, I'll update the listeners to be event filters instead of handlers.
Thanks for pointing out the issue 👍 

Regards,

**Comment by jfoenixadmin** [comment]
the fix will be included in the next release, meanwhile you can get the fix by downloading JFoenix jar from the website <a href="http://www.jfoenix.com/download/jfoenix.jar"> here</a>

**Comment by Dooardarshan** [comment]
Thank you very much! keep up the good work! cheers!

**Comment by Dooardarshan** [comment]
i wanna point out its only working for the mouse scroll button. when it is dragged its not working.

**Comment by jfoenixadmin** [comment]
Yes it's only implemented for the scroll button, feel free to add your own contribution to JFoenix :)
Regards,
