### ISSUE TITLE
How to set the position of the validator

### ISSUE THREAD

**Issue by t6jin** [jfoenixadmin/JFoenix#574]
Hi,

I was wondering if there is a way to set the position of a RequiredFieldValidator. Currently, the default position is below the text field, however, I would like to put it somewhere else, like the right of the text field.

Thanks

**Comment by jfoenixadmin** [comment]
Hi,
Currently there is no public property to change the position of the validation message. Feel free to add your own contribution to JFoeinx.

Regards,
