### ISSUE TITLE
Jfoenix tree table

### ISSUE THREAD

**Issue by johnjoshuababiera** [jfoenixadmin/JFoenix#575]
how do i get the current content of the table? for example after sorting it ill get list of objects where it is sorted like in the table? in table view correct me if im wrong its tableview.getItems().

**Comment by stormtroop** [comment]
im not sure if you are talking about the 
`JFXTreeTableView`
or the common 
`TreeTable`

There is no TableView concept for JFoenix at the moment, afaik `treeTableView.getRoot()` returns a ordered list from your TreeTableView. If not, you can simply get every column and check the sorttype property.

**Comment by johnjoshuababiera** [comment]
treetableview.getRoot().getChilren() did it. thanks!
