### ISSUE TITLE
Changing the color of the JFXList rippler 

### ISSUE THREAD

**Issue by stormtroop** [jfoenixadmin/JFoenix#576]
Hello guys,

thanks for this great framework, im currently struggling with changing the JFXList Item background color. Can someone give me a tip how to change the background-color / rippler effect color?
Actually im using the jfoenix-demo.css from the demo-application, but i somehow cant find this css class.

That the component im trying to modify:
![image](https://user-images.githubusercontent.com/15097024/34991725-ebc2fcf0-faca-11e7-9998-d52845447049.png)

My try:
![image](https://user-images.githubusercontent.com/15097024/34991736-f3a7b33e-faca-11e7-93c8-3f4e43a5ba67.png)

Thanks

**Comment by wglanzer** [comment]
Did You try it with "-jfx-rippler-fill"? 
I think you missed out the prefix "j" in your css-file.

See Demo-JFoenix-CSS:
[https://github.com/jfoenixadmin/JFoenix/blob/791eebc0b698b0dad7a589ba8470eff1014225ab/demo/src/main/resources/css/jfoenix-main-demo.css#L200](url)

**Comment by stormtroop** [comment]
Thanks, that may be the reason.
I gonna test it

**Comment by stormtroop** [comment]
Sorry for the late answer, but it doesnt change the rippler background color 
with`-jfx-rippler-fill`

Any other idea?

**Comment by jfoenixadmin** [comment]
Didn't notice the css selectors, those are outdated. You can change them using the following css:

```
.jfx-list-cell .jfx-rippler {
    -jfx-rippler-fill: #5264AE;
}
```

and for the background

```
.jfx-list-cell {
    -fx-background-color: WHITE;
}
```
I noticed that some styling in the main demo css are outdated, will fix it as soon as possible to prevent misleading. Thanks for pointing out the issue 👍 

Regards,
