### ISSUE TITLE
How am I supposed to import JFoenix into my module-info.java file?

### ISSUE THREAD

**Issue by mayuso** [jfoenixadmin/JFoenix#577]
I currently have the following `module-info.java` file:

    module JMarkPad {
        requires javafx.graphics;
        requires javafx.fxml;
        requires javafx.controls;
        requires javafx.web;
        requires com.jfoenix;
    }

The javafx libraries don't give any problem but com.jfoenix throws the following: `error: module not found: com.jfoenix`

Where am I supposed to have the `jfoenix-9.0.1.jar` file in order to get `gradle build` to read it?

**Comment by mayuso** [comment]
Nvm, found the solution, I needed to spocify gradle what to search for:    

    ext.moduleName = 'com.jfoenix'


    compileJava {
        inputs.property("moduleName", moduleName)
        doFirst {
            options.compilerArgs = [
                    '--module-path', classpath.asPath,
            ]
            classpath = files()
        }
    }

**Comment by DhillonParwinder** [comment]
module myExampleProject {
    requires javafx.graphics;
    requires javafx.fxml;
    requires javafx.controls;
    requires javafx.web;
    requires com.jfoenix;
}

It works in my case. 
Thanks
