### ISSUE TITLE
JFXMasonryPane API

### ISSUE THREAD

**Issue by Sxtanna** [jfoenixadmin/JFoenix#579]
Would it be possible to expose some of the details of the currently rendered pane through properties?

It would be nice to know the details of the following:
- Row count
- Column count
- How many nodes are in a row by index
- How many nodes are in a column by index

These details would greatly improve the ability to interact with the pane and build a more reactive application.

**Comment by jfoenixadmin** [comment]
Not sure if this info will be helpful, as nodes can expand on multiple rows and columns. So these values are dependent on the used bin packing algorithm. I think adding them will lead to confusion.

**Comment by Sxtanna** [comment]
I feel what the values are based on is completely irrelevant to the usefulness of them being exposed. 
If a node could extend into multiple rows or columns, would it not still be possible to count them as "within that row/column".

**Comment by mokun** [comment]
I suppose it will take a lot of change to make jfoenix fully "reactive" compliant.

**Comment by jfoenixadmin** [comment]
@mokun if you can be more specific it would be appreciated. 
Regards,

**Comment by camdenorrb** [comment]
Open sesame
