### ISSUE TITLE
[JFXTabPane] Header Width

### ISSUE THREAD

**Issue by Tensili** [jfoenixadmin/JFoenix#580]
How to change width of the JFXTabPane header, like.. I don't want it to be 100% wide, but for example 80% or less.

**Comment by jfoenixadmin** [comment]
the header width is related to the tab pane width, so you can change it by changing the tab pane width instead.

**Comment by Tensili** [comment]
That is not a solution for my problem. I don't want to change width of the whole JFXTabPane, but only width of the header. 

Something like that:
![example](https://user-images.githubusercontent.com/35630474/35382090-87fc7e94-01be-11e8-979a-70a5570b7cda.png)

**Comment by jfoenixadmin** [comment]
can you provide SSCCE demonstrating your issue?

**Comment by skmedix** [comment]
@jfoenixadmin 
I think he wants to extend original `JFXTabPane(Skin)`, and with a reflection change the width of `HeaderContainer`. Or add something to the same pane to make some kind of a decorator.
