### ISSUE TITLE
double-click the decorator to maximize the screen when the maximize option is false。

### ISSUE THREAD

**Issue by koy-tome** [jfoenixadmin/JFoenix#581]
Node buttonsContainer = decorator.lookup(".jfx-decorator-buttons-container");
        buttonsContainer.setOnMouseClicked((mouseEvent) -> {
            if (mouseEvent.getClickCount() == 2) {
                decorator.setMaximized(!primaryStage.isMaximized());
            }
        });

**In this way, the screen will flash it, there are other programs?**

**Comment by mayuso** [comment]
I don't get what you are trying to do. I'm currently on 8.0.1 and this functionality works by default just creating a JFXDecorator and adding it to a JavaFX scene (And that scene to a stage)

    FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("myFXMLFile.fxml"));
    fxmlLoader.setController(this);
    Parent root = (Region) fxmlLoader.load();

    //decorator is Global as I need access to it in other places
    decorator = new JFXDecorator(stage, root);

    decorator.setCustomMaximize(true);
    Scene scene = new Scene(decorator, 800, 600);

    scene.getStylesheets().add("myCSSFile.css");
    stage.initStyle(StageStyle.UNDECORATED);
    stage.setResizable(true);

    stage.setMinWidth(800);
    stage.setMinHeight(600);
    stage.setScene(scene);
    stage.show();

**Comment by koy-tome** [comment]
![image](https://user-images.githubusercontent.com/24954758/35224413-e4f15fd0-ffbf-11e7-9a58-01e9f7aa159b.png)

`
        Parent root = FXMLLoader.load(getClass().getResource("drawer.fxml"));

        JFXDecorator decorator = new JFXDecorator(stage, root,false,false,true);

        //decorator.setCustomMaximize(true);
        decorator.setBlendMode(BlendMode.MULTIPLY);

        decorator.setBlendMode(BlendMode.RED);
        decorator.setOnMouseClicked(event -> {
            if(event.getClickCount() == 2){
                decorator.setMaximized(!stage.isMaximized());
            }
        });
        Scene scene = new Scene(decorator, 800, 600);

        //scene.getStylesheets().add("myCSSFile.css");
        stage.initStyle(StageStyle.UNDECORATED);
        stage.setResizable(false);

        stage.setMinWidth(800);
        stage.setMinHeight(600);
        stage.setScene(scene);
        stage.show();`

**I hope, double-click the mark will not be enlarged to full screen, what is the solution?**
`decorator.setOnMouseClicked(event -> {
            if(event.getClickCount() == 2){
                decorator.setMaximized(!stage.isMaximized());
            }
        });`
**I added this code, But it blinks when i double-click the mark.**

**Comment by jfoenixadmin** [comment]
full screen mode is different than maximized mode, to set it you can call the following code on mouse click:
`stage.setFullScreen(!stage.isFullScreen())`
