### ISSUE TITLE
JFXPopup width and height calculated incorrectly 

### ISSUE THREAD

**Issue by ronsiven** [jfoenixadmin/JFoenix#583]
If I add just one item to my listview for my popup, the resulting popup is very narrow and very short. The more items I add, the bigger the popup gets.

1 Item:
![image](https://user-images.githubusercontent.com/466261/35286910-c84eea66-0026-11e8-97c3-949236df8433.png)

2 Items:
![image](https://user-images.githubusercontent.com/466261/35286964-f47b86bc-0026-11e8-82db-6c1cfaef9a61.png)

3 Items:
![image](https://user-images.githubusercontent.com/466261/35287012-0f705d12-0027-11e8-8717-f3be53587097.png)

10 Items:
![image](https://user-images.githubusercontent.com/466261/35287058-29ac5898-0027-11e8-9cb3-7fbf25e1c19b.png)

**Comment by jfoenixadmin** [comment]
Hi,
I was able to reproduce, will look into it. Thanks for pointing out the issue 👍 

Regards,
