### ISSUE TITLE
JFXDepthManager Not changing the depth

### ISSUE THREAD

**Issue by kingdevnl** [jfoenixadmin/JFoenix#585]
JFXDepthManager Not changing the depth.
The code: https://hastebin.com/ovepuhijob.java
The FXML: https://hastebin.com/lamanahixo.xml

**Comment by jfoenixadmin** [comment]
It does change, however JFXTextArea background is set to transparent by default. if you change that you will notice the depth.

**Comment by kingdevnl** [comment]
Where can i set the transparent to off?

**Comment by jfoenixadmin** [comment]
by changing the background color of the text area
