### ISSUE TITLE
Snack-Bar Content

### ISSUE THREAD

**Issue by Yingrjimsch** [jfoenixadmin/JFoenix#586]
Hello
Is there a way to add elements into the Snack-Bar?
I would like to add an Icon or another additional element.

I think I have to add a child to the BorderPane **content** but that's not possible yet.

I hope there is a way.

**Comment by mayuso** [comment]
You mean the top bar containing the Minimize, Maximize and Close buttons?

This is possible, **although not sure if recommended**:

    FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("yourFXML.fxml"));
    fxmlLoader.setController(this);

    Parent root = (Region) fxmlLoader.load();
    JFXDecorator decorator = new JFXDecorator(stage, root);

    decorator.setCustomMaximize(true);
    ((HBox) decorator.getChildren().get(0)).getChildren().add(0, new JFXButton());
    ((HBox) decorator.getChildren().get(0)).getChildren().add(1, new JFXButton());
    ((HBox) decorator.getChildren().get(0)).getChildren().add(2, new JFXButton());
    Pane pane = new Pane();
    HBox.setHgrow(pane, Priority.ALWAYS);
    // This pane growing horizontally helps align everything to the left. 
    // I am pretty sure there must be simple function to align all of this, but this is the code I used a while ago as it is.
    ((HBox) decorator.getChildren().get(0)).getChildren().add(3, pane); 

    Scene scene = new Scene(decorator, java.awt.Toolkit.getDefaultToolkit().getScreenSize().width, java.awt.Toolkit.getDefaultToolkit().getScreenSize().height);

    scene.getStylesheets().add("yourCSS.css");
    stage.initStyle(StageStyle.UNDECORATED);
    stage.setResizable(true);
    stage.setX(0);
    stage.setY(0);
    stage.setScene(scene);
    stage.show();

This will add 3 empty JFXButtons to that panel, again, **I am not 100% sure if this is the best way, or even if doing this is recommended, it's just a way that worked for me in the past**.

**Comment by Yingrjimsch** [comment]
Thank you for the answer.

But I meant the JFXSnackBar.
I would like to add an icon or a button in front of the text.

**Comment by jfoenixadmin** [comment]
Currently JFXSnackbar only supports a text and an action on the right, feel free to improve it and add your own contribution to JFoenix (JFXSnackbar public API needs a major change as it's very limited and not generic at all)

**Comment by jfoenixadmin** [comment]
JFXSnackBar has been updated to support custom user content

Regards,
