### ISSUE TITLE
Is it possible to modify the tab stroke color by using setStyle (in java)?

### ISSUE THREAD

**Issue by cyberpwnn** [jfoenixadmin/JFoenix#587]
Im trying to create multiple tab panes in different situations and was wondering if its possible to change the stroke color (the line on the selected tab). 

Currently I have this css as a default
```css
.jfx-tab-pane .tab-selected-line {
    -fx-background-color: #00cbff;
}
```

However I would like to override this via setstyle. I have tried setting it via the tab pane, each tab and even inlining the entire css, but im not sure if JavaFX supports selectors in the setStyle method anyways. Is it possible to do this?

```java
tabPane.setStyle("-fx-stroke:" + activity.getType().getColor() + ";"); // Does nothing
tabPane.setStyle("-fx-background-color:" + activity.getType().getColor() + ";"); // Does nothing

Tab tabOverview = new Tab();
tabOverview.setStyle("-fx-stroke:" + activity.getType().getColor() + ";"); // Does nothing
tabOverview.setStyle("-fx-background-color:" + activity.getType().getColor() + ";"); // Tab changes, not the line
```

**Comment by jfoenixadmin** [comment]
Hi, you can't use selectors in setStyle method so you can't change the line color using it. it can only be done through css.
Also using the method setStyle is a bad practice, I recommend using your own css classes/pseudo-classes instead.

Regards,
