### ISSUE TITLE
JFXTextfield failure on android, requires new release

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#588]
Hi there,
I just want to ask for a new release for android which contains the fix for jfxtextfield animation bug (#584).
Would it be available a in a day or two?

Thanks,

**Comment by jfoenixadmin** [comment]
Hi, the fix will be included in the next release (by the end of the month). meanwhile you can download it from the link provided in (#584)

Regards,

**Comment by aminabs** [comment]
Thanx.
