### ISSUE TITLE
ErrorTooltip not updated with new message

### ISSUE THREAD

**Issue by rwhite226** [jfoenixadmin/JFoenix#589]
In ValidatorBase the errorTooltip message does not change between validates if they both set hasErrors to true but have different messages. For example if you subclassed ValidatorBase to validate any positive number from a textfield. If the user typed "-5" the validator would first get "-", and the message might be "- is not a number". Then it would get "-5" and you might want to change the message to "-5 is < 0", but the tooltip sill still say "- is not a number" until their is no longer an error.

**Comment by jfoenixadmin** [comment]
I tried the previous scenario however was not able to reproduce, can you provide a sample example to demonstrate the issue?

**Comment by rwhite226** [comment]
@jfoenixadmin Here is a demo I created of the issue [https://github.com/rwhite226/JFoenixTest](url)

**Comment by jfoenixadmin** [comment]
Well, ValidatorBase was implemented with a single validation task in mind.

So to fix this issue you need to create 2 validators. A NumberValidator to validate the text value format, and a second validator to validate the less than condition.
