### ISSUE TITLE
[Java 9] Add ValidatorBase to module-info.java

### ISSUE THREAD

**Issue by jboix** [jfoenixadmin/JFoenix#592]
Would it be possible to add `exports com.jfoenix.validation.base` to the module-info.java?

I was trying to migrate a JFoenix project to Java 9 that uses extensibly the ValidatorBase class to create custom validators for certain input fields but this class is not visible in the latest version of JFoenix when using modules.

**Comment by jfoenixadmin** [comment]
yeah sure it should be exported, thanks for pointing out the issue 👍

**Comment by ivandalbosco** [comment]
Dear team,
Any clue as regards when you could release a new version with the fix? Many thanks in advance.
Yves

**Comment by jfoenixadmin** [comment]
Hello, 
It's been a very busy week for us, hopefully the next release will be out by the end of this week or early next week 

Regards,

**Comment by ivandalbosco** [comment]
That's great, thank you! We are eagerly waiting for the release.
Cheers.

**Comment by jfoenixadmin** [comment]
a new release is out 9.0.2

**Comment by ivandalbosco** [comment]
Thanks a lot, folks!
