### ISSUE TITLE
Responsive Handler Bug will give large screen for all screen types

### ISSUE THREAD

**Issue by mordechaim** [jfoenixadmin/JFoenix#595]
https://github.com/jfoenixadmin/JFoenix/blob/f80f126043cb61142d6316f3b8549071c4abfce3/jfoenix/src/main/java/com/jfoenix/responsive/JFXResponsiveHandler.java#L64

As you can see it just ignores whatever the user passed as pseudo-class.

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍
