### ISSUE TITLE
JFXDialog transparent background and white borders on Android 5.1.1.

### ISSUE THREAD

**Issue by svininykh** [jfoenixadmin/JFoenix#598]
Hello!
I have a problem with JFXDialog on Android 5.1.1.

![screenshot_2018-02-07-09-30-00](https://user-images.githubusercontent.com/1005780/35898799-e3833f6c-0bf2-11e8-85da-6e8f46bac4f9.png)

My source code:
```
        StackPane main = new StackPane();
        main.setPadding(new Insets(8.0));

        JFXButton jfxButton = new JFXButton("Button");

        jfxButton.setOnAction((PushButtonAction) -> {
            JFXTextField jfxTextField = new JFXTextField();
            jfxTextField.setPromptText("Text field");
            jfxTextField.setLabelFloat(true);
            StackPane pane = new StackPane(jfxTextField);
            pane.setPadding(new Insets(16.0));
            JFXDialog dialog = new JFXDialog(main, pane, JFXDialog.DialogTransition.TOP);
            dialog.show();            
        });
        main.getChildren().add(jfxButton);
        final Scene scene = new Scene(main, 300, 200);
        stage.setTitle("JFX Test Demo");
        stage.setScene(scene);
        stage.show();

```

**Comment by jfoenixadmin** [comment]
Hello,
What version of JFoenix are you using? are you applying any stylesheet files to the scene?

**Comment by svininykh** [comment]
Hello, 
I used current snapshot version of JFoenix. No, I used dialog without stylesheet files.

**Comment by jfoenixadmin** [comment]
try adding the following css to your project
```
.jfx-dialog-layout .jfx-layout-body{
    -fx-background-color: WHITE;
}
```

**Comment by jfoenixadmin** [comment]
try adding the following css to your project:

```
.jfx-dialog-overlay-pane > StackPane {
    -fx-background-color: WHITE;
}
```

**Comment by svininykh** [comment]
Thank you, But your solution did not resolved problem with white borders on shadow around dialog window.

**Comment by XlintXms** [comment]
I had the same problem https://github.com/jfoenixadmin/JFoenix/issues/652 , i tried with css but i did not get any changing.

**Comment by XlintXms** [comment]
Hi there ,to resolve your issue you should make **node background** as empty value : 

 `JFXTextField jfxTextField = new JFXTextField();

            jfxTextField.setPromptText("Text field");

            jfxTextField.setLabelFloat(true);

            StackPane pane = new StackPane(jfxTextField);

            pane.setBackground(Background.EMPTY);

            pane.setPadding(new Insets(16.0));

            JFXDialog dialog = new JFXDialog(main, pane, JFXDialog.DialogTransition.TOP);

            dialog.show();   `
