### ISSUE TITLE
JFXToggleButton style class issue

### ISSUE THREAD

**Issue by qtran** [jfoenixadmin/JFoenix#602]
Hi,
I have a JFXToggleButton whose style is changing dynamically. I did that by using style classes.
The issue here is that it somehow get messed up.

![image](https://user-images.githubusercontent.com/386593/35981788-68b9c092-0cee-11e8-8287-538b1ae66f11.png)

```
public class JFXSpinnerTest extends Application {

    private static final String STYLE_1 = "style1";
    private static final String STYLE_2 = "style2";

    public static void main(final String[] args) {
	launch(args);
    }

    @Override
    public void start(final Stage primaryStage) {
	primaryStage.setTitle("JFXToggleButton test");
	final JFXToggleButton btn = new JFXToggleButton();

	btn.getStyleClass().add(STYLE_1);
	btn.selectedProperty().addListener((ChangeListener<Boolean>) (observable, oldValue, newValue) -> {
	    if (newValue) {
		btn.getStyleClass().remove(STYLE_1);
		btn.getStyleClass().add(STYLE_2);
	    } else {
		btn.getStyleClass().remove(STYLE_2);
		btn.getStyleClass().add(STYLE_1);
	    }
	});

	final StackPane root = new StackPane();
	root.getStylesheets().add(JFXSpinnerTest.class.getResource("custom.css").toExternalForm());
	root.getChildren().add(btn);
	primaryStage.setScene(new Scene(root, 300, 250));
	primaryStage.show();
    }
}
```

The custom.css:

```
.style1 {
    -jfx-toggle-color: #FFD600;
    -jfx-toggle-line-color: #FFEA00;
}

.style2 {
    -jfx-toggle-color: red;
    -jfx-toggle-line-color: blue;
}
```

Another issue is that when starting the test application the "focus circle" is visible
![image](https://user-images.githubusercontent.com/386593/35981552-ca5745fa-0ced-11e8-9165-1d0d79655ddd.png)

This was tested with version 1.11.1 & 8.01

**Comment by jfoenixadmin** [comment]
Hello,
Try using css pseudo classes ("selected") instead of changing the style class. 
Regarding the focus circle, it should be visible as the toggle button is focused.

**Comment by qtran** [comment]
Hi there,
The thing is this also does not work with custom pseudo classes. Imho this is still a bug
