### ISSUE TITLE
JFXToggleButton initial selection (before stage is shown) doesn't work 

### ISSUE THREAD

**Issue by salmonb** [jfoenixadmin/JFoenix#61]
Calling JFXToggleButton.setSelected(true) before stage.show() is not reflected in the UI (the button appears as not selected).

Reproducer: just add the initial selection in the ToggleDemoButton:
```
		JFXToggleButton toggleButton = new JFXToggleButton();
		toggleButton.setText("New Skin");
		toggleButton.setSelected(true); // <-- added line
		pane.getChildren().add(toggleButton);	
```

**Comment by aminabs** [comment]
Hi,
I've had the same issue. The bug is about updating the view. It is actually selected, but not shown correctly.

**Comment by jfoenixadmin** [comment]
fixed, thanks for pointing out the issue.
