### ISSUE TITLE
ComboBox - conflict setButtonCell & setPromptText

### ISSUE THREAD

**Issue by VENT0** [jfoenixadmin/JFoenix#610]
I'm using a JFoenix library and I have a problem with ComboBox.

When I want to setPromtText and setButtonCell - the text duplicates. I want to change the size of font on ButtonCell.

Here is my code:

```
@FXML
private JFXComboBox versionList;

@Override
public void initialize(URL location, ResourceBundle resources) {
    versionList.setPromptText("<");
    versionList.setButtonCell(new ListCell<String>() {
        @Override
        protected void updateItem(String version, boolean empty) {
            super.updateItem(version, empty);
            if (empty) {
                setText(null);
            } else {
                setText(version);
                setFont(Font.font(15));
            }
        }
    });
}
```

And as the result I get this:

![98c9159818](https://user-images.githubusercontent.com/13291664/36100948-9ab28b54-1010-11e8-9e54-a38561e3dd4c.jpg)

Or if promt text is "Select":
![b4f160f58b](https://user-images.githubusercontent.com/13291664/36100933-9347b77c-1010-11e8-9599-a6d8027345c2.jpg)

What I'm doing wrong? Thanks in advance.

**Comment by jfoenixadmin** [comment]
Hello,
Nothing wrong with your code, however to override the default java behavior we had to create another prompt text node, so changing the button cell might lead to some issues.

to fix your issue for you now you can use the following css instead of changing the button cell:
```
.jfx-combo-box .prompt-text,
.jfx-combo-box > .list-cell{
    -fx-font-size: 15;
}
```

Regards,
