### ISSUE TITLE
JFXPopUp - Can't take out background when listView is expanded

### ISSUE THREAD

**Issue by GonzaV** [jfoenixadmin/JFoenix#611]
Hi,

My goal is, when the button "+ opciones" (+ options) is clicked, the popup opens the listView with expanded labels to generate the effect of floating buttons, separated from each other. As you can see in the screenShot, the listView is expanded but i can't get the effect that im looking for because of the white popup background.

Thank you and sorry for my english.

![popup](https://user-images.githubusercontent.com/26558890/36108636-0da2b482-0ffc-11e8-8c0f-2f7f3e84379c.png)

**Comment by GonzaV** [comment]
Here is the code from the View

`@FXML
    public void exec(MouseEvent mouseEvent) {
        this.loadDateListView(listView);
        listView.setVerticalGap(10.0);
        listView.depthProperty().set(1);
        listView.setExpanded(true);

        JFXPopup p = new JFXPopup(listView);
        p.setStyle("-fx-background-color: transparent;");
        p.show(opcion, JFXPopup.PopupVPosition.TOP, JFXPopup.PopupHPosition.LEFT, -190.0,10.0 );
        listView.setVisible(true);

    }

    private void loadDateListView(JFXListView list)
    {
        for(int i=0; i<4;i++)
        {
            Label lbl = new Label("item" +i);
            lbl.setGraphic(new MaterialDesignIconView(MaterialDesignIcon.ACCOUNT_CIRCLE));
            list.getItems().add(lbl);
        }
    }`

And here the CSS Im using

`.jfx-list-view .scroll-bar:horizontal .track,
.jfx-list-view .scroll-bar:vertical .track{
    -fx-background-color:transparent;
    -fx-border-color:transparent;
    -fx-background-radius: 0em;
    -fx-border-radius:2em;
}

.jfx-list-view .scroll-bar:horizontal .increment-button ,
.jfx-list-view .scroll-bar:horizontal .decrement-button {
    -fx-background-color:transparent;
    -fx-background-radius: 0em;
    -fx-padding:0 0 10 0;
}

.jfx-list-view .scroll-bar:vertical .increment-button ,
.jfx-list-view .scroll-bar:vertical .decrement-button {
    -fx-background-color:transparent;
    -fx-background-radius: 0em;
    -fx-padding:0 10 0 0;
}
.jfx-list-view  .scroll-bar .increment-arrow,
.jfx-list-view  .scroll-bar .decrement-arrow{
    -fx-shape:" ";
    -fx-padding:0;
}

.jfx-list-view .scroll-bar:horizontal .thumb,
.jfx-list-view .scroll-bar:vertical .thumb {
    -fx-background-color:derive(black,90%);
    -fx-background-insets: 2, 0, 0;
    -fx-background-radius: 2em;
}


.list-cell:even, .list-cell:odd, .list-cell:empty{
    -fx-background-color: #FAFAFA;
}

.jfx-list-view{
    -fx-background-insets: 0;
    -fx-cell-vertical-margin: 10.0;
    -jfx-expanded:true;
}

.jfx-list-view {
    -fx-background-color:transparent;
    -fx-opacity: 0.0;
}`

**Comment by GonzaV** [comment]
Here is the code from the view

> .jfx-list-view .scroll-bar:horizontal .track,
.jfx-list-view .scroll-bar:vertical .track{
    -fx-background-color:transparent;
    -fx-border-color:transparent;
    -fx-background-radius: 0em;
    -fx-border-radius:2em;
}

.jfx-list-view .scroll-bar:horizontal .increment-button ,
.jfx-list-view .scroll-bar:horizontal .decrement-button {
    -fx-background-color:transparent;
    -fx-background-radius: 0em;
    -fx-padding:0 0 10 0;
}

.jfx-list-view .scroll-bar:vertical .increment-button ,
.jfx-list-view .scroll-bar:vertical .decrement-button {
    -fx-background-color:transparent;
    -fx-background-radius: 0em;
    -fx-padding:0 10 0 0;
}
.jfx-list-view  .scroll-bar .increment-arrow,
.jfx-list-view  .scroll-bar .decrement-arrow{
    -fx-shape:" ";
    -fx-padding:0;
}

.jfx-list-view .scroll-bar:horizontal .thumb,
.jfx-list-view .scroll-bar:vertical .thumb {
    -fx-background-color:derive(black,90%);
    -fx-background-insets: 2, 0, 0;
    -fx-background-radius: 2em;
}


.list-cell:even, .list-cell:odd, .list-cell:empty{
    -fx-background-color: #FAFAFA;
}

.jfx-list-view{
    -fx-background-insets: 0;
    -fx-cell-vertical-margin: 10.0;
    -jfx-expanded:true;
}

.jfx-list-view {
    -fx-background-color:transparent;
    -fx-opacity: 0.0;
}

**Comment by jfoenixadmin** [comment]
Hello,
The white background is caused by the popup.
try adding the following css:
```
.jfx-popup,
.jfx-popup .jfx-popup-container,
.jfx-popup .jfx-list-view{
    -fx-background-color:transparent;
}
```
