### ISSUE TITLE
JFX Spinner not spinning after porting to Java 9 and switching to JFoenix 9.2

### ISSUE THREAD

**Issue by CaptainParanoid** [jfoenixadmin/JFoenix#612]
No spinners in my project is working on porting my project to Java 9. However, when I port part back to Java 8(JFoenix 8.2) it's working again. 
![capture](https://user-images.githubusercontent.com/20284339/36118899-86d87c34-1064-11e8-9862-e76ce7da7bf7.PNG)

Sample code 

<?xml version="1.0" encoding="UTF-8"?>

<?import com.jfoenix.controls.JFXButton?>
<?import com.jfoenix.controls.JFXCheckBox?>
<?import com.jfoenix.controls.JFXPasswordField?>
<?import com.jfoenix.controls.JFXSpinner?>
<?import com.jfoenix.controls.JFXTextField?>
<?import javafx.geometry.Insets?>
<?import javafx.scene.control.Hyperlink?>
<?import javafx.scene.control.Label?>
<?import javafx.scene.control.Separator?>
<?import javafx.scene.image.Image?>
<?import javafx.scene.image.ImageView?>
<?import javafx.scene.layout.BorderPane?>
<?import javafx.scene.layout.HBox?>
<?import javafx.scene.layout.Region?>
<?import javafx.scene.layout.StackPane?>
<?import javafx.scene.layout.VBox?>
<?import javafx.scene.text.Font?>

<StackPane fx:id="stackPaneLogin" prefHeight="600.0" prefWidth="800.0" xmlns="http://javafx.com/javafx/8.0.141" xmlns:fx="http://javafx.com/fxml/1" fx:controller="OTTFind.Layout.Controllers.LoginScreen">
    <BorderPane prefHeight="200.0" prefWidth="200.0">
        <top>
            <HBox prefHeight="36.0" prefWidth="800.0" style="-fx-background-color: #F57768;" stylesheets="@../CSS/subTitleHbox.css" BorderPane.alignment="CENTER">
                <Region prefHeight="36.0" prefWidth="309.0" HBox.hgrow="ALWAYS" />
                <Label maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="16.0" prefWidth="120.0" text="Login to 123Find" textFill="#f2f2f2" HBox.hgrow="NEVER">
                    <padding>
                        <Insets left="1.0" />
                    </padding>
                    <HBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </HBox.margin>
                    <font>
                        <Font name="SansSerif Regular" size="14.0" />
                    </font>
                </Label>
                <Region prefHeight="36.0" prefWidth="304.0" HBox.hgrow="ALWAYS" />
            </HBox>
        </top>
        <center>
            <Separator orientation="VERTICAL" prefHeight="594.0" prefWidth="21.0" BorderPane.alignment="CENTER" />
        </center>
        <right>
            <VBox alignment="CENTER" prefHeight="600.0" prefWidth="417.0" BorderPane.alignment="CENTER">
                <JFXTextField fx:id="id" focusColor="#f57768" labelFloat="true" promptText="Email/Phone">
                    <VBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </VBox.margin>
                </JFXTextField>
                <JFXPasswordField fx:id="password" focusColor="#f57768" labelFloat="true" promptText="Password">
                    <VBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </VBox.margin>
                </JFXPasswordField>
                <JFXCheckBox fx:id="keepMeLoggedIn" checkedColor="#f57768" prefHeight="18.0" prefWidth="326.0" text="Keep me logged in">
                    <VBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </VBox.margin>
                </JFXCheckBox>
                <JFXButton onAction="#onClickLoginButton" prefHeight="25.0" prefWidth="95.0" stylesheets="@../CSS/button.css" text="Login">
                    <VBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </VBox.margin>
                </JFXButton>
                <Hyperlink onAction="#onActionForgotPassword" text="Forgot password?">
                    <VBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </VBox.margin>
                </Hyperlink>
                <Hyperlink onAction="#onActionRegister" text="New Customer ? Click here to register.">
                    <VBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </VBox.margin>
                </Hyperlink>
            </VBox>
        </right>
        <left>
            <VBox alignment="CENTER" prefHeight="564.0" prefWidth="367.0" BorderPane.alignment="CENTER">
                <ImageView fitHeight="81.0" fitWidth="312.0" pickOnBounds="true" preserveRatio="true" VBox.vgrow="NEVER">
                    <Image url="/Images/logo.png" />
                    <VBox.margin>
                        <Insets bottom="20.0" left="20.0" right="20.0" top="20.0" />
                    </VBox.margin>
                </ImageView>
            </VBox>
        </left>
    </BorderPane>
    <VBox alignment="CENTER" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="800.0" style="-fx-background-color: rgba(76, 76, 76, 0.2);" visible="false">
        <VBox alignment="CENTER" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="400.0" prefWidth="400.0" style="-fx-background-color: ffffff;">
            <Label text="Verify OTP" textFill="#757575">
                <font>
                    <Font name="SansSerif Bold" size="22.0" />
                </font>
            </Label>
            <HBox alignment="CENTER" prefHeight="55.0" prefWidth="400.0" VBox.vgrow="NEVER">
                <JFXPasswordField focusColor="#f57768" prefHeight="25.0" prefWidth="57.0">
                    <HBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </HBox.margin>
                </JFXPasswordField>
                <JFXPasswordField focusColor="#f57768" prefHeight="25.0" prefWidth="57.0">
                    <HBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </HBox.margin>
                </JFXPasswordField>
                <JFXPasswordField focusColor="#f57768" prefHeight="25.0" prefWidth="57.0">
                    <HBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </HBox.margin>
                </JFXPasswordField>
                <JFXPasswordField focusColor="#f57768" prefHeight="25.0" prefWidth="57.0">
                    <HBox.margin>
                        <Insets bottom="10.0" left="10.0" right="10.0" top="10.0" />
                    </HBox.margin>
                </JFXPasswordField>
            </HBox>
            <JFXPasswordField focusColor="#f57768" promptText="New Password">
                <VBox.margin>
                    <Insets bottom="20.0" left="50.0" right="50.0" top="20.0" />
                </VBox.margin>
            </JFXPasswordField>
            <JFXPasswordField focusColor="#f57768" promptText="Confirm New Password">
                <VBox.margin>
                    <Insets bottom="20.0" left="50.0" right="50.0" top="20.0" />
                </VBox.margin>
            </JFXPasswordField>
            <JFXButton stylesheets="@../CSS/button.css" text="Change password" />
        </VBox>
    </VBox>
    <HBox fx:id="spinnerHbox" alignment="CENTER" maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="600.0" prefWidth="800.0" style="-fx-background-color: rgba(76, 76, 76, 0.2);" visible="false">
        <JFXSpinner maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="50.0" prefWidth="50.0" radius="40.0" />
    </HBox>
</StackPane>

**Comment by jfoenixadmin** [comment]
I believe this is related to #645
