### ISSUE TITLE
Drop shadow from JFXDecorator?

### ISSUE THREAD

**Issue by alegd** [jfoenixadmin/JFoenix#614]
Hi, I would like to know if there is a way to make JFXDecorator to drop shadow like default JavaFX stage/window does? Thanks

**Comment by jfoenixadmin** [comment]
The drop shadow of the default JavaFX stage is caused by the operating system not java.
Currently you can't add drop shadow to JFXDecorator, feel free to add your own contribution to JFoenix :)

Regards,
