### ISSUE TITLE
Java 9 Compatibility

### ISSUE THREAD

**Issue by pdemanget** [jfoenixadmin/JFoenix#620]
Could you upgrade JFoenix version for java9 Compatibility?
            see bug: https://github.com/jfoenixadmin/JFoenix/issues/365

Of course, if you want to keep java8 compatibility, you have to maintain 2 branches.

Here is the patch that works for me in JDK9:
```


diff --git a/build.gradle b/build.gradle
index baadc1f..abb3e8a 100644
--- a/build.gradle
+++ b/build.gradle
@@ -19,7 +19,7 @@ jar {
 dependencies {
     testCompile group: 'junit', name: 'junit', version: '4.12'
     compile group: 'org.xerial', name: 'sqlite-jdbc', version: '3.7.2'
-    compile 'com.jfoenix:jfoenix:1.10.0'
+    compile 'com.jfoenix:jfoenix:9.0.2'
     compile 'de.jensd:fontawesomefx-fontawesome:4.7.0-5'
     compile 'com.gluonhq:charm-down-desktop:2.0.0'
     compile 'com.googlecode.json-simple:json-simple:1.1.1'

```

**Comment by jfoenixadmin** [comment]
Hello,
There are already 2 different jars of JFoenix for Java 8/9.
for Java 8 : versions are 8.*.*
and for Java 9 : versions are 9.*.*

Regards,

**Comment by pdemanget** [comment]
Oops, I wanted to submit this issue to another repository, which depends on this one.

Regards.

**Comment by RavneetSidhu** [comment]
Hello jfoenixadmin,
I just wanted to check if in future there will be just one jar supporting both java8/9. Is there any workaround or any future work planned?

Regards.
