### ISSUE TITLE
Can't build gradle project

### ISSUE THREAD

**Issue by joepol** [jfoenixadmin/JFoenix#626]
Hi, when tying to build the project I get this error 

> Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0

I tried to use the fix suggested here : [https://stackoverflow.com/questions/44578302/splitting-all-output-directories-in-gradle] but got the same error. 
Is this a problem with the build ?
Thanks.

**Comment by jfoenixadmin** [comment]
Make sure you are using gradlew command (gradle wrapper) to build JFoenix, instead of using gradle command (which uses the installed gradle on your os)

Regards,
