### ISSUE TITLE
JFXTreeTableView, textfield initialized with wrong value

### ISSUE THREAD

**Issue by deewx** [jfoenixadmin/JFoenix#630]
Hi.

I came across an issue that occurs while editing values in a JFXTreeTableView. As far as I can tell this only happens when editing in combination with scrolling.

To cause to problem you can open the JFoenix demo for JFXTreeTableView. Edit the First Name for all the rows that are visible at the start (4 of them), then scroll down a bit and just click on the First Name field on other rows. What happens is that they sometimes are initialized with the values that you edited on the top rows.

I was using version 1.8.0_162 of Java when i tested it.

**Comment by jfoenixadmin** [comment]
Thanks for pointing out the issue 👍, the fix will be included in the next release.
