### ISSUE TITLE
JFXRippler can not cover the whole area of a node

### ISSUE THREAD

**Issue by GreenLv** [jfoenixadmin/JFoenix#637]
For some big nodes, the effect is like:
![image](https://user-images.githubusercontent.com/12895960/37138863-ae88e964-22e6-11e8-8059-e46adb2b1793.png)
And changing mask types here is useless.

**Comment by jfoenixadmin** [comment]
Hello,
By default JFXRippler cover the whole node if it was triggered in the center of the node, to change this behavior you can extend JFXRippler and override the method `computeRippleRadius` to change the ripple radius.

Regards,

**Comment by GreenLv** [comment]
@jfoenixadmin Thanks~
