### ISSUE TITLE
JFXDrawerstack hides drawer problem

### ISSUE THREAD

**Issue by catalinbalteanu** [jfoenixadmin/JFoenix#64]
After hiding the drawer can't click on other components of the content, like the drawer is above them and invisible.

**Comment by jfoenixadmin** [comment]
can you provide a sample code?

**Comment by catalinbalteanu** [comment]
@FXML
JFXDrawersStack stack;

@FXML
public void onHamburger() {
    stack.toggle(rightDrawer);
}

@Override
public void initialize(URL location, ResourceBundle resources) {
    ...
    rightDrawer = new JFXDrawer();
    StackPane rightDrawerPane = new StackPane();
    JFXButton btn = new JFXButton("Right Content");
    rightDrawerPane.getChildren().add(btn);
    rightDrawer.setDirection(JFXDrawer.DrawerDirection.RIGHT);
    rightDrawer.setSidePane(rightDrawerPane);
    rightDrawer.setDefaultDrawerSize(200);
    rightDrawer.setOverLayVisible(true);
    rightDrawer.setResizableOnDrag(false);
    rightDrawer.setId("RIGHT");
    ...
}


![image](https://cloud.githubusercontent.com/assets/6420199/13840799/7a07f1a4-ec2d-11e5-826b-7ca64aca0023.png)
![image_1](https://cloud.githubusercontent.com/assets/6420199/13840806/8519e584-ec2d-11e5-8ca6-8c7a39fb6add.png)
![image_2](https://cloud.githubusercontent.com/assets/6420199/13840809/87d3e41e-ec2d-11e5-9c3c-893f9c37b196.png)
![image_3](https://cloud.githubusercontent.com/assets/6420199/13840810/898f6152-ec2d-11e5-8797-d7ef4d9e01c1.png)

**Comment by jfoenixadmin** [comment]
I was not able to reproduce, the issue might be related to your nodes structure. 
plz provide the full code that shows the issue.

**Comment by aminabs** [comment]
Hi,
I did find a workaround:
after hiding a drawer (by calling either the drawer.hide or the stack.toggle method, if you set default size to zero, it works fine. Do not forget to reset the default value while showing the drawer again later)

BTW,
With complex structures, the issue appears and it's fairly time consuming to create a demo in which the issue appears. I also created a complex user interface in which the issue pops out. I can't send the code since it's a private one; I can't simply reproduce it in another simple demo project.

**Comment by catalinbalteanu** [comment]
[demo.zip](https://github.com/jfoenixadmin/JFoenix/files/180209/demo.zip)

what I am doing wrong ?

**Comment by catalinbalteanu** [comment]
I managed to fix the issue by removing drawerstack with a stackpane and bring drawer to front before showing and send it back the stack after hide.

**Comment by jfoenixadmin** [comment]
please notice that JFXDrawersStack is designed to be used when multiple drawers are needed, otherwise you can use JFXDrawer directly.

**Comment by jfoenixadmin** [comment]
I checked your application, the issue is fxml compatibility. i fixed the issue, you can pull the latest version of code and test. 

**Note:** that the default tag of JFXDrawersStack is content, thus in order for it to work you need **remove the children** tags after or use content tag instead
```html
<JFXDrawersStack fx:id="stack" BorderPane.alignment="CENTER">
       <BorderPane ...>
</JFXDrawersStack>
