### ISSUE TITLE
How to know is the dialog showing or not? 

### ISSUE THREAD

**Issue by Dooardarshan** [jfoenixadmin/JFoenix#641]
Hi. i was  wondering is there a method to get a boolean value like isShowing() or something to get is it showing or not, isVisible method is kinda not working. Thanx.

**Comment by jfoenixadmin** [comment]
Hello,
You can add event handler to listen to dialog open/close events by using the methods `setOnDialogOpened` and `setOnDialogClosed` in JFXDialog.

Regards,
