### ISSUE TITLE
JFXAutoCompletePopup error showing with JFXListCell

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#644]
Hello, I am starting to use the JFXAutoCompletePopup component, but I am presenting a problem, this is the code I have:

```
JFXAutoCompletePopup<String> autoCompletePopup = new JFXAutoCompletePopup<>();
autoCompletePopup.getSuggestions().addAll(listItems);
autoCompletePopup.setSelectionHandler(event -> {
    System.out.println("Selected: "+event.getObject());
});

// This produce the error
autoCompletePopup.setSuggestionsCellFactory(param -> {
            return new JFXListCell<>();
});
txtAutocomplete.textProperty().addListener(observable -> {
    autoCompletePopup.filter(item -> item.toLowerCase().contains(editor.getText().toLowerCase()));
    if (autoCompletePopup.getFilteredSuggestions().isEmpty()) {
        autoCompletePopup.hide();
    } else {
        autoCompletePopup.show(txtAutocomplete);
    }
});
```

And my view looks like this:

![githubautocomplete](https://user-images.githubusercontent.com/22163898/37259041-17514508-254f-11e8-935e-958a91548007.png)

You do not see the items completely when I add `autoCompletePopup.setSuggestionsCellFactory(param -> new JFXListCell<>());`

How could I solve this problem? Thanks :)

**Comment by jfoenixadmin** [comment]
Hello,
Currently autocomplete list has a hard coded fixed cell size of 24px, to fix this you can add the following css:

```
.autocomplete-popup .autocomplete-list {
    -fx-fixed-cell-size: 40;
}
```

Regards,

**Comment by TioCoding** [comment]
Thanks, this worked to solve the problem, but I have two more questions about the JFXAutoCompletePopup.

1. If I have a list of an object, for example `new JFXAutoCompletePopup <Client> ()`. How do I show a property of my object and not the toString () method?

![autocomplete-issue](https://user-images.githubusercontent.com/22163898/37384657-16bf217a-271e-11e8-8b97-211d02a30efe.png)

2.How do I configure the width of the `JFXAutoCompletePopup`, so it is the same as the Editor. I am testing with `autoCompletePopup.prefWidthProperty().bindBidirectional(editor.prefWidthProperty())`, but it does not work, any solution for this?

**Comment by jfoenixadmin** [comment]
Hello,
1. you can customize the cell by changing the cell factory and overriding the method updateItem in JFXlistCell.

2. currently you can only change the prefWidth of the list view through css, will update the skin and bind the list width properties to auto complete popup. so your binding should work ( in the next release).

Regards,

**Comment by TioCoding** [comment]
Thanks for the información, regards. :grin:
