### ISSUE TITLE
JFoenix flickers randomly on Windows (using JFXTreeTableView & JFXButton)

### ISSUE THREAD

**Issue by Sieu** [jfoenixadmin/JFoenix#646]
Currently the application that I have is very large, but the issue I have can be replicated if you make a new stage/scene with a JFXTreeTableView, and then relaunch the client 5-10 times until it starts flickering (on windows), when you click on the tabs, it'll turn white, and ultimately turn the whole tabpane white for a good 10 seconds until it returns back to normal. However, once you try to change tabs, it glitches up again making it unusable until you restart the application a few times.

What's weird is this only happens on Windows, and I can't seem to replicate it on my Mac.

I'm using JDK 8u152 currently.

Also I'm pretty sure this isn't affecting it, but if I put a snackbar, when the UI glitch happens, the snackbar goes from the bottom of the frame to the top left.And every animation from any JFoenix module (JFXButton, Tabs, etc), all have white when their animations go off.

I've tried to turn off GPU acceleration with the flags, but it didn't work.

I'm wondering if this is a known issue? Any work arounds or fixes?

https://i.stack.imgur.com/BOk6K.jpg

**Comment by Sieu** [comment]
Upon further testing, I removed everything from my initialize function in the controller, and JFXTabPane seems to have tabs be flickering/turn white and it causes all the other JFX elements to be white when I hover over it or click it.

**Comment by jfoenixadmin** [comment]
Hello,
Can you provide a SSCCE demonstrating the issue?

**Comment by jfoenixadmin** [comment]
@Sieu can you edit the title to be more related to JFXTabPane instead of JFXTreeTableView
