### ISSUE TITLE
Css reference

### ISSUE THREAD

**Issue by Natreve** [jfoenixadmin/JFoenix#65]
Hi again, where can I find a reference to the css attributes that you use to customize javafx? I'm finding it difficult to format elements the same way they are presented on the website.

**Comment by jfoenixadmin** [comment]
check <a href="http://fxexperience.com/scenic-view/">Scenic View</a> it will help you to find the css style for each node in the scene.

**Comment by Natreve** [comment]
Thanks, can I have the tab background css too? I can't seem to change it from it's default blue

**Comment by jfoenixadmin** [comment]
you can use the following css style:
<pre>
.jfx-tab-pane .tab-header-background{
	-fx-background-color:RED;
}
</pre>

**Comment by Sherri96** [comment]
Hello! can you please tell me how do i create a menu button with jfoenix style?
