### ISSUE TITLE
Datepicker jfoenix error

### ISSUE THREAD

**Issue by brunotkk** [jfoenixadmin/JFoenix#650]
When I use the datepicker and I compile the software it start to grow horizontally infinitly

**Comment by jfoenixadmin** [comment]
can you provide a SSCCE demonstrating the issue?

**Comment by lenikhilsingh** [comment]
in jfoenix datepicker, how can i style the arrow button in the dropdown.
Bascially I want to change the background color of those 2 arrow buttons, with CSS.
![12](https://user-images.githubusercontent.com/30202672/38659357-d19145de-3e46-11e8-8fd2-b90c5b945aa2.png)

**Comment by jfoenixadmin** [comment]
you can change it using the following css:
```
.date-picker-popup .right-button,
.date-picker-popup .left-button{
    -fx-background-color: RED;
}
```
Regards,
