### ISSUE TITLE
jfxsmoothscroll gives false Vvalues 

### ISSUE THREAD

**Issue by Dooardarshan** [jfoenixadmin/JFoenix#651]
i have been playing with scroll pane and i noticed that without smoothscroll calling i get clear values for vvalues (getVmin, getVMax) and setVvalue.  but when i call smoothscroll results are buggy.

**Comment by shadskii** [comment]
What do you mean by buggy? Can you provide sample output?

**Comment by jfoenixadmin** [comment]
will close this issue since @Dooardarshan didn't respond
