### ISSUE TITLE
JFXChipView is not available for jfoenix8.1 jar file

### ISSUE THREAD

**Issue by XlintXms** [jfoenixadmin/JFoenix#653]
![jfx](https://user-images.githubusercontent.com/20143684/37625847-e0bfdefc-2bcd-11e8-9929-7c25618a4da9.png)
When i try using JFXChipView , i find that is not available in my jar !

**Comment by jfoenixadmin** [comment]
JFXChipView has been added recently to JFoenix, so try using the latest JFoenix version.

Regards,

**Comment by XlintXms** [comment]
I downloaded the latest version yesterday !

**Comment by elgaale** [comment]
Me too, I have the same problem, this class does't exist in jfoenix-8.0.1 , please try to add this class to 8.0 jar.

**Comment by XlintXms** [comment]
It is available in 8.0.3
