### ISSUE TITLE
JFXTreeTableView destroys selection on sort

### ISSUE THREAD

**Issue by HPGlade** [jfoenixadmin/JFoenix#661]
To reproduce:

    @FXML private lateinit var treeView: JFXTreeTableView<Entry>

    // During init:
    treeView.selectionModel.selectionMode = SelectionMode.MULTIPLE

    // Later, after user selects certain rows, and data has been added so the content
    // must be sorted again
    treeView.sort()

This happens because [`JFXTreeTableView.java`](https://github.com/jfoenixadmin/JFoenix/blob/master/jfoenix/src/main/java/com/jfoenix/controls/JFXTreeTableView.java#L172) throws away the current selection, replacing it with a selection on the first row.

Is there a better way to request sort while retaining the current set of selected items?

**Comment by HPGlade** [comment]
Here is my current workaround: (apologies for Kotlin but Java would be twice as long here)

```
val selection = treeView.selectionModel.selectedItems.toList()
treeView.sort() // Destroys selection!
// Re-apply selection
val indices = selection.map {
    treeView.root.children.indexOf(it)
}
treeView.selectionModel.clearSelection()
if (indices.isNotEmpty()) {
    treeView.selectionModel.selectIndices(indices[0], *(indices.drop(1).toIntArray()))
}
```

**Comment by jfoenixadmin** [comment]
Currently we are clearing the selection because in some cases it's causing infinite loops. this issue is related to Java, (once it's been fixed will revert clearing the selection)

Regards,
