### ISSUE TITLE
CSS JFXTreeTableView - selected row color unfocused

### ISSUE THREAD

**Issue by TioCoding** [jfoenixadmin/JFoenix#663]
Hi, how can I change the selected row of my JFXTreeTableView when I have it out of focus?

- Color with focus on the JFXTreeTableView (It's okay)
![focus-brow-table](https://user-images.githubusercontent.com/22163898/38170160-54fbdb6c-3543-11e8-8e75-77988e27e6ae.png)

- Color with unfocus on the JFXTreeTableView (color for default, im need change this color)
![un-focus](https://user-images.githubusercontent.com/22163898/38170149-dbae06ea-3542-11e8-868b-559cfad1575e.png)

Thanks, regards :)

**Comment by jfoenixadmin** [comment]
Hello, 
you can use the following css:
```
.jfx-tree-table-view > .virtual-flow > .clipped-container > .sheet > .tree-table-row-cell:filled:selected {
    -fx-background-color: RED;
}
```
Regards,
