### ISSUE TITLE
JFXButton css -fx-rippler-fill not work

### ISSUE THREAD

**Issue by RodrigoSantiago** [jfoenixadmin/JFoenix#67]
JFXButton ripple is always painted using -fx-text-fill .

**Comment by jfoenixadmin** [comment]
Note that in oder to user the css property -fx-rippler-fill, you need to specify the rippler css class.
for example:
<pre>
.jfx-button .jfx-rippler{
      -fx-rippler-fill:RED;
}
</pre>

**Comment by iqbal98** [comment]
@jfoenixadmin I used `jfx-rippler-fill` instead of `fx` and it is working for me.

**Comment by haftado3** [comment]
for me too works with`jfx-rippler-fill`
