### ISSUE TITLE
About JFXCheckBox!

### ISSUE THREAD

**Issue by 8824PPZ** [jfoenixadmin/JFoenix#670]
Hello, God! When I use JFXCheckBox, I have such a problem.

When I add JFXCheckBox to the table, then I use a List to store them, and then when I click on a JFXButton, I traverse the List so that all the JFXCheckBox can be checked, but in fact, some of the JFXCheckBox can't pick it up.
This is my JFXTreeTableColumn Code:

`JFXTreeTableColumn<Controller, Boolean> checkList = new JFXTreeTableColumn<>("#");

		checkList.setPrefWidth(150);
		checkList.setCellFactory((col) -> {
			TreeTableCell<Controller, Boolean> cell = new TreeTableCell<Controller, Boolean>() {
				@Override
				public void updateItem(Boolean item, boolean empty) {
					super.updateItem(item, empty);
					this.setText(null);
					this.setGraphic(null);

					if (!empty) {
						JFXCheckBox checkBox = new JFXCheckBox();
						checkBoxList.add(checkBox);
						checkBox.setStyle("-jfx-checked-color: RED;-jfx-unchecked-color: BLACK;");
						this.setGraphic(checkBox);
						checkBox.selectedProperty().addListener((obVal, oldVal, newVal) -> {
							if (newVal) {
								
							}

						});
					}
				}

			};
			return cell;
		});`

This is my JFXButton Code:

` JFXButton selectAll = new JFXButton("Select All");
        selectAll.setStyle("-fx-padding: 0.5em 0.4em; -fx-font-size: 15px;"
				+ " -jfx-button-type: RAISED;-fx-background-color: rgb(77,102,204);"
				+ "-fx-pref-width: 100;-fx-text-fill: WHITE;");
        
        selectAll.setOnAction(new EventHandler<ActionEvent>() {
			
			@Override
			public void handle(ActionEvent event) {
				
				int num = checkBoxList.size();
				for (int i = 0;i<num;i++) {
					
					checkBoxList.get(i).setSelected(true);
					System.out.println(checkBoxList.get(i).isSelected());
					System.out.println(checkBoxList.get(i));
				}
			}
		});`

If you see, I hope you can give me a solution as soon as possible, because it is very important for me, thank you.

**Comment by jfoenixadmin** [comment]
will close this issue as it's not related to JFoeinx development, also this issue is reproducible using Java TreeTableView and CheckBox.
Regards,
