### ISSUE TITLE
JFXComboBox scroll to selected item

### ISSUE THREAD

**Issue by mdelloso** [jfoenixadmin/JFoenix#673]
Hello,

Is it possible to scroll to selected item in JFXComboBox? If I run `comboBox.getSelectionModel().select(i);` the item is selected and focused but the scroll bar doesn't move to that item.

Thanks, Matías.

**Comment by jfoenixadmin** [comment]
Hello, 
I believe this behavior is inherited from Java ComboBox control. To achieve this behavior, the combo box list view skin needs to be updated. Feel free to add your own contribution to JFoenix. 
Regards,
