### ISSUE TITLE
Changing color of selected tab line via CSS

### ISSUE THREAD

**Issue by pixelducky** [jfoenixadmin/JFoenix#68]
Hi devs,

I can't seem to change the color of the selected tab line that is sitting in the header's region of the TabPane. I have dig through the source and found the id for the selected tab line in the `JFXTabPaneSkin` class - `.tab-selected-line`

Below is a snippet of CSS code that I have tried but didn't work:

`.jfx-tab-pane .tab-header-area .headers-region .tab-selected-line {
	-fx-background-color: #FF5252
}`

Could you recommend a better approach to achieve this? Hope to hear from you. Thanks.

**Comment by pixelducky** [comment]
Okay, I have found the solution to this. I had to access the `-fx-stroke` property since `Line` is a subclass of `Shape`.

```
.jfx-tab-pane .tab-header-area .headers-region .tab-selected-line {
	-fx-stroke: #FF5252
}
```

**Comment by SylvainAssemat** [comment]
I try to change this color line too

My CSS working
![test](https://user-images.githubusercontent.com/5692760/27191100-07820abc-51f7-11e7-958e-380bf1e781d9.png)


```
.jfx-tab-pane .tab-header-area .headers-region .tab-selected-line {
    -fx-background-color: red;
}
```
