### ISSUE TITLE
Is it possible to load fontawesome from FXML with SVGGlyph

### ISSUE THREAD

**Issue by Gabirel** [jfoenixadmin/JFoenix#682]
I saw this: https://github.com/jfoenixadmin/JFoenix/issues/169#issuecomment-251038144.

I want to load an icon from FXML instead of from Controller Class. 

But you're using `<FontawesomeIconView>` in your main demo.

So is it possible to do that without adding `Fontawesomefx`?

**Comment by jfoenixadmin** [comment]
Unlike fontawesome, SVGGlyph requires the svg path of the icon. So no, you can not use SVGGlyph to load font awesome icons. For example, creating a decrement arrow using SVGGlyph:
`SVGGlyph glyph = new SVGGlyph("M298 598l214-214 214 214h-428z");`

 Currently you can create SVGGlyph in FXML, however the svg path should be set through css using "_-fx-shape_" property. Will update SVGGlyph to allow setting the path in FXML too.
