### ISSUE TITLE
using the datepicker

### ISSUE THREAD

**Issue by fredericoregateiro** [jfoenixadmin/JFoenix#683]
I'm trying to use the JFXDatePicker, but im missing something, the year and selected date labels are missing.
The print of my project: 
![erro](https://user-images.githubusercontent.com/6304701/39090107-5e56b4a8-45cd-11e8-89fc-9d1392aaf851.png)

I'm using jfoenix-8.0.1 and jdk1.8.0_161

**Comment by jfoenixadmin** [comment]
can you provide more details about the issue? 
any exceptions in the console? 
does the issue persist even without adding any css files to the scene?

**Comment by fredericoregateiro** [comment]
No exceptions in the console and the issue remains even if i remove all css files
I'll try to replicate on a smaller project

**Comment by fredericoregateiro** [comment]
The code that was making this on my app:

`Application.setUserAgentStylesheet(Application.STYLESHEET_CASPIAN);`

**Comment by jfoenixadmin** [comment]
Well applying caspian css might cause some styling issues, I don't see a reason to use it instead of modena. Especially knowing your targeting material design since you are using JFoenix :)

Anyway I'll give it a shot and track it down.

Regards,

**Comment by fredericoregateiro** [comment]
Thanks,
For me it's not a problem anymore.
It was a line that was left forgotten, and we don´t use it.
