### ISSUE TITLE
Default drawer size value doesn't exist in FXML

### ISSUE THREAD

**Issue by Gabirel** [jfoenixadmin/JFoenix#685]
this is in Scene Builder
![image](https://user-images.githubusercontent.com/12933851/39174666-f1714ad2-47da-11e8-97e6-048cfd29c1d3.png)

But I couldn't check that value in my FXML file.
```fxml
<JFXDrawer fx:id="drawer" direction="RIGHT" layoutX="549.0" layoutY="9.0" resizableOnDrag="true"
                   resizeContent="true" styleClass="jfx-drawer" stylesheets="@css/main.css"/>
```

Is it a bug or just a not-very-good feature?

**Comment by jfoenixadmin** [comment]
you can set default drawer size in fxml by adding the following attribute
`defaultDrawerSize="100"`

if this fxml was generated using Scene Builder, then I recommend opening an issue for Scene Builder as it's not related to JFoenix.
