### ISSUE TITLE
Unable to resize drawer to fit the content

### ISSUE THREAD

**Issue by Gabirel** [jfoenixadmin/JFoenix#686]
Code in `initialize()`:

```kotlin
val drawerPane = drawStackPaneController.drawerStackPane
drawer.defaultDrawerSize = 100.0
drawer.setContent(this.drawerStack)
drawer.setSidePane(drawerPane)
```

```fxml
<JFXDrawer fx:id="drawer" defaultDrawerSize="0.0" direction="RIGHT" layoutX="549.0" layoutY="9.0"
 overLayVisible="false" resizableOnDrag="true" resizeContent="true" styleClass="jfx-drawer"
 stylesheets="@css/jfoenix-main-demo.css"/>
```

![image](https://user-images.githubusercontent.com/12933851/39176885-7f775d76-47e0-11e8-8f38-e42e2924725b.png)

I can only resize the drawer to fit it after dragging it mannually. So, what exactly should I do to make it resizeable? Thanks in advance

**Comment by jfoenixadmin** [comment]
can you provide SSCCE for this issue?

**Comment by Gabirel** [comment]
Here's the demo here. Part of codes are written in Kotlin. But I think that's acceptable
[JFeonixDrawerDemo.zip](https://github.com/jfoenixadmin/JFoenix/files/1942315/JFeonixDrawerDemo.zip)

**Comment by jfoenixadmin** [comment]
Hello, 
Well you are kind of misusing the JFXDrawer, you can check JFoenix main demo for a good example on JFXDrawer. Will close this issue as it's not related to JFoeinx development.

Regards,

**Comment by Gabirel** [comment]
I'm misusing？Why did you say that？
Yes, I've already checked your `demo/components/DrawerDemo`. My current code is based on your demo. Can you point out why I'm misusing please? That would be really helpful
