### ISSUE TITLE
JFXDIALOG :CLOSED event does not handle the code

### ISSUE THREAD

**Issue by XlintXms** [jfoenixadmin/JFoenix#688]
I'm trying to handle differents methods when the JFXDialog is closing but ,CLOSE event type does not give me any response : 
This is my code : 
  SharedRegister.getDialog().addEventHandler(JFXDialogEvent.CLOSED, eventHandler -> {
            infoPopOver.hide();
            System.out.println("closed");
        });
  SharedRegister.dialog.addEventHandler(JFXDialogEvent.CLOSED, eventHandler -> {
            warningPopOver.hide();
            System.out.println("closed");
        });
  SharedRegister.dialog.addEventHandler(JFXDialogEvent.CLOSED, eventHandler -> {
            errorPopOver.hide();
            System.out.println("closed");
        });

**Comment by shadskii** [comment]
Try using the onDialogClosedProperty instead. It defines a function that will be called whenever the dialog has been closed and will fire only after the close animation has finished. I believe it should give you the behavior you're looking for.
```java
dialog.setOnDialogClosed(closeEvent -> {
     System.out.println("I am closed!");
});
```

**Comment by XlintXms** [comment]
@shadskii ,the problem I did not find onDialogClosedProperty for adding many listeners in different locations, ``
dialog.setOnDialogClosed(closeEvent -> {
     System.out.println("I am closed!");
});
`` With setOnDialogClosed() ,it is a methods allows to add only one event ,I mean if I want to change the event I need to remove the old and adding the new ,but it is not a good idea ,I'm looking for onClosedProperty() but it seems ,it is not available for Jar 8.1

**Comment by shadskii** [comment]
Ah I understand your problem now. JFXDialog's onDialogClosedProperty does not exactly support what you are trying to do but you can achieve the desired behavior by using a BooleanProperty to represent the state of the dialog and adding listeners to it instead.
```java
BooleanProperty dialogState = new SimpleBooleanProperty(false);
dialog.setOnDialogOpened(openEvent -> dialogState.set(true));
dialog.setOnDialogClosed(closeEvent -> dialogState.set(false));

dialogState.addListener((observable, oldValue, newValue) ->  {
     if(newValue){
          System.out.println("Dialog has been opened!");
     }else{
          System.out.println("Dialog has been closed!");
     }
});
```
Hope this helps!

Cheers

**Comment by jfoenixadmin** [comment]
@XlintXms thanks for pointing out the issue 👍 , will update JFXDialog and push the fix. so it will be included in the next release.

Regards,
