### ISSUE TITLE
Upgrade project dependencies

### ISSUE THREAD

**Issue by aalmiray** [jfoenixadmin/JFoenix#69]
The project defines requires outdated versions of DataFX and FontAwesomeFX. The API of FontAwesomeFX has changed too.

    compile 'de.jensd:fontawesomefx:8.9'
    compile 'io.datafx:core:8.0.7'
    compile 'io.datafx:flow:8.0.7'

**Comment by jfoenixadmin** [comment]
true, these are the demo dependencies (only used in demo). it's not included in JFoenix library.

**Comment by aalmiray** [comment]
FontawesomeFX is actually used by the libray. DataFX is only used by the demo application.
Please reconsider upgrading FontawesomeFx at the very least.

**Comment by aalmiray** [comment]
My mistake. I see that the latest version in master no longer requires `fontawesomefx` in the library. Although there's still a name reference to it (`awsomeIcon`).
