### ISSUE TITLE
JFoenix 8 doesn't have JFXbutton

### ISSUE THREAD

**Issue by PaperKites** [jfoenixadmin/JFoenix#695]
I imported JFoenix 8 but it doesn't have JFXbutton so I tried to import JFoenix 9 because it has JFXbutton but netbeans couldn't compile it because i have java 8.

**Comment by jfoenixadmin** [comment]
both have JFXButton, this issue seems related to your project class path in netbeans.
will close this issue as it's not related to JFoenix development.

Regards,
