### ISSUE TITLE
ClassNotFoundException with Java 8/JFoenix8 and Java 9/JFoenix9

### ISSUE THREAD

**Issue by pjp94** [jfoenixadmin/JFoenix#697]
When I build and run my app through the IDE it works fine, but if I build a jar and try to run it through the command line, I get an exception:

> java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
>         at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
> Caused by: java.lang.RuntimeException: Exception in Application start method
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
>         at java.base/java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/StyleConverterImpl
>         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
>         at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
>         at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
>         at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
>         at com.jfoenix.controls.JFXButton$StyleableProperties.<clinit>(JFXButton.java:196)
>         at com.jfoenix.controls.JFXButton.<init>(JFXButton.java:156)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
>         at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
>         at java.base/java.lang.Class.newInstance(Unknown Source)
>         at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(Unknown Source)
>         at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
>         at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
>         at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
>         at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
>         at javafx.fxml/javafx.fxml.FXMLLoader.load(Unknown Source)
>         at com.configurator.Configurator.start(Configurator.java:18)
>         at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
>         at java.base/java.security.AccessController.doPrivileged(Native Method)
>         at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
>         at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
>         at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
>         at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
>         ... 1 more
> Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.StyleConverterImpl
>         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
>         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
>         at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
>         ... 32 more

I've been using Java 8 with JFoenix 8.0.1. I looked at the other issues and it was recommended to use JFoenix 9.0.1 if using Java 9, but I still get the same error.

**Comment by jfoenixadmin** [comment]
it seems your JAVA_HOME is different than the one used in your IDE, make sure you are using compatible version of Java/JFoenix. will close the issue as it's not related to JFoenix development.

Regards,
