### ISSUE TITLE
Support TreeView

### ISSUE THREAD

**Issue by aalmiray** [jfoenixadmin/JFoenix#70]
Sadly there's no explicit support for `TreeView` as there is for `ListView` and `TreeTableView`. It would be great to have this widget integrated too :smile:

**Comment by anidotnet** [comment]
A material tree view like below would be awesome

![image](https://cloud.githubusercontent.com/assets/696662/22059788/4fb83d10-dd94-11e6-8702-2dd3af32e521.png)
