### ISSUE TITLE
Styling Dialog

### ISSUE THREAD

**Issue by cinder92** [jfoenixadmin/JFoenix#703]
Hello thanks for this amazing repo, i have 2 questions,

1 .- Its possible to add styles in Dialog via programming? i mean ...

```
        JFXDialog dialog = new JFXDialog();
        dialog.setStyle("-jfx-padding:20px;");
        dialog.show(rootStackPane);
```

2 .- Its possible to set a heading in Dialog via programming? like the examples or i need to make a template in FXML?

thanks

**Comment by jfoenixadmin** [comment]
Hello,
Well JFXDialog has a content node, you can style it from code or load it using FXML. You need to style the dialog content not the dialog itself.

In demo, we are using JFXDialogLayout as the JFXDialog content node which has material design dialog styling. However you can create your own content node and use it inside JFXDialog.

Regards,
