### ISSUE TITLE
JFXDatePicker floating text

### ISSUE THREAD

**Issue by myshasis** [jfoenixadmin/JFoenix#704]
Hello, I have below issue with datepicket floating text with java version "10.0.1" 2018-04-17 ... I'm using JFoneix 9.0.4 jar version.
If I set date via setValue(localdate) prompt text ignores nonempty text field.
After mouse click on text field with date it started working normally and prompt text floats above text field. Could you please check it?
![issue](https://user-images.githubusercontent.com/24541167/39773877-93642250-52f9-11e8-89dc-80d2a1c26c89.png)

**Comment by jfoenixadmin** [comment]
Hello,
I wasn't able to reproduce using the JFoenix 9.0.4, is there any exception in the console? can you provide a SSCCE for this issue?

Regards,

**Comment by ramprajapat94** [comment]
Hello, This issue even exists in the earlier versions of foenix and with other components as well like JFXComboBox. Many times they ignores non-empty component but once we click on them, its starts working fine.

**Comment by myshasis** [comment]
Hello, here is code. I'm working with jfoenix-9.0.4.jar and jdk-10.0.1. I have added 2 datepickers. First is from fxml where the value is ignored until I click on the datepickers textfield and second is added from code where datepicker floating text works but little bit strange as prompttext floats to high, this one is corrected also after I manually click on datepickers textfield.

Main.java

    @Override
    public void start(Stage primaryStage) throws Exception{
        FXMLLoader loader = new FXMLLoader(getClass().getResource("sample.fxml"));
        Parent root = loader.load();
        Scene scene = new Scene(root, 600, 400);
        scene.getStylesheets().add(Main.class.getResource("sample.css").toExternalForm());
        primaryStage.setScene(scene);
        JFXDatePicker pickerfromfxml = (JFXDatePicker)loader.getNamespace().get("pickerfromfxml");
        AnchorPane anchorfromxml = (AnchorPane)loader.getNamespace().get("anchorfromxml");

        JFXDatePicker pickerfromcode = new JFXDatePicker();
        pickerfromcode.setLayoutX(54.0);
        pickerfromcode.setLayoutY(282.0);
        pickerfromcode.setPromptText("test prompt");
        pickerfromcode.setOverLay(true);

        anchorfromxml.getChildren().add(pickerfromcode);
        LocalDate localDate = LocalDate.now();
        pickerfromfxml.setValue(localDate);
        pickerfromcode.setValue(localDate);
        primaryStage.show();
    }



    public static void main(String[] args) {
        launch(args);
    }

sample.css
`.jfx-date-picker > .jfx-text-field {
    -jfx-label-float: true;
}
`

sample.fxml
add datepicker with following:
`JFXDatePicker fx:id="pickerfromfxml" layoutX="54.0" layoutY="179.0" overLay="true" prefHeight="27.0" prefWidth="283.0" promptText="Initial Date"`
Full image of sample.fxml, can't it paste here
![fxmlfile](https://user-images.githubusercontent.com/24541167/39813233-e377df0c-538f-11e8-873e-5b575154b655.png)

This is how it looks right after program start
![beforetextfieldclick](https://user-images.githubusercontent.com/24541167/39813050-3e53aa38-538f-11e8-8312-7df35e278301.png)

This is how it looks after manually click on datapickers text fields
![aftertextfieldclick](https://user-images.githubusercontent.com/24541167/39813116-7783b352-538f-11e8-8b5d-0a1659ae8053.png)

**Comment by MHTaleb** [comment]
is there any fox to this yet ?

**Comment by jfoenixadmin** [comment]
It's been fixed however not released yet, you can fetch JFoenix repo and build it to get the fix or wait for the next release.

Regards,
