### ISSUE TITLE
JavaFx JFXComboBox

### ISSUE THREAD

**Issue by giulian96** [jfoenixadmin/JFoenix#705]
Hi, when i try to insert my data from Combobox into database it gives me this error: java.lang.ClassCastException: com.sun.javafx.scene.control.skin.ComboBoxPopupControl$FakeFocusTextField cannot be cast to com.jfoenix.controls.JFXTextField

..

**Comment by jfoenixadmin** [comment]
Hello, can you provide a SSCCE demonstrating the issue?

**Comment by jfoenixadmin** [comment]
will close this issue as @giulian96 didn't reply
