### ISSUE TITLE
Vertical JFXTabPane shows rendering artifacts

### ISSUE THREAD

**Issue by aalmiray** [jfoenixadmin/JFoenix#71]
Configuring a `JFXTabPane` with `side="Side.LEFT"` results in unaligned shadows. The yellow band (with default jfoenix css applied) also gives the wrong impression that the selected tab is actually unselected.

**Comment by RAnders00** [comment]
Maybe you could attach a screenshot?

**Comment by aalmiray** [comment]
Sure, here goes. The tab with the `edit` icon is the active one, whereas the `play` tab is the unselected one.

<img width="176" alt="jfoenix-tabpane" src="https://cloud.githubusercontent.com/assets/13969/14024449/5e2476b2-f1e9-11e5-9ff3-ace5d633598f.png">

**Comment by jfoenixadmin** [comment]
well,it's not supported yet. this configuration is disabled in the latest version of JFoenix (it has no effect on the JFXTabPane). so it's always on the top.

**Comment by aalmiray** [comment]
Was this issue closed because it's not supported? If so then this would become a feature request, rather than a bug and should stay open.

If the issue was closed because the feature is not supported and never will then it's OK to close IMHO.

**Comment by yogi0823** [comment]
change slider color on selected tab and also change the background color of tab pane by background like this
![required](https://cloud.githubusercontent.com/assets/7446446/14488884/f35e0af6-0187-11e6-9275-bb1ffbf51682.PNG)
