### ISSUE TITLE
jfoenix not working as artifect

### ISSUE THREAD

**Issue by asfand10** [jfoenixadmin/JFoenix#710]
Hi, I am using eclipse and javafx scene builder. Recently I have created a scene and used jfoenix in it. Anyways when I run it, exception is thrown.
This is my main class.
`package application;
	
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;

public class Main extends Application {
	@Override
	public void start(Stage primaryStage) {
		try{  
		       Parent root = FXMLLoader.load(getClass().getResource("\\application\\login.fxml"));
		       Scene scene = new Scene(root);
		       //scene.getStylesheets().add(getClass().getResource("Style.css").toExternalForm());
		       
		        primaryStage.initStyle(StageStyle.UNDECORATED);
		       primaryStage.setScene(scene);
		       primaryStage.show();
		       
		       
		       
		    }
		       catch(Exception e){
		           e.printStackTrace();
		       }
		    }
	
	public static void main(String[] args) {
		launch(args);
		
	}
}
error
`java.lang.NullPointerException: Location is required.
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(Unknown Source)
	at application.Main.start(Main.java:16)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`
`

**Comment by asfand10** [comment]
`package application;




import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.util.Iterator;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import static org.apache.poi.hssf.usermodel.HeaderFooter.file;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;

public class MainController {
    @FXML
    private Label LabelID;
    
   // @FXML
     
    @FXML
    private TextField Username;
    @FXML
    private TextField Password;
    @FXML
    private TextField genre;
  
   public void Login(ActionEvent event)throws Exception{
         
       if(Username.getText().equals("user") && Password.getText().equals("Pass")){
        LabelID.setText("Login Success");
        
        Stage primaryStage2 = new Stage();
        
       Parent root = FXMLLoader.load(getClass().getResource("firstpage.fxml"));
       Scene scene = new Scene(root);
       scene.getStylesheets().add(getClass().getResource("Style.css").toExternalForm());
       
       primaryStage2.setTitle("OOP project");
       primaryStage2.setScene(scene);
      
       primaryStage2.show();
         
        
       }
       else{
           LabelID.setText("Incorrect user name or Password");
       }
   }
   
   public void search(ActionEvent event)throws Exception{
       String genre1 = genre.getText();
       
      
       if(genre1.equals("Action")){
           System.out.printf("You have searched for %s movies", genre1);
           
       };
   

}
   public void fileSearch()throws FileNotFoundException, IOException{
       
       
      
   }
}



`

**Comment by jfoenixadmin** [comment]
Hello, 
Well, most probably there is an issue in your fxml files. will close this issue as it's not related to JFoenix development.

Regards,
