### ISSUE TITLE
JfxToggleButton animation

### ISSUE THREAD

**Issue by itsdax** [jfoenixadmin/JFoenix#711]
I can't seem to find a way to disable the animation of the toggle button (the circle that expands out)

Is there a way to do so?

https://cdn.caskit.io/ZGRIgUNr.mp4

**Comment by jfoenixadmin** [comment]
you disable it using the following css: 
```
.jfx-toggle-button {
    -jfx-disable-visual-focus: true;
}

.jfx-toggle-button .jfx-rippler{
    -jfx-rippler-disabled: true;
}
```
however it will be valid in the next release, 8.0.5

Regards,
