### ISSUE TITLE
TreeItem value is null, throwing Null Pointer Exception

### ISSUE THREAD

**Issue by Devlver** [jfoenixadmin/JFoenix#716]
Hello,

I've come around a weird issue. I am creating and adding JFXTreeTableColumn's to the table view, but when I try to set a cell value factory, NPE occurs. I have pretty much the same code in another class and it works perfectly.

I have a tree table mapped through fxml

`@FXML
private JFXTreeTableView<MyObject> table;`

I create a new ObservableList and fill it with data which is absolutely not null, because I can print it out and the debugger shows so
`ObservableList<MyObject> list= FXCollections.observableArrayList(task.getValue());`

Defining column
`JFXTreeTableColumn<MyObject, String> Column1 = new JFXTreeTableColumn<>("Column1");`

After that I try to set its value factory like so:
`nameColumn.setCellValueFactory(param -> new SimpleStringProperty(param.getValue().getValue().getStringValue()));`

At this point debugger shows me that param RecursiveTreeItem value is null.

Been trying to solve this for a lot of time, but I just don't get what's wrong.

Appreciate any help,

Thank you

**Comment by jfoenixadmin** [comment]
Well it seems that `task.getValue()` returns a list of items that contains null values.
will close this issue as it's not related to JFoenix development.

Regards,

**Comment by jfoenixadmin** [comment]
To clarify things, I guess we need to update the constructor of RecursiveTreeItem to force value parameter.

**Comment by Devlver** [comment]
Sorry for late response. The solution you provided worked. This should be a
little more obvious indeed
