### ISSUE TITLE
how to make JFXDecorator resizeable if the resize border is 0px?

### ISSUE THREAD

**Issue by xinkunZ** [jfoenixadmin/JFoenix#717]
```
.jfx-decorator .resize-border{
 -fx-border-width: 0px;
}
```
I just use this css to make jfx-decorator do not show border, it looks good, just like windows 10 theme. But the panel couldn't resize...
![image](https://user-images.githubusercontent.com/7759897/40110723-5539143c-5933-11e8-8260-b44182390724.png)
Also, I try to make border transparent, but it seems not work.. plz help..

**Comment by jfoenixadmin** [comment]
Hello,
Currently it's not supported in JFXDecorator, feel free to add your own contribution to JFoenix.

Regards,
