### ISSUE TITLE
JFXDrawer can't click content in the back even if drawer is closed

### ISSUE THREAD

**Issue by roger1891** [jfoenixadmin/JFoenix#721]
Whenever I close the drawer and no drawer is visible I am not able to click the buttons that are behind it. What can I do to solve this?

**Comment by jfoenixadmin** [comment]
can you provide SSCCE demonstrating the issue? as i wasn't able to reproduce.

**Comment by roger1891** [comment]
Thank you so much it worked geniusKoder! In my case I put the JFXDrawer in a AnchorPane so I just changed my code to the ff:

```
        if(drawer.isShown()){
                    drawer.close();   
                    anchorPane.setDisable(true);
                     
        }
        else{
            drawer.open();   
            anchorPane.setDisable(false);            
        }
```

**Comment by geniusKoder** [comment]
No problem. Glad it helped you solve the problem. By the way I am not a youtuber, although I may plan to start one? Haha....

**Comment by geniusKoder** [comment]
My pleasure. Feel free to close this issue since the problem is solved. :)

**Comment by jfoenixadmin** [comment]
@roger1891 if you can provide a sample example demonstrating the issue it would be appreciated, as this solution is a dirty fix. JFXDrawer shouldn't cause such an issue unless it was misused somehow.

**Comment by roger1891** [comment]
Hi admin,

I think the issue was that I put the drawer inside of an Anchor Pane. So the drawer was fine but the anchor pane prevented me from using the buttons in the back.
