### ISSUE TITLE
JFXButton add -fx-background-image Not effective

### ISSUE THREAD

**Issue by dudylan** [jfoenixadmin/JFoenix#722]
JFXButton add style -fx-background-image Not effective

**Comment by jfoenixadmin** [comment]
can you provide a SSCCE? as I was not able to reproduce the issue.

**Comment by dudylan** [comment]
![tim 20180522131627](https://user-images.githubusercontent.com/34180156/40343453-8bac8e02-5dc2-11e8-913e-c9a1b24f10fa.png)
![tim 20180522131639](https://user-images.githubusercontent.com/34180156/40343457-90908aa4-5dc2-11e8-8745-241020ba1138.png)
![tim 20180522131558](https://user-images.githubusercontent.com/34180156/40343460-93669c8c-5dc2-11e8-8e5d-0da1cb144d23.png)
The first graph is the directory

The second graph is demo

The third graph is code

**Comment by dudylan** [comment]
sorry.
I don`t know you understand
I change the saying。
 
Can JFXButton be set -fx-background-image?

**Comment by jfoenixadmin** [comment]
sure it can be set, however you got the image path wrong.
will close this issue as it's not related to JFoenix development.

Regards,

**Comment by dudylan** [comment]
My example
If I use Button .
the image path is correct
