### ISSUE TITLE
How To Join Date and Time Picker As one control 

### ISSUE THREAD

**Issue by kamlesh0606** [jfoenixadmin/JFoenix#723]
Hi,

Currently , JFXDatePicker and JFXTimePicker are different control .  But mostly system need to  Date and Time Picker as one common control (As Same Android).

Thanks,
Kamlesh

**Comment by jfoenixadmin** [comment]
Hello,
Well currently they are two different controls and can't be joined out of the box. Feel free to add your own contribution to JFoenix.

Regards,
