### ISSUE TITLE
JFXDatePickerSkin: getPopupContent() method is protected

### ISSUE THREAD

**Issue by Aniruddha-Deb** [jfoenixadmin/JFoenix#729]
I'm looking to access only the calendar dropdown widget on a JFXDatePicker. On a normal date picker, I do that like so:

```java
DatePicker dp = new DatePicker();
DatePickerSkin dps = new DatePickerSkin( dp );
Node popupContent = dps.getPopupContent();
```

however, the getPopupContent has protected access in the JFXDatePickerSkin and hence cannot be accessed by my program. 
IMHO, it would be better if this method were made public.

**Comment by jfoenixadmin** [comment]
This method is set to protected in the base class ComboBoxPopupControl, thus it can't be set to public. 
Regards,
