### ISSUE TITLE
Please someone has an example of using JFXDialog ? Thank you.

### ISSUE THREAD

**Issue by diegodesdecolombia** [jfoenixadmin/JFoenix#73]

**Comment by RAnders00** [comment]
Come on, you can do better. Why did you create a issue for this? A couple minutes of looking either at the demo or the source code would have saved this.

Take a look [here](https://github.com/jfoenixadmin/JFoenix/blob/master/demo/resources/fxml/ui/Button.fxml).

**Comment by diegodesdecolombia** [comment]
OK. thanks for answering. But as I invoke or I call this dialog from the controller.

**Comment by RAnders00** [comment]
Using `JFXDialog` in a controller is entirely different. Sorry. I was pointing you at the wrong file anyways.

[Here](https://github.com/jfoenixadmin/JFoenix/blob/masterdemo/resources/fxml/ui/Dialog.fxml) is the FXML file for the demo and [here]() you can find the controller for it. Just keep in mind that the parent of the `JFXDialog` must be a `StackPane`.
