### ISSUE TITLE
How to use JFXHighlighter

### ISSUE THREAD

**Issue by Acapetahua** [jfoenixadmin/JFoenix#731]
I tried to copy the code that is in github but it did not work I do not know if I did something wrong

**Comment by jfoenixadmin** [comment]
it's as simple as creating a new instance of JFXHiglighter and calling the method highlight

```
JFXHighlighter highlighter = new JFXHighlighter();
highlighter.highlight(Parent to highlight, simple search query string )
```
the highlighter instance can be re-used to highlight any other parent, so there is no need to create another instance. Also, it can be cleared by calling the method `clear()`

**Comment by Acapetahua** [comment]
Oh i see thank you, now it its imposible to use with a textarea? i tried but it didnt work. it works perfectly with Text.

**Comment by jfoenixadmin** [comment]
yes you can:
`Platform.runLater(()-> highlighter.highlight((Parent) textArea.lookup(".content"), "query"));`

**Comment by Acapetahua** [comment]
When i try using like that i have the next error 
> incompatible types: Parent cannot be converted to Pane
        Platform.runLater(()-> highlighter.highlight((Parent)textarea.lookup(".content"), "word"));

and if i cast it as **Pane** i have other error

> "JavaFX Application Thread" java.lang.ClassCastException: com.sun.javafx.scene.control.skin.TextAreaSkin$ContentView cannot be cast to javafx.scene.layout.Pane

**Comment by jfoenixadmin** [comment]
Yeah I totally forgot, my bad. I updated JFXHighlighter recently to support Parent instead of Pane. however it's not released yet, it will be included in the next release hopefully in the next few days.

Regards,

**Comment by Acapetahua** [comment]
Ok thx, i hope it you will update the .jar too cause i dont use maven. Well i have to start using that
