### ISSUE TITLE
How to call requestFocus() method for a textfield on a JFXDialog box

### ISSUE THREAD

**Issue by Dooardarshan** [jfoenixadmin/JFoenix#732]
Hi this is not a bug. i just wanna know how to call requestFocus() for a textfield on a JFXDialog box. i have my controller and when i click a button a JFXDialog box pops up. there are few textfield. i wanna focus the first textfield on that JFXDialog box. i tried it but i fail. nothing get focused. any suggestion?

**Comment by myshasis** [comment]
this works for me 
`Platform.runLater(()->textfield.requestFocus());`

**Comment by Acapetahua** [comment]
You can call it when the dialog is opening
`dialog.setOnDialogOpened((event) -> {
     textField.requestFocus();
 });`

**Comment by Dooardarshan** [comment]
oh got it. thanx guys!!
