### ISSUE TITLE
Error with JFXHamburger

### ISSUE THREAD

**Issue by Javi-r** [jfoenixadmin/JFoenix#733]
f I change the state from the login window to the main window and  I execute the HamburgerBackArrowBasicTransitionplay play method  to show the arrow, this one becomes deformed. How can I show the arrow without executing the play method?

**Comment by jfoenixadmin** [comment]
Hello,
Can you provide SSCCE demonstrating the issue? what do you mean by deformed? can you clarify with images?  

Regards,

**Comment by jfoenixadmin** [comment]
will close this issue as @Javi-r  didn't respond
