### ISSUE TITLE
How to increase "space" between Tabs in JFXTabPane?

### ISSUE THREAD

**Issue by ayushchadha23** [jfoenixadmin/JFoenix#735]
HI, i wanna increase space between tabs in JFXTabPane,but Scenebuilder doesn't allow me to do that :( can i do that by css or java? or is it even possible?

**Comment by skmedix** [comment]
#623 #640

**Comment by ayushchadha23** [comment]
by Exploring #623 and #640 i figured it out : 
.jfx-tab-pane .tab
{
-fx-padding:0 0 0 65;
}
