### ISSUE TITLE
When i use the function setText() in JFXTextfield more than one time there are a bug

### ISSUE THREAD

**Issue by nospelon** [jfoenixadmin/JFoenix#736]
The String stay strange .
![print](https://user-images.githubusercontent.com/39862092/40879061-ccdbdfc0-6670-11e8-8d9b-b177f1c45ecf.png)

**Comment by jfoenixadmin** [comment]
Hello, can you provide a SSCCE demonstrating the issue?

**Comment by nospelon** [comment]
hello, i use a thread for search in a database  of table and sum the values  of a list  and i set the fields with this sum.

action cb function :


    @FXML
    void cbGetDatabaseValues(ActionEvent event) {
        cbInventario.hide();

        // TODO add your handling code here:
        cbItemSelected = (ce28m) cbInventario.getValue();
        somatorioCusto = 0.00;
        somatorioCMC = 0.00;
        itensQtd = 0;
        vrUnitario = 0.0;
        ce28DAO dao = new ce28DAO();
        cbInventario.setDisable(true);
        dateChooser.setDisable(true);
        btnProcessar.setDisable(true);
        btnPrint.setDisable(true);
        btnConfig.setDisable(true);
        imagem.setVisible(true);
        spinner.setVisible(true);
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

        Log.Write("[" + now.format(formatter) + "] " + "Carregando registros, controle: " + cbItemSelected.getId_inventario() + "\n");
        txtLog.setText(txtLog.getText() + "[" + now.format(formatter) + "] " + "Carregando registros, controle: " + cbItemSelected.getId_inventario() + ".\n");

        new Thread() {
            @Override
            public void run() {
                for (ce28 itens : dao.read("ID_INVENTARIO = " + cbItemSelected.getId_inventario())) {
                    if (itens.getId_inventario() == cbItemSelected.getId_inventario()) {
                        somatorioCusto = somatorioCusto + (itens.getUnitario() * itens.getQuantidade());
                        somatorioCMC = somatorioCMC + (itens.getCmc() * itens.getQuantidade());
                        itensQtd = itensQtd + 1;
                        vrUnitario = vrUnitario + itens.getUnitario();
                    } else {

                    }

                }
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) {
                    System.out.println("Erro ao percorrer inventario: " + ex.getMessage());
                }
                cbInventario.setDisable(false);
                dateChooser.setDisable(false);
                btnProcessar.setDisable(false);
                btnPrint.setDisable(false);
                btnConfig.setDisable(false);
                imagem.setVisible(false);
                spinner.setVisible(false);

                if (itensQtd == 0) {
                    JOptionPane.showMessageDialog(null, "Não há registros de produtos inseridos no inventário selecionado!");
                    Log.Write("[" + now.format(formatter) + "] " + "Não há registros de produtos inseridos no inventário selecionado, Controle: " + cbItemSelected.getId_inventario() + ".\n");
                    txtLog.setText(txtLog.getText() + "[" + now.format(formatter) + "] " + "Não há registros de produtos inseridos no inventário selecionado, Controle: " + cbItemSelected.getId_inventario() + ".\n");

                } else {
                    if (vrUnitario == 0) {
                        JOptionPane.showMessageDialog(null, "Os produtos do inventário selecionado estão sem preço de custo ou sem quantidade!");
                        txtLog.setText(txtLog.getText() + "[" + now.format(formatter) + "] " + "Os produtos do inventário selecionado estão sem preço de custo ou sem quantidade, Controle: " + cbItemSelected.getId_inventario() + ".\n");
                        Log.Write("[" + now.format(formatter) + "] " + "Os produtos do inventário selecionado estão sem preço de custo, Controle: " + cbItemSelected.getId_inventario() + ".\n");
                    } else {
                        Log.Write("[" + now.format(formatter) + "] " + "Inventário carregado.\n");
                        txtLog.setText(txtLog.getText() + "[" + now.format(formatter) + "] " + "Inventário carregado.\n");

                    }
                }
                String resultadoCusto = NumberFormat.getCurrencyInstance().format(somatorioCusto);
                String resultadoCMC = NumberFormat.getCurrencyInstance().format(somatorioCMC);
                txtItens1.setText(Integer.toString(itensQtd));
                txtSubCusto1.setText(resultadoCusto);
                txtSubCMC1.setText(resultadoCMC);

            }
        }.start();

    }

css  code for the textfield:

    -fx-primary : #F4F4F4;
    -fx-secondary : #115ADE;

.text-field
{
    -fx-text-fill: black;
    -fx-font-weight: bold;
    -fx-font-size : 10pt;
    -jfx-focus-color: -fx-secondary;
}

Fxml for the text field

 <JFXTextField id="txtItens2" fx:id="txtItens2" editable="false" labelFloat="true" layoutX="6.0" layoutY="14.0" prefHeight="27.0" prefWidth="300.0" promptText="Itens" text="0" />
                  <JFXTextField id="txtSubCusto2" fx:id="txtSubCusto2" editable="false" labelFloat="true" layoutX="6.0" layoutY="63.0" prefHeight="27.0" prefWidth="300.0" promptText="Subtotal sobre custo" text="0,00" />
                  <JFXTextField id="txtSubCMC2" fx:id="txtSubCMC2" editable="false" labelFloat="true" layoutX="6.0" layoutY="111.0" prefHeight="27.0" prefWidth="300.0" promptText="Subtotal sobre custo contábil" text="0,00" />

The bug its happen in variable times as the gif bellow

![gif](https://user-images.githubusercontent.com/39862092/40880491-5f924eb4-6688-11e8-8a32-0d6d8a160f66.gif)

**Comment by nospelon** [comment]
maybe can be a thread? i will go to try with a task

**Comment by jfoenixadmin** [comment]
I believe this issue is related to JavaFX itself, is there any exception in the console?

**Comment by nospelon** [comment]
hello, there was the thread it self, i used a task  and the bug stops

**Comment by nospelon** [comment]
thanks for help
