### ISSUE TITLE
JFXDialog without StackPan please.

### ISSUE THREAD

**Issue by diegodesdecolombia** [jfoenixadmin/JFoenix#74]
Hi , as the jxfdialog without StackPane is used.
I am using a panel within the fxml and the respective controlador the fxml.

![error dialogo 2](https://cloud.githubusercontent.com/assets/6775620/14056296/29e06936-f2b8-11e5-967f-7310dd7fbc13.png)

Some example please?

**Comment by RAnders00** [comment]
What do you want? Ask a more concrete question, what is your problem?
