### ISSUE TITLE
JFXButton white highlight on focused

### ISSUE THREAD

**Issue by orochies** [jfoenixadmin/JFoenix#741]
I followed the instructions in this blog, but I could not cancel the bright white color of the buttons.

https://www.jensd.de/wordpress/?p=1245

How can I do it?

The button turns whitish when receiving the focus.

**Comment by jfoenixadmin** [comment]
By default, JFXButton removes the highlight through css. btw, the blog you mentioned is related to JavaFX button, not JFXButton.

**Comment by orochies** [comment]
thanks for answering, apologies for the blog that is not with JFoenix, I include the difference:

Only button Save is focused:

![crop1](https://user-images.githubusercontent.com/753803/41050608-1d078456-6971-11e8-92aa-f8ab137a414d.png)

Only button Delete is focused:

![crop2](https://user-images.githubusercontent.com/753803/41050627-2993b712-6971-11e8-9e96-ecd2a86a556a.png)

The color the button is focused, see the color difference pale to lit.

Cancel the effect but it remains the same:

`-fx-effect: none;`

I thought it was the rippler but nothing.; Any clue what can happen?

**Comment by jfoenixadmin** [comment]
well yeah it's the rippler overlay, you can remove it by using the following css:
```
.jfx-button{
    -jfx-disable-visual-focus: true;
}
```
Regards,

**Comment by orochies** [comment]
That solves the problem, thank you very much.
