### ISSUE TITLE
Resources should be in com.jfoenix package

### ISSUE THREAD

**Issue by yushijinhun** [jfoenixadmin/JFoenix#743]
## Description
Currently, the resources of JFoenix are in `css` and `font.roboto` packages. They should be in their own packages like `com.jfoenix.css` and `com.jfoenix.font.roboto`. Otherwise, if another module also puts its resources in such a package, a conflict will occur. Notice that this only happens on Java 9.

## How to reproduce
File `module-info.java`:
```java
module moe.yushi.test {
	requires com.jfoenix;
}
```
File `moe/yushi/test/Test.java`:
```java
package moe.yushi.test;
public class Test {
	public static void main(String[] args) {
		Test.class.getResourceAsStream("/css/something.fxml");
	}
}
```
File `css/something.fxml`:
```
something
```

Output:
```
Error occurred during initialization of boot layer
java.lang.LayerInstantiationException: Package css in both module com.jfoenix and module moe.yushi.test
```

**Comment by skmedix** [comment]
IMO it would be better to move `css` and `font`_s_ to `assets` package like:
`com.jfoenix.assets.css`
`com.jfoenix.assets.fonts.roboto`

**Comment by yushijinhun** [comment]
OK. They are now in `com.jfoenix.assets` in PR #744.

**Comment by jfoenixadmin** [comment]
thanks @yushijinhun for the PR
