### ISSUE TITLE
refreshing the items in RecursiveTreeItem using ObservableList<E>.setAll is not handled correctly

### ISSUE THREAD

**Issue by zdevwu** [jfoenixadmin/JFoenix#746]
https://github.com/jfoenixadmin/JFoenix/blob/d73d6cca60208950b3f5e3a03b03a2d2577727dd/jfoenix/src/main/java/com/jfoenix/controls/RecursiveTreeItem.java#L185

Say if I have 15 items, (1) ``setAll`` the items to reduce the size to 10, then (2) ``setAll`` the items to 0. after ``setAll` to 0, I can still see the items after (1) but before (2).

What happens in the change handling regarding the setAll in (1) is that it first add the extract 10 items to the existing 15:
https://github.com/jfoenixadmin/JFoenix/blob/d73d6cca60208950b3f5e3a03b03a2d2577727dd/jfoenix/src/main/java/com/jfoenix/controls/RecursiveTreeItem.java#L190
override the existing map of ``child -> treeItem``:
https://github.com/jfoenixadmin/JFoenix/blob/d73d6cca60208950b3f5e3a03b03a2d2577727dd/jfoenix/src/main/java/com/jfoenix/controls/RecursiveTreeItem.java#L191
later on when handling ``change.wasRemoved()``, the code is trying to remove the 15 ``treeItem``s from ``itemMap``:
https://github.com/jfoenixadmin/JFoenix/blob/d73d6cca60208950b3f5e3a03b03a2d2577727dd/jfoenix/src/main/java/com/jfoenix/controls/RecursiveTreeItem.java#L199
but the ``treeItem``s are the added new ones at this line:
https://github.com/jfoenixadmin/JFoenix/blob/d73d6cca60208950b3f5e3a03b03a2d2577727dd/jfoenix/src/main/java/com/jfoenix/controls/RecursiveTreeItem.java#L193
it appears to have done the right thing the (1) step but actually it's displaying the original ones which are still in the ``getChildren()`` but cannot be referenced and removed whatsoever later on.

should the logic here do removing first instead of adding?

**Comment by jfoenixadmin** [comment]
yeah you are right @zdevwu , thanks for pointing out the issue 👍. Removing children should go first before adding new ones. can you create a PR for the issue?
