### ISSUE TITLE
jfx-textfield float label alignment issue for initialized text

### ISSUE THREAD

**Issue by roger1891** [jfoenixadmin/JFoenix#753]
![prompt text problem](https://user-images.githubusercontent.com/18215084/41202612-560c21ae-6cfe-11e8-87b2-22a188b50188.jpg)

I encounter the following issue. When the textfield is empty it displays the textfield text, prompt text and float label in the center as shown in Image 2. However, if text of textfield is initialized with content via controller then floating label is aligned to the left like in Image 1. Note that if I delete content and fill up new content then it displays it again in the middle like in Image 2. How can I fix the issue that the float label is displaying in the center when initialized with text? Is this a bug or am I missing out on something. I appreciate your help in advance. Thank you.

**Comment by jfoenixadmin** [comment]
@roger1891 Thanks for pointing out the issue 👍 
Regards,

**Comment by roger1891** [comment]
No problem.
