### ISSUE TITLE
JFXDatePicker  display error

### ISSUE THREAD

**Issue by Tobi2707** [jfoenixadmin/JFoenix#754]
I'm using JFXDatePicker for a few months now. Today i tested a dialog ealier implemented and got wierd symbols displayed. A small basic application gets the same result, on other pc's everything works fine..

Anybody got a similar error or a solution for this problem?
![capture20180611115121852](https://user-images.githubusercontent.com/33152599/41225072-419641da-6d6e-11e8-868a-7f74f459e7bb.png)

**Comment by jfoenixadmin** [comment]
Hello, try changing the date picker Chronology property.

**Comment by Tobi2707** [comment]
Do you think it helps? How should I change it?
This error also appears with this simple example:
`public class Main extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception{
        BorderPane root = new BorderPane( );
        primaryStage.setTitle("DatePicker Test");

        JFXDatePicker datePickerFX_ = new JFXDatePicker( );
        root.setCenter( datePickerFX_ );

        primaryStage.setScene(new Scene(root, 300, 275));
        primaryStage.show();
    }


    public static void main(String[] args) {
        launch(args);
    }
}`

I found out that all Strings are shiftet in ascii table about 2 chars. So a C is shown as A, D as B,...
When debugging the strings are correctly passed to the labels, so I don't know what else could be wrong...

**Comment by jfoenixadmin** [comment]
you can change chronology using the method `setChronology`
