### ISSUE TITLE
Can't import JFXTimePicker into SceneBuilder

### ISSUE THREAD

**Issue by buaashn** [jfoenixadmin/JFoenix#758]
I import "jfoenix-8.0.4.jar" into SceneBuilder for Java 8. But in the Import Dialog, the JFXTimePicker is "uncheck". I try ti check it and chick "Import Components". This doesn't seem to work. I use JDK1.8.0_161. What should I do? Thank you very much.

**Comment by jfoenixadmin** [comment]
Hello, 
I tried it with scene builder 8.3.0 and it worked.

Regards,
