### ISSUE TITLE
Unexpected change in api: setDialogContainer argument type

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#76]
Hi there,
I want to know why you changed the argument type for setDialogContainer from Pane to StackPane, since it simply breaks my previous application?!
Is there any hope for it to be a mistake or is it your final decision for that?

Thanks in advance.

**Comment by jfoenixadmin** [comment]
Hi, currently the goal is to force the user to set the dialog parent to be a stack pane, in order to show the dialog properly. 

e.g if the user sets the parent to be VBox, showing the dialog will add it as the last child in the VBox instead of showing it over the content of the VBox.

**Comment by aminabs** [comment]
Thanks, it makes sense.
