### ISSUE TITLE
How to change the JFoenix date picker's arrow button's background by using CSS?

### ISSUE THREAD

**Issue by PandukaNandara** [jfoenixadmin/JFoenix#763]
![date picker](https://user-images.githubusercontent.com/37260467/41731480-2707fcd8-759c-11e8-8476-950264a1b9bd.JPG)
I want to change the background of this date swapping button by using CSS. Do you have any suggestion?

**Comment by Acapetahua** [comment]
That arrow is a jfx-button so you can do this:
`.jfx-date-picker .jfx-button{
    -fx-background-color: red;
}`

**Comment by PandukaNandara** [comment]
Thank you very much Mr. JFoenix.💚
Can I email you when I have a problem?
________________________________

**Comment by Acapetahua** [comment]
Well i am actually not Mr. JFoenix and i know simple things i help the community as much as i can.
