### ISSUE TITLE
JFXToggleButton did not apply setToggleColor with setSelected 

### ISSUE THREAD

**Issue by svininykh** [jfoenixadmin/JFoenix#764]
By default JFXToggleButton did not apply option setToggleColor with option setSelected  before try action.
```
        toggleButton.setSelected(true);
        toggleButton.setToggleColor(PRIMARY_COLOR);
```

**Comment by jfoenixadmin** [comment]
@svininykh thanks for pointing out the issue 👍 
Regards,
