### ISSUE TITLE
How to use mini drawer in JFXDrawer

### ISSUE THREAD

**Issue by ayushchadha23** [jfoenixadmin/JFoenix#768]
hi, recently i am having problem with JFXDrawer to set size of mini drawer, can anyone send me example of a JFXDrawer with minidrawer?

**Comment by jfoenixadmin** [comment]
you can simply call the method `setMiniDrawerSize(double)`
Regards,

**Comment by ayushchadha23** [comment]
could you please send an example i tried it and all it is showing whole drawer.

**Comment by ayushchadha23** [comment]
@jfoenixadmin please show me a example using FXML PLS it's not working
