### ISSUE TITLE
Can't set ripple color to JFXButton using CSS.

### ISSUE THREAD

**Issue by PandukaNandara** [jfoenixadmin/JFoenix#769]
I'm using Java 8.171 and Jfonix 8.9. I tried to set ripple color for the Buttons using the following css code.
```
.jfx-button .jfx-rippler{
      -fx-rippler-fill:RED;
}
```
But I cannot do it. Please give me a suggestion.

**Comment by DropSnorz** [comment]
Possible solution in #67 using `-jfx-rippler-fill`
