### ISSUE TITLE
JFXDialogLayout setBody, setActions, setXXX, is it a bug?

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#77]
Hi there,
In implementing JFXDialogLayout.**setBody**, why don't you call getChildren().setAll instead of getChildren().addAll? Or why did you name the method as setBody rather than addBody? 
I know you are using StackPane and I know what it does when you add children to it, however, in my opinion, the method names are misleading anyway:
```
public void setBody(Node... body) {
    this.body.getChildren().addAll(
}
```

**Comment by jfoenixadmin** [comment]
yeah, you are right the method _**addAll**_ must be replaced with _**setAll**_
