### ISSUE TITLE
Change code for support Android 5.1.1

### ISSUE THREAD

**Issue by svininykh** [jfoenixadmin/JFoenix#771]
Thank you for amazing library JFoenix. One year ago I found it for my projects, during this year you are fixed my issues for support Android 5.1.1 platform. If you have a time, please fixed some "forEach" codes in sources of JFoenix:

https://github.com/jfoenixadmin/JFoenix/search?q=forEach&unscoped_q=forEach

**Comment by jfoenixadmin** [comment]
Other foreach statements are either part of the demo app or deprecated API and will be removed later.
Regards,
