### ISSUE TITLE
JFXRippler setOverlayVisible(false) right behaviour?

### ISSUE THREAD

**Issue by schlegel11** [jfoenixadmin/JFoenix#774]
I'm not sure if the "rippler.setOverlayVisible(false);" method is the right thing to call in my case.
If I use a JFXRippler like that:

![peek 2018-07-05 02-37](https://user-images.githubusercontent.com/5841076/42297059-a45cfe4e-7ffc-11e8-8afb-742d9046e841.gif)

I always see the big blue circle that I don't want to see.

If I comment out in JFXRippler class line 401 "overlayRect.inAnimation.play();" it works like I want:

![peek 2018-07-05 02-38](https://user-images.githubusercontent.com/5841076/42297086-f0ce1060-7ffc-11e8-8957-88242bb09c55.gif)

So is this the right behaviour of "rippler.setOverlayVisible(false);"?

**Comment by jfoenixadmin** [comment]
Hello, well the method `setOverlayVisible` doesn't have a permanent effect. it will only hide/show the overlay once called, it doesn't disable the overlay.

**Comment by schlegel11** [comment]
Ah ok I get it. So it's not possible to hide better you are right to deactivate the overlay before I click.
But it works in situation when I e.g. create the rippler manual and hide the overlay afterwards.
