### ISSUE TITLE
Issue With JFEONIX 8.X.X import

### ISSUE THREAD

**Issue by dbanerjee1410** [jfoenixadmin/JFoenix#776]
I am unable to see lot of jfeonix components(like JFXButton) in Scenebuilder.

jfeonix jar version = jfoenix-8.0.5.jar
jDK version = 1.8
netbeans version = 8.2
scenebuilder version = JavaFX Scene Builder 9.0.1

Do let me know which is the JDK/scenebuilder/jfeonix version i should use to use all components.

**Comment by Kool-Koder** [comment]
You should use a 8.X.X Scene Builder Version instead for JFoenix 8.X.X

Use SceneBuilder for Java 8:
https://gluonhq.com/products/scene-builder/
