### ISSUE TITLE
How to edit date cell and year cell in JFoenix date picker

### ISSUE THREAD

**Issue by roger1891** [jfoenixadmin/JFoenix#779]
Right now I have this grey hover effect for the date cell and year cell in my jfoenix date-picker. I would like to add a pointer and a different color whenever I hover over the two. Below you may see an image depicting the two. Would anybody know the css solution to this?

![date-picker](https://user-images.githubusercontent.com/18215084/42537733-5b42a60c-84c8-11e8-9b44-9a36cf174e5c.jpg)

**Comment by jfoenixadmin** [comment]
you can check <a href="https://github.com/jfoenixadmin/JFoenix/blob/master/jfoenix/src/main/java/com/jfoenix/skins/JFXDatePickerContent.java>JFXDatePickerContent</a> for implementation details

**Comment by roger1891** [comment]
For date picker I was able to find a solution. Thank you.
