### ISSUE TITLE
How to edit hour and min cell in JFoenix time picker

### ISSUE THREAD

**Issue by roger1891** [jfoenixadmin/JFoenix#780]
Currently the color for the hour cell and min cell in my jfoenix time-picker is black. I would like to add a pointer and a different color whenever I hover over the two. Below you may see an image depicting the two. Would anybody know the css solution to this?

![time-picker](https://user-images.githubusercontent.com/18215084/42537921-df18da1e-84c8-11e8-99cd-6e028c80f84d.jpg)

**Comment by jfoenixadmin** [comment]
you can check <a href="https://github.com/jfoenixadmin/JFoenix/blob/master/jfoenix/src/main/java/com/jfoenix/skins/JFXTimePickerContent.java">JFXTimePickerContent</a> for implementation details

**Comment by roger1891** [comment]
So I guess I have to overwrite a function and create a class since there is no specific class assigned for the clock?

**Comment by jfoenixadmin** [comment]
or by using the css path, e.g:
```
.date-picker-popup BorderPane{
    -fx-background-color: RED;
}

.date-picker-popup BorderPane Circle{
    -fx-fill: BLUE;
}
```
however we still need to add some style classes. 

Regards,

**Comment by roger1891** [comment]
Noted. Thank you admin :) Just wanted to be sure before I do some unnecessary edits.
