### ISSUE TITLE
Input Validation error for Focus Color & Unfocus Color

### ISSUE THREAD

**Issue by roger1891** [jfoenixadmin/JFoenix#783]
I noticed that if I pick my own focus and unfocus colors, the red validation error notice for the textfield does not turn red. However if I use the original colors #4059a9 (focus color) and #4d4d4d (unfocus color) then the red validation error notice for the textfield appears. Is there any way I can choose my own colors and still retain the validation error colors?

Here are the images
1. Original focus and unfocus colors
![with error](https://user-images.githubusercontent.com/18215084/42723189-1acae802-878c-11e8-8010-7bc2c73c287f.jpg)
2. My colors for focus and unfocus
![bug1111](https://user-images.githubusercontent.com/18215084/42723195-2a4db0c0-878c-11e8-8fc6-fef7cf7d9fc5.jpg)

**Comment by jfoenixadmin** [comment]
Hi, Well i'm not sure if it's possible using scene builder. Upon validation, the pseudo class "error" is enabled on text field control. you can force validation styling using the following css:
```
.jfx-text-field:error {
    -jfx-focus-color: #D34336;
    -jfx-unfocus-color: #D34336;
}
```
Regards,
