### ISSUE TITLE
How to make the jfxslider animated thumb stay on

### ISSUE THREAD

**Issue by Jam516** [jfoenixadmin/JFoenix#784]
Is there a way of keeping the jfxslider animated thumb constantly active using the fxml or css of your project.
![capture](https://user-images.githubusercontent.com/15823285/42729307-c284146e-8788-11e8-93ab-d61e30f0d687.PNG)

**Comment by jfoenixadmin** [comment]
Hello, 
Currently you can't do that, no exposed api to force showing the animated thumb. Meanwhile, feel free to add your own contribution to JFoenix.

Regards,
