### ISSUE TITLE
JFXTreeTableView CSS column heading alignment ineffective

### ISSUE THREAD

**Issue by Slipstream737** [jfoenixadmin/JFoenix#786]
I am trying to center left align the column headings of the JFXTreeTableView. I have tried using the following CSS to do so:

`.tree-table-view .column-header .label {
   -fx-alignment: CENTER-LEFT;
}`

However, the above CSS has no effect on the alignment of the column headings which remain center aligned as they are by default.

**Comment by jfoenixadmin** [comment]
you can use the following css:
```
.tree-table-view .column-header > StackPane{
    -fx-alignment: center-left;
}
```
Regards,
