### ISSUE TITLE
JFX TreeTableView - Alternate Row Style Applied to all TreeTableViews

### ISSUE THREAD

**Issue by edmundhaley** [jfoenixadmin/JFoenix#787]
Good Day

I have a particular situation that I am hoping to find some assistance with.  I have applied an Alternate Row Style Background Color to the JFX TreeTable View and it works successsfully; however I have been given direction that not all occurrences of the JFX TreeTableView, within our newly developed application, will require an alternate row styling.  This is where I am noticing an issue.  I have implemented Custom CSS Style Classes that should be able to compensate for turning on/off the alternate row styling; however to no avail, when the first instance of ".tree-table-row-cell:odd " is encountered it is applied to all TreeTableViews regardless of the other Custom CSS Style Class created for the Alternate Row Stylling Turned off.  I guess I should suggest, by turned off, i am simply setting the background color to either "White" or "Transparent".  Has anyone else seen this type of behavior?  If so what was the fix or how did you resolve it?

Looking forward to your thoughts.

**Comment by jfoenixadmin** [comment]
Hello,
If you can provide a SSCCE for this issue, I might be able to help.
Regards,

**Comment by edmundhaley** [comment]
i apologize for the delayed response.  Unfortunately the code is specific to the company and as you might guess, it is proprietary.  Let me see if I can spin something up at home and then share it.

**Comment by jfoenixadmin** [comment]
will close this issue as @edmundhaley didn't reply, and most probably it's not related to JFoenix development.
