### ISSUE TITLE
Nodes on left side area are not focussing in the jfxtabpane in javafx

### ISSUE THREAD

**Issue by rajankit911** [jfoenixadmin/JFoenix#788]
Currently i am working on multiple scenes switching through the static AnchorPane. In one of my stackpane, i am using tabpane/jfxtabpane. What happens is that when i run the fxml file containing JFXtabpane independently, it works fine, but when i load it through the static AnchorPane, then nodes on the left side area of JFXtabpane are not focussing.

`AnchorPane static temporaryPane;
StackPane pane = FXMLLoader.load(getClass().getResource("/panel/TabPane.fxml"));
DashboardViewController.temporaryPane.getChildren().clear();
DashboardViewController.temporaryPane.getChildren().addAll(pane);`

**Comment by jfoenixadmin** [comment]
can you provide a SSCCE for this issue?

**Comment by jfoenixadmin** [comment]
will close this issue as @rajankit911 didn't reply
