### ISSUE TITLE
MINI drawer example

### ISSUE THREAD

**Issue by ayushchadha23** [jfoenixadmin/JFoenix#790]
Can anyone send me a Jfoenix JFXDrawer mini drawer example using FXML I posted this in a earlier issue but it was ignored.pls send an example using JFXDrawer minidrawer with source code.

**Comment by DeeVeX** [comment]
something like that?

```
<JFXDrawer>
    <sidePane>
        <StackPane>
            <children>
                    <JFXButton>Left Content</JFXButton>
            </children>
        </StackPane>
    </sidePane>
</JFXDrawer>
```

Came up with that fxml by trying out a fxml equivalent to this code:
http://www.jfoenix.com/documentation.html?search=validator#Drawer
