### ISSUE TITLE
JFXDrawer always visible

### ISSUE THREAD

**Issue by Giulianini** [jfoenixadmin/JFoenix#792]
![jfxdrawer](https://user-images.githubusercontent.com/39558398/43368608-3ccc19fa-9360-11e8-94b2-ff94cf6a76a2.png)
![scenebuilder](https://user-images.githubusercontent.com/39558398/43368609-3ce59cd6-9360-11e8-9001-c268add76f18.png)
The drawer might stay hidden, only the sidePane has to became visible when opened; but this does not happen
How can i solve this?

**Comment by jfoenixadmin** [comment]
According to your scene hierarchy it seems that there are no content/sidepane inside JFXDrawer.
try using JFXDrawer from code/ or check JFoenix demo for a better example.

Regards,
