### ISSUE TITLE
Integers in JFXTreeTableView

### ISSUE THREAD

**Issue by Acapetahua** [jfoenixadmin/JFoenix#793]
Is there any way to use Integer data in the tree table view?

**Comment by jfoenixadmin** [comment]
sure same as javafx tree table view

**Comment by bogdanbaghiu** [comment]
Hello. It happens to me that I have a class called Client that has a phone number, I intend to assign it to the column of the table but it tells me that it is not possible. Can you tell me how to solve it?

Method setTableView()
`JFXTreeTableColumn<Client, Integer> numberPhoneColumn = new JFXTreeTableColumn("Phone Number");
numberPhoneColumn.setPrefWidth(100);`
`numberPhoneColumn.setCellValueFactory(
                (TreeTableColumn.CellDataFeatures<Client, Integer> param)
                -> param.getValue().getValue().phone_numberProperty()
);`

**Comment by bogdanbaghiu** [comment]
I use jfoenix_8.0.7.jar library

**Comment by bogdanbaghiu** [comment]
Solution:
`numberPhoneColumn.setCellValueFactory( (TreeTableColumn.CellDataFeatures<Client, Integer> param) -> param.getValue().getValue().phone_numberProperty().asObject() );`
