### ISSUE TITLE
JFXTextField ignores -fx-prompt-text-fill on first load

### ISSUE THREAD

**Issue by mnxn** [jfoenixadmin/JFoenix#795]
JFXTextField in JFoenix 8.0.5 does not use `-fx-prompt-text-fill ` for the prompt text color until after you focus and unfocus it. When the app first opens, it uses the default color, but changes its color to the correct one after you click on and off of it. This does not happen in JFoenix 8.0.4 and JFXTextArea does not have the same problem.

**JFoenix 8.0.5:** 

![2018-08-01_15-45-15](https://user-images.githubusercontent.com/25037249/43553027-fc27f1aa-95a1-11e8-8a17-08a9c397cb89.gif)

**JFoenix 8.04:**

![2018-08-01_15-42-34](https://user-images.githubusercontent.com/25037249/43553031-0104e46c-95a2-11e8-93d6-c99232595339.gif)

All of my source code is the same between both examples (other than the 8.05/8.04 labels), both running on Running on JDK 1.8.0_181. The only difference is the version of JFoenix. 

**CSS:**

![code_2018-08-01_15-29-15](https://user-images.githubusercontent.com/25037249/43552873-3c641826-95a1-11e8-9b8f-e624d5f00101.png)

**FXML:**
![code_2018-08-01_15-52-00](https://user-images.githubusercontent.com/25037249/43553265-fd2f18b6-95a2-11e8-9d56-2e4978d8a88a.png)
![code_2018-08-01_15-53-03](https://user-images.githubusercontent.com/25037249/43553266-fd651ee8-95a2-11e8-8006-739cc74383da.png)

**Comment by jfoenixadmin** [comment]
Hi,
I'm already aware of this issue, and it's been fixed (will be included in the next release). Thanks for pointing out the issue 👍 

Regards,

**Comment by mnxn** [comment]
@jfoenixadmin is there an estimated time for when the next release will hit maven?

**Comment by jfoenixadmin** [comment]
today :)
