### ISSUE TITLE
RegexValidator

### ISSUE THREAD

**Issue by DeeVeX** [jfoenixadmin/JFoenix#796]
I need a regexvalidator for my application (JFXTextField only).
So I added a class "RegexFieldValidator", which inherits from your `com.jfoenix.validation.base.ValidatorBase` in my local code.
Would be nicer if we could have that code in the JFoenix package.

1. Is there already a better way to do that?
2. How are you handling this in general? Would you be glad if I'd provide a little Pull-Request for this case?

**Comment by jfoenixadmin** [comment]
Hello,
Well yeah this is the right way to do, sure feel free to create PR for this 👍 

Regards,
