### ISSUE TITLE
PromptText of JFXDatePicker has "wrong" color after validation

### ISSUE THREAD

**Issue by Dearbone** [jfoenixadmin/JFoenix#797]
Currently we upgraded to new 8.0.7.
Many changes that were made are nice =)

I now question myself abut the promptText of a JFXDatePicker.
After validation the prompText stays red as long as the user focuses the datepicker. After focus change the promptText color will be default.
The error-Text below the datePicker is already gone. That works fine.

![grafik](https://user-images.githubusercontent.com/8487566/43722900-abe650e4-9996-11e8-9886-829ffeacae6c.png)

Would be nice if you can look into it, or tell me if this is the right behaviour =)

**Comment by jfoenixadmin** [comment]
Hello, 
Yeah you need to override JFXDatePicker styling when "error" pseudo class is enabled

```
.jfx-date-picker:error > .jfx-text-field {
	-jfx-focus-color: RED;
	-jfx-unfocus-color: RED;
}
```

also you can change `-fx-prompt-text-filll` property if needed

Regards,

**Comment by Dearbone** [comment]
Hello, thanks for your Reply.

Thats exactly what we did. I just thought the promptText color will change color after validation result changed......I guess i just remember it wrong. 

Thanks for clarifying it.
