### ISSUE TITLE
JFXComboBox not getting class from css in scenebuilder

### ISSUE THREAD

**Issue by Acapetahua** [jfoenixadmin/JFoenix#801]
I'm trying to set font-size to a jfxcombobox whit css file. In the css file i'm using the class 

> .jfx-combo-box{-fx-font-size:13pt; } 

but it not recognize it, i also tried a different class name and put it using SceneBuilder but it dont save it, when i tried it with other component like a `jfx-text-field` it works correctly.
And when i put it in the Style section it works correctly.

I'm using the 8.0.7 version of jfoenix and SeneBuilder 8.0.4

**Comment by jfoenixadmin** [comment]
Hello, 
you can change it in a similar way to JavaFX Combobox using the following css:
```
.jfx-combo-box > .list-cell{
    -fx-font-size: 20px;
}
```
Regards,
