### ISSUE TITLE
DatePicker Selected Year Text Color

### ISSUE THREAD

**Issue by raju248** [jfoenixadmin/JFoenix#806]
How can i change the color of the text of selected year and it should be different from the default color.

![year](https://user-images.githubusercontent.com/26528784/43893334-6656b030-9bf0-11e8-932c-da63eb696c95.PNG)

**Comment by jfoenixadmin** [comment]
I updated JFXDatePicker, now you can change it using the following css:

```
.date-picker-popup .date-picker-list-view .data-picker-list-cell:selected-year {
    -fx-text-fill: RED;
}
```
this fix will be included in the next release *.*.8

Regards,
