### ISSUE TITLE
Is this a weird behaviour from AlertDemo.java from the demos?

### ISSUE THREAD

**Issue by 1w3j** [jfoenixadmin/JFoenix#809]
jdk: 1.8.0_172
jfoenix cloned repo commit: e5318cf074dbc08a0219064768e2df609739004f
OS: Manjaro Linux x86_64
Kernel: 4.14.57-1-MANJARO
DE: GNOME 3.28.3
WM: i3

![ezgif-1-d711ec84ac](https://user-images.githubusercontent.com/21296115/44071892-5d5eeb14-9f51-11e8-8db3-27ba98996da6.gif)

**Comment by jfoenixadmin** [comment]
Hello,
How were you able to drag/resize it? such code is not implemented in JFXAlert.
looks cool though...

**Comment by 1w3j** [comment]
It does this when clicking on the gray area and dragging the mouse around, left click + drag. Single click on gray are won't close the alert dialog, rather thinks user is going to drag & resize the whole dialog. The dialog closes when hitting `Esc`. Clicking on white part of the dialog does nothing. Hope someone reports this too.

**Comment by jfoenixadmin** [comment]
I'll close this issue for now, if you were able to reproduce this issue outside the demo scope let's re-open.

Regards,
