### ISSUE TITLE
TreeTableView: RecurisiveTreeItem needs to be extended in order for object to show on TreeTable

### ISSUE THREAD

**Issue by azmatzuberi** [jfoenixadmin/JFoenix#81]
Hi,

I'm having issues with the recursiveTreeItem class needing to be extended by the subclass in order for the objects to show on the tree. Is there any way around this so that I don't have to extend to this class?

**Comment by jfoenixadmin** [comment]
can you provide a concrete example? 

**Note:**  your data class must extend **RecursiveTreeObject**,in order to create **RecursiveTreeItem** using your data class.
