### ISSUE TITLE
Disable TabPane animations

### ISSUE THREAD

**Issue by SnShalitha** [jfoenixadmin/JFoenix#810]
I facing serious performance drop on some old pcs (2008 processor) when switching between tabs.. Animations are not smooth.. They stuter heavily.. Is there a way to disable rifler effect on them

**Comment by jfoenixadmin** [comment]
Currently, you can't disable tabs animation

**Comment by skmedix** [comment]
This feature was implemented in https://github.com/jfoenixadmin/JFoenix/commit/eab78c57c5f55b798033638154e912e9ab36a740

You can disable animations via method:
```java
setDisableAnimation(true);
```
or via CSS
```css
.jfx-tab-pane {
    -jfx-disable-animation: true;
}
```
