### ISSUE TITLE
how  to run Demo?

### ISSUE THREAD

**Issue by auwoqu** [jfoenixadmin/JFoenix#812]
I  use gradle first build run NullPointerException;
i just want to see some component,
but i study gradle in 2hours 
i try to use maven  but can not find main class  
  could you build a demo jar ?

**Comment by knkyli** [comment]
sadasd

**Comment by jfoenixadmin** [comment]
will close this issue since @auwoqu didn't reply

**Comment by trimcode** [comment]
Terminal --> gradlew run
