### ISSUE TITLE
Problems with the JFXChipView

### ISSUE THREAD

**Issue by BubbleEgg** [jfoenixadmin/JFoenix#813]
1: Is it possible to change the max. length of a chip?
http://prntscr.com/kkvtmc

2: I can make a unlimited amount of chips. Is this a Bug?
http://prntscr.com/kkvug5

**Comment by jfoenixadmin** [comment]
1. yes you can by changing the chip content size (width)
2. No it's not a bug there is no limit on chips count, however there is a bug in the ui we need to fix. thank for pointing out the issue 👍 

Regards,

**Comment by BubbleEgg** [comment]
1. How can I change the chip content size? In Java or in CSS?
    When I have to change it in CSS, how can I do it/what do I need to write in the CSS file?

2. Are you planning to implement a feature to limit the chips count or a scollbar?

**Comment by jfoenixadmin** [comment]
1. You can create your own chip and customize the way you want through css or code.
2. I just updated JFXChipView, now it supports scrollbar.
