### ISSUE TITLE
How to add a JFXButton in any row of the JFXTreeTableView?

### ISSUE THREAD

**Issue by bogdanbaghiu** [jfoenixadmin/JFoenix#814]
I need a button when pressed delete a row to table. I search on Google but don't work correctly add button to row.

**Comment by jfoenixadmin** [comment]
Well adding a button to the row can cause some issues, instead try to add it as a column/cell-value to tree table view. You can find many example for this online. Will close this issue as it's not related to JFoenix development.

Regards,
