### ISSUE TITLE
JFX Combo-Box Glitch

### ISSUE THREAD

**Issue by juzimmer** [jfoenixadmin/JFoenix#815]
Just wondering if anyone else can reproduce this problem. The project I'm working on requires me to have  two combo boxes. Upon clicking a value in the first one tells the second combo box to populate different values. Sometimes when I cycle through the first combo box then click on the values in the second combo box the drop down selection values are appearing in another area in the application(not connected to the node). I was trying to use the snipping tool to show the picture of what happens but every time I click off my application the value box disappears. I also have ruled out any other interference that could cause this issue so I disabled all my CSS.

**Comment by jfoenixadmin** [comment]
@juzimmer can you provide a SSCCE for this issue?

**Comment by jfoenixadmin** [comment]
will close the issue since @juzimmer  didn't reply.
