### ISSUE TITLE
JFXButton not center left icon in jfoenix-8.0.7.jar

### ISSUE THREAD

**Issue by bogdanbaghiu** [jfoenixadmin/JFoenix#819]
I use Java 8 jdk, Mac OS High Sierra, Netbeans 8.2 and Scene Builder last version to Java 8.
But the Basseline_Left work.

![image](https://user-images.githubusercontent.com/37840937/44779553-128a0980-ab80-11e8-92d2-c67f3dc70dad.png)

**Comment by jfoenixadmin** [comment]
this issue is also reproducible using JavaFX button, thus it will be inherited in JFXButton 
@bogdanbaghiu , I suggest opening an issue for OpenJFX regarding this.

Regards,
