### ISSUE TITLE
JFXTextField label should float above entered text

### ISSUE THREAD

**Issue by imgx64** [jfoenixadmin/JFoenix#82]
Entering text into `JFXTextField` makes the label disappear:
![JFXTextField](http://jfoenix.com/img/shots/shot_inputs.gif)

But according to [Material Design](https://www.google.com/design/spec/components/text-fields.html#text-fields-labels):

> When the user engages with the text input field, the floating inline labels move to float above the field.

(Note the small "Title" above "Vintage 50")

<img src="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3UHZpZjVsYjRHcXc/components_textfields_labels1.png" width="300" />

**Comment by jfoenixadmin** [comment]
you must set the labelFloatProperty to true.

**Comment by Dooardarshan** [comment]
Is there a way to float to left or to right?

**Comment by jfoenixadmin** [comment]
you can change that by changing node orientation

**Comment by ammarkhan786** [comment]
i am having the same issue. i come i have imported jfoenix library in scenebuilder, but whenever i use jfxtextfield that dont show ( FLOAT LABEL ) checkbox in the properties inside the inspector. 
Any solutions for that?

**Comment by fatehOurghi** [comment]
thanks, it works for me

**Comment by MohammadMahdiHassani** [comment]
is there a way to put label float in right and cursor in left?
