### ISSUE TITLE
Background colour of time picker clock title

### ISSUE THREAD

**Issue by ashitshah** [jfoenixadmin/JFoenix#820]
Just like the month-year-pane of date picker how to change the colour of hour minute pane of time picker?

**Comment by jfoenixadmin** [comment]
you can change it using the following css:

```
.date-picker-popup .time-pane{
    -fx-background-color:RED;
}
```
or to change the whole theme
```
.jfx-time-picker{
    -jfx-default-color: RED;
}
```

Regards,
