### ISSUE TITLE
On the Datepicker the textField is not painted

### ISSUE THREAD

**Issue by vincenzopalazzo** [jfoenixadmin/JFoenix#822]
in the Datepicker is not painted the textField, I tried to change the color of the textField and is not changed, I explain using a screen, I want the two textField take the same color, in this case the blue, but I can not just set it

![bugjavafx](https://user-images.githubusercontent.com/17150045/44954399-ab32c900-aea1-11e8-9b51-6518236a8d61.png)

**Comment by jfoenixadmin** [comment]
try to change the color using css file instead of code.

**Comment by vincenzopalazzo** [comment]
@jfoenixadmin well, can I ask you what should I add in the code and where?

ps: I am a neophyte in css
