### ISSUE TITLE
Where did 'roboto.fonts' and 'css' go?

### ISSUE THREAD

**Issue by micheljung** [jfoenixadmin/JFoenix#823]
I'd like to update from 9.0.4 which included the resource packages `roboto.fonts` and `css` but they have been removed with 9.0.5+.
They're still in the repository and I could not find any related GitHub issue and `jfoenix/build.gradle` hasn't been touched within a year, so what happened?

**Comment by jfoenixadmin** [comment]
they have been <a href="https://github.com/jfoenixadmin/JFoenix/tree/JFoenix-9.0.0/jfoenix/src/main/resources/com/jfoenix/assets">refactored</a>, so they can be loaded using <a href="https://github.com/jfoenixadmin/JFoenix/blob/JFoenix-9.0.0/jfoenix/src/main/java/com/jfoenix/assets/JFoenixResources.java">JFoenixResources</a>
