### ISSUE TITLE
JFXSnackBar : not dismissed upon action clicked

### ISSUE THREAD

**Issue by ricard-v** [jfoenixadmin/JFoenix#824]
I noticed that the `JFXSnackBar` does not get _automatically_ dismissed (closed) upon button click.

Looking at the source code, it appears that the public method `void close()` is never called, not even once from the whole class.

Based on Android's component, I was expecting the same behavior where the `Snackbar` gets dismissed upon click on the action button / text.

I don't know if this is intended behavior or not, but this behavior is the same regardless of the timeout (indefinite or specific duration).

Furthermore, after looking deeper into the source code, I noticed that in case the timeout is a specific duration (e.g. 5 seconds), the `JFXSnackbar` does get dismissed upon timeout as expected, but not by calling the `close()` method but instead using the `TimeLine# animation.setAutoReverse(true);` method.

Finally, as a workaround, I have no choice but the to call the `show(...)` method the following way to make sure the `JFXSnackbar` gets dismissed upon action click:

```
public final void showSnackbar(
        @NonNull final String message,
        final long duration,
        @NonNull final String action,
        @NonNull final EventHandler<ActionEvent> actionHandler) {

    this.snackbar.show(message, action, duration, event -> {
        this.snackbar.close();
        actionHandler.handle(event);
    });
 }
```

My `showSnackbar(...)` method has its signature as close as possible to that of the `JFXSnackbar#show(...)` method's. However, I have to create some sort of a bridge where I make sure to call `JFXSnackbar#close()` before executing the code supplied via the `actionHandler` parameter.

I will admit that this work around is simple but I don't know if I am supposed to do it that way or if I am missing something.

Thank you for the hard work and best regards,

**Comment by jfoenixadmin** [comment]
Hello,
Well, yes you need to specify the action handler for the button to dismiss the snackbar.
Btw, JFXSnackbar public/internal api will be re-architected. The current api is confusing and very limited. it will be updated in later versions of JFoenix.

Regards,
