### ISSUE TITLE
JFXComboBox prompt text overflow

### ISSUE THREAD

**Issue by TheTomTom3901** [jfoenixadmin/JFoenix#827]
![image](https://user-images.githubusercontent.com/22203095/45617793-5b402e80-ba6b-11e8-9d28-ed87319a9272.png)

So as the above screenshot shows, I added some text to the prompt and realised that it overflows out of the node and even goes off screen, I hadn't noticed it with my first combo box because the text perfectly fitted the size but was very confused when this popped up.

Thanks in advance

**Comment by jfoenixadmin** [comment]
Hello @TheTomTom3901, Thanks for pointing out the issue 👍
