### ISSUE TITLE
How to move rows in jfxtableview

### ISSUE THREAD

**Issue by uisuru** [jfoenixadmin/JFoenix#828]
Hi, 
I am new to JavaFX and JFoenix. I went throw the following link and find out how to make a table using jfxtableview. https://github.com/jfoenixadmin/JFoenix/blob/master/demo/src/main/java/demos/components/TreeTableDemo.java
In that example, columns can move by default. But rows can't. I go throw several documents but doesn't find any way to do that. Can anyone help me?

**Comment by jfoenixadmin** [comment]
Hello,
well, you won't be able to find such feature out of the box, this feature requires a custom drag and drop handler on the tree table (which is not implemented by default). Feel free to add your own contribution to JFoenix.

Regards,
