### ISSUE TITLE
JFXDecorator hides windows taskbar if maximized

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#83]
Hi there,
In windows, if I click on the maximized icon of the JFXDecorator, it currently hides the windows taskbar (the bar on the bottom) which is not the default behavior for most of windows applications. I would see this an issue to be resolved in the future. Am I right or wrong?

**Comment by jfoenixadmin** [comment]
Hi, well yes, this behavior is provided by java. Not sure it will be solved anytime soon.
you can try it by setting the init style of a stage to Transparent then maximizing it through code.

**Comment by aminabs** [comment]
Oh, I think the work _maximized_ misleads you to fullscreen mode mistakenly. I'm sorry for that.
Anyway, the issue is for sure about the JFXDecorator and has nothing to do with java. By maximize, I **do not** mean _go fullscreen_; I mean by clicking on the full square icon on the decorator, it should maximize the application without hiding the windows taskbar. Please note that this is the default behavior even with javafx's Stage. If you show a stage and click to maximize it, it will never hides the taskbar.

**Comment by aminabs** [comment]
Hi,
Please take a look at this [question](http://stackoverflow.com/questions/36513951/javafxports-screen-size).  
I am not sure about your internal implementation of the decorator, however, it might be possible to take the taskbar height into consideration when maximizing the decorator. The difference between

**Comment by jfoenixadmin** [comment]
plz note that the stage style is set to transparent, and that's what causing java maximize functionality to  behave this way. sure, we can solve it by changing the bounds but prefer to stick with java default maximize functionality.

**Comment by aminabs** [comment]
A very basic workaround is to simply create a normal stage and keep its width/height values after setting it to maximized. Then apply the saved width/height value on the original stage when maximized. I've provided a demo [here](https://github.com/aminabs/javafx-samples/blob/master/UndecoratedMaximizeDemo.java)

**Comment by jfoenixadmin** [comment]
this issue is related to 
https://bugs.openjdk.java.net/browse/JDK-8095426

the JFXDecorator has been updated, it has two new methods regarding maximization:

**_setCustomMaximize(boolean)_** that will trigger custom maximization method instead of JavaFX default method, by default it's set to false.

**_setMaximized(boolean)_** to maximized/restore the stage

**Comment by aminabs** [comment]
Thanks.
OK for now :)
