### ISSUE TITLE
Update the material design to current one ?

### ISSUE THREAD

**Issue by Typhon0** [jfoenixadmin/JFoenix#831]
Hello , 

are you interested to update the material design of this library to be close to the current design ?

Thanks

**Comment by jfoenixadmin** [comment]
Hello,
well that's the point of JFoenix, however MD keeps changing frequently. It's hard to keep up with a very limited resources.

Regards,

**Comment by Typhon0** [comment]
I will try to update the design in my free time and do pull request.

**Comment by jfoenixadmin** [comment]
All contributions are appreciated :)
