### ISSUE TITLE
Memory leaks using JFXMasonryPane

### ISSUE THREAD

**Issue by DropSnorz** [jfoenixadmin/JFoenix#833]
Hi ! I'm facing an issue and I don't know if it's a bug or if i don't use the Masonry component correctly.

### 1. Issue
I have a use case where i need to add and remove childrens in the masonry pane. For example, displayed nodes can be filtered using a text input. 

![owplug-store-search](https://user-images.githubusercontent.com/15964929/46257803-6e69ea00-c4c0-11e8-8149-6c2d179cf448.gif)

So, when the user submit a text query:
1. I remove all child in masonry pane using `getChildrens.clear()`
2. I  clear previous layouting using `masonryPane.clearLayout()`
3. I add nodes corresponding to the user text query `getChildrens.add(...)`

Maybe the component is not initially designed to do that but after each use of my filtering feature, i noticed that the memory footprint of my app increase. So i suspected a memory leak somewhere. I run an analysis on my app memory dump and the tool seems to indicate that the JFXMasonryPane component keep holding all nodes references throughout the `animationMap` attribute. 

![jfxmasonrypane-memleak-analysis](https://user-images.githubusercontent.com/15964929/46257814-99543e00-c4c0-11e8-8b28-f9f792ae5b20.png)

I started my investigation reading the [JFXMasonryPane.java](https://github.com/jfoenixadmin/JFoenix/blob/master/jfoenix/src/main/java/com/jfoenix/controls/JFXMasonryPane.java) file and i can't see any point where the content of this map is flushed / cleared... So for me, the map keeps references of removed child nodes.

### 2. Reproduce
I've created a small example to reproduce the issue. You can add nodes to the masonry pane, clears them, add new ones and see the `animationMap` size growing.

```java
public class Main extends Application{

  @Override
  public void start(Stage stage) throws Exception {
    
    VBox root = new VBox();
    JFXMasonryPane masonryPane = new JFXMasonryPane();
    JFXButton addButton = new JFXButton("+ Add a node in masonry pane");
    addButton.setOnAction(e -> {
      masonryPane.getChildren().add(new Label("Hi there !"));
      displayMasonryPaneStats(masonryPane);
      
    });
    
    JFXButton clearButton = new JFXButton("- Clear all nodes");
    clearButton.setOnAction(e -> {
      masonryPane.getChildren().clear();
      masonryPane.clearLayout();
      displayMasonryPaneStats(masonryPane);
      
    });
    
    root.getChildren().add(addButton);
    root.getChildren().add(clearButton);
    root.getChildren().add(masonryPane);
    Scene scene = new Scene(root, 400, 400);
    stage.setScene(scene);
    stage.centerOnScreen();
    stage.show();
  }
  
  public void displayMasonryPaneStats(JFXMasonryPane masonryPane) {
    
    try {
      //Prints masonry pane childrens list size
      System.out.println("MansoryPane - Childrens count:" + masonryPane.getChildren().size());
      //Prints masonry pane animation map size using reflection (can be monitored using debugger)
      Field f = masonryPane.getClass().getDeclaredField("animationMap");
      f.setAccessible(true);
      HashMap<Region, Transition> animationMap = (HashMap<Region, Transition>) f.get(masonryPane);
      System.out.println("MansoryPane - AnimationMap size:" + animationMap.size());

    } catch (Exception e) {
      e.printStackTrace();
    } 
  }
}
```

Output example

```java
MansoryPane - Childrens count:1
MansoryPane - AnimationMap size:0
MansoryPane - Childrens count:2
MansoryPane - AnimationMap size:1
MansoryPane - Childrens count:3
MansoryPane - AnimationMap size:2
MansoryPane - Childrens count:4
MansoryPane - AnimationMap size:3
MansoryPane - Childrens count:0
MansoryPane - AnimationMap size:4
MansoryPane - Childrens count:1
MansoryPane - AnimationMap size:4
MansoryPane - Childrens count:2
MansoryPane - AnimationMap size:5
```

### 3. Possible solution

For me, a possible fix is to remove childs from `animationMap` when they are removed from children collection. This can be done on the existing `childrenListener` using:

```
for(Node removedNode : change.getRemoved()) {
    animationMap.remove(removedNode);
}
```
Since, i don't really know how the MasonryPane animation works, i don't know if it's really safe to remove `animationMap` entries in the `childrenListener`. 
Maybe there is other alternatives to fix this issue, so i will wait for feedbacks before submitting any PR. 

Thank you.

DropSnorz.

**Comment by jfoenixadmin** [comment]
Hello @DropSnorz,
Thanks for pointing out the issue 👍 , yes you are right `animationMap` is not being cleared when removing masonry pane children. I believe your solution is a valid solution, go ahead and create PR for the issue. 

Thanks again 👍 
Regards,
