### ISSUE TITLE
Can't change progressBar color in Java code

### ISSUE THREAD

**Issue by lozohcum** [jfoenixadmin/JFoenix#839]
I can't find a way to change the color of progress bar without using CSS. Looks like adding style in xml doesn't work.

Is it even possible? Can anyone give an example how to make progress bar orange just by using java code?

**Comment by ramprajapat94** [comment]
Yes, even i need this.

**Comment by jfoenixadmin** [comment]
currently there is no direct method for this, however you can use the method `lookup` to get a specific node and change its styling after being shown on the scene.
