### ISSUE TITLE
JFXListCell doesn't allow easy text change with a changed cellFactory

### ISSUE THREAD

**Issue by darksmall** [jfoenixadmin/JFoenix#84]
Hello, I have a JFXComboBox\<DataType> so I wrote a CellFactory to change the display, instead of the default DataType::toString() call. 

Unfortunately, since JFXListCell makes most of its behaviour in updateItem();, the code as in example 14-5 of the JafaFX documentation does not work properly. ([https://docs.oracle.com/javafx/2/ui_controls/combo-box.htm](https://docs.oracle.com/javafx/2/ui_controls/combo-box.htm))

Calling setText() completely messes JFXListCell.

There needs to be a way to nicely edit the text contents of the cell for factories.

ie:
```
JFXComboBox profesoresCB=...;
profesoresCB.setCellFactory(new Callback<ListView<Profesor>, ListCell<Profesor>>() {
      @Override
      public JFXListCell<Profesor> call(ListView<Profesor> param) {
        final JFXListCell<Profesor> cell = new JFXListCell<Profesor>() {
          @Override
          public void updateItem(Profesor item, boolean empty) {
            super.updateItem(item, empty);
            if (item != null && !empty) {
              setText(item.getNombreCompleto());
            } else {
              setText(null);
            }
          }
        };
        return cell;
      }
    });
```

This fucks up the JFXListCell.

**Comment by jfoenixadmin** [comment]
the implementation of JFXListCell might be changed, however in the mean time a work around for your issue would be to override the method toString() in the Professor class instead of changing the list cell factory.

**Comment by jfoenixadmin** [comment]
The JFXListCell has been updated, you can edit the cell content as you did,
but you need to call **_setGraphic(null)_** to remove its default content.

**Comment by jfoenixadmin** [comment]
JFXListCell has been updated, you can change the cell text using the previous code.
but you need to call the method _**setGraphic(null)**_ in order to remove its current content.

**Comment by Miha-x64** [comment]
Thanks, `setGraphic(null)` worked for me. But this was completely counterintuitive.
Shouldn't `toString()` be for debug purpose only?
