### ISSUE TITLE
jfxautocompletion show all data while run the project even not focused and typed. 

### ISSUE THREAD

**Issue by raghunath004** [jfoenixadmin/JFoenix#841]
jfxautocompletion show all data while run the project even not focused and typed.  i am using 4 to 6 textfields suggest me

**Comment by jfoenixadmin** [comment]
can you provide SSCCE for this issue?

**Comment by jfoenixadmin** [comment]
you are showing the autocomplete on text changed maybe you want to change that to focus changed. will close this issue as it's not valid.
Regards,
