### ISSUE TITLE
Buttons with Graphics aren't resizable properly

### ISSUE THREAD

**Issue by hitsu420** [jfoenixadmin/JFoenix#846]
Hey wonderful JFoenix team,
Is it possible to resize a JFXButton with a Graphic on it to the size of the Graphic?

So it isn't a wide rectangle like this
![image](https://user-images.githubusercontent.com/44146045/46922199-c8f95f00-d005-11e8-84b3-1f20b0b100ca.png)

But rather a square like in Chrome
![image](https://user-images.githubusercontent.com/44146045/46922204-e75f5a80-d005-11e8-8ad3-422d502fb9f3.png)

Btw, that "bug"  is also the case for usual JavaFX buttons
![image](https://user-images.githubusercontent.com/44146045/46922271-d9f6a000-d006-11e8-92c2-d1b3d18448dc.png)

I already tried resizing it in SceneBuilder, as well as in Code but it doesn't go smaller than in Image 1.
It seems to only be possible when I resize the SVGPath really small, which isn't what I want.

Thanks for any help! (I love jfoenix btw uwu)

**Comment by MarekKristof** [comment]
Hello, can i take it ?

**Comment by jfoenixadmin** [comment]
this issue is related to button's padding, will close this issue as it's not related to JFoenix development.
Regards,
