### ISSUE TITLE
JFXComboBox prompt overflow

### ISSUE THREAD

**Issue by TheTomTom3901** [jfoenixadmin/JFoenix#851]
Im really sorry to be doing this again but the style is not exactly what I was expecting, could it be formatted like the standard ComboBox where it uses an ellipsis if overflowing?

<img width="130" alt="screen shot 2018-10-18 at 23 06 13" src="https://user-images.githubusercontent.com/22203095/47206811-7ca17c80-d381-11e8-8fe1-3fd3926217f4.png">

Thanks again

**Comment by jfoenixadmin** [comment]
Currently, prompt text is using Text node which doesn't support ellipsis. feel free to add your own contribution to JFoenix.

Regards,
