### ISSUE TITLE
jfxautocompletion showing all data while run the project even not focused and typed

### ISSUE THREAD

**Issue by raghunath004** [jfoenixadmin/JFoenix#852]
job is textfield.

private void jobAutoComplete() {
autoCompletePopup.setSelectionHandler(event -> job.setText(event.getObject()));
autoCompletePopup.getSuggestions().clear();
autoCompletePopup.getSuggestions().addAll(jobData);
job.textProperty().addListener(observable -> {
autoCompletePopup.filter(s -> s.contains(job.getText()));
if (!autoCompletePopup.getFilteredSuggestions().isEmpty()) {
autoCompletePopup.show(job);
} else {
autoCompletePopup.hide();
}
});}

i used same code for others text fields

![image](https://user-images.githubusercontent.com/42633854/47209137-3e21b700-d3ad-11e8-9033-a94004cd1e79.png)

**Comment by jfoenixadmin** [comment]
According to your code, the autocomplete will be shown when invalidating the text property of the text field regardless of its focus state. you may want to consider focus state as well to fix this behavior.

Regards,
