### ISSUE TITLE
Scene is laggy when running and compiling

### ISSUE THREAD

**Issue by Lucky38i** [jfoenixadmin/JFoenix#853]
So I saw Jfoenix and decided to give it a go since it achieved material designed making my UI much nicer. But there's a few laggy situations. 

- Switching tabs is a freezing situation rather than smooth
- The Dialog box, when I call it via a button, causes the entire program to run at about 5fps till the dialog opens, upon closing it, it slows down again until normal.
- Adding the spinner while viewing the first tab causes scene builder and the spinner to perform horribly, whereas if I switch to the second tab the spinner and scene builder perform fine. When running the actual code the spinner spins smoothly.

It's a very nice UI and looks beautiful when performing smoothly and I'd really like to try and get these issues sorted. it may be with out I'm doing my layouts or not as this is only my second program in JavaFX

I've attached [gists](https://gist.github.com/Lucky38i/6e1d56a88faaeee2e8f85115c77ea758) for debugging

**Comment by jfoenixadmin** [comment]
Hello, 
the animation is laggy because you are using some text effects/strokes without caching the text nodes, try setting cache hint to SPEED  and cache to true. 
will close this issue as it's not related to JFoenix development.

Regards,

**Comment by jfoenixadmin** [comment]
Hello, 
the animation is laggy because you are using some text effects/strokes without caching the text nodes, try setting cache hint to SPEED  and cache to true. 
will close this issue as it's not related to JFoenix development.

Regards,

**Comment by Lucky38i** [comment]
> Hello,
> the animation is laggy because you are using some text effects/strokes without caching the text nodes, try setting cache hint to SPEED and cache to true.
> will close this issue as it's not related to JFoenix development.
> 
> Regards,

Hi, I'm a bit confused, which text nodes are being the most resource heavy and do I set the cache to true in the initialisation of the UI?
