### ISSUE TITLE
Disable default Left/Right Arrow Navigation  from Keyboard

### ISSUE THREAD

**Issue by goxr3plus** [jfoenixadmin/JFoenix#854]
Is there any way to disable the default right/left arrow from changing tabs on the TabPane :) ?

**Comment by goxr3plus** [comment]
@jfoenixadmin  Sorry for miss undestanding . I mean when the user presses the Left/Right arrows from the Keyboard :)

**Comment by jfoenixadmin** [comment]
I see, I think adding a key press/release filter will fix this. I

**Comment by goxr3plus** [comment]
Can i have some code? I have tried but no success.

**Comment by schlegel11** [comment]
Sure:

This suppresses(consumes) all incoming KeyEvents:

```java
...
    tabPane.addEventFilter(KeyEvent.ANY, Event::consume);
...
```
or use it more specific only on LeftRight Keys:

```java
...
    tabPane.addEventFilter(
        KeyEvent.ANY,
        event -> {
          if (EnumSet.of(KeyCode.LEFT, KeyCode.RIGHT).contains(event.getCode())) {
            event.consume();
          }
        });
...
```

Greetings

**Comment by goxr3plus** [comment]
3 years writing JavaFX and still i am impressed by the provided code.


Thank you unlimited ❤

**Comment by schlegel11** [comment]
You are welcome :smiley: 
Ah and you could also use the "isArrowKey()" method included in KeyCode Enum:

```java
...
    tabPane.addEventFilter(
        KeyEvent.ANY,
        event -> {
          if (event.getCode().isArrowKey()) {
            event.consume();
          }
        });
...
```
But this also includes the UP and DOWN and Numpad Arrow Keys. 
I dont know if this is the desired behaviour :wink:

**Comment by goxr3plus** [comment]
@schlegel11  I have one problem with that ... all the children that belong inside JFXTabPane don't receive arrow events anymore :( . 

What i really want is only the children inside to receive events and not the JFXTabPane.

**Comment by schlegel11** [comment]
Ah ok I see :wink: 
So you have to distinguish between the JFXTabPane and other Nodes in the dispatch hierarchy.
You can do it the following way:

We use the "event.getTarget()" method to get our target element. The event target is more or less the target element where this event belongs to or better where it was triggered.

If you have direct access to your JFXTabPane instance the solution is more simple:

```java
...
    tabPane.addEventFilter(
        KeyEvent.ANY,
        event -> {
          if (event.getCode().isArrowKey() && event.getTarget() == tabPane) {
            event.consume();
          }
        });
...
```
So in any case where a KeyEvent was triggered from a child element of tabPane the target element is not the tabPane instance itself and therefore the event isn't consumed.

if you don't have direct access to your JFXTabPane instance we could use the common Node Id as an identifier:


```java
...
    //We have to set an Id to the JFXTabPane
    tabPane.setId("__MyUniqueTabPaneId__");

...

    tabPane.addEventFilter(
        KeyEvent.ANY,
        event -> {
          // I think we can expected that the EventTarget represents always a Node but if a child element 
          // in tabPane isn't a Node we do a type check for safety.
         // If the cast or the getId method returns null we get an empty String.
          String eventTargetId =
              Optional.of(event.getTarget())
                      .filter(Node.class::isInstance)
                      .map(Node.class::cast)
                      .map(Node::getId).orElse("");

          if (event.getCode().isArrowKey() && eventTargetId.equals("__MyUniqueTabPaneId__")) {
            event.consume();
          }
        });
...
```

Now If the event target id is equal to our tabPane instance we consume the event.

**Comment by goxr3plus** [comment]
Socked ©_©. In Love. Thank you soo much, o my god you know so much!!!

**Comment by schlegel11** [comment]
No problem :smile: You are welcome.
So if you go with the second approach I would remove the isInstance check because currently I don't see any situation where event.getTarget() isn't a Node type. So you could write:

```java
...

    tabPane.addEventFilter(
        KeyEvent.ANY,
        event -> {

          String eventTargetId =
              Optional.of(event.getTarget())
                      .map(Node.class::cast)
                      .map(Node::getId).orElse("");

          if (event.getCode().isArrowKey() && eventTargetId.equals("__MyUniqueTabPaneId__")) {
            event.consume();
          }
        });
...
```
Maybe I'd still do it a little bit differently, because I tried to use a more functional approach with Optional. I'm currently not sure how the JVM handles such an Optional or if the performance decreases (ok anyway this small code part is so minimal I don't think the performance would suffer at all). So we could use also this approach:

```java
...

    tabPane.addEventFilter(
        KeyEvent.ANY,
        event -> {

          Node eventTarget = (Node) event.getTarget();
          String eventTargetId = eventTarget.getId();
          if (eventTargetId == null || !eventTargetId.equals("__MyUniqueTabPaneId__")) {
            return;
          }

          if (event.getCode().isArrowKey()) {
            event.consume();
          }
        });
...
```
Overall the impact of readability or performance should be minimal, so you can decide :wink:
