### ISSUE TITLE
JFXDialogLayout - Unable to set random heading background color

### ISSUE THREAD

**Issue by vigneshrcsengg** [jfoenixadmin/JFoenix#858]
I'm struggling to set style class/style into JFXDialogLayout. For my application, I'm trying to show the alert using JFXDialogLayout with various header colour based on user interaction.

For example,

Error  -  Show dialog header in RED colour
Info  -  Show dialog header in GREEN colour
default    -  Show dialog header in BLUE color (defined in CSS -jfx-layout-heading: background-color: blue)

I was trying to apply CSS class to JFXDialogLayout also fails.. setStyle().

How to apply random JFXDialogLayout header colour??

**Comment by vigneshrcsengg** [comment]
Hello

Any update?

**Comment by jfoenixadmin** [comment]
you can use custome Pseudo classes in css, a class for each type. then to style it  u can use the following css:

```
.jfx-dialog-layout:someclass > .jfx-dialog-heading {
    -fx-background-color: RED;
}
```
Regards,

**Comment by vigneshrcsengg** [comment]
So in CSS

`.jfx-dialog-layout:someclass > .jfx-dialog-heading {
    -fx-background-color: RED;
}`

and in Java

`JFXDialogLayout dialogLayout = new JFXDialogLayout();
 dialogLayout.getStyleClass().add("someclass");`

is correct??

**Comment by vigneshrcsengg** [comment]
Hello

Please review the above code, is it correct?? I'm not getting the result as expected.

**Comment by jfoenixadmin** [comment]
that's not how you apply css in JavaFX , you can check this <a href="https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html">link</a> for more info about javafx css and pseudo classes.

Regards,
