### ISSUE TITLE
Change distance between JFXDatePicker textfield and glyph button

### ISSUE THREAD

**Issue by mej71** [jfoenixadmin/JFoenix#859]
I cannot find any css or setting to change the distance between the textfield for JFXDatePicker and the glyph button.  In my application, it is placed a bit too far away for my taste.

**Comment by jfoenixadmin** [comment]
you can use the following css:

```
.jfx-date-picker > .arrow-button{
    -fx-padding: 1 8 1 yourvalue;
}
```

Regards,
