### ISSUE TITLE
 please. as I can apply this style ?

### ISSUE THREAD

**Issue by diegodesdecolombia** [jfoenixadmin/JFoenix#86]
![sin titulo](https://cloud.githubusercontent.com/assets/6775620/14728038/cc19f2b4-07f6-11e6-8d6b-571135c64789.png)

**Comment by jfoenixadmin** [comment]
you can get this style by applying the following css:
<pre>
.jfx-text-field Line{
	-fx-stroke-width:1;
	-fx-translate-y:0;
}
</pre>
