### ISSUE TITLE
Should JFXColorPickers have a fixed minHeight?

### ISSUE THREAD

**Issue by KilianB** [jfoenixadmin/JFoenix#860]
I just came across an issue that JFXColorpickers disappear inside a fit to height scroll pane if the windows gets resized. On the one hand I see that unlike other components they might be embedded inside other controls which require color pickers to be re-sizable, but is the current behavior really desired?

![colorpicker](https://user-images.githubusercontent.com/9025925/47573394-7ab95980-d93d-11e8-8150-399420da39cf.png)

**Comment by jfoenixadmin** [comment]
Hello, 
yeah sure, thanks for pointing out the issue 👍
