### ISSUE TITLE
More properties in JFXChipView

### ISSUE THREAD

**Issue by tomriddly** [jfoenixadmin/JFoenix#866]
JFoenix is such a great library. Here is a small advice of JFXChipView.

I just want to add a chip with text in the text area while chipview is not focused. 
At first, I tried `focusedProperty()` of view itself, but the event was not triggered.
Then, I tried whether I can get TextArea of view. I tried everything and got nothing but only `getAccessibleText()`, which is definitely not what I want.
After that, I went through the source code of JFXChipView and found JFXChipViewSkin which is what I could work around. But `view.getSkin().getChildren()` was `null`.
    At last, I finished my target with code as flow which is weird and not elegant:
```java
@FXML
private JFXChipView<String> view;
...
JFXChipViewSkin<String> skin = new JFXChipViewSkin<>(view);
    view.setSkin(skin);
    TextArea textArea = (TextArea) ((FlowPane)skin.getChildren().get(0)).getChildren().get(0);
    textArea.focusedProperty().addListener((obs, oldValue, newValue) -> {
        if (!newValue) {
            if (StringUtils.isNotBlank(textArea.getText())) {
                view.getChips().add(textArea.getText());
                textArea.clear();
            }
        }
    });
```

The problems I found was:
1. `focusedProperty()` is not working.
2. TextArea or text in TextArea is not reachable with property in JFXChipView. To get them requests some hack trick.

THX~~

**Comment by jfoenixadmin** [comment]
Hello @tomriddly , can you provide a SSCCE demonstrating the issue?

**Comment by tomriddly** [comment]
JDK:1.8.0_191
jfoenix:8.0.7
I make a simple scene with JFXChipView and a button. I hope to get the event when focus changed.
But the console will only output a `true` and a `false` at very beginning and no longer answer my click operation.

![demo](https://user-images.githubusercontent.com/14344444/47907362-11e65a00-dec6-11e8-8235-7e51f2abadf5.gif)

Besides, there is no such a function which can get text area of chipview.

test/test.fxml:
```xml
<?import com.jfoenix.controls.JFXChipView?>
<?import javafx.scene.control.Button?>
<?import javafx.scene.layout.AnchorPane?>

<AnchorPane prefHeight="262.0" prefWidth="298.0" style="-fx-background-color: black;" xmlns="http://javafx.com/javafx/8.0.171" xmlns:fx="http://javafx.com/fxml/1" fx:controller="test.testController">
   <children>
      <JFXChipView fx:id="view" style="-fx-background-color: white;" />
      <Button layoutX="166.0" layoutY="73.0" mnemonicParsing="false" text="Button" />
   </children>
</AnchorPane>
```

test/testController.java:
```java
package test;

import java.net.URL;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXChipView;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;

public class testController implements Initializable {
    @FXML
    JFXChipView<String> view;

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        view.focusedProperty().addListener((obs, oldValue, newValue) -> {
            System.out.println(newValue);
        });
    }

}
```

test/Main.java
```
package test;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

public class Main extends Application {

    public static void main(String[] args) {

        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        AnchorPane mainPanel = FXMLLoader.load(getClass().getResource("/test/test.fxml"));
        Scene scene = new Scene(mainPanel, 1000, 400);
        Stage stage = new Stage();
        stage.setScene(scene);
        stage.show();
    }

}
```

**Comment by tomriddly** [comment]
The purpose can be achieved by unpacking children of JFXChipViewSkin. But I thought a offical method should be provided.

![2](https://user-images.githubusercontent.com/14344444/47907902-1c552380-dec7-11e8-8243-305f9b0b876b.gif)

```java
package test;

import java.net.URL;
import java.util.ResourceBundle;

import com.jfoenix.controls.JFXChipView;
import com.jfoenix.skins.JFXChipViewSkin;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextArea;
import javafx.scene.layout.FlowPane;
import org.apache.commons.lang.StringUtils;

public class testController implements Initializable {
    @FXML
    JFXChipView<String> view;

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        JFXChipViewSkin<String> skin = new JFXChipViewSkin<>(view);
        view.setSkin(skin);
        TextArea textArea = (TextArea) ((FlowPane)skin.getChildren().get(0)).getChildren().get(0);
        textArea.focusedProperty().addListener((obs, oldValue, newValue) -> {
            System.out.println(newValue);
            if (!newValue) {
                if (StringUtils.isNotBlank(textArea.getText())) {
                    view.getChips().add(textArea.getText());
                    textArea.clear();
                }
            }
        });
    }

}

```

**Comment by jfoenixadmin** [comment]
Hello @tomriddly, 
this issue has been fixed <a href="https://github.com/jfoenixadmin/JFoenix/commit/643ce0354b728042cb5be9a044b3a4440d3bfacd#diff-6e1b8127b710cac4b779f49f287beb48">recently</a>. However there is no build that includes this fix yet. it will be included in the next build, hopefully by the end of this month.

Regards,
