### ISSUE TITLE
When update the maven repository

### ISSUE THREAD

**Issue by Dan2712** [jfoenixadmin/JFoenix#872]
The lastest version on maven is 9.0.6, that is not including /transitions/template folder. SO the demo is not working with the maven building.
Pls help updating, many thx!

**Comment by schlegel11** [comment]
Hi,
I don't know exactly the release cycle but I think I've read in another issue something about "end of month".
I hope I can do some advertising :wink: 
If you are interested in the JFXAnimationTemplate stuff and also the demo, I created a separate project:
[JFXAnimation](https://github.com/schlegel11/JFXAnimation)

If the implementation is also included in the next JFoenix release you can remove the JFXAnimation dependency and rename the import packages.

Greetings

**Comment by DfM7** [comment]
So is the new release already near? 😃

**Comment by jfoenixadmin** [comment]
Hello, 
I just released new JFoenix jars `*.*.8` , they will be available in a couple of hours on maven central.

Regards,

**Comment by DfM7** [comment]
I guess that this issue can be closed now. 😉
