### ISSUE TITLE
Proguard building error

### ISSUE THREAD

**Issue by bigenergy** [jfoenixadmin/JFoenix#873]
Log: https://pastebin.com/uFTbSTrY

I just added jfoenix via compile 'com.jfoenix:jfoenix:8.0.7', 
Proguard: 
-keeppackagenames com.jfoenix.**
-keep class com.jfoenix.*

**Comment by jfoenixadmin** [comment]
i think there is a mismatch with the java version you are using.
I'll close this issue as it's not related to JFoenix dev.

Regards,

**Comment by dzivi** [comment]
I have the same error. And I am using com.jfoenix:jfoenix:8.0.8 and java 8. How can I solve this error in that case?
