### ISSUE TITLE
JFXTextField prompt text opacity

### ISSUE THREAD

**Issue by EoneRizuwan** [jfoenixadmin/JFoenix#876]
Hi, I've an issue with JFXTextField components. The prompt text opacity is too clear that I hardly differentiate either the text is a prompt or a normal text. 

![jfxtextfield](https://user-images.githubusercontent.com/44917063/48771193-9ecd4800-ecfb-11e8-8626-f9772b2c77a4.PNG)

I can fix it if I put styling on the field, `-fx-prompt-text-fill` and set it to gray, but that would be inconvenience to type it every time when I set a new text field. I've seen others have no problem on this, but it seems only on mine. I don't know if it an issue with Scene Builder or JFeonix itself.

I'm using JFeonix 8.0.7 on Gluon Scene Builder 8.5.0.

**Comment by jfoenixadmin** [comment]
you can change the prompt text fill in a css file and apply it to your scene instead of adding it to every text field.

Regards,
