### ISSUE TITLE
Jar export version issues

### ISSUE THREAD

**Issue by sarankup** [jfoenixadmin/JFoenix#881]
I have done my development and I am planning to distribute my app as JAR file. I am using JDK 9, and here is the command I have been trying to export jar

`mvn jfx:jar`

But I am getting the following error. Please advise how to resolve.
`
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:8.8.3:jar (default-cli) on project silk: Execution default-cli of goal com.zenjava:javafx-maven-plugin:8.8.3:jar failed: Plugin com.zenjava:javafx-maven-plugin:8.8.3 or one of its dependencies could not be resolved: Could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20 at specified path /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/../lib/ant-javafx.jar -> [Help 1]

`

**Comment by jfoenixadmin** [comment]
Hello,
I can't see any relation to jfoenix here, it seems there is some wrong dependency related to javafx-packager in your project.
I'll close this issue as it's not related to JFoenix.
Regards,

**Comment by Atrebao** [comment]
Bonjour depuis un moment j'essaie de lancer mon application et voici l'erreur qui apparait dans la console : 
Modules fontawesomefx.glyphsbrowser.all and controlsfx export package impl.org.controlsfx.behavior to module org.eclipse.fx.ide.css.jfx8
