### ISSUE TITLE
DatePicker not using default color on header

### ISSUE THREAD

**Issue by DJViking** [jfoenixadmin/JFoenix#882]
I have a root style which seems to affect the DatePicker header area not using the default color.
![jfoenix-datepicker-wrong](https://user-images.githubusercontent.com/3070076/49072496-a7101080-f230-11e8-924d-799f1e776611.png) ![jfoenix-timepicker-right](https://user-images.githubusercontent.com/3070076/49072505-a9726a80-f230-11e8-9d1d-abdd7f7d9080.png)

As you can see the DatePicker header area is not green.

This is also evident when changing the default color:

```
.jfx-date-picker {
    -jfx-default-color: rgb(100, 100, 100);
}

.jfx-time-picker {
    -jfx-default-color: rgb(100, 100, 100);
}
```
![jfoenix-datepicker](https://user-images.githubusercontent.com/3070076/49072580-ce66dd80-f230-11e8-81fc-a1ae93c24699.png) ![jfoenix-timepicker](https://user-images.githubusercontent.com/3070076/49072590-d3c42800-f230-11e8-9a32-20accf6468f4.png)

This is my root css style:

```
.root {
    -fx-base: rgb(240, 240, 240);
    -fx-background: rgb(240, 240, 240);
    -fx-border-color: rgb(220, 220, 220);

    /* make controls (buttons, thumb, etc.) slightly lighter */
    -fx-color: derive(-fx-base, 10%);

    /* text fields and table rows background */
    -fx-control-inner-background: rgb(248, 248, 248);
    /* version of -fx-control-inner-background for alternative rows */
    -fx-control-inner-background-alt: derive(-fx-control-inner-background, -2.5%);

    /* text colors depending on background's brightness */
    -fx-light-text-color: rgb(220, 220, 220);
    -fx-mid-text-color: rgb(100, 100, 100);
    -fx-dark-text-color: rgb(20, 20, 20);

    /* A bright blue for highlighting/accenting objects.  For example: selected
     * text; selected items in menus, lists, trees, and tables; progress bars */
    -fx-accent: rgb(0, 80, 100);

    /* color of non-focused yet selected elements */
    -fx-selection-bar-non-focused: rgb(50, 50, 50);

    -fx-font-family: "Roboto"; /* "Segoe UI Semibold", "Roboto", "Monospaced" */
    -fx-font-size: 1em;
}
```

**Comment by jfoenixadmin** [comment]
Thanks @DJViking for pointing out the issue 👍 
Regards,
