### ISSUE TITLE
JFXButton Rippler

### ISSUE THREAD

**Issue by abbestrov** [jfoenixadmin/JFoenix#883]
The rippler in JFXButton doesn't work on rotating (90 and -90 degrees).

**Comment by BulaMar** [comment]
Hi, recently had same problem.
Here is SSCCE:
```
public class Main extends Application {

    @Override
    public void start(Stage stage) {
        JFXButton leftButton = new JFXButton("Rotated Button");
        
        leftButton.rotateProperty().setValue(-90); // <-> no ripple effect anymore

        final Scene scene = new Scene(leftButton, 800, 800);
        stage.setScene(scene);
        stage.setResizable(true);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

Is there any solution for that or currently ripple effect is working only for none-rotated buttons?
Should I do a ripple mask on my own then? 

Thanks

**Comment by jfoenixadmin** [comment]
Hello,
Well, this issue is caused by using `CacheHint.SPEED`. Which is very important for the animation performance.
I don't recommend using Rotations/Scale transformations to layout nodes on the scene. For example, to create a rotated button you can try the following instead:

```
JFXButton leftButton = new JFXButton();
Label  label  = new Label("Rotated Button");
label.setRotate(-90);
leftButton.setGraphic(new Group(label));
```
Regards,
