### ISSUE TITLE
Add a JFXDateTimePicker

### ISSUE THREAD

**Issue by DJViking** [jfoenixadmin/JFoenix#884]
It could be useful to have a combined control with DatePicker and TimePicker and only one text field.

One text field for a datetime string (yyyy-MM-dd'T'hh:mm.ss.SSS), and two buttons for DatePicker and TimePicker.

    JFXDateTimePicker picker = new JFXDateTimePicker();
    picker.setValue(LocalDateTime.now());
    DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS");
    StringConverter<LocalDateTime> defaultDateTimeConverter =
                new LocalDateTimeStringConverter(timeFormatter, timeFormatter);

**Comment by Vuvyka** [comment]
hi there, some dirty work done, not ready to pull request, but it's fully functional and seems not buggy:
https://github.com/Vuvyka/jfoenix-JFXDateTimePicker
