### ISSUE TITLE
LabelFloat when setText()

### ISSUE THREAD

**Issue by RobinMalfait** [jfoenixadmin/JFoenix#89]
Hello,

When we are trying to set the text of a JFXTextField, the label is not moved to the top and we get weird quircks like this: 

![](http://d.pr/i/1hxfB+) 

where the text and prompt-text are merged.

Any thoughts how to fix this or what we are doing wrong?

```java
@FXML
JFXTextField someField;

someField.setText("0"); // Not working
```

/cc @DemianD

**Comment by jfoenixadmin** [comment]
Hello, thanks for pointing out the issue. it's been fixed, feel free to test on the latest version of JFoenix.
you can download the latest jar from the link: 

http://www.jfoenix.com/download/jfoenix.jar

or from maven snapshot repo:
<pre>
repositories {
    maven {
       url "https://oss.sonatype.org/content/groups/public"
    }
}
dependencies { 
    compile 'com.jfoenix:jfoenix:0.0.0-SNAPSHOT'    
}
</pre>

**Comment by RobinMalfait** [comment]
Hmm thanks for the quick response but I think it is not fixed yet. Let me show you some code and a little video:

Video: http://d.pr/v/1igOX

And some code we used:

````java
import com.jfoenix.controls.JFXTextField;

public class AddProductController extends VBox
{
    @FXML
    private JFXTextField txfName;

    @FXML
    private JFXTextField txfAmount;

    @FXML
    private JFXTextField txfAmountUnavailable;

    @FXML
    private JFXTextField txfPrice;

    @FXML
    private void buttonAddProductAction(ActionEvent event) {
        
        // ...
        
       if(txfPrice.getText().isEmpty())
           txfPrice.setText("0");
       if(txfAmount.getText().isEmpty())
           txfAmount.setText("0");
       if(txfAmountUnavailable.getText().isEmpty())
           txfAmountUnavailable.setText("0");

       //...
            
    }
}
```

**Comment by jfoenixadmin** [comment]
fixed :)

**Comment by RobinMalfait** [comment]
Thank you very much, this fixed it!
