### ISSUE TITLE
[Bug] JFXDatePicker "Chinese environment week display" workaround leads to error

### ISSUE THREAD

**Issue by jjyyxx** [jfoenixadmin/JFoenix#893]
When I develop with zh-CN as the default locale, the JFXDatePicker fails to render due to the following code segment:
https://github.com/jfoenixadmin/JFoenix/blob/9f53564b49e1db075593ab6029ee058a28bd9203/jfoenix/src/main/java/com/jfoenix/skins/JFXDatePickerContent.java#L559-L564

In `L561`, the code expects something with the structure of "星期x" like "星期一"(Monday), "星期二"(Tuesday), and extracts the "x" ("一", "二").

However, in my version of JDK (10.0.2), the locale has the structure of "周x" like "周一"(Monday), "周二"(Tuesday). The "星期x" and "周x" share identical “x“, but have different length, so `name.substring(2, 3)` leads to **error** in my environment.

I'm Chinese. And I'm sure that in chinese, "星期x" and "周x" are the only two common ways to express days of a week. So **getting the last character of the zh-CN locale string** could be a simple and safe fix.  

If it's necessary, I can contribute a pr to fix this :smile:.

**Comment by jjyyxx** [comment]
Since the minor fix has been merged, is there a schedule for the next 9.0.x release? Currently, I have to workaround by setting default locale to English.

**Comment by jfoenixadmin** [comment]
The next release will be by the end of January 2019
