### ISSUE TITLE
Please avoid streams

### ISSUE THREAD

**Issue by rjahn** [jfoenixadmin/JFoenix#9]
You have an IntStream in JFXListViewSkin. This is no problem for JavaFX on desktop, but if you try to use JFoenix on mobile devices, this dependency would be a problem.

There's a backport of streams: http://sourceforge.net/projects/streamsupport/
Use this lib or simply replace the stream code.

Both worked in my case.

**Comment by jfoenixadmin** [comment]
thanks for pointing this, we are aware of this issue and we already replaced all streams code guess we missed this class.
