### ISSUE TITLE
Mnemonic Actions still execute behind modal JFXDialog

### ISSUE THREAD

**Issue by hpjerico** [jfoenixadmin/JFoenix#900]
Hello, when we bring up a modal JFXDialog, the mnemonic actions that are configured behind it are still executing.  Is there a way to prevent this from happening?  We have the mnemonic "ALT + F" configured to execute one command on our main scene and a different command when the JFXDialog is opened.  When the dialog is opened, the mnemonic configured on the main scene still executes even.

**Comment by jfoenixadmin** [comment]
Hello,
JFXDialog opens in the the same stage. Try using JFXAlert instead.

Regards,
