### ISSUE TITLE
Java 11: JFXSnackbar doesn't dismiss after timeout

### ISSUE THREAD

**Issue by RohitAwate** [jfoenixadmin/JFoenix#901]
I'm trying to migrate [Everest](https://github.com/RohitAwate/Everest) to Java 11 and hence made the shift to JFoenix 9.0.8.

![snackbar](https://user-images.githubusercontent.com/23148259/50331113-939c5080-0523-11e9-86e9-67ba9eafd81d.gif)
_(This is supposed to be a 3000ms timeout)_

The snackbar does show up, but doesn't dismiss after the timeout.

```java
public class SnackbarChannel extends JFXSnackbar implements Channel {
    private Label label = new Label();

    public SnackbarChannel(Pane container) {
        super(container);
    }

    @Override
    public void push(String message, long duration) {
        label.setText(message);
        enqueue(new SnackbarEvent(label, Duration.seconds(duration), null));
    }
}
```

Am I doing something incorrectly here or is this a bug/WIP?

**Comment by jfoenixadmin** [comment]
plz note that you are using seconds instead of milliseconds.
will close this issue as it's not valid.

Regards,

**Comment by RohitAwate** [comment]
Oops, that's embarrassing. Sorry about that.
Thanks! :)
