### ISSUE TITLE
JFXcheckbox on start some checkboxes have radial fill 

### ISSUE THREAD

**Issue by tbenne10** [jfoenixadmin/JFoenix#902]
<img width="68" alt="screen shot 2018-12-22 at 12 18 23 pm" src="https://user-images.githubusercontent.com/22963234/50377947-4df38c80-05e4-11e9-9f79-b0068f12307d.png">

Tested issue with multiple FXML documents and JavaFX controller code. Having multiple JFXcheckboxes will leave a persistent radial fill on a random checkbox upon application
start that disappears when checked/unchecked. 

Checkbox in photo is checked by default in application start. Independent of color, size, and placement.  Invoked solely by the loading of an fxml document and is unrelated to use of checkboxes in application code. Unknown source of issue

Reproduction: Mac OSX, IntelliJ IDEA Ultimate and Community edition
                         Java SDK 10 with level 10 Project language level
                         No frameworks/build tools 

FXML: 
`<JFXCheckBox fx:id="d1" checkedColor="#e46a6b" layoutY="14.0" text="*some text*" textFill="#fffbfb" unCheckedColor="#649ea1" /> `

Controller:
 `@FXML
    private JFXCheckBox d1;`

Each repeated 5 times in series and varying IDs

**Comment by jfoenixadmin** [comment]
Hello, 
the radial fill the focus indicator, you can disable it by code or css by setting disable visual focus property (`-jfx-disable-visual-focus`) to false.

Regards,

**Comment by tbenne10** [comment]
Thank you!
