### ISSUE TITLE
JFXDatePicker - Change background color in controller.

### ISSUE THREAD

**Issue by luis-alves** [jfoenixadmin/JFoenix#903]
Can't find a way to change the DatePicker input field background color to red, when the user inputs, manually, an invalid input format.
Is this possible to do, in the controller class?

**Comment by jfoenixadmin** [comment]
you can change it using the following css:
```
.jfx-date-picker > .jfx-text-field{
    -fx-background-color: Blue;
}
```
in case of error, simply add `error` pseudo class to the picker style class.

Regards,
