### ISSUE TITLE
Not downloading JFoenix maven dependencies in intelijeidea 

### ISSUE THREAD

**Issue by jayamaljayamaha** [jfoenixadmin/JFoenix#905]
I am using java 1.8 so I used JFoenix 8. I added maven dependency to pom.xml file but dependencies were not downloaded to my project and in pom.xml file said that "cannot resolve JFoenix artifact descriptor"
is that a bug or anything that I did wrong?

**Comment by jfoenixadmin** [comment]
make sure you are adding the correct descriptor in your pom file

**Comment by jayamaljayamaha** [comment]
What is the correct descriptor ?? Can you please send me the link?

**Comment by jfoenixadmin** [comment]
For example:

```
<dependency>
  <groupId>com.jfoenix</groupId>
  <artifactId>jfoenix</artifactId>
  <version>8.0.8</version>
</dependency>
```
