### ISSUE TITLE
Is possible use more 3 colors on JFXFillTransition?

### ISSUE THREAD

**Issue by bogdanbaghiu** [jfoenixadmin/JFoenix#907]
Hello. I think that is possible use 3 or more color Fill Transition? For example now is possible set From value color and To Value Color, but intermediary colors not possible. I working with Java 8 and jfoenix-8.0.8

**Comment by schlegel11** [comment]
Hi,
yes it is possible but you have to use a SequentialTransition. With this transition you can chain e.g. multiple JFXFillTransition's like:

```java
     // root is my root Region
    JFXFillTransition transitionA =
        new JFXFillTransition(Duration.seconds(5), root, Color.AQUA, Color.CRIMSON);

    JFXFillTransition transitionB =
        new JFXFillTransition(Duration.seconds(5), root, Color.CRIMSON, Color.DARKBLUE);

    SequentialTransition sequentialTransition = new SequentialTransition(transitionA, transitionB);
    sequentialTransition.play();
```

Greetings

**Comment by bogdanbaghiu** [comment]
Thanks @schlegel11 
Greetings
