### ISSUE TITLE
JFXDialog remove instance from the container onClose

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#91]
Hi,
I think you should remove the jfxdialog instance from its container after it is closed. In order to save the close effect, its better to do the removal when animation finished; Unfortunately, the close event is still sent before animation finishing. For now, it's a workaround:

        dialog.close();
        jfxcontainer.getChildren().remove(dialog);

**Comment by jfoenixadmin** [comment]
Hi, thanks for pointing out the issue. the close event is now sent at the end of the animation and the dialog is being removed from its container.

**Comment by aminabs** [comment]
Works fine. Thanks.
BTW, I've reported a new issue with the latest jfoenix.jar you provided above.
