### ISSUE TITLE
Card View

### ISSUE THREAD

**Issue by sacOO7** [jfoenixadmin/JFoenix#92]
Can you add Cardview to jfoenix and other material design components like fab, nav drawer etc?

**Comment by jfoenixadmin** [comment]
fab and the drawer already there, check JFXDrawer and JFXButton. 
the cardview might be added later, however is not planned yet. 
Feel free to add your own contribution to JFoenix :)

Regards,

**Comment by hendraanggrian** [comment]
would love to see simple CardView as well

**Comment by Asim-A** [comment]
A cardview would be awesom!
