### ISSUE TITLE
JFXDatepicker : can't set date to 30 dec 2018

### ISSUE THREAD

**Issue by lenikhilsingh** [jfoenixadmin/JFoenix#921]
Hello, i'm currently using the java version "1.8.0_161".  So, the issue is, when i select 30th december 2018  or 31st december 2018 in JFXDatePicker, The date that appears selected is 30th december 2019 and 31st december 2019 respectively. Same goes with 2019 too and so on. But, 30th december 2017(or 31st december 2017) is very possible. 

![screenshot 51](https://user-images.githubusercontent.com/30202672/51404539-bb5df300-1b79-11e9-89da-c0a28739a68e.png)

**Comment by schlegel11** [comment]
Hi,
I couldn't directly reproduce your issue but I tried a little bit around and found maybe a solution for your issue or a new issue :wink: 
See #922 

Greetings

**Comment by jfoenixadmin** [comment]
@lenikhilsingh can you provide a SSCCE demonstrating the issue? as i was not able to reproduce it.
