### ISSUE TITLE
JFoenix 8.0.8 is buggy (JFXDialog.show(StackPane) causes crash)

### ISSUE THREAD

**Issue by PeratX** [jfoenixadmin/JFoenix#925]
I saw this bug has been fixed in fce51526dd44f51ce274925b4846eee3fdc0f9a9
Please release a new version.

**Comment by PeratX** [comment]
Everything ok with the 8.0.7. 👍

**Comment by Ammaccabananee** [comment]
Nevermind, I've discovered by myself that was my fault, as with 8.0.7 I was setting up both setLimitColumn and setLimitRow to -1, to have them limitless.
It seems like with 8.0.8 setting up setLimitRow to -1 causes my JFXMasonryPane to behave bad.
