### ISSUE TITLE
Autocomplete in JFXTextArea for multiple words

### ISSUE THREAD

**Issue by Ligandfas** [jfoenixadmin/JFoenix#926]
Hi,
 Is it possible to implement autocomplete for a JFXTextArea for each word typed or on the start of each sentence or line . 
Thanks

**Comment by jfoenixadmin** [comment]
Hi, 
Yes it's possible. You can check JFXChipView implementation for a simple example.

Regards,

**Comment by Ligandfas** [comment]
Hey,

Thank you . I already know that option but I wanted to do it with JFXTextArea I mean without chips

Thanks
