### ISSUE TITLE
bug JFXDatepicker TAIWAN should be added

### ISSUE THREAD

**Issue by dudylan** [jfoenixadmin/JFoenix#927]
![image](https://user-images.githubusercontent.com/34180156/51663855-e4a3d680-1ff2-11e9-86ff-2115f1a249ac.png)

Specify the location as shown above

TAIWAN should be added

**Comment by dudylan** [comment]
Sorry,What is SSCCE?

**Comment by DfM7** [comment]
@dudylan Short, Self Contained, Correct Example.
See [sscce.org](http://sscce.org/).
