### ISSUE TITLE
PropertyNotFoundException with JFXTextField

### ISSUE THREAD

**Issue by syednoman84** [jfoenixadmin/JFoenix#928]
Hello JFoenix Team

This is similar to Issue # 41 but I am having this problem with JFXTextField. I am using your latest jar version 8.0.8 downloaded from this repository for Java 8. After I save my .fxml file with Margin property set for the JFXTextField and try to open it from Eclipse in Scene Builder, I get the attached error. If I do not set the margin property, then I am able to open my .fxml file in Scene Builder without any issues. 

Please help me with this and excuse me for any silly questions as I am newbie.

I am attaching both the error stack and my fxml code as Text files here.

[myFXMLFileCode.txt](https://github.com/jfoenixadmin/JFoenix/files/2799216/myFXMLFileCode.txt)

[ErrorStack_JFXTextField.txt](https://github.com/jfoenixadmin/JFoenix/files/2799215/ErrorStack_JFXTextField.txt)

Thanks for your help and support.

Looking forward to use this library as much as I can :)

**Comment by schlegel11** [comment]
Hi,
hmm I haven't used the integrated scenebuilder in eclipse but I tried your FXML in the standalone version of the gluon scenebuilder and in IntelliJ IDE. There were no problems.
Maybe it's a eclipse issue.
If you want you can try it with the gluon scenebuilder directly:
[https://gluonhq.com/products/scene-builder/](https://gluonhq.com/products/scene-builder/)

Greetings

**Comment by syednoman84** [comment]
Thanks for the prompt response. I will give it a shot and see what happens. I will keep you updated if I make any progress. One thing I noticed that although this error comes up when I am trying to open the fxml from Eclipse but when I run the project, the JVM does not throw any error and loads my application perfectly.

Once again, thanks for your time and support.

**Comment by schlegel11** [comment]
Your welcome :smiley:

**Comment by syednoman84** [comment]
Just an update. The problem got resolved after I used the latest version of Scene Builder from this link https://gluonhq.com/products/scene-builder/ 

Thanks for your time and support.
