### ISSUE TITLE
JFXTabPane: Previous Tab is still selected when click other tabs 

### ISSUE THREAD

**Issue by Linkadi98** [jfoenixadmin/JFoenix#929]
Hello, I'm working on a java application which I use JFXTabPane inside. So, the issue here is when I select one tab and next I select the second one, the previous tab is still selected, I have to double click on the second tab then the second tab is selected. I have tried many ways but the issue still appears. What I want is I just need one click and the tab is selected. The method getSelectedModel().getSelectedItem() always returns the previous tab when select the second one. How do I fix this issue? It's very uncomfortable to me.

**Comment by jfoenixadmin** [comment]
@Linkadi98 can you provide a SSCCE for the issue?

**Comment by Linkadi98** [comment]
Hi Jfoenixadmin, I solve my problem yesterday, I used JFXTabpane mouse pressed listener and a selected change listener so that was the cause of my problem. When I click on the tab in tab pane, it (probably the listener) listens both mouse pressed event and the change of selection of tabs event so it makes conflict here. Sorry about not being careful in debugging :).
