### ISSUE TITLE
Unwanted Code ?

### ISSUE THREAD

**Issue by TheItachiUchiha** [jfoenixadmin/JFoenix#93]
Is there a reason why `Interpolator.LINEAR` is mentioned in multiple places like [JFXSpinner](https://github.com/jfoenixadmin/JFoenix/blob/master/src/com/jfoenix/controls/JFXSpinner.java#L99), [JFXRippler](https://github.com/jfoenixadmin/JFoenix/blob/master/src/com/jfoenix/controls/JFXRippler.java#L294) etc. ?

The default Interpolator of  `KeyFrame` is `Interpolator.LINEAR`. If there isn't a reason for its existence, we can remove the noise from the code. I will be more than happy to raise a PR.

**Comment by jfoenixadmin** [comment]
It's fine, I'd rather keep it in code in case the default interpolator has been changed.
Regards,
