### ISSUE TITLE
How do I make a dropdown button?

### ISSUE THREAD

**Issue by Linkadi98** [jfoenixadmin/JFoenix#930]
Like the question above, drop down button is a button which I move the pointer to it, it's gonna drop a group of buttons, or simply when I click on the button, it will drop a group of buttons. I know the standard menu button or split menu button is what I need if someone suggests me, but I want a new drop down button that has beautiful animation or simply it's just beautiful than the standard one. How do I deal with this? I can start with changing css of menu button or split button, but, is there a better idea for this issue? 
Thank you for paying attention to this issue.

**Comment by jfoenixadmin** [comment]
you can use JFXNodesList, an example is already included in the demo.

Regards,
