### ISSUE TITLE
Undesired CSS styling of Popups

### ISSUE THREAD

**Issue by mej71** [jfoenixadmin/JFoenix#933]
If you specify a background color in .root, it colors a previously hidden sub-window

Bolded line added to demo's main css
.root {
    **-fx-background-color: #051b27;**
    -fx-font-family: "Roboto";
    -fx-font-smoothing-type: gray;
}

results in
![e3099d0a1043caa4a68f5dd21f3332f4](https://user-images.githubusercontent.com/10199000/52080643-479eeb80-2566-11e9-8e53-465b423b0f2e.png)

And I can't find the styling class for that sub-window

**Comment by jfoenixadmin** [comment]
@mej71 thanks for pointing out the issue 👍
