### ISSUE TITLE
Transparent border around JFXPopup

### ISSUE THREAD

**Issue by michaelhelmbrecht** [jfoenixadmin/JFoenix#934]
Hello,

I got a problem with JFXPopup. There is an approximately 10px transparent border around the popup and i'm not able to remove it.

If anyone can help me, I would be very grateful.

**Comment by dulkith** [comment]
Add -fx-effect: null; 
in your CSS for the ContextMenu

**Comment by jfoenixadmin** [comment]
@michaelhelmbrecht can you add a screenshot?
