### ISSUE TITLE
DrawerStack got Null Exception

### ISSUE THREAD

**Issue by Linkadi98** [jfoenixadmin/JFoenix#939]
Hi all,
I have a problem with JFXDrawerStack. I put 2 drawers on drawer stack, one is on left, the other is on right. I also use hamburger and a button to control how drawers appear. So, when I pressed hamburger to show the first drawer, and then I pressed the button to show the second drawer, no error. But, when I closed the second drawer and pressed hamburger again, I got an exception.
This is exception:
`Caused by: java.lang.NullPointerException: Children: child node is null: parent = StackPane@2cbed098
	at javafx.graphics/javafx.scene.Parent$3.onProposedChange(Parent.java:546)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at com.jfoenix.controls.JFXDrawer.setContent(JFXDrawer.java:634)
	at com.jfoenix.controls.JFXDrawersStack.updateDrawerPosition(JFXDrawersStack.java:164)
	at com.jfoenix.controls.JFXDrawersStack.toggle(JFXDrawersStack.java:185)
	at Controllers.MainController.hamburgerOnMousePressed(MainController.java:74)`

And this is the error line:
`drawerStack.toggle(infoDrawer);`

I have done a null checking infoDrawer if it is null but the infoDrawer is not null at all. 
This is the initialize method:
`@Override
    public void initialize(URL location, ResourceBundle resources) {
        StackPane infoPane = new StackPane();
        StackPane humanPane = new StackPane();
        drawer = new JFXDrawer();
        infoDrawer = new JFXDrawer();

        hamburgerArrow = new HamburgerBasicCloseTransition(hamburger);
        hamburgerArrow.setRate(-1);
        FXMLLoader menuLoader = new FXMLLoader(getClass().getResource("/FXMLS/Menu.fxml"));
        try {
            humanPane.getChildren().add(menuLoader.load());
        } catch (IOException e) {
            e.printStackTrace();
        }
        drawer.setDefaultDrawerSize(200);
        drawer.setSidePane(humanPane);

        FXMLLoader infoLoader = new FXMLLoader(getClass().getResource("/FXMLS/Info.fxml"));
        try {
            infoPane.getChildren().add(infoLoader.load());
        } catch (IOException e) {
            e.printStackTrace();
        }

        infoDrawer.setSidePane(infoPane);
        infoDrawer.setDefaultDrawerSize(200);
        infoDrawer.setDirection(JFXDrawer.DrawerDirection.LEFT);
        drawer.setDirection(JFXDrawer.DrawerDirection.RIGHT);
    }`

and 

`public void humanOnMousePressed(MouseEvent mouseEvent) {
        drawerStack.toggle(drawer);
    }
`

is no error. why?

What's wrong in this code? 
I don't know how to fix this. I did this because in the demo about the drawer stack, admins did the same things but nothing was gone wrong.

**Comment by Linkadi98** [comment]
In the first press, 2 drawers was very normal, but after pressing the button and pressing the hamburger again, the first drawer disappeared and throw an exception like above

**Comment by jfoenixadmin** [comment]
According to the exception, you are setting a null value as the drawer content.
Make sure you initialized all variables properly.

Regards,
