### ISSUE TITLE
AwsomeIcon validation

### ISSUE THREAD

**Issue by Natreve** [jfoenixadmin/JFoenix#94]
validator.setAwsomeIcon(new Icon(AwesomeIcon.WARNING,"2em",";","error"));    
Gives an error "The method setAwsomeIcon(Icon) is undefined for the type RequiredFieldValidator"
Where can I get the class with with the methods?

**Comment by jfoenixadmin** [comment]
use the method validator.**setIcon**(new Icon(AwesomeIcon.WARNING,"2em",";","error"))
setIcon takes Node object as a parameter.

**Comment by xchz** [comment]
AwsomeIcon is another library？i can not find AwsomeIcon class in this repository

**Comment by xchz** [comment]
i find that library...
```
<dependency>
    <groupId>de.jensd</groupId>
    <artifactId>fontawesomefx</artifactId>
    <version>8.9</version>
</dependency>
```

**Comment by xchz** [comment]
`new Icon(AwesomeIcon.WARNING,"2em",";","error")`  AwesomeIcon replace with FontAwesomeIcon?

**Comment by xchz** [comment]
i can not find Icon class .....

**Comment by skmedix** [comment]
@xchz https://github.com/jfoenixadmin/JFoenix/blob/master/demo/build.gradle#L14

**Comment by xchz** [comment]
@skmedix thank you, i have found that library. i just use maven, so i dont know how to read gradle config file...
