### ISSUE TITLE
Possible new control JFXRippleRect

### ISSUE THREAD

**Issue by ayushchadha23** [jfoenixadmin/JFoenix#940]
Hi,First thank you for this amazing project jfoenix team, i intend to contribute to this project with a new control JFXRippleRect shown in action in like below
[link](https://youtu.be/9ZQfePRXg28)
JFXRippleRect can be use for changing UI i.e changing ui from log in to register, Changing color schemes etc. 
Any suggestions will be appreciated.
 I Hope you will like it!

**Comment by ayushchadha23** [comment]
PS i have a crappy video editor that is why the video is rough

**Comment by jfoenixadmin** [comment]
Hi @ayushchadha23 looking forward for the new control :)

**Comment by ayushchadha23** [comment]
@jfoenixadmin Thank you!  But before adding JFXRippleRect to jfoenix, i want to know what the community thinks about it

**Comment by Ammaccabananee** [comment]
@ayushchadha23 
You have all my interest, Sir

**Comment by ayushchadha23** [comment]
@jfoenixadmin  I  have issued a pull request to merge JFXRippleRect with JFoenix..
