### ISSUE TITLE
JFXTreeTableView error

### ISSUE THREAD

**Issue by Ligandfas** [jfoenixadmin/JFoenix#944]
Hi ,
With JFXTreeTableView I am using the editing feature and getting the rowvalue, every thing is ok when I don't use the seaching feature . Indeed after making the search for an item and getting the table sorted when calling getrowvalue it gets me wrong values
for example this table
![1erro](https://user-images.githubusercontent.com/18163788/53037831-85af7100-347b-11e9-8cbc-7aa332b55b5a.PNG)
and then when sorting and calling getRowValue from the CellEditevent instead of getting "moliere" I'm getting "glissa" 
![erro2](https://user-images.githubusercontent.com/18163788/53038016-f8b8e780-347b-11e9-9066-db4d9be47dec.PNG)

**Comment by jfoenixadmin** [comment]
Hi @Ligandfas, can you provide a SSCCE demonstrating the issue?

**Comment by Ligandfas** [comment]
hey @jfoenixadmin  thank you Problem solved , I was making the stupid mistake of recreating the treetableView before calling getRowValue()
