### ISSUE TITLE
my upload function recuperate path without backslash

### ISSUE THREAD

**Issue by sarragdroura** [jfoenixadmin/JFoenix#946]
@FXML
    private void upload(ActionEvent event) {
       FileChooser fc = new FileChooser();
      fc.setTitle("upload Image");
      fc.getExtensionFilters().add(new ExtensionFilter("load image","*.*" ));
      File f=fc.showOpenDialog(null);
      if(f !=null)
      {
          tf_image.setText(f.getAbsolutePath());
         
      }
    }
![capture](https://user-images.githubusercontent.com/47931096/53341821-dce69300-390c-11e9-8694-7f05467a1f9e.PNG)

**Comment by jfoenixadmin** [comment]
@sarragdroura what does this has to do with JFoenix?
