### ISSUE TITLE
Top drawer can not open smoothly 

### ISSUE THREAD

**Issue by Linkadi98** [jfoenixadmin/JFoenix#948]
Hi all, 
I have set a drawer stack at the center of the border pane. Then, I have set a top drawer. When initializing all components, nothing error. But, when I firstly pressed button which handled drawer's opening, it took almost 1 second to open the top drawer, which was not my expect. How can I make the drawer more responsively? Sorry if i have bad english. 
Thank you.

**Comment by jfoenixadmin** [comment]
Hi @Linkadi98,
Can you provide a SSCCE demonstrating the issue?
I've added recently a caching policy to JFXDrawer which you need to set manually, it might help solving the issue.

Regards,

**Comment by Linkadi98** [comment]
Hello @jfoenixadmin,
My problem seems to be appeared when I set a fxml file on the drawers of drawer stack. They open very slowly, while opening other which I don't set any fxml file is very fast. Did I make mistake why try to set content for drawers?
Here is my demo code, I put all things in a function, then in initialize method, i just call that method:

` private void prepareDrawerContent() throws IOException {
        List<Pair<JFXDrawer, String> > drawers = new ArrayList<>();
        profileDrawer = new JFXDrawer();
        peopleDrawer = new JFXDrawer();
        newOrderDrawer = new JFXDrawer();
        homeDrawer = new JFXDrawer();
        orderHistoryDrawer = new JFXDrawer();
        billDrawer = new JFXDrawer();

        drawers.add(new Pair<>(profileDrawer, "/fxmls/Account.fxml"));
        drawers.add(new Pair<>(peopleDrawer, "/fxmls/People.fxml"));
        drawers.add(new Pair<>(newOrderDrawer, "/fxmls/NewOrder.fxml"));
        drawers.add(new Pair<>(orderHistoryDrawer, "/fxmls/History.fxml"));

        listDrawer.add(new KeyValue<>(false, profileDrawer));
        listDrawer.add(new KeyValue<>(false, newOrderDrawer));
        listDrawer.add(new KeyValue<>(false, homeDrawer));
        listDrawer.add(new KeyValue<>(false, orderHistoryDrawer));

        for(Pair<JFXDrawer, String> pair: drawers) {
            FXMLLoader loader = new FXMLLoader(getClass().getResource(pair.getValue()));
            StackPane pane = new StackPane();
            pane.getChildren().add(loader.load());
            pair.getKey().setSidePane(pane);
//            pair.getKey().setDefaultDrawerSize(768);
            
            pair.getKey().setDirection(JFXDrawer.DrawerDirection.TOP);
        }`
One more thing, it is about the resizing of drawer. I can not make the drawer resizable when set it to the center of the border pane? how do I do that? Jfoenix has or will provide a method to do that?
Thank you for helping me.

**Comment by jfoenixadmin** [comment]
Try optimizing the drawer side content, heavy nodes that contain effects / custom fonts might drastically affect the animation performance. JavaFX node caching (`setCache`, `setCacheHint`) might help you solve the issue.

Regarding BorderPane issue, can you provide a SSCCE for it?

**Comment by Linkadi98** [comment]
Hi admin,
Thank you for your solution, I will try it immidiately.
The borderpane problem, the code I’ve given to you is what I can provide. The problem, basically, when the window is maximized, the drawer is still have the default size, which is 768 like above. Ive looked for the source code of jfxdrawer and I’ve seen the method updateSize(), I have tried to set it myself to update the size of the drawer when I maximize the window, but, unfortunately, the size is not changed. That is the new problem. 
Thank you for your help.

**Comment by jfoenixadmin** [comment]
Hi @Linkadi98,
Well resizing feature in JFXDrawer allows the user to expand the drawer size beyond its original size while dragging (It doesn't handle updating the parent size). Also the method `updateSize` doesn't actually change the drawer size, it just updates the bounds on the drawer size.

Regards,

**Comment by Linkadi98** [comment]
Thank you!
