### ISSUE TITLE
JFXSnackbar non default constuctor causes  NPE

### ISSUE THREAD

**Issue by aminabs** [jfoenixadmin/JFoenix#95]
Hi,
I've got an NPE while trying to use the latest jfoenix.jar (which you provided 2 hours ago). The exception occurs when I try to create a jfxsnackbar using this command:
    new JFXSnackbar(somePane);
If I use the default constructor and then call .registerSnackbarContainer it works fine too.

Note that this works fine with jfoenix version 'jfoenix-0.0.0-20160321.094207',

It seems the listener is null:

`Caused by: java.lang.NullPointerException 	at com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:67) 	at javafx.beans.property.ReadOnlyDoubleWrapper$ReadOnlyPropertyImpl.addListener(ReadOnlyDoubleWrapper.java:168) 	at com.jfoenix.controls.JFXSnackbar.registerSnackbarContainer(JFXSnackbar.java:163) 	at com.jfoenix.controls.JFXSnackbar.<init>(JFXSnackbar.java:126)`

**Comment by jfoenixadmin** [comment]
it's been fixed, thanks for pointing out the issue.

**Comment by aminabs** [comment]
So, did you update the latest jfoenix.jar on jfonix.com?
