### ISSUE TITLE
JFX Highlighter clear does not clear highlights

### ISSUE THREAD

**Issue by CaptainDaVinci** [jfoenixadmin/JFoenix#951]
I have a single instance of `JFXHighlighter`, and I pass `javafx.scene.control.Labeled` as the parent on which `query` string is to be searched, however on calling `clear()` method the highlights still remain.

**Comment by jfoenixadmin** [comment]
Hi @CaptainDaVinci can you provide SSCCE demonstrating the issue?

**Comment by jfoenixadmin** [comment]
will close this issue as @CaptainDaVinci  didn't respond

**Comment by hoanghun** [comment]
I have the same issue as CaptainDaVinci.

Passing `JFXTextArea` as Parent, if the word to be highlighted exactly matches the word in the text area **the highlight gets darker**. After calling `clear()` method it clears everything except the dark highlight.
