### ISSUE TITLE
Featured Commuinty Control :) Vote is required 

### ISSUE THREAD

**Issue by jfoenixadmin** [jfoenixadmin/JFoenix#952]
Hello JFoenix community :),

Since I have some free time at the moment, I've decided to add a new control to JFoenix.
To make this more interesting, I would like to make it a collaborative decision. Which means, the community will decide on the next new control :).

So let's start by collecting some suggestions/likes in the next few days. The most liked control will be implemented in JFoenix.

(Hint: try to keep it simple :p)

**Comment by DropSnorz** [comment]
Hi ! Really good news :)  

Voted ! I've put a 👍 in 2 issues flagged with _New Control_ label

**Comment by jfoenixadmin** [comment]
so let's see, here are the suggestions

- Material spotlight effect #751 
- JFXTooltip #440
- JFXNotifications #439 is excluded as @TioCoding might do a PR in the future, let's hope so :p

so it's either Spotlight or Tooltip, suggestions are still open.

**Comment by TioCoding** [comment]
I have not done a PR because @jfoenixadmin did not react to my publication #439  with a "like" :c ... Hahahaha.

Seriously speaking, I was not entirely satisfied with the design, and for lack of time I could not improve it: /, I had also forgotten a little about the "JFX Notification" control. But now I feel more motivated to finish it. I was thinking about creating 2 JFXNotification controls, one like the one that presents # 439 JFXSimpleNotification (Simple notification), and another more advanced and customized one like the official material design JFXNotification.

@jfoenixadmin What do you think about the idea?

**Comment by TioCoding** [comment]
By the way, I vote for this control #910 :P

**Comment by jfoenixadmin** [comment]
@TioCoding , there you go all the emojis I can give :p 

I think 1 JFXNotification is enough, however the user should be able to change the content (Graphic). Which means 1 Control but several content layouts. So if the user didn't set the graphic property, the default graphic will be created using the text and type properties. (type properties should be applied as pseudo classes, better performance / css readability). 
@TioCoding go ahead and submit a PR for it and we can improve it together :)

**Comment by Ammaccabananee** [comment]
Wonderful idea!
My vote certainly belongs to #751

**Comment by jfoenixadmin** [comment]
so far the next control seems to be JFXTooltip

**Comment by skmedix** [comment]
It's worth to consider changing current JFXSnackbar behavior to:
https://material.io/design/components/snackbars.html#behavior

**Comment by jfoenixadmin** [comment]
@skmedix I'm summing the number of reactions on each issue labeled as New Control :p
Regarding, JFXSnackbar and JFXTextField I agree with you maybe I'll schedule those changes in the future.

**Comment by jfoenixadmin** [comment]
The voting ends, and the next control will be JFXTooltip

**Comment by jfoenixadmin** [comment]
Hello, 
I just pushed JFXTooltip implementation to github, it will be included in the next JFoenix release :)

Regards,

**Comment by skmedix** [comment]
Awesome! I'll test this out later today
