### ISSUE TITLE
TabPane in a Drawer

### ISSUE THREAD

**Issue by Claydelas** [jfoenixadmin/JFoenix#953]
I've been trying to implement a JFXTabPane in a JFXDrawer as a side navigation for the past few days, but I can't get the actual tabs to display content. I believe it's because a tab's content pane is attached to the side of the tab itself, and in this case, the drawer overlays it. However it could be a mistake on my part as I'm just learning javafx. Is there a workaround or is it just a limitation?

**Comment by jfoenixadmin** [comment]
Hello, @Claydelas 
can you provide a SSCCE demonstrating the issue?

**Comment by Claydelas** [comment]
I've uploaded the core files for the example here:
https://github.com/Claydelas/tabpane-drawer-interaction-sample
Cheers!
