### ISSUE TITLE
Can't run Jfoenix in Intellij idea

### ISSUE THREAD

**Issue by jack5505** [jfoenixadmin/JFoenix#954]
I downloaded  project into Idea but I can't run it in proper way when I try to run MainDemo class it gives following errors
Error:java: invalid flag: -release
![image](https://user-images.githubusercontent.com/20322245/54632355-ba750f00-4a9f-11e9-84d3-64ba61814952.png)
what might be reason

**Comment by jfoenixadmin** [comment]
JFoenix has 2 branches, master for Java 8 and JFoenix-9.0.0 for Java 9. Make sure you are using a compatible version with the installed JRE
