### ISSUE TITLE
JFeonix TabPane Tab Label Text Not Sharp

### ISSUE THREAD

**Issue by mickey4u** [jfoenixadmin/JFoenix#958]
I am using the JTabPane but it appears the text within the Tab content (tab label) is not sharp. Is there a way to fix this @jfoenixadmin.

![Capture](https://user-images.githubusercontent.com/15174041/54705596-19389800-4b35-11e9-9017-122e0269c5e0.PNG)

**Comment by DannPeterson** [comment]
I have same issue, some kind of shadow effect, i can't find out, how to fix this. 
![blur](https://user-images.githubusercontent.com/48986272/55070830-bfcded00-508f-11e9-841b-0f5a591efe30.png)

**Comment by mickey4u** [comment]
@DannPeterson In my case the tab was placed inside a TitledPane, so what I did was I took the tabpane out of and placed it in an AnchorPane and text look sharp  now. I don't know the parent layout of your tabpane, you try a similar approach and see if solves your problem.

**Comment by jfoenixadmin** [comment]
@DannPeterson Tab pane header has a shadow effect, and it seems you set the header background to transparent. thus the shadow effect will be applied directly to the text.
