### ISSUE TITLE
Help with JFXPopup please! :)

### ISSUE THREAD

**Issue by JoshidCoates** [jfoenixadmin/JFoenix#961]
Hello,
I'm trying to get the height of a pop-up but it is returning 0.
This is most likely because the pop-up hasn't been shown yet.
I've tried getPopupContent().getHeight() but that also returns 0.
Thanks,
Joshid

I'm trying to stop the pop-up from displaying off-screen; code: 

        // Show the pop-up when the button is pressed
        colourBlockButton.setOnMouseClicked((event) -> {

            // Get the height of the pop-up
            double popupHeight = changeWorkPeriodPopup.getPopupContent().getHeight();

            // Get the current height of the scene
            double currentSceneHeight = ((Node) event.getSource()).getScene().getHeight();

            System.out.println("Pop-up Height: " + popupHeight);
            System.out.println("Mouse Height: " + event.getSceneY());
            System.out.println("Scene Height: " + currentSceneHeight);

            // If the mouse Y position added to the height of the pop-up is less than or equal to the size of the scene, then display the pop-up to the bottom right of the mouse
            if (event.getSceneY() + popupHeight <= currentSceneHeight) {
                changeWorkPeriodPopup.show(colourBlockButton, JFXPopup.PopupVPosition.TOP, JFXPopup.PopupHPosition.LEFT, event.getX(), event.getY());

                // Otherwise display the pop-up to the top right of the mouse
            } else {
                changeWorkPeriodPopup.show(colourBlockButton, JFXPopup.PopupVPosition.BOTTOM, JFXPopup.PopupHPosition.LEFT, event.getX(), event.getY());
            }

        });

**Comment by jfoenixadmin** [comment]
Currently JFXPopup doesn't consider screen bounds, feel free to add your own contribution to JFoenix 
Regards,
