### ISSUE TITLE
Cannot add padding to TextField Text WITHOUT moving line

### ISSUE THREAD

**Issue by pablo67340** [jfoenixadmin/JFoenix#963]
I am trying to give this textfield some padding ONLY on the text. Having it right against the beginning of the line looks odd and I feel it needs padding of just a few px. When I add padding to the textfield, it also pads the line with the text, So if the text is moved 3px right, the bottom line does as well, making it look much worse.

TextField I am editing: https://gyazo.com/280658bf71d6a6bdea585a1991c68359

What I want it to look like: https://gyazo.com/acbdd9af1cd8a45e9ecbff7cf74a3ca1

This is with a padding of 5px, You can see the line moves too: https://gyazo.com/fbd2019897cb124e2d34cfa69c288579

Is there any other selectors I can use to specifically target the text and not the input line? Seeing as I cannot use :not I am not sure where to go from here.

**Comment by jfoenixadmin** [comment]
Currently that's not doable, feel free to add your own contribution to JFoenix

Regards,

**Comment by pablo67340** [comment]
Could I ask for the reasoning why those 2 elements are bonded together? Was it a bug? Workaround for something? Just trying to get an idea of what to look for if I were to contribute this enhancement.
