### ISSUE TITLE
Can't close JFXDrawer when one of its elements is clicked

### ISSUE THREAD

**Issue by WilliamAboucaya** [jfoenixadmin/JFoenix#964]
Hello!

I'm trying to close a JFXDrawer when one of the elements in its JFXListView is clicked. Unfortunately, when I click an element, the closing animation plays but the JFXDrawer re-opens itself immediately after the end of the animation.
My implementation is close to the demo folder of this repo, with the following changes:

In MainController.java, after the initialization of the **context** attribute:
```java
        ...
        context.register("drawer", drawer);
        
        // set the default controller
        ...
```
In SideMenuController.java, replace the **bindNodeToController** method with:
```java
        ...
        private void bindNodeToController(Node node, Class<?> controllerClass, Flow flow, FlowHandler flowHandler) {
            flow.withGlobalTaskAction(node.getId(), () -> {
                JFXDrawer drawer = (JFXDrawer) context.getRegisteredObject("drawer");
                drawer.close();
            });
        }
        ...
```

Am I doing something wrong? Is there another way to implement this feature? I'm using Java 11 with OpenJFX 11 and JFoenix 9.0.8

Thanks,
William

**Comment by jfoenixadmin** [comment]
Hello,
Maybe someplace in your code, you are recalling the open/toggle method.

**Comment by WilliamAboucaya** [comment]
Hello, 

The rest of the code is strictly identical to the one in the demo folder. I only have one other toggle/open in the code (in the `MainController.init` method, inside the `titleBurgerContainer.setOnMouseClicked`) but it isn't called when I click an element of the JFXListView.

I have just found out that sometimes, randomly, the drawer behaves the right way. It isn't dependent to the element clicked but happens more often the first times I click one of them.

**Comment by jfoenixadmin** [comment]
@WilliamAboucaya can provide SSCCE demonstrating the issue?

**Comment by WilliamAboucaya** [comment]
@jfoenixadmin Sure! It is available in this repo: [https://github.com/WilliamAboucaya/jFoenixBugSSCCE/tree/master]

**Comment by jfoenixadmin** [comment]
Try removing `sideMenuFlowHandler.handle(newVal.getId());` it might solve the issue.
I'll close this issue as it seems related to DataFX usage.

Regards,

**Comment by WilliamAboucaya** [comment]
Thanks for the reply but this is not solving the issue, it is just disabling the bugged feature.
I will try to find a solution and eventually post it on this issue.

Regards,
