### ISSUE TITLE
Add graphic support to text/password fields.

### ISSUE THREAD

**Issue by t-jd** [jfoenixadmin/JFoenix#965]
I use JFoenix a lot in my project and for me and other developers it would be really useful to have a possibility to add icon (graphic) into **JFXTextField**, **JFXPasswordField** like with **JFXButton**, so I can add, for example: **FontAwesomeIconView** to any text field and specify a position in the fields where the icon should be shown (left, right...).

I've been searching in google for an existing solution but with no result.
Thanks.

**Comment by TimurJD** [comment]
@jfoenixadmin Hi, are there any updates?

**Comment by jfoenixadmin** [comment]
Hi @TimurJD ,
No updates regarding this feature, feel free to add your own contribution to JFoenix.

Regards,

**Comment by TimurJD** [comment]
Hi @jfoenixadmin,
Ok, I will try🙂
