### ISSUE TITLE
JFXScollPane banner/top bar has unstable shading/rendering

### ISSUE THREAD

**Issue by SwissCheese5** [jfoenixadmin/JFoenix#968]
![2019-03-30_21-43-29](https://user-images.githubusercontent.com/7407478/55280954-874f3d00-5335-11e9-832c-aa23d1a8f492.gif)

The top bar goes transparent mid-way through, attempting to transition between images when there's nothing but solid color. This occurs with 2 different colors as well, you can see the scroll bar peaking through a little mid-way through because the bar tries to fade between colors but does so improperly. 
This is why the transparency is leaking.

Not only that, but there's a weird render issue where there's a very vibrant and obvious and unstable white line in the separation between the bar and the content panel.

**Comment by SwissCheese5** [comment]
Another rendering issue with the scroll pane: The background content leaves an outline around it's child content pane

![image](https://user-images.githubusercontent.com/7407478/55429833-0bebc680-5595-11e9-8d72-d6a31ab96f33.png)

**Comment by jfoenixadmin** [comment]
@SwissCheese5 can you provide a SSCCE demonstrating the issue?

**Comment by SwissCheese5** [comment]
@jfoenixadmin I thought the images would be self explanatory, but basically:

The first issue is the fading between two images or colors in the scrollpane header is not a 1 to 1 inverse fade. Transparency leaks through mid-way through the scroll and you can see the scroll bar appear behind the header as well as see the whole header turn into a brighter color because it's essentially transparent in mid-transition, leaking the color behind it which makes it look transparent.

The scroll pane is a very normal scroll pane, the header is set to the same color in both full and condensed mode

```
					spotifyImportScrollPane.setAlignment(Pos.CENTER);
					spotifyImportScrollPane.getMainHeader().setStyle("-fx-background-color: " + ColorScheme.mainColorDarker.hashColor);
					spotifyImportScrollPane.getCondensedHeader().setStyle("-fx-background-color: " + ColorScheme.mainColorDarker.hashColor);
					spotifyImportScrollPane.setStyle("-fx-background-color: " + ColorScheme.mainColorDarkest.hashColor);
					homePane.getChildren().add(spotifyImportScrollPane);
```

This image is full view header
![image](https://user-images.githubusercontent.com/7407478/55506842-1b374680-565f-11e9-8f06-c6f1e7d3229c.png)

This is the condensed view header
![image](https://user-images.githubusercontent.com/7407478/55506884-2c805300-565f-11e9-89b4-97e365e4b67e.png)

And this is the transition in between
![image](https://user-images.githubusercontent.com/7407478/55506902-3904ab80-565f-11e9-90c9-b61c4be77e23.png)

As you can see, transparency leaks mid-way through because the transition between the two is not a perfect 1-1 fade. You can see the scroll bar peaking through the transparency in the mid-position.


The second issue is the content pane inside the scroll pane.
If you look at the code, I'm setting the scrollpane's background color to the same dark color as the headers `					spotifyImportScrollPane.setStyle("-fx-background-color: " + ColorScheme.mainColorDarkest.hashColor);
`
But it seams the node does not support styling on it's main pane. So it's left as white. I've reported this issue separately.
The main issue to highlight here is that the white background has highlighted the rendering issue where it's child node (the content pane added here) is a few pixels too small and reveals the white outline of the background to leak through the edges of the content pane.

![image](https://user-images.githubusercontent.com/7407478/55507220-d9f36680-565f-11e9-9d4d-377e8b5ec3fa.png)
It's very clear, there's a white border around the scroll pane's content node. The content node is a vbox, it extends to the edges of the parent, so the vbox is not the issue, rather the scroll pane's content node is the issue where it's not allowing the node/vbox to expand to the edges/corners.

I hope i managed to get the idea across.
