### ISSUE TITLE
Open JDK 11 project in Intellij  can't detect JFoenix 

### ISSUE THREAD

**Issue by rigorio** [jfoenixadmin/JFoenix#972]
My pom file:
```
    <!-- JavaFX dependencies -->
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-controls</artifactId>
      <version>11</version>
    </dependency>
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-fxml</artifactId>
      <version>11</version>
    </dependency>

    <!-- JFoenix UI -->
    <dependency>
      <groupId>com.jfoenix</groupId>
      <artifactId>jfoenix</artifactId>
      <version>9.0.8</version>
    </dependency>
```

Scenebuilder: gluon imported in intellij (I'm not using the separate Scene Builder application, it's added in intellij)

Whenever I try to use JFoenix, it's found in the fxml, but when I open it in intellij Scene Builder, it just throws me this error:

> java.lang.UnsupportedClassVersionError: com/jfoenix/controls/JFXTextField has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by rigorio** [comment]
More info, I tried doing it via external gluon scene builder app. I imported the JFoenix 9 jar. Added JFoenix components. Then run the application. It's working. So I see the problem is with intellij. Does anybody know a fix with this?

**Comment by GillHargun** [comment]
I got the same problem.  Scenebuilder: gluon imported in intellij (I'm not using the separate Scene Builder application, it's added in intellij)

Whenever I try to use JFoenix, it's found in the fxml, but when I open it in intellij Scene Builder, it just throws me this error:
java.lang.UnsupportedClassVersionError: com/jfoenix/controls/JFXTextField has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by jfoenixadmin** [comment]
It seems you are using incompatible versions of JFoenix/SceneBuilder
JFoenix 9 build is for Java 9 while SceneBuilder build used in intellj is for Java 8
