### ISSUE TITLE
Can not use intellij scenebuilder with jfoenix

### ISSUE THREAD

**Issue by dulkith** [jfoenixadmin/JFoenix#974]
Error:
`java.lang.UnsupportedClassVersionError: com/jfoenix/controls/JFXButton has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

**Comment by jfoenixadmin** [comment]
Make sure you are using a compatible version of JFoenix with the running JRE.
