### ISSUE TITLE
why jfoenix.jar for java8 have no JFButton?

### ISSUE THREAD

**Issue by ljh95** [jfoenixadmin/JFoenix#978]
can't use JFButton on java8??

**Comment by skmedix** [comment]
U mean `JFXButton`? It's in both 8.x and 9.x JFoenix editions

**Comment by ljh95** [comment]
this is for java8 version JFoenix when it open SceneBuilder
<img width="225" alt="java8" src="https://user-images.githubusercontent.com/40597662/55671136-a450b680-58c7-11e9-9bd9-d0ee0fff67d9.png">

and this is for java9 version JFoenix when it open SceneBuilder
<img width="229" alt="java9" src="https://user-images.githubusercontent.com/40597662/55671150-c77b6600-58c7-11e9-8bfd-e2ab4ac1b3d6.png">

i did wrong..?

**Comment by Linkadi98** [comment]
Hi, 
You should move to Java 9 or Java 10 to use JFXButton if you can not find it in Jfoenix for java 8. I had the same problem but I moved to JFoenix for java 9 and JFXButton came back. Java 8 is old and no longer supported by Oracle so the better idiea is switch to the newer version of Java.

**Comment by ljh95** [comment]
Thank you advice to me 
But Our Team already dicision to use java8 ..ㅠㅠ

i really want to use JFoenix.. anyway thank you !!

**Comment by skmedix** [comment]
The problem is with your Scene Builder, make sure you're using the latest version (J8 - 8.5.0), for me with build-in Scene Builder in Intellij IDEA, JFXButton is clearly visible

**Comment by ljh95** [comment]
I'm success!! Thanks a lot!! bb!

Thank you Thank you~~!!

**Comment by Riteshverma11** [comment]
ljh95 how do you fixed it? i mean you switched to java 9 or still on java 8. If you still using java 8 then let me know how you've fixed this issue. Thanks please help

**Comment by cristhian-net** [comment]
> ljh95 how do you fixed it? i mean you switched to java 9 or still on java 8. If you still using java 8 then let me know how you've fixed this issue. Thanks please help

I've downgraded SceneBuilder V11 to V8 (For Java8), and it shows all the options now. Cheers

**Comment by Riteshverma11** [comment]
i coundn't fixed this issue in java 8 so, i upgraded java version to 9
