### ISSUE TITLE
JFXScrollPane remove/disable mainHeader

### ISSUE THREAD

**Issue by Teodor95** [jfoenixadmin/JFoenix#979]
Hello, 
it is possible to remove/disable mainHeader in JFXScrollPane? 
I've tried this:
```
this.chatListScrollPane.getMainHeader().setMinSize(0,0);
this.chatListScrollPane.getMainHeader().setMaxSize(0,0);
this.chatListScrollPane.getMainHeader().setMaxHeight(0);
this.chatListScrollPane.getMainHeader().setMinHeight(0);
```

<img width="619" alt="Schermata 2019-04-08 alle 11 09 20" src="https://user-images.githubusercontent.com/15701619/55712328-d577d680-59ee-11e9-95e0-0027fc3fbbf2.png">
Thank you.

**Comment by jfoenixadmin** [comment]
Hello,
@Teodor95, I suggest using JavaFX ScrollPane instead of JFXScrollPane. 
Regards,
