### ISSUE TITLE
Time JFXDatePicker

### ISSUE THREAD

**Issue by AshrafKACIMI** [jfoenixadmin/JFoenix#98]
Hello,

The JFXDatePicker, when chosen with the time option does not correctly parse the selected time. In fact, the following error occurs:

`Exception in thread "JavaFX Application Thread" java.time.format.DateTimeParseException: Text '2:17 AM' could not be parsed, unparsed text found at index 4`

I have tried it both in my own application and in the demo.

Any suggestions ?

**Comment by jfoenixadmin** [comment]
Hello, Which java version are you using?

**Comment by AshrafKACIMI** [comment]
I am using JDK 1.8u73.

**Comment by Quentame** [comment]
Hello,

This bug exists from months ago.
It is triggered when JFoenix is not used with a non English like locale, so the LocalTimeStringConverter crash.

To solve it, you just needs to precise in the LocalTimeStringConverter constructor : Locale.ENGLISH

I don't know how to make a pull request when it's not my project, but I'll try a bit later.

Also that might be cool to internationalize the TimePicker.
It looks like this in French, and obviously in Spanish too: 
![timepicker24h](https://cloud.githubusercontent.com/assets/14821482/15121944/1a40dbcc-161d-11e6-9017-15915ccfcfc1.png)

Thanks.

**Comment by AshrafKACIMI** [comment]
Hello,

Adding  Locale.ENGLISH to the LocalTimeStringConverter constructor in the JFXTimePickerContent.java file worked perfectly.

Thank you for you answer.

**Comment by GNorbi** [comment]
Please someone tell me how to fix it. THX!! I cant edit the constructor becouse i use jfoenix.jar
