### ISSUE TITLE
JFXDatePicker shows random data

### ISSUE THREAD

**Issue by marinaionel** [jfoenixadmin/JFoenix#981]
Hello, I used JFoenix elements in a project yesterday but when I reopened the file in Scene Builder it shows random characters. I deleted and then added again the jar file to Scenene Builder, but nothing changed. How can I solve this?
![image](https://user-images.githubusercontent.com/19744901/55937586-99848180-5c39-11e9-9491-f0a05b58c39f.png)

**Comment by jfoenixadmin** [comment]
Hi @marinaionel 
I think this is related to Locale you are using, try changing the default locale.
Regards

**Comment by marinaionel** [comment]
Thanks for your answer. I tried to change the locale but it is the same. What else can you suggest?

**Comment by jfoenixadmin** [comment]
try changing the default language of your operating system
