### ISSUE TITLE
IllegalAccessException for JFXTextField / JFXPasswordField with JDK12

### ISSUE THREAD

**Issue by jonathansim97** [jfoenixadmin/JFoenix#986]
I found the same problem as the issue raised [here](https://github.com/jfoenixadmin/JFoenix/issues/966) where using JFXTextField and/or JFXPasswordField returns an IllegalAccessException especially on JFXTextFieldSkin trying to access a member of class javafx.scene.control.skin.TextFieldSkin which seems to be private.

I can open the FXML file using Scene Builder by Gluon (outside of InteliJ) but I can't build it with the built in Scene Builder within InteliJ. 

Anyone can help me please?

Thanks in advance.

**Comment by jonathansim97** [comment]
Been browsing a while and found [this](https://github.com/jfoenixadmin/JFoenix/issues/955) as well, the issue doesn't seem to be solved there either.

**Comment by MohamedOthman1** [comment]
I have the same error . Is there any solution ?  @jonathansim97

**Comment by AlanBateman** [comment]
Came up on SO here:
https://stackoverflow.com/questions/55889654/illegalaccessexception-for-jfxtextfield-with-java-sdk-12

**Comment by cmf-cv** [comment]
Same problem here, a fix would be awesome. :-)

**Comment by jonathansim97** [comment]
As @AlanBateman suggested, back down to JDK 11.0.2, it is more stable anyway and it supports long time management. It works for me on JDK 11.0.2

**Comment by AlanBateman** [comment]
My comment was not a suggestion to go back to 11.0.2, it was instead just a link to a post on StackOverflow where the issue is being discussed. As I understand it, JFoenix has code that is hacking a private/undocumented field in jlr.Field and that hack breaks in JDK 12.
