### ISSUE TITLE
JFXDatePicker animation error

### ISSUE THREAD

**Issue by marinaionel** [jfoenixadmin/JFoenix#989]
Every time I open the view or try to edit it in scene builder date picker shows this (bug) animation that you can see in the link below. I tried to fix it but nothing helped. It appeared randomly without any change in the FXML file so I really don't know what could cause it. How can I fix this?

https://media.giphy.com/media/6mmsqWIealM8gooaTf/source.mp4

**Comment by jfoenixadmin** [comment]
which JFoenix version are you using? try updating to the latest version *.0.8

**Comment by marinaionel** [comment]
I am using 9.0.8

**Comment by jfoenixadmin** [comment]
can you provide a SSCCE demonstrating the issue?
