### ISSUE TITLE
Cut, Copy & Paste Action in JFXTextField?

### ISSUE THREAD

**Issue by vigneshrcsengg** [jfoenixadmin/JFoenix#991]
Is there any feature available to disable the cut, copy and paste action for JFXTextField?

I know it is possible to avoid paste action by override `paste()`

`JFXTextField myTextField = new JFXTextField() {
    @Override
    public void paste() { }
};`

But my forms have multiple JFXTextFiled?? How to avoid actions cut, copy and paste in JFXTextFiled??

**Comment by mej71** [comment]
That's a pretty specific use case, you could just make a simple child class that does what you want 

```
public class NoPasteJFXTextField extends JFXTextField {
	@Override public void paste() {}
}
```

If you want to use it in SceneBuilder, make this class in a new project outside of your current project and export it as a jar.  SceneBuilder won't use new nodes defined in your project for some reason

**Comment by vigneshrcsengg** [comment]
Awesome! Solved this issue.

**Comment by jfoenixadmin** [comment]
Currently, there is no code for this enhancement in JFXTextField. What applies on TextField applies on JFXTextField, so you can use the same solution.
