### ISSUE TITLE
Problem with JFXAutoCompletePopup

### ISSUE THREAD

**Issue by FelipeTomazEC** [jfoenixadmin/JFoenix#997]
Hello,
I am trying to use a JFXAutoCompletePopup in my app but it is throwing a IllegalAccessError exception. I'm using javaFX 11.0.2 .
This is the complete error message :

> Caused by: java.lang.IllegalAccessError: class com.jfoenix.controls.JFXAutoCompletePopup (in unnamed module @0x4c0f0772) cannot access class com.sun.javafx.stage.PopupWindowHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.stage to unnamed module @0x4c0f0772
> 	at com.jfoenix.controls.JFXAutoCompletePopup.<init>(JFXAutoCompletePopup.java:68).

How can i fix it? Thanks.

**Comment by jfoenixadmin** [comment]
Hello,
this issue is a duplicate for #889

Regards,
